/home/caio/mfiles/packages/jhandles-0.3.5/inst/__area__.m
NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__area__.m -
SYNOPSIS
Functions
addprop (hh,'BaseValue','double', bv)
addprop (hh,'XData','doublearray', X(:, k))
addprop (hh,'YData','doublearray', Y(:, k))
addprop (hh,'FaceColor','colorradio','flat|interp|none','flat')
addprop (hh,'EdgeColor','colorradio','flat|interp|none','k')
addprop (hh,'CDataMapping','radio','scaled|direct','scaled','hidden')
addprop (hh,'AreaGroup','handle','hidden')
addprop (hh,'LineStyle','linestyle','-')
addprop (hh,'LineWidth','double', 0.5)
set (hh,'CLimInclude', true)
set (hh, varargin{:})
addlistener (hh,{'FaceColor','EdgeColor','LineStyle','LineWidth'},@updatePatchColor)
addlistener (hh,'ObjectDeleted',@memberDeleted)
if (k==1) vv
X(:, k) Y( X (end, k) bv 0]
endfor if (!isempty(h)) set(h
endif endfunction function memberDeleted (h) hlist
hlist (find(hlist==h))
if (!isempty(hlist)) set(hlist
endif endfunction function updatePatchColor (h) hv
set (hv.children(1),'FaceColor', hv.facecolor,...'EdgeColor', hv.edgecolor,...'LineStyle', hv.linestyle,...'LineWidth', hv.linewidth)
endfunction function updatePatchData (h) hlist
if (isempty(YY)) vv
x y zeros (length(y), 1)
x (end) bv 0]
length(y zeros ()
id y ()
if (!isempty(hp)) set(hp(1)
Variables
function [h]
YY = cumsum (Y, 2)
for k
hh_v = get (hh)
fv = [1:size(vv,1)]
else vv = [X(end:-1:1,k-1) YY(end:-1:1,k-1) zeros(size(Y,1),1)
endif fvc = k * ones (size (vv,1), 1)
hp
h = [h hh]
endfor AreaGroup
hlist
bv = get (h, 'BaseValue')
for hh
y = get (hh, 'YData')
x = x(:)
Faces
Vertices
Function Documentation
addlistener (hh)
addlistener (hh, 'ObjectDeleted', @memberDeleted)
addprop (hh, 'BaseValue', 'double', bv)
addprop (hh, 'XData', 'doublearray', X(:, k))
addprop (hh, 'YData', 'doublearray', Y(:, k))
addprop (hh, 'FaceColor', 'colorradio', 'flat|interp|none', 'flat')
addprop (hh, 'EdgeColor', 'colorradio', 'flat|interp|none', 'k')
addprop (hh, 'CDataMapping', 'radio', 'scaled|direct', 'scaled', 'hidden')
addprop (hh, 'AreaGroup', 'handle', 'hidden')
addprop (hh, 'LineStyle', 'linestyle', '-')
addprop (hh, 'LineWidth', 'double', 0.5)
hlist (find(hlist==h))
if (k = =1)
endfor if (!isemptyh)
if (!isemptyhlist)
if (isempty(YY))
if (!isemptyhp)
endif endfunction function memberDeleted (h)
set (hh, 'CLimInclude', true)
set (hh)
set (hv.children1, 'FaceColor', hv.facecolor, ...'EdgeColor', hv.edgecolor, ...'LineStyle', hv.linestyle, ...'LineWidth', hv.linewidth)
endif endfunction function updatePatchColor (h)
endfunction function updatePatchData (h)
X (:,k) Y( X (end, k)
x (end)
id y () [static, virtual]
x y zeros (length(y), 1)
length (y zeros () [static, virtual]
Variable Documentation
AreaGroup
Definition at line 56 of file __area__.m.
bv = get (h, 'BaseValue')
Definition at line 84 of file __area__.m.
Faces
Definition at line 102 of file __area__.m.
function[h]"Initial value:
 __area__ (ax, X, Y, bv, varargin)
  h = []
Definition at line 16 of file __area__.m.
endif fv = [1:size(vv,1)]
Definition at line 43 of file __area__.m.
endif fvc = k * ones (size (vv,1), 1)
Definition at line 48 of file __area__.m.
endif endif h = [h hh]
Definition at line 52 of file __area__.m.
Referenced by gl2psPrintPDFBeginViewport(), gl2psPrintPGFBeginViewport(), gl2psPrintPostScriptBeginViewport(), gl2psPrintSVGBeginViewport(), and gl2psWriteByte().
for hh"Initial value:
 hlist(:)'
    x = get (hh, 'XData')
Definition at line 86 of file __area__.m.
hh_v = get (hh)
Definition at line 39 of file __area__.m.
hlist
Definition at line 66 of file __area__.m.
hp"Initial value:
 patch (hh, 'Faces', fv, 'Vertices', vv, 'FaceVertexCData', fvc, ...
      'FaceColor', hh_v.facecolor, 'EdgeColor', hh_v.edgecolor, 'LineStyle', hh_v.linestyle, ...
      'LineWidth', hh_v.linewidth, '__Index__', k-1)
Definition at line 49 of file __area__.m.
for k"Initial value:
 1:size (Y,2)
    hh = hggroup (ax)
Definition at line 22 of file __area__.m.
Referenced by gl2psAddIndex().
Vertices
Definition at line 102 of file __area__.m.
vv = [X(end:-1:1,k-1) YY(end:-1:1,k-1) zeros(size(Y,1),1)
Definition at line 45 of file __area__.m.
else x = x(:)
Definition at line 90 of file __area__.m.
Referenced by gl2psPrintPDFBeginViewport(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPGFBeginViewport(), gl2psPrintPostScriptBeginViewport(), gl2psPrintSVGBeginViewport(), and gl2psPrintSVGHeader().
else y = get (hh, 'YData')
Definition at line 88 of file __area__.m.
Referenced by gl2psGetRGB(), gl2psPrintPDFBeginViewport(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPGFBeginViewport(), gl2psPrintPostScriptBeginViewport(), gl2psPrintSVGBeginViewport(), and gl2psPrintSVGHeader().
YY = cumsum (Y, 2)
Definition at line 20 of file __area__.m.
Author
Generated automatically by Doxygen for Octave from the source code.