.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__get_object__.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__get_object__.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBobj\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP[\fBobj\fP]"\fBInitial value:\fP
.PP
.nf
 __get_object__ (handle)

  obj = java_invoke ('org\&.octave\&.graphics\&.HandleObject', 'getHandleObject', handle)
.fi
.PP
Definition at line 16 of file __get_object__\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
