.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_colorbar.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_colorbar.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (!isempty(cb_obj)) \fBh\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBh\fP]"
.br
.ti -1c
.RI "else \fBh\fP = []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP (!isemptycb_obj)"
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP[\fBh\fP]"\fBInitial value:\fP
.PP
.nf
 __jhandles_go_colorbar (ax, mode)

  cb_obj = java_invoke (__get_object__ (ax), 'makeColorbar', mode)
.fi
.PP
Definition at line 16 of file __jhandles_go_colorbar\&.m\&.
.SS "else \fBh\fP = []"
.PP
Definition at line 22 of file __jhandles_go_colorbar\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
