.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_waitfor.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_waitfor.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fB__jhandles_waitfor\fP (\fBh\fP, \fBvarargin\fP) \fBj1\fP"
.br
.ti -1c
.RI "\fBobj\fP \fBwaitFor\fP (\fBvarargin\fP{:})"
.br
.ti -1c
.RI "unwind_protect_cleanup \fBjava_convert_matrix\fP (\fBj1\fP)"
.br
.ti -1c
.RI "\fBjava_unsigned_conversion\fP (\fBj2\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBj2\fP = \fBjava_unsigned_conversion\fP (1)"
.br
.ti -1c
.RI "unwind_protect \fBobj\fP = \fB__get_object__\fP (\fBh\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfunction\fP \fB__jhandles_waitfor\fP (\fBh\fP, \fBvarargin\fP)"
.SS "unwind_protect_cleanup \fBjava_convert_matrix\fP (\fBj1\fP)"
.SS "\fBjava_unsigned_conversion\fP (\fBj2\fP)"
.SS "\fBobj\fP \fBwaitFor\fP ()"
.SH "Variable Documentation"
.PP 
.SS "\fBj2\fP = \fBjava_unsigned_conversion\fP (1)"
.PP
Definition at line 19 of file __jhandles_waitfor\&.m\&.
.SS "unwind_protect \fBobj\fP = \fB__get_object__\fP (\fBh\fP)"
.PP
Definition at line 22 of file __jhandles_waitfor\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
