.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_delete.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_delete.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fB__jhandles_go_delete\fP (\fBhandle\fP) \fBobj\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBobj\fP \fBdelete\fP"
.br
.ti -1c
.RI "\fB__request_drawnow__\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfunction\fP \fB__jhandles_go_delete\fP (\fBhandle\fP)"
.SH "Variable Documentation"
.PP 
.SS "\fB__request_drawnow__\fP"
.PP
Definition at line 20 of file __jhandles_go_delete\&.m\&.
.SS "\fBobj\fP \fBdelete\fP"
.PP
Definition at line 19 of file __jhandles_go_delete\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
