.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_figure.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_figure.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (isempty(fnum)||isnan(fnum)) \fBf_obj\fP"
.br
.ti -1c
.RI "\fBendif\fP \fBif\fP (!isempty(\fBf_obj\fP)) \fBf\fP"
.br
.ti -1c
.RI "\fBif\fP (\fBlength\fP(\fBvarargin\fP) > 0) \fBset\fP(\fBf\fP"
.br
.ti -1c
.RI "\fBendif\fP \fBf_obj\fP \fBvalidate\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBf\fP]"
.br
.ti -1c
.RI "else \fBf_obj\fP = root\&.createNewFigure(fnum)"
.br
.ti -1c
.RI "\fBf\fP = f_obj\&.getHandle ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP (isempty(fnum)||isnan(fnum))"
.SS "\fBendif\fP \fBif\fP (!isemptyf_obj)"
.SS "\fBif\fP (\fBlength\fP(\fBvarargin\fP), 0)"
.SS "\fBendif\fP \fBf_obj\fP \fBvalidate\fP ()"
.SH "Variable Documentation"
.PP 
.SS "else \fBf\fP = f_obj\&.getHandle ()"
.PP
Definition at line 31 of file __jhandles_go_figure\&.m\&.
.SS "else \fBf_obj\fP = root\&.createNewFigure(fnum)"
.PP
Definition at line 22 of file __jhandles_go_figure\&.m\&.
.SS "\fBfunction\fP[\fBf\fP]"\fBInitial value:\fP
.PP
.nf
 __jhandles_go_figure (fnum, varargin)

  root = __get_object__ (0)
.fi
.PP
Definition at line 16 of file __jhandles_go_figure\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
