.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_line.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_line.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "unwind_protect_cleanup \fBjava_convert_matrix\fP (\fBj1\fP)"
.br
.ti -1c
.RI "\fBjava_unsigned_conversion\fP (\fBj2\fP)"
.br
.ti -1c
.RI "\fBif\fP (\fBlength\fP(\fBvarargin\fP) > 0) \fBset\fP(\fBh\fP"
.br
.ti -1c
.RI "\fBendif\fP \fBobj\fP \fBvalidate\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBh\fP]"
.br
.ti -1c
.RI "\fBj2\fP = \fBjava_unsigned_conversion\fP (1)"
.br
.ti -1c
.RI "unwind_protect \fBobj\fP = \fBjava_new\fP ('org\&.octave\&.graphics\&.LineObject', __get_object__ (\fBax\fP))"
.br
.ti -1c
.RI "end_unwind_protect \fBh\fP = obj\&.getHandle ()"
.br
.ti -1c
.RI "else \fB__request_drawnow__\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP (\fBlength\fP(\fBvarargin\fP), 0)"
.SS "unwind_protect_cleanup \fBjava_convert_matrix\fP (\fBj1\fP)"
.SS "\fBjava_unsigned_conversion\fP (\fBj2\fP)"
.SS "\fBendif\fP \fBobj\fP \fBvalidate\fP ()"
.SH "Variable Documentation"
.PP 
.SS "else \fB__request_drawnow__\fP"
.PP
Definition at line 31 of file __jhandles_go_line\&.m\&.
.SS "\fBfunction\fP[\fBh\fP]"\fBInitial value:\fP
.PP
.nf
 __jhandles_go_line (ax, varargin)

  j1 = java_convert_matrix (1)
.fi
.PP
Definition at line 16 of file __jhandles_go_line\&.m\&.
.SS "end_unwind_protect \fBh\fP = obj\&.getHandle ()"
.PP
Definition at line 28 of file __jhandles_go_line\&.m\&.
.SS "\fBj2\fP = \fBjava_unsigned_conversion\fP (1)"
.PP
Definition at line 19 of file __jhandles_go_line\&.m\&.
.SS "unwind_protect \fBobj\fP = \fBjava_new\fP ('org\&.octave\&.graphics\&.LineObject', __get_object__ (\fBax\fP))"
.PP
Definition at line 22 of file __jhandles_go_line\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
