.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_exit.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_exit.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBjava_invoke\fP ('org\&.octave\&.graphics\&.HandleObject','shutdown')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP __jhandles_exit close \fBall\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBjava_invoke\fP ('org\&.octave\&.graphics\&.HandleObject', 'shutdown')"
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP __jhandles_exit close \fBall\fP"
.PP
Definition at line 18 of file __jhandles_exit\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
