/home/caio/mfiles/packages/jhandles-0.3.5/src/__jhandles__.cc
NAME
/home/caio/mfiles/packages/jhandles-0.3.5/src/__jhandles__.cc -
SYNOPSIS
#include <octave/oct.h>
#include <octave/graphics.h>
#include <octave/unwind-prot.h>
#include <__java__.h>
Defines
#define TO_JAVA(obj) dynamic_cast<octave_java*>((obj).internal_rep())
Functions
static octave_value handle_to_object (const octave_value &h)
static octave_value get_parent_arg (octave_value_list &args, int idx)
static void set_properties (octave_java *obj, const octave_value_list &args, octave_idx_type idx)
static void initialize_object (octave_java *obj, const octave_value_list &args, octave_idx_type idx)
DEFUN_DLD (__jhandles__, args,,'')
DEFUN_DLD (__jhandles_go_patch2, _args,,'')
Define Documentation
#define TO_JAVA(obj) dynamic_cast<octave_java*>((obj).internal_rep())
Definition at line 22 of file __jhandles__.cc.
Referenced by DEFUN_DLD().
Function Documentation
DEFUN_DLD (__jhandles__, args, '')
Definition at line 85 of file __jhandles__.cc.
{
  return octave_value ();
}
DEFUN_DLD (__jhandles_go_patch2, _args, '')
Definition at line 90 of file __jhandles__.cc.
References args, get_parent_arg(), handle, handle_to_object(), initialize_object(), obj, parent, and TO_JAVA.
{
  octave_value_list args (_args);
  octave_value parent = get_parent_arg (args, 1);
  octave_value retval;
  if (parent.is_undefined ())
    parent = args(0);
  parent = handle_to_object (parent);
  if (error_state)
    return retval;
  octave_value obj = octave_java::do_java_create ('org.octave.graphics.PatchObject', parent);
  if (! error_state)
    {
      octave_java *jobj = TO_JAVA (obj);
      octave_value handle = jobj->do_java_invoke ('getHandle', octave_value_list ());
      initialize_object (jobj, args, 1);
      if (! error_state)
        retval = handle;
    }
  return retval;
}
static octave_value get_parent_arg (octave_value_list &args, intidx) [static]
Definition at line 31 of file __jhandles__.cc.
References args, and i.
Referenced by DEFUN_DLD().
{
  octave_value retval;
  caseless_str pstr ('parent');
  for (int i = idx; i < args.length (); i += 2)
    {
      if (args(i).is_string () && (i+1) < args.length ())
        {
          if (pstr.compare (args(i).string_value ()))
            {
              retval = args(i+1);
              args = args.splice (i, 2);
            }
        }
      else
        return retval;
    }
  return retval;
}
static octave_value handle_to_object (const octave_value &h) [static]
Definition at line 26 of file __jhandles__.cc.
Referenced by DEFUN_DLD().
{
  return octave_java::do_java_invoke('org.octave.graphics.HandleObject', 'getHandleObject', h);
}
static void initialize_object (octave_java *obj, const octave_value_list &args, octave_idx_typeidx) [static]
Definition at line 74 of file __jhandles__.cc.
References idx, and set_properties().
Referenced by DEFUN_DLD().
{
  if (args.length () > idx)
    set_properties (obj, args, idx);
  if (! error_state)
    obj->do_java_invoke ('validate', octave_value_list ());
}
static void set_properties (octave_java *obj, const octave_value_list &args, octave_idx_typeidx) [static]
Definition at line 53 of file __jhandles__.cc.
References args, and i.
Referenced by initialize_object().
{
  octave_value_list set_args(2, octave_value ());
  unwind_protect::begin_frame ('jhandles_set_properties');
  unwind_protect_bool (Vjava_convert_matrix);
  unwind_protect_bool (Vjava_unsigned_conversion);
  Vjava_convert_matrix = true;
  Vjava_unsigned_conversion = true;
  for (int i = idx; (! error_state) && (i < (args.length () - 1)); i += 2)
    {
      set_args(0) = args(i);
      set_args(1) = args(i+1);
      obj->do_java_invoke ('set', set_args);
    }
  unwind_protect::run_frame ('jhandles_set_properties');
}
Author
Generated automatically by Doxygen for Octave from the source code.