.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_axes_init.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_go_axes_init.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fB__jhandles_go_axes_init\fP (\fBh\fP, \fBmode\fP) \fBax_obj\fP"
.br
.ti -1c
.RI "\fBax_obj\fP \fBreset\fP (\fBmode\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfunction\fP \fB__jhandles_go_axes_init\fP (\fBh\fP, \fBmode\fP)"
.SS "\fBax_obj\fP \fBreset\fP (\fBmode\fP)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
