/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_add_property.m
NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_add_property.m -
SYNOPSIS
Functions
function __jhandles_add_property (h, pname, ptype, opts, varargin) parent
unwind_protect switch (ptype) case'radio'if(n > 0 &&ischar(varargin
if (!strcmp(defval,'')&&!any(strcmp(vals, defval))) error('default value for radio property must be part of possible values')
else error ('radio property values are missing')
endfor case colorradio if (n > 0 &&ischar(varargin{1})) vals
if (length(vals) > 0) missing
if (ischar(defval)&&!any(strcmp(vals, defval))&&(length(defval) > 1||isempty(findstr(defval,'rgbywkmc')))) error('invalid default value for colorradio property')
p set (defval, true)
else error ('colorradio property values are missing')
endif otherwise error ('unknown property type `%s'', ptype)
endswitch unwind_protect_cleanup java_convert_matrix (j1)
java_unsigned_conversion (j2)
end_unwind_protect if (!opts.visible) p.setVisible(false)
endif if (opts.readonly) p.setReadOnly(true)
endif if (any(cellfun(@(x) isa(varargin{1}, x), ctype))) val
error ('invalid property default value, expected `%s'', tstr(1:end-4))
Variables
n = length (varargin)
j1 = java_convert_matrix (1)
j2 = java_unsigned_conversion (1)
vals = regexp (varargin{1}, '[^|]+', 'match')
defval = get_default_value ('char', '', varargin{2:end})
endif p = java_new ('org.octave.graphics.RadioProperty', parent, pname, vals, defval)
for hh
else missing = [0 0 0]
endif endfunction function [val]
else tstr = sprintf ('%s or ', ctype{:})
endif else val = missing
Function Documentation
function __jhandles_add_property (h, pname, ptype, opts, varargin)
else error ('radio property values are missing')
else error ('colorradio property values are missing')
endif otherwise error ('unknown property type `%s'', ptype)
error ('invalid property defaultvalue, expected`%s'', tstr(1:end-4))
if (!strcmpdefval,'')&&!any(strcmp(vals, defval))
endfor case colorradio if (n, 0 &&ischarvarargin{1})
if (length(vals), 0)
if (ischar(defval)&&!any(strcmp(vals, defval))&&(length(defval) > 1||isempty(findstr(defval,'rgbywkmc'))))
end_unwind_protect if (!opts.visible)
endif if (opts.readonly)
endif if (any(cellfun(@(x) isa(varargin{1}, x), ctype)))
endswitch unwind_protect_cleanup java_convert_matrix (j1)
java_unsigned_conversion (j2)
p set (defval, true)
unwind_protect switch (ptype)
Definition at line 25 of file __jhandles_add_property.m.
                                   {1}))
Variable Documentation
endif defval = get_default_value ('char', '', varargin{2:end})
Definition at line 29 of file __jhandles_add_property.m.
endif endfunction function[val]"Initial value:
 get_default_value (ctype, missing, varargin)
  if (length (varargin) > 0)
    if (! iscellstr (ctype))
      ctype = {ctype}
Definition at line 92 of file __jhandles_add_property.m.
for hh"Initial value:
 defval(:)'
        p.addElement (__get_object__ (hh))
Definition at line 55 of file __jhandles_add_property.m.
j1 = java_convert_matrix (1)
Definition at line 21 of file __jhandles_add_property.m.
j2 = java_unsigned_conversion (1)
Definition at line 22 of file __jhandles_add_property.m.
else missing = [0 0 0]
Definition at line 64 of file __jhandles_add_property.m.
else n = length (varargin)
Definition at line 19 of file __jhandles_add_property.m.
Referenced by gl2psGetPlaneFromPoints(), gl2psListRealloc(), gl2psParseStipplePattern(), gl2psPrintGzipFooter(), gl2psPrintPGFDash(), gl2psPrintPostScriptDash(), gl2psPrintSVGDash(), gl2psSameColorThreshold(), and gl2psSVGGetCoordsAndColors().
endif p = java_new ('org.octave.graphics.RadioProperty', parent, pname, vals, defval)
Definition at line 33 of file __jhandles_add_property.m.
else tstr = sprintf ('%s or ', ctype{:})
Definition at line 101 of file __jhandles_add_property.m.
endif else val = missing
Definition at line 105 of file __jhandles_add_property.m.
vals = regexp (varargin{1}, '[^|]+', 'match')
Definition at line 28 of file __jhandles_add_property.m.
Author
Generated automatically by Doxygen for Octave from the source code.