/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_get.m
NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_get.m -
SYNOPSIS
Functions
if (!isempty(handle)) if(nargin
elseif (nargout > 0) names
else handle show ()
endif else error ('invalid handle')
endif unwind_protect_cleanup java_convert_matrix (j1)
java_unsigned_conversion (j2)
Variables
function [varargout]
j2 = java_unsigned_conversion (1)
unwind_protect handle = __get_object__ (h)
ret = struct([])
for k
Function Documentation
elseif (nargout, 0)
endif else error ('invalid handle')
if (!isemptyhandle)
endif unwind_protect_cleanup java_convert_matrix (j1)
java_unsigned_conversion (j2)
else handle show ()
Variable Documentation
function[varargout]"Initial value:
 __jhandles_get (h, property)
  j1 = java_convert_matrix (1)
Definition at line 16 of file __jhandles_get.m.
unwind_protect handle = __get_object__ (h)
Definition at line 22 of file __jhandles_get.m.
Referenced by DEFUN_DLD().
j2 = java_unsigned_conversion (1)
Definition at line 19 of file __jhandles_get.m.
for k"Initial value:
 1:length (names)
          ret.(tolower(names{k})) = java2mat (handle.get (names{k}))
Definition at line 29 of file __jhandles_get.m.
endfor endswitch else ret = struct([])
Definition at line 28 of file __jhandles_get.m.
Referenced by gl2psAddInBspImageTree(), gl2psAddPlanesInBspTreeImage(), and gl2psPrintf().
Author
Generated automatically by Doxygen for Octave from the source code.