.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_set.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/__jhandles_set.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fB__jhandles_set\fP (\fBh\fP, \fBvarargin\fP) \fBj1\fP"
.br
.ti -1c
.RI "unwind_protect \fBif\fP (strcmp(class(\fBh\fP),'octave_java')) for \fBk\fP"
.br
.ti -1c
.RI "\fBif\fP (!isempty(\fBhandle\fP)) for \fBk\fP"
.br
.ti -1c
.RI "endfor else \fBerror\fP ('invalid \fBhandle\fP')"
.br
.ti -1c
.RI "\fBendif\fP endfor \fBendif\fP 
.br
unwind_protect_cleanup \fBjava_convert_matrix\fP (\fBj1\fP)"
.br
.ti -1c
.RI "\fBjava_unsigned_conversion\fP (\fBj2\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBj2\fP = \fBjava_unsigned_conversion\fP (1)"
.br
.ti -1c
.RI "endfor else for \fBhk\fP"
.br
.ti -1c
.RI "end_unwind_protect \fB__request_drawnow__\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfunction\fP \fB__jhandles_set\fP (\fBh\fP, \fBvarargin\fP)"
.SS "endfor else \fBerror\fP ('invalid \fBhandle\fP')"
.SS "unwind_protect \fBif\fP (strcmp(class(\fBh\fP),'octave_java'))"
.SS "\fBif\fP (!isemptyhandle)"
.SS "\fBendif\fP endfor \fBendif\fP unwind_protect_cleanup \fBjava_convert_matrix\fP (\fBj1\fP)"
.SS "\fBjava_unsigned_conversion\fP (\fBj2\fP)"
.SH "Variable Documentation"
.PP 
.SS "end_unwind_protect \fB__request_drawnow__\fP"
.PP
Definition at line 43 of file __jhandles_set\&.m\&.
.SS "endfor else for \fBhk\fP"\fBInitial value:\fP
.PP
.nf
 h(:)'
        handle = __get_object__ (hk)
.fi
.PP
Definition at line 27 of file __jhandles_set\&.m\&.
.SS "\fBj2\fP = \fBjava_unsigned_conversion\fP (1)"
.PP
Definition at line 19 of file __jhandles_set\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
