.TH "_GL2PSimagemap" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GL2PSimagemap \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSimage\fP * \fBimage\fP"
.br
.ti -1c
.RI "\fBGL2PSimagemap\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 206 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGL2PSimage\fP* \fB_GL2PSimagemap::image\fP"
.PP
Definition at line 207 of file gl2ps\&.c\&.
.PP
Referenced by gl2psFreeImagemap(), and gl2psParseFeedbackBuffer()\&.
.SS "\fBGL2PSimagemap\fP* \fB_GL2PSimagemap::next\fP"
.PP
Definition at line 208 of file gl2ps\&.c\&.
.PP
Referenced by gl2psFreeImagemap(), and gl2psParseFeedbackBuffer()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
