.TH "_GL2PSbsptree" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GL2PSbsptree \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSplane\fP \fBplane\fP"
.br
.ti -1c
.RI "\fBGL2PSlist\fP * \fBprimitives\fP"
.br
.ti -1c
.RI "\fBGL2PSbsptree\fP * \fBfront\fP"
.br
.ti -1c
.RI "\fBGL2PSbsptree\fP * \fBback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGL2PSbsptree\fP * \fB_GL2PSbsptree::back\fP"
.PP
Definition at line 165 of file gl2ps\&.c\&.
.PP
Referenced by gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), and gl2psTraverseBspTree()\&.
.SS "\fBGL2PSbsptree\fP* \fB_GL2PSbsptree::front\fP"
.PP
Definition at line 165 of file gl2ps\&.c\&.
.PP
Referenced by gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), and gl2psTraverseBspTree()\&.
.SS "\fBGL2PSplane\fP \fB_GL2PSbsptree::plane\fP"
.PP
Definition at line 163 of file gl2ps\&.c\&.
.PP
Referenced by gl2psBuildBspTree(), and gl2psTraverseBspTree()\&.
.SS "\fBGL2PSlist\fP* \fB_GL2PSbsptree::primitives\fP"
.PP
Definition at line 164 of file gl2ps\&.c\&.
.PP
Referenced by gl2psBuildBspTree(), gl2psBuildPolygonBoundary(), and gl2psTraverseBspTree()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
