.TH "_GL2PSbsptree2d" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GL2PSbsptree2d \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSplane\fP \fBplane\fP"
.br
.ti -1c
.RI "\fBGL2PSbsptree2d\fP * \fBfront\fP"
.br
.ti -1c
.RI "\fBGL2PSbsptree2d\fP * \fBback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 150 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGL2PSbsptree2d\fP * \fB_GL2PSbsptree2d::back\fP"
.PP
Definition at line 152 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddPlanesInBspTreeImage()\&.
.SS "\fBGL2PSbsptree2d\fP* \fB_GL2PSbsptree2d::front\fP"
.PP
Definition at line 152 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddPlanesInBspTreeImage()\&.
.SS "\fBGL2PSplane\fP \fB_GL2PSbsptree2d::plane\fP"
.PP
Definition at line 151 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddPlanesInBspTreeImage()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
