.TH "/home/caio/mfiles/atan2d.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/atan2d.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBangle\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP \fBangle\fP"\fBInitial value:\fP
.PP
.nf
 atan2d(y,x)
% atan2d(y,x) : return atan2d(y,x) in degree
angle=atan2(y,x)*180/pi
.fi
.PP
Definition at line 1 of file atan2d\&.m\&.
.PP
Referenced by gl2psAddText()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
