.TH "/home/caio/mfiles/AWG.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/AWG.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (awgnumber==-1) \fBawg\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBawg\fP"
.br
.ti -1c
.RI "\fBkeyboard\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP (awgnumber = \fC=-1\fP)"
.SH "Variable Documentation"
.PP 
.SS "else \fBawg\fP"
.PP
Definition at line 3 of file AWG\&.m\&.
.SS "\fBkeyboard\fP"
.PP
Definition at line 97 of file AWG\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
