.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/bar3.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/bar3.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (nargout > 0) \fBh\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBh\fP]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP (nargout, 0)"
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP[\fBh\fP]"\fBInitial value:\fP
.PP
.nf
 bar3 (varargin)

  tmp = __bar3__ ('bar3', 0, varargin{:})
.fi
.PP
Definition at line 16 of file bar3\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
