.TH "/home/caio/mfiles/clcc.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/clcc.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBclcc\fP ()%%Clean the terminal history and clean \fBall\fP the screen%shell_cmd('reset')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBfunction\fP \fBclcc\fP ()"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
