.TH "/home/caio/mfiles/demo1.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/demo1.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBnum\fP = 1"
.br
.ti -1c
.RI "\fBden\fP = [1 10 20]"
.br
.ti -1c
.RI "\fBKp\fP = 300"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBden\fP = [1 10 20]"
.PP
Definition at line 2 of file demo1\&.m\&.
.SS "\fBKp\fP = 300"
.PP
Definition at line 3 of file demo1\&.m\&.
.SS "\fBnum\fP = 1"
.PP
Definition at line 1 of file demo1\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
