.TH "/home/caio/mfiles/dummy.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/dummy.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBa\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBendif\fP endfor endfunction \fBfunction\fP"\fBInitial value:\fP
.PP
.nf
 dummy (b=10)








a=20
.fi
.PP
Definition at line 24 of file dummy\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
