.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/gcbf.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/gcbf.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBh\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP[\fBh\fP]"\fBInitial value:\fP
.PP
.nf
 gcbf ()

  [tmp, h] = gcbo ()
.fi
.PP
Definition at line 16 of file gcbf\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
