.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/gcbo.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/gcbo.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (!ishandle(\fBh\fP)) \fBh\fP"
.br
.ti -1c
.RI "\fBelseif\fP (nargout > 1) \fBfig\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBh\fP, \fBfig\fP]"
.br
.ti -1c
.RI "\fBfig\fP = []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBelseif\fP (nargout, 1)"
.SS "\fBif\fP (!ishandleh)"
.SH "Variable Documentation"
.PP 
.SS "\fBfig\fP = []"
.PP
Definition at line 21 of file gcbo\&.m\&.
.SS "\fBfunction\fP[\fBh\fP, \fBfig\fP]"\fBInitial value:\fP
.PP
.nf
 gcbo ()

  h = get (0, 'callbackobject')
.fi
.PP
Definition at line 16 of file gcbo\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
