.TH "GL2PSstring" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSstring \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLshort \fBfontsize\fP"
.br
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "char * \fBfontname\fP"
.br
.ti -1c
.RI "GLint \fBalignment\fP"
.br
.ti -1c
.RI "GLfloat \fBangle\fP"
.br
.ti -1c
.RI "GLfloat \fBmargin\fP"
.br
.ti -1c
.RI "GLboolean \fBoffsetmargin\fP"
.br
.ti -1c
.RI "GLfloat \fBlinewidth\fP"
.br
.ti -1c
.RI "\fBGL2PSrgba\fP \fBlinecolor\fP"
.br
.ti -1c
.RI "GLushort \fBlinepattern\fP"
.br
.ti -1c
.RI "GLint \fBlinefactor\fP"
.br
.ti -1c
.RI "\fBGL2PSrgba\fP \fBfillcolor\fP"
.br
.ti -1c
.RI "GLboolean \fBdepthtest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 178 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "GLint \fBGL2PSstring::alignment\fP"
.PP
Definition at line 183 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), and gl2psPrintTeXPrimitive()\&.
.SS "GLfloat \fBGL2PSstring::angle\fP"
.PP
Definition at line 184 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), and gl2psPrintTeXPrimitive()\&.
.SS "GLboolean \fBGL2PSstring::depthtest\fP"
.PP
Definition at line 192 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psBuildBspTree(), and gl2psCopyText()\&.
.SS "\fBGL2PSrgba\fP \fBGL2PSstring::fillcolor\fP"
.PP
Definition at line 191 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "char * \fBGL2PSstring::fontname\fP"
.PP
Definition at line 180 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psFreeText(), gl2psPrintPDFText(), gl2psPrintPostScriptPrimitive(), and gl2psPrintSVGPrimitive()\&.
.SS "GLshort \fBGL2PSstring::fontsize\fP"
.PP
Definition at line 179 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), and gl2psPutPDFText()\&.
.SS "\fBGL2PSrgba\fP \fBGL2PSstring::linecolor\fP"
.PP
Definition at line 188 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLint \fBGL2PSstring::linefactor\fP"
.PP
Definition at line 190 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLushort \fBGL2PSstring::linepattern\fP"
.PP
Definition at line 189 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLfloat \fBGL2PSstring::linewidth\fP"
.PP
Definition at line 187 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLfloat \fBGL2PSstring::margin\fP"
.PP
Definition at line 185 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLboolean \fBGL2PSstring::offsetmargin\fP"
.PP
Definition at line 186 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "char* \fBGL2PSstring::str\fP"
.PP
Definition at line 180 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psFreeText(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), and gl2psPutPDFText()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
