.TH "GL2PSlist" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSlist \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLint \fBnmax\fP"
.br
.ti -1c
.RI "GLint \fBsize\fP"
.br
.ti -1c
.RI "GLint \fBincr\fP"
.br
.ti -1c
.RI "GLint \fBn\fP"
.br
.ti -1c
.RI "char * \fBarray\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 155 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "char* \fBGL2PSlist::array\fP"
.PP
Definition at line 157 of file gl2ps\&.c\&.
.PP
Referenced by gl2psListAdd(), gl2psListCreate(), gl2psListDelete(), gl2psListPointer(), gl2psListRealloc(), and gl2psListSort()\&.
.SS "GLint \fBGL2PSlist::incr\fP"
.PP
Definition at line 156 of file gl2ps\&.c\&.
.PP
Referenced by gl2psListCreate(), and gl2psListRealloc()\&.
.SS "GLint \fBGL2PSlist::n\fP"
.PP
Definition at line 156 of file gl2ps\&.c\&.
.PP
Referenced by gl2psListAdd(), gl2psListCreate(), gl2psListNbr(), gl2psListPointer(), gl2psListReset(), and gl2psListSort()\&.
.SS "GLint \fBGL2PSlist::nmax\fP"
.PP
Definition at line 156 of file gl2ps\&.c\&.
.PP
Referenced by gl2psListCreate(), and gl2psListRealloc()\&.
.SS "GLint \fBGL2PSlist::size\fP"
.PP
Definition at line 156 of file gl2ps\&.c\&.
.PP
Referenced by gl2psListAdd(), gl2psListCreate(), gl2psListPointer(), gl2psListRealloc(), and gl2psListSort()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
