.TH "GL2PScompress" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PScompress \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdummy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 224 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBGL2PScompress::dummy\fP"
.PP
Definition at line 229 of file gl2ps\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
