.TH "GL2PSimage" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSimage \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLsizei \fBwidth\fP"
.br
.ti -1c
.RI "GLsizei \fBheight\fP"
.br
.ti -1c
.RI "GLenum \fBformat\fP"
.br
.ti -1c
.RI "GLenum \fBtype\fP"
.br
.ti -1c
.RI "GLfloat * \fBpixels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 195 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "GLenum \fBGL2PSimage::format\fP"
.PP
Definition at line 200 of file gl2ps\&.c\&.
.PP
Referenced by gl2psAddInImageTree(), gl2psCopyPixmap(), gl2psDrawPixels(), gl2psGetRGB(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPrintPDFPixmap(), and gl2psPrintPDFPixmapStreamData()\&.
.SS "GLsizei \fBGL2PSimage::height\fP"
.PP
Definition at line 196 of file gl2ps\&.c\&.
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), gl2psGetRGB(), gl2psParseFeedbackBuffer(), gl2psPrintPDFPixmap(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPostScriptPixmap(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPixmap(), and gl2psPutPDFImage()\&.
.SS "GLfloat* \fBGL2PSimage::pixels\fP"
.PP
Definition at line 201 of file gl2ps\&.c\&.
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), gl2psFreeImagemap(), gl2psFreePixmap(), gl2psGetRGB(), gl2psParseFeedbackBuffer(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLenum \fBGL2PSimage::type\fP"
.PP
Definition at line 200 of file gl2ps\&.c\&.
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), gl2psParseFeedbackBuffer(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLsizei \fBGL2PSimage::width\fP"
.PP
Definition at line 196 of file gl2ps\&.c\&.
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), gl2psGetRGB(), gl2psParseFeedbackBuffer(), gl2psPrintPDFPixmap(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPostScriptPixmap(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPixmap(), and gl2psPutPDFImage()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
