/home/caio/mfiles/packages/jhandles-0.3.5/src/gl2ps_java.c
NAME
/home/caio/mfiles/packages/jhandles-0.3.5/src/gl2ps_java.c -
SYNOPSIS
#include <jni.h>
#include <gl2ps.h>
#include <stdio.h>
#include <errno.h>
Defines
#define JSTRING(s) const char* s = (_ ## s ? (*env)->GetStringUTFChars(env, _ ## s, NULL) : NULL)
#define END_JSTRING(s) if (s) (*env)->ReleaseStringUTFChars(env, _ ## s, s)
#define WITH_JSTRING(s, code) JSTRING(s); do { code } while (0); END_JSTRING(s);
#define JINTARRAY(s) jint* s = (_ ## s ? (*env)->GetIntArrayElements(env, _ ## s, NULL) : NULL)
#define END_JINTARRAY(s) if (s) (*env)->ReleaseIntArrayElements(env, _ ## s, s, 0)
#define WITH_JINTARRAY(s, code) JINTARRAY(s); do { code } while (0); END_JINTARRAY(s);
#define JFLOATARRAY(s) jfloat* s = (_ ## s ? (*env)->GetFloatArrayElements(env, _ ## s, NULL) : NULL)
#define END_JFLOATARRAY(s) if (s) (*env)->ReleaseFloatArrayElements(env, _ ## s, s, 0)
#define WITH_JFLOATARRAY(s, code) JFLOATARRAY(s); do { code } while (0); END_JFLOATARRAY(s);
Functions
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psBeginPage (JNIEnv *env, jclass cls, jstring _title, jstring _producer, jintArray _viewport, jint format, jint sort, jint options, jint colormode, jint colorsize, jobjectArray colortable, jint nr, jint ng, jint nb, jint buffersize, jstring _outputname, jstring _filename)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psEndPage (JNIEnv *env, jclass cls)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psText (JNIEnv *env, jclass cls, jstring _string, jstring _fontname, jint fontsize)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psTextOpt (JNIEnv *env, jclass cls, jstring _string, jstring _fontname, jint fontsize, jint align, jfloat angle, jfloat margin, jboolean offsetmargin, jfloat linewidth, jfloatArray _linecolor, jshort linepattern, jint linefactor, jfloatArray _fillcolor)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psEnable (JNIEnv *env, jclass cls, jint mode)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psDisable (JNIEnv *env, jclass cls, jint mode)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psBeginViewport (JNIEnv *env, jclass cls, jintArray _viewport)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psEndViewport (JNIEnv *env, jclass cls)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psLineWidth (JNIEnv *env, jclass cls, jfloat w)
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psSpecial (JNIEnv *env, jclass cls, jint format, jstring _string, jint moveTo)
Variables
static FILE * stream = NULL
Define Documentation
#define END_JFLOATARRAY(s) if (s) (*env)->ReleaseFloatArrayElements(env, _ ## s, s, 0)
Definition at line 23 of file gl2ps_java.c.
#define END_JINTARRAY(s) if (s) (*env)->ReleaseIntArrayElements(env, _ ## s, s, 0)
Definition at line 18 of file gl2ps_java.c.
#define END_JSTRING(s) if (s) (*env)->ReleaseStringUTFChars(env, _ ## s, s)
Definition at line 13 of file gl2ps_java.c.
#define JFLOATARRAY(s) jfloat* s = (_ ## s ? (*env)->GetFloatArrayElements(env, _ ## s, NULL) : NULL)
Definition at line 22 of file gl2ps_java.c.
#define JINTARRAY(s) jint* s = (_ ## s ? (*env)->GetIntArrayElements(env, _ ## s, NULL) : NULL)
Definition at line 17 of file gl2ps_java.c.
#define JSTRING(s) const char* s = (_ ## s ? (*env)->GetStringUTFChars(env, _ ## s, NULL) : NULL)
Definition at line 12 of file gl2ps_java.c.
#define WITH_JFLOATARRAY(s, code) JFLOATARRAY(s); do { code } while (0); END_JFLOATARRAY(s);
Definition at line 24 of file gl2ps_java.c.
Referenced by Java_org_octave_graphics_GL2PS_gl2psTextOpt().
#define WITH_JINTARRAY(s, code) JINTARRAY(s); do { code } while (0); END_JINTARRAY(s);
Definition at line 19 of file gl2ps_java.c.
Referenced by Java_org_octave_graphics_GL2PS_gl2psBeginPage(), and Java_org_octave_graphics_GL2PS_gl2psBeginViewport().
#define WITH_JSTRING(s, code) JSTRING(s); do { code } while (0); END_JSTRING(s);
Definition at line 14 of file gl2ps_java.c.
Referenced by Java_org_octave_graphics_GL2PS_gl2psBeginPage(), Java_org_octave_graphics_GL2PS_gl2psSpecial(), Java_org_octave_graphics_GL2PS_gl2psText(), and Java_org_octave_graphics_GL2PS_gl2psTextOpt().
Function Documentation
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psBeginPage (JNIEnv *env, jclasscls, jstring_title, jstring_producer, jintArray_viewport, jintformat, jintsort, jintoptions, jintcolormode, jintcolorsize, jobjectArraycolortable, jintnr, jintng, jintnb, jintbuffersize, jstring_outputname, jstring_filename)
Definition at line 28 of file gl2ps_java.c.
References GL2PS_ERROR, gl2psBeginPage(), printf(), stream, WITH_JINTARRAY, and WITH_JSTRING.
{
  GLint result;
  WITH_JSTRING(title,
    WITH_JSTRING(producer,
      WITH_JSTRING(outputname,
        WITH_JSTRING(filename,
          WITH_JINTARRAY(viewport,
            if (stream != NULL)
              result = GL2PS_ERROR;
            else
            {
              stream = fopen(outputname, 'w');
              if (stream == NULL)
              {
                printf('cannot open %s for writing\n', outputname);
                result = GL2PS_ERROR;
              }
              else
                result = gl2psBeginPage(
                  title, producer,
                  viewport,
                  format, sort, options,
                  colormode, colorsize,
                  NULL /* TODO */,
                  nr, ng, nb,
                  buffersize, stream,
                  filename);
            }
            )))))
  return result;
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psBeginViewport (JNIEnv *env, jclasscls, jintArray_viewport)
Definition at line 134 of file gl2ps_java.c.
References gl2psBeginViewport(), and WITH_JINTARRAY.
{
  GLint result;
  WITH_JINTARRAY(viewport,
    result = gl2psBeginViewport(viewport);
    )
  return result;
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psDisable (JNIEnv *env, jclasscls, jintmode)
Definition at line 128 of file gl2ps_java.c.
References gl2psDisable().
{
  return gl2psDisable(mode);
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psEnable (JNIEnv *env, jclasscls, jintmode)
Definition at line 122 of file gl2ps_java.c.
References gl2psEnable().
{
  return gl2psEnable(mode);
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psEndPage (JNIEnv *env, jclasscls)
Definition at line 72 of file gl2ps_java.c.
References fclose(), GL2PS_UNINITIALIZED, gl2psEndPage(), and stream.
{
  GLint result = GL2PS_UNINITIALIZED;
  if (stream != NULL)
  {
    result = gl2psEndPage();
    fclose(stream);
    stream = NULL;
  }
  
  return result;
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psEndViewport (JNIEnv *env, jclasscls)
Definition at line 146 of file gl2ps_java.c.
References gl2psEndViewport().
{
  return gl2psEndViewport();
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psLineWidth (JNIEnv *env, jclasscls, jfloatw)
Definition at line 152 of file gl2ps_java.c.
References gl2psLineWidth(), and printf().
{
  printf('gl2psLineWidth: %f\n', w);
  return gl2psLineWidth(w);
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psSpecial (JNIEnv *env, jclasscls, jintformat, jstring_string, jintmoveTo)
Definition at line 159 of file gl2ps_java.c.
References gl2psSpecial(), and WITH_JSTRING.
{
  GLint result;
  WITH_JSTRING(string,
    result = gl2psSpecial(format, string, moveTo);
    )
  return result;
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psText (JNIEnv *env, jclasscls, jstring_string, jstring_fontname, jintfontsize)
Definition at line 87 of file gl2ps_java.c.
References gl2psText(), and WITH_JSTRING.
{
  GLint result;
  WITH_JSTRING(string,
    WITH_JSTRING(fontname,
      result = gl2psText(string, fontname, fontsize);
      ))
  return result;
}
JNIEXPORT jint JNICALL Java_org_octave_graphics_GL2PS_gl2psTextOpt (JNIEnv *env, jclasscls, jstring_string, jstring_fontname, jintfontsize, jintalign, jfloatangle, jfloatmargin, jbooleanoffsetmargin, jfloatlinewidth, jfloatArray_linecolor, jshortlinepattern, jintlinefactor, jfloatArray_fillcolor)
Definition at line 102 of file gl2ps_java.c.
References gl2psTextOpt(), WITH_JFLOATARRAY, and WITH_JSTRING.
{
  GLint result;
  WITH_JSTRING(string,
    WITH_JSTRING(fontname,
      WITH_JFLOATARRAY(linecolor,
        WITH_JFLOATARRAY(fillcolor,
          result = gl2psTextOpt(string, fontname, fontsize, align, angle, margin, offsetmargin,
            linewidth, linecolor, linepattern, linefactor, fillcolor);
          ))))
  return result;
}
Variable Documentation
FILE* stream = NULL [static]
Definition at line 10 of file gl2ps_java.c.
Referenced by gl2psBeginPage(), Java_org_octave_graphics_GL2PS_gl2psBeginPage(), and Java_org_octave_graphics_GL2PS_gl2psEndPage().
Author
Generated automatically by Doxygen for Octave from the source code.