.TH "GL2PSpdfgroup" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSpdfgroup \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSlist\fP * \fBptrlist\fP"
.br
.ti -1c
.RI "int \fBgsno\fP"
.br
.ti -1c
.RI "int \fBfontno\fP"
.br
.ti -1c
.RI "int \fBimno\fP"
.br
.ti -1c
.RI "int \fBshno\fP"
.br
.ti -1c
.RI "int \fBmaskshno\fP"
.br
.ti -1c
.RI "int \fBtrgroupno\fP"
.br
.ti -1c
.RI "int \fBgsobjno\fP"
.br
.ti -1c
.RI "int \fBfontobjno\fP"
.br
.ti -1c
.RI "int \fBimobjno\fP"
.br
.ti -1c
.RI "int \fBshobjno\fP"
.br
.ti -1c
.RI "int \fBmaskshobjno\fP"
.br
.ti -1c
.RI "int \fBtrgroupobjno\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 233 of file gl2ps\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "int \fBGL2PSpdfgroup::fontno\fP"
.PP
Definition at line 235 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListInit(), gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBGL2PSpdfgroup::fontobjno\fP"
.PP
Definition at line 236 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteObjects(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBGL2PSpdfgroup::gsno\fP"
.PP
Definition at line 235 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBGL2PSpdfgroup::gsobjno\fP"
.PP
Definition at line 236 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBGL2PSpdfgroup::imno\fP"
.PP
Definition at line 235 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteXObjectResources(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBGL2PSpdfgroup::imobjno\fP"
.PP
Definition at line 236 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBGL2PSpdfgroup::maskshno\fP"
.PP
Definition at line 235 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBGL2PSpdfgroup::maskshobjno\fP"
.PP
Definition at line 236 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "\fBGL2PSlist\fP* \fBGL2PSpdfgroup::ptrlist\fP"
.PP
Definition at line 234 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBGL2PSpdfgroup::shno\fP"
.PP
Definition at line 235 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBGL2PSpdfgroup::shobjno\fP"
.PP
Definition at line 236 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBGL2PSpdfgroup::trgroupno\fP"
.PP
Definition at line 235 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteXObjectResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBGL2PSpdfgroup::trgroupobjno\fP"
.PP
Definition at line 236 of file gl2ps\&.c\&.
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
