GL2PSbackend
NAME
GL2PSbackend -
SYNOPSIS
Public Attributes
void(* printHeader )(void)
void(* printFooter )(void)
void(* beginViewport )(GLint viewport[4])
GLint(* endViewport )(void)
void(* printPrimitive )(void *data)
void(* printFinalPrimitive )(void)
const char * file_extension
const char * description
Detailed Description
Definition at line 279 of file gl2ps.c.
Member Data Documentation
void(* GL2PSbackend::beginViewport)(GLint viewport[4])
Definition at line 282 of file gl2ps.c.
Referenced by gl2psBeginViewport().
const char* GL2PSbackend::description
Definition at line 287 of file gl2ps.c.
Referenced by gl2psGetFormatDescription().
GLint(* GL2PSbackend::endViewport)(void)
Definition at line 283 of file gl2ps.c.
Referenced by gl2psEndViewport().
const char* GL2PSbackend::file_extension
Definition at line 286 of file gl2ps.c.
Referenced by gl2psGetFileExtension().
void(* GL2PSbackend::printFinalPrimitive)(void)
Definition at line 285 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
void(* GL2PSbackend::printFooter)(void)
Definition at line 281 of file gl2ps.c.
Referenced by gl2psEndPage().
void(* GL2PSbackend::printHeader)(void)
Definition at line 280 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
void(* GL2PSbackend::printPrimitive)(void *data)
Definition at line 284 of file gl2ps.c.
Referenced by gl2psPrintPrimitives().
Author
Generated automatically by Doxygen for Octave from the source code.