.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/isprop.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/isprop.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBret\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "catch \fBret\fP"\fBInitial value:\fP
.PP
.nf
 isprop (h, propname)

  try
    get (h, propname)
.fi
.PP
Definition at line 16 of file isprop\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
