.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/light.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/light.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (\fBlength\fP(\fBvarargin\fP) > 0) \fBset\fP(\fBtmp\fP"
.br
.ti -1c
.RI "\fBendif\fP \fBif\fP (nargout > 0) \fBh\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [\fBh\fP]"
.br
.ti -1c
.RI "\fBl_obj\fP = \fBjava_new\fP ('org\&.octave\&.graphics\&.LightObject', ax_obj)"
.br
.ti -1c
.RI "\fBtmp\fP = l_obj\&.getHandle ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP (\fBlength\fP(\fBvarargin\fP), 0)"
.SS "\fBendif\fP \fBif\fP (nargout, 0)"
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP[\fBh\fP]"\fBInitial value:\fP
.PP
.nf
 light (varargin)

  ax_obj = __get_object__ (gca)
.fi
.PP
Definition at line 16 of file light\&.m\&.
.SS "\fBl_obj\fP = \fBjava_new\fP ('org\&.octave\&.graphics\&.LightObject', ax_obj)"
.PP
Definition at line 19 of file light\&.m\&.
.SS "\fBtmp\fP = l_obj\&.getHandle ()"
.PP
Definition at line 20 of file light\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
