.TH "/home/caio/mfiles/PKG_ADD.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/PKG_ADD.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBautoload\fP ('AF_UNIX','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('AF_LOCAL','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('AF_INET','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('AF_APPLETALK','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('SOCK_STREAM','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('SOCK_DGRAM','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('SOCK_SEQPACKET','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('SOCK_RAW','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('SOCK_RDM','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('MSG_PEEK','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('MSG_DONTWAIT','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('MSG_WAITALL','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('socket','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('connect','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('disconnect','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('gethostbyname','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('send','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('recv','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('bind','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('listen','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('accept','sockets\&.oct')"
.br
.ti -1c
.RI "\fBautoload\fP ('load_socket_constants','sockets\&.oct')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBautoload\fP ('AF_UNIX', 'sockets\&.oct')"
.SS "\fBautoload\fP ('AF_LOCAL', 'sockets\&.oct')"
.SS "\fBautoload\fP ('AF_INET', 'sockets\&.oct')"
.SS "\fBautoload\fP ('AF_APPLETALK', 'sockets\&.oct')"
.SS "\fBautoload\fP ('SOCK_STREAM', 'sockets\&.oct')"
.SS "\fBautoload\fP ('SOCK_DGRAM', 'sockets\&.oct')"
.SS "\fBautoload\fP ('SOCK_SEQPACKET', 'sockets\&.oct')"
.SS "\fBautoload\fP ('SOCK_RAW', 'sockets\&.oct')"
.SS "\fBautoload\fP ('SOCK_RDM', 'sockets\&.oct')"
.SS "\fBautoload\fP ('MSG_PEEK', 'sockets\&.oct')"
.SS "\fBautoload\fP ('MSG_DONTWAIT', 'sockets\&.oct')"
.SS "\fBautoload\fP ('MSG_WAITALL', 'sockets\&.oct')"
.SS "\fBautoload\fP ('socket', 'sockets\&.oct')"
.SS "\fBautoload\fP ('connect', 'sockets\&.oct')"
.SS "\fBautoload\fP ('disconnect', 'sockets\&.oct')"
.SS "\fBautoload\fP ('gethostbyname', 'sockets\&.oct')"
.SS "\fBautoload\fP ('send', 'sockets\&.oct')"
.SS "\fBautoload\fP ('recv', 'sockets\&.oct')"
.SS "\fBautoload\fP ('bind', 'sockets\&.oct')"
.SS "\fBautoload\fP ('listen', 'sockets\&.oct')"
.SS "\fBautoload\fP ('accept', 'sockets\&.oct')"
.SS "\fBautoload\fP ('load_socket_constants', 'sockets\&.oct')"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
