.TH "/home/caio/mfiles/prova1.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/prova1.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "incia vetor Z3 Coluna \fBR03\fP (1, 1)"
.br
.ti -1c
.RI "\fBR03\fP (2, 1)"
.br
.ti -1c
.RI "\fBR03\fP (3, 1)"
.br
.ti -1c
.RI "Coluna \fBR03\fP (1, 2)"
.br
.ti -1c
.RI "\fBR03\fP (2, 2)"
.br
.ti -1c
.RI "\fBR03\fP (3, 2)=0"
.br
.ti -1c
.RI "Coluna \fBR03\fP (1, 3)"
.br
.ti -1c
.RI "\fBR03\fP (2, 3)"
.br
.ti -1c
.RI "\fBR03\fP (3, 3)"
.br
.ti -1c
.RI "\fBdisp\fP ('\fBR03\fP=') \fBdisp\fP(\fBR03\fP) X3"
.br
.ti -1c
.RI "q1 \fBq2\fP q3 \fBq4\fP \fBq5\fP \fBq6\fP Testes \fBprintf\fP ('Testes\\\fBn\fP\\\fBn\fP')"
.br
.ti -1c
.RI "id \fBM\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Configuracoes \fBclc\fP clear \fBd2\fP"
.br
.ti -1c
.RI "\fBARM\fP"
.br
.ti -1c
.RI "\fBq2\fP"
.br
.ti -1c
.RI "\fBq4\fP"
.br
.ti -1c
.RI "\fBq5\fP"
.br
.ti -1c
.RI "\fBq6\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBdisp\fP ('R03 = \fC'\fP)"
.SS "id \fBM\fP ()\fC [virtual]\fP"
.SS "q1 \fBq2\fP q3 \fBq4\fP \fBq5\fP \fBq6\fP Testes \fBprintf\fP ('Testes\\\fBn\fP\\\fBn\fP')"
.SS "incia vetor Z3 Coluna \fBR03\fP (1, 1)"
.SS "\fBR03\fP (2, 1)"
.SS "\fBR03\fP (3, 1)"
.SS "Coluna \fBR03\fP (1, 2)"
.SS "\fBR03\fP (2, 2)"
.SS "\fBR03\fP (3, 2)\fC [pure virtual]\fP"
.SS "Coluna \fBR03\fP (1, 3)"
.SS "\fBR03\fP (2, 3)"
.SS "\fBR03\fP (3, 3)"
.SH "Variable Documentation"
.PP 
.SS "\fBARM\fP"\fBInitial value:\fP
.PP
.nf
'\n\nAngulo teta4'

% Constantes auxiliares
C1=cosd(q1)
S1=sind(q1)
C23=cosd(q2+q3)
S23=sind(q2+q3)


R03=zeros(3,3)
.fi
.PP
Definition at line 20 of file prova1\&.m\&.
.SS "Configuracoes \fBclc\fP clear \fBd2\fP"\fBInitial value:\fP
.PP
.nf
1
a2=1

a3=-1

d4=1

d6=1


T=[ 0 , 1 , 0 ,-1
.fi
.PP
Definition at line 7 of file prova1\&.m\&.
.SS "\fBq2\fP"
.PP
Definition at line 163 of file prova1\&.m\&.
.SS "\fBq4\fP"
.PP
Definition at line 163 of file prova1\&.m\&.
.SS "\fBq5\fP"
.PP
Definition at line 163 of file prova1\&.m\&.
.SS "\fBq6\fP"
.PP
Definition at line 163 of file prova1\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
