.TH "/home/caio/mfiles/solar/pvcreate.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/solar/pvcreate.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP []"
.br
.ti -1c
.RI "\fBmodel\fP = input('Model:','\fBs\fP')"
.br
.ti -1c
.RI "\fBVoc\fP = input('Voc [A]:')"
.br
.ti -1c
.RI "\fBIsc\fP = input('Isc [A]:')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP[]"\fBInitial value:\fP
.PP
.nf
 pvcreate ()
%{
Cria Variavel Com parâmetros do  Modulo Fotovoltaico

uso: PV=pvcreate()

%}

manufacture=input('Manufacture:','s')
.fi
.PP
Definition at line 1 of file pvcreate\&.m\&.
.SS "\fBIsc\fP = input('Isc [A]:')"
.PP
Definition at line 12 of file pvcreate\&.m\&.
.SS "\fBmodel\fP = input('Model:','\fBs\fP')"
.PP
Definition at line 10 of file pvcreate\&.m\&.
.SS "\fBVoc\fP = input('Voc [A]:')"
.PP
Definition at line 11 of file pvcreate\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
