.TH "/home/caio/mfiles/sensor.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/sensor.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBSENSOR\fP"
.br
.ti -1c
.RI "\fBSENSOR\fP \fBSensorRange\fP = \fBSensorRange\fP"
.br
.ti -1c
.RI "\fBSENSOR\fP \fBCountsRange\fP = \fBCountsRange\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBSENSOR\fP \fBCountsRange\fP = \fBCountsRange\fP"
.PP
Definition at line 9 of file sensor\&.m\&.
.SS "\fBfunction\fP \fBSENSOR\fP"\fBInitial value:\fP
.PP
.nf
sensor(InputRange,SensorRange,CountsRange=[0,1024],units=['V' 'rpm'])
%
%   InputRange:  Voltage Value/Current Value
%   SensorRange: Measurement range
%   CountsRange: Analog Card counting
%   Units
SENSOR\&.InputRange=InputRange
.fi
.PP
Definition at line 1 of file sensor\&.m\&.
.SS "\fBSENSOR\fP \fBSensorRange\fP = \fBSensorRange\fP"
.PP
Definition at line 8 of file sensor\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
