.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/stem.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/stem.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (isempty(\fBax\fP)) \fBax\fP"
.br
.ti -1c
.RI "else \fBaxes\fP (\fBax\fP)"
.br
.ti -1c
.RI "\fBendif\fP \fBnewplot\fP ()"
.br
.ti -1c
.RI "\fBif\fP (isvector(\fBy\fP)) \fBy\fP"
.br
.ti -1c
.RI "\fBendif\fP \fBif\fP (isvector(\fBx\fP)) \fBx\fP"
.br
.ti -1c
.RI "endfor \fBif\fP (nargout > 0) \fBh\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBh\fP"
.br
.ti -1c
.RI "\fBendif\fP [\fBax\fP, \fBx\fP, \fBy\fP, \fBz\fP, \fBdofill\fP, \fBlc\fP, \fBls\fP, \fBmc\fP, \fBms\fP] = __parse_stem_args__ ('stem', 0, varargin{:})"
.br
.ti -1c
.RI "\fBendif\fP \fBn\fP = columns (\fBy\fP)"
.br
.ti -1c
.RI "\fBtmp\fP = \fBzeros\fP (1, \fBn\fP)"
.br
.ti -1c
.RI "for \fBk\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "else \fBaxes\fP (\fBax\fP)"
.SS "\fBif\fP (isempty(\fBax\fP))"
.SS "\fBif\fP (isvector(\fBy\fP))"
.SS "\fBendif\fP \fBif\fP (isvector(\fBx\fP))"
.SS "endfor \fBif\fP (nargout, 0)"
.SS "\fBendif\fP \fBnewplot\fP ()"
.SH "Variable Documentation"
.PP 
.SS "\fBendif\fP[\fBax\fP, \fBx\fP, \fBy\fP, \fBz\fP, \fBdofill\fP, \fBlc\fP, \fBls\fP, \fBmc\fP, \fBms\fP] = __parse_stem_args__ ('stem', 0, varargin{:})"
.PP
Definition at line 101 of file stem\&.m\&.
.SS "\fBfunction\fP \fBh\fP"\fBInitial value:\fP
.PP
.nf
 stem (varargin)

  if (nargin < 1 || nargin > 5)
    print_usage ()
.fi
.PP
Definition at line 95 of file stem\&.m\&.
.SS "for \fBk\fP"\fBInitial value:\fP
.PP
.nf
 1:n
    tmp(k) = __jhandles_go_stemseries (ax, x(:,k), y(:,k), [], dofill, lc, ls, mc, ms)
.fi
.PP
Definition at line 119 of file stem\&.m\&.
.SS "\fBendif\fP \fBn\fP = columns (\fBy\fP)"
.PP
Definition at line 116 of file stem\&.m\&.
.SS "\fBtmp\fP = \fBzeros\fP (1, \fBn\fP)"
.PP
Definition at line 118 of file stem\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
