.TH "/home/caio/mfiles/step1.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/step1.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBM\fP = 1"
.br
.ti -1c
.RI "\fBK\fP = 10"
.br
.ti -1c
.RI "\fBB\fP = 2"
.br
.ti -1c
.RI "\fBnum\fP = 1"
.br
.ti -1c
.RI "\fBden\fP = [\fBM\fP \fBB\fP \fBK\fP]"
.br
.ti -1c
.RI "\fBsys\fP = tf(\fBnum\fP,\fBden\fP)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBB\fP = 2"
.PP
Definition at line 3 of file step1\&.m\&.
.SS "\fBden\fP = [\fBM\fP \fBB\fP \fBK\fP]"
.PP
Definition at line 5 of file step1\&.m\&.
.SS "\fBK\fP = 10"
.PP
Definition at line 2 of file step1\&.m\&.
.SS "\fBM\fP = 1"
.PP
Definition at line 1 of file step1\&.m\&.
.SS "\fBnum\fP = 1"
.PP
Definition at line 4 of file step1\&.m\&.
.SS "\fBsys\fP = tf(\fBnum\fP,\fBden\fP)"
.PP
Definition at line 6 of file step1\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
