.TH "/home/caio/mfiles/stop.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/stop.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "Permite para \fBfun\fPção ou 
.br
script para testar variáveis 
.br
e valores \fBdisp\fP ('\\nModo debug entre \fBcom\fP \fBbreak\fP para sair\\\fBn\fP') while(true) userinputt"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Permite para \fBfun\fPção ou script para testar variáveis e valores \fBdisp\fP ('\\nModo debug entre \fBcom\fP \fBbreak\fP para sair\\\fBn\fP')"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
