.TH "/home/caio/mfiles/packages/jhandles-0.3.5/doc/testX.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/doc/testX.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (~is_octave) ax_view"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP [r1, r2]"
.br
.ti -1c
.RI "\fBax_proj\fP = \fBget\fP(gca, 'x_ProjectionTransform')"
.br
.ti -1c
.RI "\fBax_viewport\fP = \fBget\fP(gca, 'x_ViewPortTransform')"
.br
.ti -1c
.RI "\fBax_render\fP = \fBget\fP(gca, 'x_RenderTransform')"
.br
.ti -1c
.RI "\fBax_normrender\fP = \fBget\fP(gca, 'x_NormRenderTransform')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP (~is_octave)"
.SH "Variable Documentation"
.PP 
.SS "\fBax_normrender\fP = \fBget\fP(gca, 'x_NormRenderTransform')"
.PP
Definition at line 10 of file testX\&.m\&.
.SS "\fBax_proj\fP = \fBget\fP(gca, 'x_ProjectionTransform')"
.PP
Definition at line 7 of file testX\&.m\&.
.SS "\fBax_render\fP = \fBget\fP(gca, 'x_RenderTransform')"
.PP
Definition at line 9 of file testX\&.m\&.
.SS "\fBax_viewport\fP = \fBget\fP(gca, 'x_ViewPortTransform')"
.PP
Definition at line 8 of file testX\&.m\&.
.SS "\fBfunction\fP[r1, r2]"\fBInitial value:\fP
.PP
.nf
 testX

is_octave = (exist('octave_config_info') == 5)
.fi
.PP
Definition at line 1 of file testX\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
