.TH "/home/caio/mfiles/trabalho.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/trabalho.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBclc\fP () K1"
.br
.ti -1c
.RI "id \fBK3\fP ()"
.br
.ti -1c
.RI "id \fBC2\fP ()"
.br
.ti -1c
.RI "id \fBC3\fP ()"
.br
.ti -1c
.RI "id \fBsao:q:X:\fP (\fBw\fP \fBK\fP,[q] id Autovalor,[\fBX\fP] q A)"
.br
.ti -1c
.RI "C1+\fBC2\fP \fBM1\fP ()"
.br
.ti -1c
.RI "\fBC2\fP+\fBC3\fP \fBM2\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBM2\fP"
.br
.ti -1c
.RI "\fBM3\fP \fBK\fP = [ K1+K2, -K2 , 0"
.br
.ti -1c
.RI "\fBK3\fP \fBM3\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "id \fBC2\fP ()\fC [virtual]\fP"
.SS "id \fBC3\fP ()\fC [virtual]\fP"
.SS "\fBclc\fP ()"
.SS "id \fBK3\fP ()\fC [virtual]\fP"
.SS "C1+\fBC2\fP \fBM1\fP ()\fC [virtual]\fP"
.SS "\fBC2\fP+\fBC3\fP \fBM2\fP ()\fC [virtual]\fP"
.SS "id \fBsao:q:X:\fP (\fBw\fPK, [q] idAutovalor, [X] qA)\fC [virtual]\fP"
.SH "Variable Documentation"
.PP 
.SS "\fBM3\fP \fBK\fP = [ K1+K2, -K2 , 0"
.PP
Definition at line 24 of file trabalho\&.m\&.
.SS "K2 \fBM2\fP"
.PP
Definition at line 23 of file trabalho\&.m\&.
.SS "\fBK3\fP \fBM3\fP"
.PP
Definition at line 50 of file trabalho\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
