.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/uiresume.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/uiresume.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBuiresume\fP (\fBfig\fP) \fBif\fP(ishandle(\fBfig\fP)&&strcmp(\fBget\fP(\fBfig\fP"
.br
.ti -1c
.RI "\fBfunction\fP figure try \fBset\fP (\fBfig\fP,'__wait__','\fBoff\fP')"
.br
.ti -1c
.RI "end else \fBprint_usage\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBtype\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "end else \fBprint_usage\fP ()"
.SS "\fBfunction\fP figure try \fBset\fP (\fBfig\fP, '__wait__', 'off')"
.SS "\fBfunction\fP \fBuiresume\fP (\fBfig\fP)"
.SH "Variable Documentation"
.PP 
.SS "\fBfunction\fP \fBtype\fP"
.PP
Definition at line 18 of file uiresume\&.m\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
