.TH "/home/caio/mfiles/packages/jhandles-0.3.5/inst/waitfor.m" 3 "Tue Nov 27 2012" "Version 3.0" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/caio/mfiles/packages/jhandles-0.3.5/inst/waitfor.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunction\fP \fBwaitfor\fP (\fBh\fP, \fBvarargin\fP) \fBif\fP(ishandle(\fBh\fP)) \fBif\fP(nargin >"
.br
.ti -1c
.RI "else \fBprint_usage\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "else \fBprint_usage\fP ()"
.SS "\fBfunction\fP \fBwaitfor\fP (\fBh\fP, \fBvarargin\fP)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
