## Copyright (C) 2007 Michael Goffioul
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; If not, see <http://www.gnu.org/licenses/>.

function [ h ] = dialog (varargin)

# TODO: these properties should be added back, when supported
#    "BackingStore", "off", ...
#    "DockControls", "off", ...
#    "InvertHardcopy", "off", ...
#    "MenuBar", "none", ...
#    "PaperPositionMode", "auto", ...
#    "WindowStyle", "modal", ...

  args = {
    "ButtonDownFcn", "if isempty(allchild(gcbf)), close(gcbf), end", ...
    "Colormap", [], ...
    "Color", get(0, "DefaultUicontrolBackgroundColor"), ...
    "HandleVisibility", "callback", ...
    "IntegerHandle", "off", ...
    "NumberTitle", "off", ...
    "Resize", "off", ...
    "Toolbar", "none", ...
    "Visible", "on", ...
    varargin{:}};

  tmp = figure(args{:});
  if (nargout > 0)
    h = tmp;
  endif

endfunction
