.TH "packages/jhandles-0.3.5/inst/__get_parent_arg__.m" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/jhandles-0.3.5/inst/__get_parent_arg__.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fB__get_parent_arg__\fP (in p, in args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fB__get_parent_arg__\fP (inp, inargs)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
