.TH "packages/jhandles-0.3.5/inst/__jhandles_go_stemseries.m" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/jhandles-0.3.5/inst/__jhandles_go_stemseries.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fB__jhandles_go_stemseries\fP (in ax, in x, in y, in z, in dofill, in lc, in ls, in mc, in ms)"
.br
.ti -1c
.RI "function \fBupdateStemData\fP (in h, in evt)"
.br
.ti -1c
.RI "function \fBupdateBaseValue\fP (in h, in evt)"
.br
.ti -1c
.RI "function \fBupdateLineData\fP (in h, in evt, in hl)"
.br
.ti -1c
.RI "function \fBupdateBaseLineBaseValue\fP (in h, in evt, in h2)"
.br
.ti -1c
.RI "function \fBupdateShowBaseLine\fP (in h, in evt)"
.br
.ti -1c
.RI "function \fBupdateBaseLineVisible\fP (in hb, in evt, in h)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fB__jhandles_go_stemseries\fP (inax, inx, iny, inz, indofill, inlc, inls, inmc, inms)"
.SS "function \fBupdateBaseLineBaseValue\fP (inh, inevt, inh2)"
.SS "function \fBupdateBaseLineVisible\fP (inhb, inevt, inh)"
.SS "function \fBupdateBaseValue\fP (inh, inevt)"
.SS "function \fBupdateLineData\fP (inh, inevt, inhl)"
.SS "function \fBupdateShowBaseLine\fP (inh, inevt)"
.SS "function \fBupdateStemData\fP (inh, inevt)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
