.TH "packages/jhandles-0.3.5/inst/__parse_stem_args__.m" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/jhandles-0.3.5/inst/__parse_stem_args__.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fB__parse_stem_args__\fP (in name, in is3D, in varargin)"
.br
.ti -1c
.RI "function \fBstem_line_spec\fP (in name, in str)"
.br
.ti -1c
.RI "function \fBset_default_values\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fB__parse_stem_args__\fP (inname, inis3D, invarargin)"
.SS "function \fBset_default_values\fP ()"
.SS "function \fBstem_line_spec\fP (inname, instr)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
