.TH "GL2PSbsptree" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSbsptree \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSplane\fP \fBplane\fP"
.br
.ti -1c
.RI "\fBGL2PSlist\fP * \fBprimitives\fP"
.br
.ti -1c
.RI "GL2PSbsptree * \fBfront\fP"
.br
.ti -1c
.RI "GL2PSbsptree * \fBback\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GL2PSbsptree * \fBback\fP"
.SS "GL2PSbsptree* \fBfront\fP"
.SS "\fBGL2PSplane\fP \fBplane\fP"
.SS "\fBGL2PSlist\fP* \fBprimitives\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
