.TH "GL2PSimagemap" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSimagemap \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSimage\fP * \fBimage\fP"
.br
.ti -1c
.RI "GL2PSimagemap * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBGL2PSimage\fP* \fBimage\fP"
.SS "GL2PSimagemap* \fBnext\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
