.TH "ActionListener" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCheckBoxControl\fP, \fBEditControl\fP, \fBFigureObject\fP, \fBPopupMenuControl\fP, and \fBPushButtonControl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
