.TH "packages/jhandles-0.3.5/inst/colorbar.m" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/jhandles-0.3.5/inst/colorbar.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBcolorbar\fP (in varargin)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fBcolorbar\fP (invarargin)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
