.TH "GL2PStriangle" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PStriangle \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSvertex\fP \fBvertex\fP [3]"
.br
.ti -1c
.RI "int \fBprop\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int \fBprop\fP"
.PP
Referenced by gl2psAssignTriangleProperties(), gl2psInitTriangle(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "\fBGL2PSvertex\fP \fBvertex\fP[3]"
.PP
Referenced by gl2psAssignTriangleProperties(), gl2psFillTriangleFromPrimitive(), gl2psInitTriangle(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFRectHull(), and gl2psPrintPDFShaderStreamData()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
