.TH "GL2PSpdfgroup" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSpdfgroup \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSlist\fP * \fBptrlist\fP"
.br
.ti -1c
.RI "int \fBgsno\fP"
.br
.ti -1c
.RI "int \fBfontno\fP"
.br
.ti -1c
.RI "int \fBimno\fP"
.br
.ti -1c
.RI "int \fBshno\fP"
.br
.ti -1c
.RI "int \fBmaskshno\fP"
.br
.ti -1c
.RI "int \fBtrgroupno\fP"
.br
.ti -1c
.RI "int \fBgsobjno\fP"
.br
.ti -1c
.RI "int \fBfontobjno\fP"
.br
.ti -1c
.RI "int \fBimobjno\fP"
.br
.ti -1c
.RI "int \fBshobjno\fP"
.br
.ti -1c
.RI "int \fBmaskshobjno\fP"
.br
.ti -1c
.RI "int \fBtrgroupobjno\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int \fBfontno\fP"
.PP
Referenced by gl2psPDFgroupListInit(), gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBfontobjno\fP"
.PP
Referenced by gl2psPDFgroupListWriteFontResources(), gl2psPDFgroupListWriteObjects(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBgsno\fP"
.PP
Referenced by gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBgsobjno\fP"
.PP
Referenced by gl2psPDFgroupListWriteGStateResources(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBimno\fP"
.PP
Referenced by gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteXObjectResources(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBimobjno\fP"
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), and gl2psPDFgroupObjectInit()\&.
.SS "int \fBmaskshno\fP"
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBmaskshobjno\fP"
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "\fBGL2PSlist\fP* \fBptrlist\fP"
.PP
Referenced by gl2psPDFgroupListDelete(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBshno\fP"
.PP
Referenced by gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBshobjno\fP"
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteShaderResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBtrgroupno\fP"
.PP
Referenced by gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteXObjectResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.
.SS "int \fBtrgroupobjno\fP"
.PP
Referenced by gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPDFgroupObjectInit(), and gl2psSortOutTrianglePDFgroup()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
