.TH "GL2PSimage" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSimage \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLsizei \fBwidth\fP"
.br
.ti -1c
.RI "GLsizei \fBheight\fP"
.br
.ti -1c
.RI "GLenum \fBformat\fP"
.br
.ti -1c
.RI "GLenum \fBtype\fP"
.br
.ti -1c
.RI "GLfloat * \fBpixels\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GLenum \fBformat\fP"
.PP
Referenced by gl2psAddInImageTree(), gl2psCopyPixmap(), gl2psDrawPixels(), gl2psGetRGB(), gl2psPDFgroupListWriteObjects(), gl2psPDFgroupListWriteXObjectResources(), gl2psPrintPDFPixmap(), and gl2psPrintPDFPixmapStreamData()\&.
.SS "GLsizei \fBheight\fP"
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), gl2psGetRGB(), gl2psPrintPDFPixmap(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPostScriptPixmap(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPixmap(), and gl2psPutPDFImage()\&.
.SS "GLfloat* \fBpixels\fP"
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), gl2psFreePixmap(), gl2psGetRGB(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLenum \fBtype\fP"
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLsizei \fBwidth\fP"
.PP
Referenced by gl2psCopyPixmap(), gl2psDrawPixels(), gl2psGetRGB(), gl2psPrintPDFPixmap(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPostScriptPixmap(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPixmap(), and gl2psPutPDFImage()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
