.TH "GL2PSstring" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSstring \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GLshort \fBfontsize\fP"
.br
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "char * \fBfontname\fP"
.br
.ti -1c
.RI "GLint \fBalignment\fP"
.br
.ti -1c
.RI "GLfloat \fBangle\fP"
.br
.ti -1c
.RI "GLfloat \fBmargin\fP"
.br
.ti -1c
.RI "GLboolean \fBoffsetmargin\fP"
.br
.ti -1c
.RI "GLfloat \fBlinewidth\fP"
.br
.ti -1c
.RI "\fBGL2PSrgba\fP \fBlinecolor\fP"
.br
.ti -1c
.RI "GLushort \fBlinepattern\fP"
.br
.ti -1c
.RI "GLint \fBlinefactor\fP"
.br
.ti -1c
.RI "\fBGL2PSrgba\fP \fBfillcolor\fP"
.br
.ti -1c
.RI "GLboolean \fBdepthtest\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GLint \fBalignment\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), and gl2psPrintTeXPrimitive()\&.
.SS "GLfloat \fBangle\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), and gl2psPrintTeXPrimitive()\&.
.SS "GLboolean \fBdepthtest\fP"
.PP
Referenced by gl2psAddText(), gl2psBuildBspTree(), and gl2psCopyText()\&.
.SS "\fBGL2PSrgba\fP \fBfillcolor\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "char * \fBfontname\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psFreeText(), gl2psPrintPDFText(), gl2psPrintPostScriptPrimitive(), and gl2psPrintSVGPrimitive()\&.
.SS "GLshort \fBfontsize\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), and gl2psPutPDFText()\&.
.SS "\fBGL2PSrgba\fP \fBlinecolor\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLint \fBlinefactor\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLushort \fBlinepattern\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLfloat \fBlinewidth\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLfloat \fBmargin\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "GLboolean \fBoffsetmargin\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), and gl2psPrintPostScriptPrimitive()\&.
.SS "char* \fBstr\fP"
.PP
Referenced by gl2psAddText(), gl2psCopyText(), gl2psFreeText(), gl2psPDFgroupListWriteObjects(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), and gl2psPutPDFText()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
