.TH "GL2PSvertex" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GL2PSvertex \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGL2PSxyz\fP \fBxyz\fP"
.br
.ti -1c
.RI "\fBGL2PSrgba\fP \fBrgba\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBGL2PSrgba\fP \fBrgba\fP"
.PP
Referenced by gl2psAdaptVertexForBlending(), gl2psAddBoundaryInList(), gl2psAddText(), gl2psAssignTriangleProperties(), gl2psBeginPage(), gl2psCutEdge(), gl2psDrawPixels(), gl2psEndPostScriptLine(), gl2psEndSVGLine(), gl2psGetVertex(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListInit(), gl2psPDFgroupListWriteMainStream(), gl2psPDFgroupListWriteObjects(), gl2psPrintPDFShaderStreamDataAlpha(), gl2psPrintPDFShaderStreamDataRGB(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), and gl2psVertsSameColor()\&.
.SS "\fBGL2PSxyz\fP \fBxyz\fP"
.PP
Referenced by gl2psAddBoundaryInList(), gl2psAddPlanesInBspTreeImage(), gl2psAddText(), gl2psBeginPage(), gl2psCheckPrimitive(), gl2psCompareDepth(), gl2psComputeTightBoundingBox(), gl2psCutEdge(), gl2psDrawPixels(), gl2psEndPostScriptLine(), gl2psEndSVGLine(), gl2psGetPlane(), gl2psGetVertex(), gl2psParseFeedbackBuffer(), gl2psPDFgroupListWriteMainStream(), gl2psPDFRectHull(), gl2psPrintPDFShaderStreamDataCoord(), gl2psPrintPGFPrimitive(), gl2psPrintPostScriptPrimitive(), gl2psPrintSVGPrimitive(), gl2psPrintTeXPrimitive(), gl2psRescaleAndOffset(), gl2psSplitPrimitive(), gl2psSplitPrimitive2D(), gl2psSVGGetCoordsAndColors(), and gl2psTestSplitPrimitive()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
