PatchObject
NAME
PatchObject -
SYNOPSIS
Inherits GraphicObject.
Public Member Functions
PatchObject (HandleObject parent)
void validate ()
void draw (Renderer r)
void propertyChanged (Property p) throws PropertyException
AxesObject getAxes ()
void set (Property p, Object value) throws PropertyException
void set (String name, Object value) throws PropertyException
boolean isLegendable ()
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
void delete ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
java.awt.Component getComponent ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
Object get (Property p)
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Protected Member Functions
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
int glID
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Functions
double[][] getCData ()
double[] getAlphaData ()
int[] getFaceCount ()
Package Attributes
DoubleProperty __Index__
ArrayProperty Faces
ArrayProperty Vertices
ArrayProperty FaceVertexCData
RadioProperty CDataMapping
VectorProperty FaceVertexAlphaData
RadioProperty AlphaDataMapping
ColorProperty FaceColor
ColorProperty EdgeColor
RadioProperty FaceLighting
RadioProperty EdgeLighting
DoubleRadioProperty FaceAlpha
DoubleRadioProperty EdgeAlpha
LineStyleProperty LineStyle
DoubleProperty LineWidth
MarkerProperty Marker
ColorProperty MarkerEdgeColor
ColorProperty MarkerFaceColor
DoubleProperty MarkerSize
DoubleProperty AmbientStrength
DoubleProperty DiffuseStrength
DoubleProperty SpecularStrength
DoubleProperty SpecularExponent
ArrayProperty VertexNormals
ArrayProperty XData
ArrayProperty YData
ArrayProperty ZData
ArrayProperty CData
VectorProperty XLim
VectorProperty YLim
VectorProperty ZLim
VectorProperty CLim
VectorProperty ALim
BooleanProperty XLimInclude
BooleanProperty YLimInclude
BooleanProperty ZLimInclude
BooleanProperty CLimInclude
BooleanProperty ALimInclude
BooleanProperty LegendInclude
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
void updateMinMax ()
void updateXYZData ()
void updateCData ()
boolean checkXYZData ()
void updateFVData ()
void updateFVCData ()
boolean checkConsistency ()
void updateFaceCount ()
Matrix computeNormals ()
Private Attributes
int[] faceCount
Constructor & Destructor Documentation
PatchObject (HandleObjectparent) [inline]
References PatchObject.__Index__, GraphicObject.ALimInclude, PatchObject.AlphaDataMapping, PatchObject.AmbientStrength, PatchObject.CData, PatchObject.CDataMapping, GraphicObject.CLimInclude, PatchObject.DiffuseStrength, PatchObject.EdgeAlpha, PatchObject.EdgeColor, PatchObject.EdgeLighting, PatchObject.FaceAlpha, PatchObject.FaceColor, PatchObject.FaceLighting, PatchObject.Faces, PatchObject.FaceVertexAlphaData, PatchObject.FaceVertexCData, PatchObject.LineStyle, PatchObject.LineWidth, HandleObject.listen(), PatchObject.Marker, PatchObject.MarkerEdgeColor, PatchObject.MarkerFaceColor, PatchObject.MarkerSize, Property.reset(), Property.setVisible(), PatchObject.SpecularExponent, PatchObject.SpecularStrength, PatchObject.VertexNormals, PatchObject.Vertices, PatchObject.XData, PatchObject.YData, PatchObject.ZData, and GraphicObject.ZLimInclude.
        {
                super(parent, 'patch');
                Faces = new ArrayProperty(this, 'Faces', new String[] {'double'}, 2, null);
                Vertices = new ArrayProperty(this, 'Vertices', new String[] {'double'}, 2, null);
                FaceVertexCData = new ArrayProperty(this, 'FaceVertexCData', new String[] {'double', 'byte'}, 2, null);
                CDataMapping = new RadioProperty(this, 'CDataMapping', new String[] {'direct', 'scaled'}, 'scaled');
                FaceVertexAlphaData = new VectorProperty(this, 'FaceVertexAlphaData', -1, new double[0]);
                AlphaDataMapping = new RadioProperty(this, 'AlphaDataMapping', new String[] {'none', 'scaled', 'direct'}, 'scaled');
                FaceColor = new ColorProperty(this, 'FaceColor', new String[] {'none', 'flat', 'interp'}, Color.black);
                EdgeColor = new ColorProperty(this, 'EdgeColor', new String[] {'none', 'flat', 'interp'}, Color.black);
                FaceLighting = new RadioProperty(this, 'FaceLighting', new String[] {'none', 'flat', 'gouraud', 'phong'}, 'none');
                EdgeLighting = new RadioProperty(this, 'EdgeLighting', new String[] {'none', 'flat', 'gouraud', 'phong'}, 'none');
                FaceAlpha = new DoubleRadioProperty(this, 'FaceAlpha', new String[] {'flat', 'interp'}, 1.0);
                EdgeAlpha = new DoubleRadioProperty(this, 'EdgeAlpha', new String[] {'flat', 'interp'}, 1.0);
                LineStyle = new LineStyleProperty(this, 'LineStyle', '-');
                LineWidth = new DoubleProperty(this, 'LineWidth', 0.5);
                Marker = new MarkerProperty(this, 'Marker', 'none');
                MarkerSize = new DoubleProperty(this, 'MarkerSize', 7.0);
                MarkerEdgeColor = new ColorProperty(this, 'MarkerEdgeColor', new String[] {'none', 'auto', 'flat'}, 'auto');
                MarkerFaceColor = new ColorProperty(this, 'MarkerFaceColor', new String[] {'none', 'auto', 'flat'}, 'none');
                AmbientStrength = new DoubleProperty(this, 'AmbientStrength', 0.3);
                DiffuseStrength = new DoubleProperty(this, 'DiffuseStrength', 0.6);
                SpecularStrength = new DoubleProperty(this, 'SpecularStrength', 0.9);
                SpecularExponent = new DoubleProperty(this, 'SpecularExponent', 10);
                VertexNormals = new ArrayProperty(this, 'VertexNormals', new String[] {'double'}, 2, null);
                __Index__ = new DoubleProperty(this, '__Index__', 0);
                __Index__.setVisible(false);
                XData = new ArrayProperty(this, 'XData', new String[] {'double'}, 2, null);
                YData = new ArrayProperty(this, 'YData', new String[] {'double'}, 2, null);
                ZData = new ArrayProperty(this, 'ZData', new String[] {'double'}, 2, null);
                CData = new ArrayProperty(this, 'CData', new String[] {'double'}, -1, null);
                ZLimInclude.reset(new Boolean(true));
                CLimInclude.reset(new Boolean(true));
                ALimInclude.reset(new Boolean(true));
                listen(Faces);
                listen(Vertices);
                listen(FaceVertexCData);
                listen(XData);
                listen(YData);
                listen(ZData);
                listen(CData);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
boolean checkConsistency () [inline, private]
References PatchObject.EdgeColor, PatchObject.FaceColor, PatchObject.Faces, PatchObject.FaceVertexCData, ArrayProperty.getDim(), ColorProperty.is(), ColorProperty.isSet(), MarkerProperty.isSet(), PatchObject.Marker, PatchObject.MarkerEdgeColor, PatchObject.MarkerFaceColor, and PatchObject.Vertices.
Referenced by PatchObject.draw().
        {
                int nf = Faces.getDim(0), nv = Vertices.getDim(0), nfv = FaceVertexCData.getDim(0);
                if (nf == 0 || nv == 0)
                        return false;
                if (!FaceColor.isSet() && !FaceColor.is('none'))
                {
                        if (FaceColor.is('flat') && nfv != nf && nfv != nv && nfv != 1)
                        {
                                System.err.println('Warning: Color data must be given per-face');
                                return false;
                        }
                        else if (FaceColor.is('interp') && nfv != nv && nfv != 1)
                        {
                                System.err.println('Warning: Color data must be given per-vertex');
                                return false;
                        }
                }
                if (!EdgeColor.isSet() && !EdgeColor.is('none'))
                {
                        if (nfv != nv && nfv != 1)
                        {
                                System.err.println('Warning: Color data must be given per-vertex');
                                return false;
                        }
                }
                if (Marker.isSet())
                {
                        if ((!MarkerEdgeColor.isSet() && (MarkerEdgeColor.is('flat') ||
                                (MarkerEdgeColor.is('auto') && (EdgeColor.is('flat') || EdgeColor.is('interp'))))) ||
                            (!MarkerFaceColor.isSet() && (MarkerFaceColor.is('flat') ||
                                (MarkerFaceColor.is('auto') && (EdgeColor.is('flat') || EdgeColor.is('interp'))))))
                        {
                                if (nfv != nv && nfv != 1)
                                {
                                        System.err.println('Warning: Color data must be given per-vertex');
                                        return false;
                                }
                        }
                }
                return true;
        }
boolean checkXYZData () [inline, private]
References ArrayProperty.getDim(), ArrayProperty.getNDims(), ArrayProperty.isEmpty(), PatchObject.XData, PatchObject.YData, and PatchObject.ZData.
Referenced by PatchObject.updateFVCData(), and PatchObject.updateFVData().
        {
                boolean has_z = !ZData.isEmpty();
                if (XData.isEmpty() || YData.isEmpty())
                        return false;
                if (XData.getNDims() != YData.getNDims() || (has_z && XData.getNDims() != ZData.getNDims()))
                        return false;
                for (int i=0; i<XData.getNDims(); i++)
                        if (XData.getDim(i) != YData.getDim(i) || (has_z && XData.getDim(i) != ZData.getDim(i)))
                                return false;
                return true;
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
Matrix computeNormals () [inline, private]
References ArrayProperty.asDoubleMatrix(), Utils.crossProduct(), PatchObject.faceCount, PatchObject.Faces, and PatchObject.Vertices.
Referenced by PatchObject.propertyChanged(), and PatchObject.validate().
        {
                double[][] f = Faces.asDoubleMatrix();
                double[][] v = Vertices.asDoubleMatrix();
                if (f == null || v == null || f.length == 0 || v.length == 0)
                        return null;
                boolean has_z = (v[0].length > 2);
                int nv = v.length;
                double[][] n = new double[nv][3];
                double[] vCount = new double[v.length];
                int vIndex;
                for (int i=0; i<f.length; i++)
                {
                        if (faceCount[i] <= 2)
                                continue;
                        double[] v1 = v[(int)f[i][0]-1], vp = v[(int)f[i][1]-1], vc = v[(int)f[i][2]-1];
                        if (has_z)
                        {
                                Utils.crossProduct(
                                        v1[0]-vp[0], v1[1]-vp[1], v1[2]-vp[2],
                                        vc[0]-vp[0], vc[1]-vp[1], vc[2]-vp[2],
                                        n[(int)f[i][1]-1]);
                                Utils.crossProduct(
                                        v1[0]-vp[0], v1[1]-vp[1], v1[2]-vp[2],
                                        vc[0]-vp[0], vc[1]-vp[1], vc[2]-vp[2],
                                        n[(int)f[i][0]-1]);
                        }
                        else
                        {
                                Utils.crossProduct(
                                        v1[0]-vp[0], v1[1]-vp[1], 0,
                                        vc[0]-vp[0], vc[1]-vp[1], 0,
                                        n[(int)f[i][1]-1]);
                                Utils.crossProduct(
                                        v1[0]-vp[0], v1[1]-vp[1], 0,
                                        vc[0]-vp[0], vc[1]-vp[1], 0,
                                        n[(int)f[i][0]-1]);
                        }
                        vCount[(int)f[i][0]-1]++;
                        vCount[(int)f[i][1]-1]++;
                        for (int j=2; j<faceCount[i]; j++)
                        {
                                vIndex = (int)(f[i][j]-1);
                                vc = v[vIndex];
                                if (has_z)
                                        Utils.crossProduct(
                                                vp[0]-vc[0], vp[1]-vc[1], vp[2]-vc[2],
                                                v1[0]-vc[0], v1[1]-vc[1], v1[2]-vc[2],
                                                n[vIndex]);
                                else
                                        Utils.crossProduct(
                                                vp[0]-vc[0], vp[1]-vc[1], 0,
                                                v1[0]-vc[0], v1[1]-vc[1], 0,
                                                n[vIndex]);
                                vCount[vIndex]++;
                                vp = vc;
                        }
                }
                for (int i=0; i<v.length; i++)
                {
                        if (vCount[i] > 0)
                        {
                                n[i][0] /= vCount[i];
                                n[i][1] /= vCount[i];
                                n[i][2] /= vCount[i];
                        }
                }
                return new Matrix(n);
        }
void delete () [inline, inherited]
Reimplemented from PropertySet.
Reimplemented in FigureObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
References HandleObject.BeingDeleted, HandleObject.cachedData, HandleEventSourceHelper.delete(), HandleObject.deleteChildren(), HandleObject.DeleteFcn, HandleObjectListProperty.elementAt(), HandleObject.eventSource, HandleObject.eventSourceSet, CallbackProperty.execute(), HandleEventSourceHelper.fireEvent(), HandleObject.getHandle(), HandleObject.Parent, HandleObject.removeChild(), HandleObject.removeHandleEventSink(), HandleObject.removeHandleObject(), and Property.reset().
Referenced by HandleObject.deleteChildren(), AxesObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), and AxesObject.makeLegend().
        {
                BeingDeleted.reset('on');
                try { eventSource.fireEvent('ObjectDeleted'); }
                catch (PropertyException ex) {}
                DeleteFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
                removeHandleObject(getHandle());
                super.delete();
                Iterator it = eventSourceSet.iterator();
                while (it.hasNext())
                        ((HandleEventSource)it.next()).removeHandleEventSink(this);
                eventSource.delete();
                deleteChildren();
                if (cachedData != null)
                        cachedData.dispose();
                Parent.elementAt(0).removeChild(this);
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void draw (Rendererr) [inline, virtual]
Implements GraphicObject.
References PatchObject.checkConsistency(), and Renderer.draw().
        {
                if (checkConsistency())
                {
                        r.draw(this);
                }
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
double [] getAlphaData () [inline, package]
References AxesObject.ALim, PatchObject.AlphaDataMapping, FigureObject.Alphamap, PatchObject.FaceVertexAlphaData, VectorProperty.getArray(), GraphicObject.getAxes(), AxesObject.getFigure(), and RadioProperty.is().
Referenced by GLRenderer.draw().
        {
                if (AlphaDataMapping.is('none'))
                        return FaceVertexAlphaData.getArray();
                else if (AlphaDataMapping.is('direct'))
                {
                        double[] amap = getAxes().getFigure().Alphamap.getArray();
                        double[] aa = FaceVertexAlphaData.getArray();
                        double[] res = new double[aa.length];
                        for (int i=0; i<res.length; i++)
                                res[i] = amap[(int)Math.min(Math.max(1, aa[i]), amap.length)-1];
                        return res;
                }
                else if (AlphaDataMapping.is('scaled'))
                {
                        double[] amap = getAxes().getFigure().Alphamap.getArray();
                        double[] aa = FaceVertexAlphaData.getArray();
                        double[] alim = getAxes().ALim.getArray();
                        double[] res = new double[aa.length];
                        for (int i=0; i<aa.length; i++)
                        {
                                double s = (aa[i]-alim[0])/(alim[1]-alim[0]);
                                res[i] = amap[(int)Math.round((amap.length-1)*s)];
                        }
                        return res;
                }
                return null;
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxes () [inline, inherited]
References HandleObjectListProperty.elementAt(), and HandleObject.Parent.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), J2DRenderer.draw(), GLRenderer.draw(), TextObject.drawAsImage(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), SurfaceObject.getCData(), PatchObject.getCData(), TextObject.getExtent(), ImageObject.ImageObject(), BaseLineObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.SurfaceObject(), TextObject.toPostScript(), TextObject.updateData(), BaseLineObject.updateLine(), and TextObject.updateMinMax().
        {
                HandleObject obj = Parent.elementAt(0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                else
                        return ((GraphicObject)obj).getAxes();
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
double [][] getCData () [inline, package]
References ArrayProperty.asDoubleMatrix(), ArrayProperty.asDoubleVector(), PatchObject.CDataMapping, AxesObject.convertCData(), PatchObject.FaceVertexCData, GraphicObject.getAxes(), ArrayProperty.getDim(), and RadioProperty.getValue().
Referenced by GLRenderer.draw().
        {
                if (FaceVertexCData.getDim(1) == 3)
                        /* true colors */
                        return FaceVertexCData.asDoubleMatrix();
                else if (FaceVertexCData.getDim(1) == 1)
                        /* indexed colors */
                        return getAxes().convertCData(FaceVertexCData.asDoubleVector(), CDataMapping.getValue());
                else
                        return null;
        }
java.awt.Component getComponent () [inline, inherited]
Reimplemented in FigureObject, UIPanelObject, and UIControlObject.
Referenced by UIControlObject.getParentComponent(), and UIPanelObject.getParentComponent().
        {
                System.out.println('Warning: no component associated with ' + getClass());
                return null;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
int [] getFaceCount () [inline, package]
References PatchObject.faceCount.
Referenced by GLRenderer.draw().
        {
                return faceCount;
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented from HandleObject.
Reimplemented in BaseLineObject.
References BooleanProperty.isSet(), and GraphicObject.LegendInclude.
        {
                return LegendInclude.isSet();
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from HandleObject.
References PatchObject.CData, PatchObject.computeNormals(), PatchObject.Faces, PatchObject.FaceVertexCData, HandleObject.isAutoMode(), Property.set(), PatchObject.updateCData(), PatchObject.updateFaceCount(), PatchObject.updateFVCData(), PatchObject.updateFVData(), PatchObject.updateMinMax(), PatchObject.updateXYZData(), PatchObject.VertexNormals, PatchObject.Vertices, PatchObject.XData, PatchObject.YData, and PatchObject.ZData.
        {
                super.propertyChanged(p);
                if (!isAutoMode())
                {
                        if (p == XData || p == YData || p == ZData || p == CData)
                        {
                                updateFVData();
                                updateFVCData();
                                updateFaceCount();
                                updateMinMax();
                                VertexNormals.set(computeNormals());
                        }
                        else if (p == Faces || p == Vertices || p == FaceVertexCData)
                        {
                                if (p == Faces)
                                        updateFaceCount();
                                if (p == Vertices || p == FaceVertexCData)
                                        updateMinMax();
                                if (p == Faces || p == Vertices)
                                {
                                        VertexNormals.set(computeNormals());
                                        updateXYZData();
                                }
                                updateCData();
                        }
                }
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References FigureObject.__Dirty__, HandleObject.getAncestor(), and Property.reset().
Referenced by LegendObject.propertyChanged().
        {
                super.set(p, value);
                FigureObject fig = (FigureObject)getAncestor('figure');
                fig.__Dirty__.reset('on');
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void updateCData () [inline, private]
References ArrayProperty.asDoubleMatrix(), HandleObject.autoSet(), PatchObject.CData, PatchObject.Faces, PatchObject.FaceVertexCData, ArrayProperty.getDim(), ArrayProperty.isEmpty(), and PatchObject.Vertices.
Referenced by PatchObject.propertyChanged(), and PatchObject.validate().
        {
                if (FaceVertexCData.isEmpty() || Faces.isEmpty() || Vertices.isEmpty())
                        return;
                double[][] fv = FaceVertexCData.asDoubleMatrix();
                int nf = Faces.getDim(0), nv = Vertices.getDim(0), nfv = FaceVertexCData.getDim(0);
                boolean is_true_color = (FaceVertexCData.getDim(1) == 3);
                Matrix m = null;
                if (nfv == nf)
                {
                        // per-face color specification
                        if (is_true_color)
                        {
                                double[] c = new double[nf*3];
                                int[] dims = new int[] {1, nf, 3};
                                for (int i=0; i<fv.length; i++)
                                {
                                        c[i] = fv[i][0];
                                        c[i+nf] = fv[i][1];
                                        c[i+2*nf] = fv[i][2];
                                }
                                m = new Matrix(c, dims);
                        }
                        else
                        {
                                double[] c = new double[nf];
                                int[] dims = new int[] {1, nf};
                                for (int i=0; i<fv.length; i++)
                                        c[i] = fv[i][0];
                                m = new Matrix(c, dims);
                        }
                }
                else if (nfv == nv)
                {
                        double[][] f = Faces.asDoubleMatrix();
                        double[][] v = Vertices.asDoubleMatrix();
                        // per-vertex color specification
                        if (is_true_color)
                        {
                                int cx = Faces.getDim(1);
                                double[] c = new double[nf*cx*3];
                                int[] dims = new int[] {cx, nf, 3};
                        
                                for (int j=0; j<nf; j++)
                                {
                                        int idx = j*cx;
                                        for (int i=0; i<cx && !Double.isNaN(f[j][i]); i++, idx++)
                                        {
                                                int vidx = (int)f[j][i]-1;
                                                if (vidx < 0 || vidx >= v.length)
                                                        return;
                                                c[idx] = fv[vidx][0];
                                                c[idx+nf*cx] = fv[vidx][1];
                                                c[idx+2*nf*cx] = fv[vidx][2];
                                        }
                                }
                                m = new Matrix(c, dims);
                        }
                        else
                        {
                                int cx = Faces.getDim(1);
                                double[] c = new double[nf*cx];
                                int[] dims = new int[] {cx, nf};
                        
                                for (int j=0; j<nf; j++)
                                {
                                        int idx = j*cx;
                                        for (int i=0; i<cx && !Double.isNaN(f[j][i]); i++, idx++)
                                        {
                                                int vidx = (int)f[j][i]-1;
                                                if (vidx < 0 || vidx >= v.length)
                                                        return;
                                                c[idx] = fv[vidx][0];
                                        }
                                }
                                m = new Matrix(c, dims);
                        }
                }
                else if (nfv == 1)
                {
                }
                if (m != null)
                        autoSet(CData, m);
        }
void updateFaceCount () [inline, private]
References ArrayProperty.asDoubleMatrix(), PatchObject.faceCount, and PatchObject.Faces.
Referenced by PatchObject.propertyChanged(), and PatchObject.validate().
        {
                double[][] f = Faces.asDoubleMatrix();
                if (f != null)
                {
                        faceCount = new int[f.length];
                        for (int i=0; i<f.length; i++)
                                for (int j=0; j<f[i].length; j++)
                                        if (Double.isNaN(f[i][j]))
                                                break;
                                        else
                                                faceCount[i]++;
                }
        }
void updateFVCData () [inline, private]
References ArrayProperty.asDoubleVector(), HandleObject.autoSet(), PatchObject.CData, PatchObject.checkXYZData(), PatchObject.FaceVertexCData, ArrayProperty.getDim(), ArrayProperty.getNDims(), ArrayProperty.isEmpty(), and PatchObject.XData.
Referenced by PatchObject.propertyChanged(), and PatchObject.validate().
        {
                if (!checkXYZData() || CData.isEmpty())
                        return;
                boolean is_true_color = (CData.getNDims() == 3 && CData.getDim(2) == 3);
                Matrix m = null;
                if (CData.getDim(0) == 1)
                {
                        // pre-face color specification
                        int nf = CData.getDim(1);
                        double[] cd = CData.asDoubleVector();
                        double[] c = (double[])cd.clone();
                        if (is_true_color)
                                m = new Matrix(c, new int[] {nf, 3});
                        else
                                m = new Matrix(c, new int[] {nf, 1});
                }
                else
                {
                        // per-vertex color specification
                        double[] cd = CData.asDoubleVector();
                        double[] c = (double[])cd.clone();
                        int cn = XData.getDim(0)*XData.getDim(1);
                        if (is_true_color)
                                m = new Matrix(c, new int[] {cn, 3});
                        else
                                m = new Matrix(c, new int[] {cn, 1});
                }
                if (m != null)
                        autoSet(FaceVertexCData, m);
        }
void updateFVData () [inline, private]
References ArrayProperty.asDoubleMatrix(), HandleObject.autoSet(), PatchObject.checkXYZData(), PatchObject.Faces, ArrayProperty.getDim(), ArrayProperty.isEmpty(), PatchObject.Vertices, plt.x, PatchObject.XData, plt.y, PatchObject.YData, and PatchObject.ZData.
Referenced by PatchObject.propertyChanged(), and PatchObject.validate().
        {
                if (!checkXYZData())
                        return;
                int n = XData.getDim(1), m = XData.getDim(0);
                double[][] x = XData.asDoubleMatrix();
                double[][] y = YData.asDoubleMatrix();
                boolean has_z = !ZData.isEmpty();
                double[][] z = (has_z ? ZData.asDoubleMatrix() : null);
                double[] f = new double[m*n];
                double[] v = new double[(has_z ? 3 : 2)*m*n];
                int vidx = 0;
                for (int j=0; j<n; j++)
                {
                        int i;
                        for (i=0; i<m; i++)
                        {
                                if (Double.isNaN(x[i][j]) || Double.isNaN(y[i][j]) ||
                                    (has_z && Double.isNaN(z[i][j])))
                                        break;
                                f[i*n+j] = vidx+1;
                                v[vidx] = x[i][j];
                                v[vidx+n*m] = y[i][j];
                                if (has_z)
                                        v[vidx+2*n*m] = z[i][j];
                                vidx++;
                        }
                        for (; i<m; i++)
                        {
                                f[i*n+j] = Double.NaN;
                                v[vidx] = Double.NaN;
                                v[vidx+n*m] = Double.NaN;
                                if (has_z)
                                        v[vidx+2*n*m] = Double.NaN;
                                vidx++;
                        }
                }
                autoSet(Faces, new Matrix(f, new int[] {n, m}));
                autoSet(Vertices, new Matrix(v, new int[] {n*m, (has_z ? 3 : 2)}));
        }
void updateMinMax () [inline, private]
References ArrayProperty.asDoubleMatrix(), ArrayProperty.asDoubleVector(), PatchObject.CDataMapping, GraphicObject.CLim, PatchObject.FaceVertexCData, ArrayProperty.getDim(), RadioProperty.is(), Property.set(), PatchObject.Vertices, GraphicObject.XLim, GraphicObject.YLim, and GraphicObject.ZLim.
Referenced by PatchObject.propertyChanged(), and PatchObject.validate().
        {
                double xmin, xmax, ymin, ymax, zmin, zmax, cmin, cmax;
                double xmin2, xmax2, ymin2, ymax2, zmin2, zmax2;
                double[][] v = Vertices.asDoubleMatrix();
                xmin = ymin = zmin = Double.POSITIVE_INFINITY;
                xmax = ymax = zmax = Double.NEGATIVE_INFINITY;
                xmin2 = ymin2 = zmin2 = Double.POSITIVE_INFINITY;
                xmax2 = ymax2 = zmax2 = Double.MIN_VALUE;
                boolean has_z = false;
                if (v != null && v.length > 0)
                {
                        has_z = v[0].length > 2;
                        for (int i=0; i<v.length; i++)
                        {
                                if (v[i][0] < xmin) xmin = v[i][0];
                                if (v[i][0] > xmax) xmax = v[i][0];
                                if (v[i][0] > 0)
                                {
                                        if (v[i][0] < xmin2) xmin2 = v[i][0];
                                        if (v[i][0] > xmax2) xmax2 = v[i][0];
                                }
                                if (v[i][1] < ymin) ymin = v[i][1];
                                if (v[i][1] > ymax) ymax = v[i][1];
                                if (v[i][1] > 0)
                                {
                                        if (v[i][1] < ymin2) ymin2 = v[i][1];
                                        if (v[i][1] > ymax2) ymax2 = v[i][1];
                                }
                                if (has_z)
                                {
                                        if (v[i][2] < zmin) zmin = v[i][2];
                                        if (v[i][2] > zmax) zmax = v[i][2];
                                        if (v[i][2] > 0)
                                        {
                                                if (v[i][2] < zmin2) zmin2 = v[i][2];
                                                if (v[i][2] > zmax2) zmax2 = v[i][2];
                                        }
                                }
                        }
                }
                XLim.set(new double[] {xmin, xmax, xmin2, xmax2}, true);
                YLim.set(new double[] {ymin, ymax, ymin2, ymax2}, true);
                if (has_z)
                        ZLim.set(new double[] {zmin, zmax, zmin2, zmax2}, true);
                if (FaceVertexCData.getDim(1) == 1 && CDataMapping.is('scaled'))
                {
                        double[] cdata = FaceVertexCData.asDoubleVector();
                        if (cdata != null && cdata.length > 0)
                        {
                                cmin = cmax = cdata[0];
                                for (int i=1; i<cdata.length; i++)
                                {
                                        if (cdata[i] < cmin) cmin = cdata[i];
                                        else if (cdata[i] > cmax) cmax = cdata[i];
                                }
                        }
                        else
                        {
                                cmin = Double.POSITIVE_INFINITY;
                                cmax = Double.NEGATIVE_INFINITY;
                        }
                }
                else
                {
                        cmin = Double.POSITIVE_INFINITY;
                        cmax = Double.NEGATIVE_INFINITY;
                }
                CLim.set(new double[] {cmin, cmax}, true);
        }
void updateXYZData () [inline, private]
References ArrayProperty.asDoubleMatrix(), HandleObject.autoSet(), PatchObject.Faces, ArrayProperty.getDim(), ArrayProperty.isEmpty(), PatchObject.Vertices, plt.x, PatchObject.XData, plt.y, PatchObject.YData, and PatchObject.ZData.
Referenced by PatchObject.propertyChanged(), and PatchObject.validate().
        {
                if (Faces.isEmpty() || Vertices.isEmpty())
                        return;
                int m, n, idx; /* X/Y/Z data size */
                double[][] f = Faces.asDoubleMatrix();
                double[][] v = Vertices.asDoubleMatrix();
                boolean has_z = (v.length > 0 && v[0].length > 2);
                n = Faces.getDim(0);
                m = Faces.getDim(1);
                double[] x = new double[m*n];
                double[] y = new double[m*n];
                double[] z = (has_z ? new double[m*n] : null);
                idx = 0;
                for (int j=0; j<n; j++)
                {
                        int i;
                        for (i=0; i<m && !Double.isNaN(f[j][i]); i++, idx++)
                        {
                                int vidx = (int)f[j][i]-1;
                                if (vidx < 0 || vidx >= v.length)
                                        return;
                                x[idx] = v[vidx][0];
                                y[idx] = v[vidx][1];
                                if (has_z)
                                        z[idx] = v[vidx][2];
                        }
                        for (; i<m; i++, idx++)
                        {
                                x[idx] = Double.NaN;
                                y[idx] = Double.NaN;
                                if (has_z)
                                        z[idx] = Double.NaN;
                        }
                }
                int[] dims = new int[] {m, n};
                autoSet(XData, new Matrix(x, dims));
                autoSet(YData, new Matrix(y, dims));
                if (has_z)
                        autoSet(ZData, new Matrix(z, dims));
        }
void validate () [inline]
Reimplemented from HandleObject.
References PatchObject.CData, PatchObject.computeNormals(), PatchObject.Faces, PatchObject.FaceVertexCData, ArrayProperty.getDim(), ArrayProperty.isEmpty(), Property.reset(), PatchObject.updateCData(), PatchObject.updateFaceCount(), PatchObject.updateFVCData(), PatchObject.updateFVData(), PatchObject.updateMinMax(), PatchObject.updateXYZData(), PatchObject.VertexNormals, PatchObject.Vertices, PatchObject.XData, and PatchObject.YData.
        {
                if (!Faces.isEmpty() && !Vertices.isEmpty())
                {
                        /* only compute XYZ data if needed */
                        if (XData.isEmpty() || YData.isEmpty())
                                updateXYZData();
                }
                else
                        updateFVData();
                if (!FaceVertexCData.isEmpty())
                {
                        /* only compute CData is needed */
                        if (CData.isEmpty())
                                updateCData();
                }
                else if (!CData.isEmpty())
                        updateFVCData();
                updateFaceCount();
                updateMinMax();
                if (VertexNormals.getDim(0) == 0)
                        VertexNormals.reset(computeNormals());
                super.validate();
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
DoubleProperty __Index__ [package]
Referenced by PatchObject.PatchObject().
VectorProperty ALim [package, inherited]
Referenced by GroupObject.childValidated(), GraphicObject.GraphicObject(), and GroupObject.updateLimits().
BooleanProperty ALimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
RadioProperty AlphaDataMapping [package]
Referenced by PatchObject.getAlphaData(), and PatchObject.PatchObject().
DoubleProperty AmbientStrength [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
ArrayProperty CData [package]
Referenced by PatchObject.PatchObject(), PatchObject.propertyChanged(), PatchObject.updateCData(), PatchObject.updateFVCData(), and PatchObject.validate().
RadioProperty CDataMapping [package]
Referenced by PatchObject.getCData(), PatchObject.PatchObject(), and PatchObject.updateMinMax().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
VectorProperty CLim [package, inherited]
Referenced by AxesObject.autoScaleC(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), SurfaceObject.updateColorMinMax(), GroupObject.updateLimits(), ImageObject.updateMinMax(), and PatchObject.updateMinMax().
BooleanProperty CLimInclude [package, inherited]
Referenced by AxesObject.autoScaleC(), BarseriesObject.BarseriesObject(), GraphicObject.GraphicObject(), ImageObject.ImageObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
DoubleProperty DiffuseStrength [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
DoubleRadioProperty EdgeAlpha [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
ColorProperty EdgeColor [package]
Referenced by BarseriesObject.BarseriesObject(), PatchObject.checkConsistency(), GLRenderer.draw(), PatchObject.PatchObject(), and BarseriesObject.propertyChanged().
RadioProperty EdgeLighting [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
DoubleRadioProperty FaceAlpha [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
ColorProperty FaceColor [package]
Referenced by BarseriesObject.BarseriesObject(), PatchObject.checkConsistency(), GLRenderer.draw(), PatchObject.PatchObject(), and BarseriesObject.propertyChanged().
int [] faceCount [private]
Referenced by PatchObject.computeNormals(), PatchObject.getFaceCount(), and PatchObject.updateFaceCount().
RadioProperty FaceLighting [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
ArrayProperty Faces [package]
Referenced by PatchObject.checkConsistency(), PatchObject.computeNormals(), BarseriesObject.doLayout(), GLRenderer.draw(), PatchObject.PatchObject(), PatchObject.propertyChanged(), PatchObject.updateCData(), PatchObject.updateFaceCount(), PatchObject.updateFVData(), PatchObject.updateXYZData(), and PatchObject.validate().
VectorProperty FaceVertexAlphaData [package]
Referenced by PatchObject.getAlphaData(), and PatchObject.PatchObject().
ArrayProperty FaceVertexCData [package]
Referenced by PatchObject.checkConsistency(), BarseriesObject.doLayout(), PatchObject.getCData(), PatchObject.PatchObject(), PatchObject.propertyChanged(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateMinMax(), and PatchObject.validate().
int glID [protected, inherited]
Referenced by GraphicObject.GraphicObject().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
BooleanProperty LegendInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), GraphicObject.isLegendable(), and LineObject.LineObject().
LineStyleProperty LineStyle [package]
Referenced by PatchObject.PatchObject().
DoubleProperty LineWidth [package]
Referenced by PatchObject.PatchObject().
MarkerProperty Marker [package]
Referenced by PatchObject.checkConsistency(), and PatchObject.PatchObject().
ColorProperty MarkerEdgeColor [package]
Referenced by PatchObject.checkConsistency(), and PatchObject.PatchObject().
ColorProperty MarkerFaceColor [package]
Referenced by PatchObject.checkConsistency(), and PatchObject.PatchObject().
DoubleProperty MarkerSize [package]
Referenced by PatchObject.PatchObject().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
DoubleProperty SpecularExponent [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
DoubleProperty SpecularStrength [package]
Referenced by GLRenderer.draw(), and PatchObject.PatchObject().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
ArrayProperty VertexNormals [package]
Referenced by GLRenderer.draw(), PatchObject.PatchObject(), PatchObject.propertyChanged(), and PatchObject.validate().
ArrayProperty Vertices [package]
Referenced by PatchObject.checkConsistency(), PatchObject.computeNormals(), BarseriesObject.doLayout(), GLRenderer.draw(), PatchObject.PatchObject(), PatchObject.propertyChanged(), PatchObject.updateCData(), PatchObject.updateFVData(), PatchObject.updateMinMax(), PatchObject.updateXYZData(), and PatchObject.validate().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
ArrayProperty XData [package]
Referenced by PatchObject.checkXYZData(), PatchObject.PatchObject(), PatchObject.propertyChanged(), PatchObject.updateFVCData(), PatchObject.updateFVData(), PatchObject.updateXYZData(), and PatchObject.validate().
VectorProperty XLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty XLimInclude [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
ArrayProperty YData [package]
Referenced by PatchObject.checkXYZData(), PatchObject.PatchObject(), PatchObject.propertyChanged(), PatchObject.updateFVData(), PatchObject.updateXYZData(), and PatchObject.validate().
VectorProperty YLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty YLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
ArrayProperty ZData [package]
Referenced by PatchObject.checkXYZData(), PatchObject.PatchObject(), PatchObject.propertyChanged(), PatchObject.updateFVData(), and PatchObject.updateXYZData().
VectorProperty ZLim [package, inherited]
Referenced by GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty ZLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), LineObject.LineObject(), PatchObject.PatchObject(), LineObject.propertyChanged(), SurfaceObject.SurfaceObject(), and LineObject.validate().
Author
Generated automatically by Doxygen for Octave from the source code.