UnwindHandleObject
NAME
UnwindHandleObject -
SYNOPSIS
Public Member Functions
UnwindHandleObject ()
void start ()
void end ()
synchronized void unwind (Property p, Object value)
Private Member Functions
synchronized void swapValues ()
Private Attributes
Map unwindMap
Constructor & Destructor Documentation
UnwindHandleObject () [inline]
References UnwindHandleObject.unwindMap.
        {
                unwindMap = new HashMap();
        }
Member Function Documentation
void end () [inline]
References UnwindHandleObject.swapValues(), and UnwindHandleObject.unwindMap.
Referenced by OctaveCallback.execute().
        {
                swapValues();
                unwindMap.clear();
        }
void start () [inline]
References UnwindHandleObject.swapValues().
Referenced by OctaveCallback.execute().
        {
                swapValues();
        }
synchronized void swapValues () [inline, private]
References Property.get(), Property.reset(), and UnwindHandleObject.unwindMap.
Referenced by UnwindHandleObject.end(), and UnwindHandleObject.start().
        {
                Iterator it = unwindMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        Property p = (Property)entry.getKey();
                        Object value = p.get();
                        p.reset(entry.getValue());
                        entry.setValue(value);
                }
        }
synchronized void unwind (Propertyp, Objectvalue) [inline]
References UnwindHandleObject.unwindMap.
Referenced by Callback.unwind().
        {
                unwindMap.put(p, value);
        }
Member Data Documentation
Map unwindMap [private]
Referenced by UnwindHandleObject.end(), UnwindHandleObject.swapValues(), UnwindHandleObject.unwind(), and UnwindHandleObject.UnwindHandleObject().
Author
Generated automatically by Doxygen for Octave from the source code.