SimpleTextEngine.TeXElement
NAME
SimpleTextEngine.TeXElement -
SYNOPSIS
Inherits SimpleTextEngine.Element.
Package Functions
TeXElement (String txt)
Rectangle layout (Layouter l)
void render (Graphics2D g)
void render (TextRenderer r)
Rectangle layout (RenderCanvas comp, Font font)
Static Package Functions
static Font getSymbolFont (Font f)
static String convertString (String s, int idx)
static String convertString (String s)
static int getSymbolCode (String s, int idx)
static int getSymbolCode (String s)
static boolean isSymbol (String s)
Package Attributes
String symbol
String text
Rectangle rect
Static Private Attributes
static String[] symbol_names
static int[][] symbol_codes
static Map symbol_map
static boolean use_symbol_font = System.getProperty('os.name').startsWith('Windows')
Constructor & Destructor Documentation
TeXElement (Stringtxt) [inline, package]
References SimpleTextEngine.TeXElement.convertString(), SimpleTextEngine.TeXElement.symbol, and SimpleTextEngine.TeXElement.use_symbol_font.
                {
                        super(convertString(txt, (use_symbol_font ? 1 : 0)));
                        this.symbol = txt;
                }
Member Function Documentation
static String convertString (Strings, intidx) [inline, static, package]
References SimpleTextEngine.TeXElement.getSymbolCode().
Referenced by SimpleTextEngine.TeXElement.convertString(), and SimpleTextEngine.TeXElement.TeXElement().
                {
                        int c = getSymbolCode(s, idx);
                        if (c >= 0)
                                return new String(new int[] {c}, 0, 1);
                        return '';
                }
static String convertString (Strings) [inline, static, package]
References SimpleTextEngine.TeXElement.convertString().
                {
                        return convertString(s, 0);
                }
static int getSymbolCode (Strings, intidx) [inline, static, package]
References SimpleTextEngine.TeXElement.symbol_codes, SimpleTextEngine.TeXElement.symbol_map, and SimpleTextEngine.TeXElement.symbol_names.
Referenced by SimpleTextEngine.TeXElement.convertString(), SimpleTextEngine.TeXElement.getSymbolCode(), SimpleTextEngine.TeXElement.isSymbol(), and SimpleTextEngine.PSTextRenderer.render().
                {
                        if (symbol_map == null)
                        {
                                symbol_map = new HashMap();
                                for (int i=0; i<symbol_names.length; i++)
                                        if (symbol_names[i] != null && symbol_codes[i][0] != 0)
                                                symbol_map.put(symbol_names[i], symbol_codes[i]);
                        }
                        int[] c = (int[])symbol_map.get(s);
                        if (c != null && idx >= 0 && idx < c.length)
                                return c[idx];
                        return -1;
                }
static int getSymbolCode (Strings) [inline, static, package]
References SimpleTextEngine.TeXElement.getSymbolCode().
                {
                        return getSymbolCode(s, 0);
                }
static Font getSymbolFont (Fontf) [inline, static, package]
Referenced by SimpleTextEngine.TeXElement.layout(), and SimpleTextEngine.TeXElement.render().
                {
                        return new Font('Symbol', f.getStyle(), f.getSize());
                }
static boolean isSymbol (Strings) [inline, static, package]
References SimpleTextEngine.TeXElement.getSymbolCode().
Referenced by SimpleTextEngine.SimpleFactory.parse().
                {
                        return (getSymbolCode(s) >= 0);
                }
Rectangle layout (RenderCanvascomp, Fontfont) [inline, package, inherited]
Referenced by SimpleTextEngine.LineElement.layout(), and SimpleTextEngine.ScriptElement.layout().
                {
                        return layout(new Layouter(comp, font));
                }
Rectangle layout (Layouterl) [inline, package]
Reimplemented from SimpleTextEngine.Element.
References SimpleTextEngine.Layouter.font, SimpleTextEngine.TeXElement.getSymbolFont(), SimpleTextEngine.Element.rect, and SimpleTextEngine.TeXElement.use_symbol_font.
                {
                        if (use_symbol_font)
                        {
                                Font currentFont = l.font;
                                l.font = getSymbolFont(currentFont);
                                super.layout(l);
                                l.font = currentFont;
                                return rect;
                        }
                        else
                                return super.layout(l);
                }
void render (Graphics2Dg) [inline, package]
Reimplemented from SimpleTextEngine.Element.
References SimpleTextEngine.TeXElement.getSymbolFont(), and SimpleTextEngine.TeXElement.use_symbol_font.
                {
                        if (use_symbol_font)
                        {
                                Font currentFont = g.getFont();
                                g.setFont(getSymbolFont(currentFont));
                                super.render(g);
                                g.setFont(currentFont);
                        }
                        else
                                super.render(g);
                }
void render (TextRendererr) [inline, package]
Reimplemented from SimpleTextEngine.Element.
References SimpleTextEngine.TextRenderer.render().
{ r.render(this); }
Member Data Documentation
Rectangle rect [package, inherited]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.LineElement.layout(), SimpleTextEngine.SubscriptElement.layout(), SimpleTextEngine.SuperscriptElement.layout(), SimpleTextEngine.ScriptElement.layout(), SimpleTextEngine.TeXFontCommand.layout(), SimpleTextEngine.TeXElement.layout(), SimpleTextEngine.Content.layout(), SimpleTextEngine.PSTextRenderer.render(), SimpleTextEngine.LineElement.render(), SimpleTextEngine.SuperscriptElement.render(), and SimpleTextEngine.Content.render().
String symbol [package]
Referenced by SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.TeXElement.TeXElement().
int [][] symbol_codes [static, private]
Referenced by SimpleTextEngine.TeXElement.getSymbolCode().
Map symbol_map [static, private]
Referenced by SimpleTextEngine.TeXElement.getSymbolCode().
String [] symbol_names [static, private]
Referenced by SimpleTextEngine.TeXElement.getSymbolCode().
String text [package, inherited]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.Element.render().
boolean use_symbol_font = System.getProperty('os.name').startsWith('Windows') [static, private]
Referenced by SimpleTextEngine.TeXElement.layout(), SimpleTextEngine.TeXElement.render(), and SimpleTextEngine.TeXElement.TeXElement().
Author
Generated automatically by Doxygen for Octave from the source code.