HandleEventSinkAdapter
NAME
HandleEventSinkAdapter -
SYNOPSIS
Inherits HandleEventSink.
Public Member Functions
HandleEventSinkAdapter ()
void listen (Property p)
void listen (HandleEventSource source, String name)
void dispose ()
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Protected Attributes
Set sourceSet = new HashSet()
Constructor & Destructor Documentation
HandleEventSinkAdapter () [inline]
        {
        }
Member Function Documentation
void dispose () [inline]
References HandleEventSinkAdapter.sourceSet.
Referenced by PushButtonControl.dispose(), OctaveSink.dispose(), CheckBoxControl.dispose(), EditControl.dispose(), PopupMenuControl.dispose(), UIControlAdapter.dispose(), Edit2Control.dispose(), TextControl.dispose(), and ListBoxControl.dispose().
        {
                Iterator it = sourceSet.iterator();
                while (it.hasNext())
                        ((HandleEventSource)it.next()).removeHandleEventSink(this);
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline]
Implements HandleEventSink.
        {
        }
boolean executeOnce () [inline]
Implements HandleEventSink.
        {
                return false;
        }
void listen (Propertyp) [inline]
Referenced by ListBoxControl.ListBoxControl(), OctaveSink.OctaveSink(), PopupMenuControl.PopupMenuControl(), TextControl.TextControl(), and UIControlAdapter.UIControlAdapter().
        {
                listen(p, 'PropertyChanged');
        }
void listen (HandleEventSourcesource, Stringname) [inline]
References HandleEventSource.addHandleEventSink(), and HandleEventSinkAdapter.sourceSet.
        {
                source.addHandleEventSink(name, this);
                sourceSet.add(source);
        }
void sourceDeleted (Objectsource) [inline]
Implements HandleEventSink.
References HandleEventSinkAdapter.sourceSet.
        {
                sourceSet.remove(source);
        }
Member Data Documentation
Set sourceSet = new HashSet() [protected]
Referenced by HandleEventSinkAdapter.dispose(), HandleEventSinkAdapter.listen(), and HandleEventSinkAdapter.sourceDeleted().
Author
Generated automatically by Doxygen for Octave from the source code.