.TH "Renderer.CachedData" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Renderer.CachedData \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGLRenderer\&.TextureData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBdispose\fP ()"
.PP
Implemented in \fBGLRenderer\&.TextureData\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
