.TH "HandleEventSource" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HandleEventSource \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHandleObject\fP, and \fBProperty\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBhasHandleEvent\fP (String name)"
.br
.ti -1c
.RI "void \fBaddHandleEventSink\fP (String name, \fBHandleEventSink\fP sink)"
.br
.ti -1c
.RI "void \fBremoveHandleEventSink\fP (\fBHandleEventSink\fP sink)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBaddHandleEventSink\fP (Stringname, \fBHandleEventSink\fPsink)"
.PP
Implemented in \fBHandleObject\fP, and \fBProperty\fP\&.
.PP
Referenced by HandleEventSinkAdapter\&.listen()\&.
.SS "boolean \fBhasHandleEvent\fP (Stringname)"
.PP
Implemented in \fBHandleObject\fP, and \fBProperty\fP\&.
.SS "void \fBremoveHandleEventSink\fP (\fBHandleEventSink\fPsink)"
.PP
Implemented in \fBHandleObject\fP, and \fBProperty\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
