SimpleTextEngine.SuperscriptElement
NAME
SimpleTextEngine.SuperscriptElement -
SYNOPSIS
Inherits SimpleTextEngine.LineElement.
Package Functions
SuperscriptElement (String txt)
Font getSuperscriptFont (Font f)
Rectangle layout (Layouter l)
void render (Graphics2D g)
void render (TextRenderer r)
Rectangle layout (RenderCanvas comp, Font font)
void add (Element e)
Iterator iterator ()
Package Attributes
String text
Rectangle rect
Constructor & Destructor Documentation
SuperscriptElement (Stringtxt) [inline, package]
                {
                        super(txt);
                }
Member Function Documentation
void add (Elemente) [inline, package, inherited]
References SimpleTextEngine.LineElement.elements.
                {
                        elements.add(e);
                }
Font getSuperscriptFont (Fontf) [inline, package]
Referenced by SimpleTextEngine.SuperscriptElement.layout(), and SimpleTextEngine.SuperscriptElement.render().
                {
                        return new Font(f.getFamily(), f.getStyle(), f.getSize()-2);
                }
Iterator iterator () [inline, package, inherited]
References SimpleTextEngine.LineElement.elements.
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        return elements.iterator();
                }
Rectangle layout (RenderCanvascomp, Fontfont) [inline, package, inherited]
Referenced by SimpleTextEngine.LineElement.layout(), and SimpleTextEngine.ScriptElement.layout().
                {
                        return layout(new Layouter(comp, font));
                }
Rectangle layout (Layouterl) [inline, package]
Reimplemented from SimpleTextEngine.LineElement.
References SimpleTextEngine.Layouter.font, SimpleTextEngine.Layouter.getFontMetrics(), SimpleTextEngine.SuperscriptElement.getSuperscriptFont(), and SimpleTextEngine.Element.rect.
                {
                        Font currentFont = l.font;
                        l.font = getSuperscriptFont(currentFont);
                        super.layout(l);
                        FontMetrics fm = l.getFontMetrics();
                        rect.y += fm.getMaxAscent()/2;
                        l.font = currentFont;
                        return rect;
                }
void render (Graphics2Dg) [inline, package]
Reimplemented from SimpleTextEngine.LineElement.
References SimpleTextEngine.SuperscriptElement.getSuperscriptFont(), and SimpleTextEngine.Element.rect.
                {
                        Font currentFont = g.getFont();
                        FontMetrics fm = g.getFontMetrics();
                        int ascent = fm.getMaxAscent();
                        Font subscriptFont = getSuperscriptFont(currentFont);
                        g.setFont(subscriptFont);
                        g.translate(0, -(rect.height+rect.y)-ascent/2);
                        super.render(g);
                        g.translate(0, (rect.height+rect.y)+ascent/2);
                        g.setFont(currentFont);
                }
void render (TextRendererr) [inline, package]
Reimplemented from SimpleTextEngine.LineElement.
References SimpleTextEngine.TextRenderer.render().
{ r.render(this); }
Member Data Documentation
Rectangle rect [package, inherited]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.LineElement.layout(), SimpleTextEngine.SubscriptElement.layout(), SimpleTextEngine.SuperscriptElement.layout(), SimpleTextEngine.ScriptElement.layout(), SimpleTextEngine.TeXFontCommand.layout(), SimpleTextEngine.TeXElement.layout(), SimpleTextEngine.Content.layout(), SimpleTextEngine.PSTextRenderer.render(), SimpleTextEngine.LineElement.render(), SimpleTextEngine.SuperscriptElement.render(), and SimpleTextEngine.Content.render().
String text [package, inherited]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.Element.render().
Author
Generated automatically by Doxygen for Octave from the source code.