TextObject
NAME
TextObject -
SYNOPSIS
Inherits GraphicObject.
Public Member Functions
TextObject (HandleObject parent, String txt, double[] pos)
void validate ()
Rectangle getExtent ()
void render (Graphics g)
void drawAsImage (Renderer renderer)
void draw (Renderer renderer)
void propertyChanged (Property p) throws PropertyException
String toPostScript ()
AxesObject getAxes ()
void set (Property p, Object value) throws PropertyException
void set (String name, Object value) throws PropertyException
boolean isLegendable ()
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
void delete ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
java.awt.Component getComponent ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
Object get (Property p)
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Protected Member Functions
void updateMinMax ()
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
int glID
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
int h
ColorProperty BackgroundColor
ColorProperty TextColor
ColorProperty EdgeColor
RadioProperty FontAngle
StringProperty FontName
DoubleProperty FontSize
RadioProperty FontWeight
RadioProperty FontUnits
RadioProperty HAlign
LineStyleProperty LineStyle
DoubleProperty LineWidth
DoubleProperty Margin
VectorProperty Position
BooleanProperty PositionMode
DoubleProperty Rotation
StringProperty TextString
RadioProperty Units
RadioProperty VAlign
VectorProperty XLim
VectorProperty YLim
VectorProperty ZLim
VectorProperty CLim
VectorProperty ALim
BooleanProperty XLimInclude
BooleanProperty YLimInclude
BooleanProperty ZLimInclude
BooleanProperty CLimInclude
BooleanProperty ALimInclude
BooleanProperty LegendInclude
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
void updateContent ()
void updateData ()
Private Attributes
Font font = null
SimpleTextEngine.Content content
ByteBuffer data
AffineTransform T
Rectangle r
int w
String currentUnits
Constructor & Destructor Documentation
TextObject (HandleObjectparent, Stringtxt, double[]pos) [inline]
References TextObject.BackgroundColor, HandleObject.Clipping, TextObject.currentUnits, TextObject.EdgeColor, TextObject.FontAngle, TextObject.FontName, TextObject.FontSize, TextObject.FontUnits, TextObject.FontWeight, TextObject.HAlign, TextObject.LineStyle, TextObject.LineWidth, HandleObject.listen(), TextObject.Margin, TextObject.Position, TextObject.PositionMode, Property.reset(), TextObject.Rotation, TextObject.TextColor, TextObject.TextString, TextObject.Units, and TextObject.VAlign.
        {
                super(parent, 'text');
                Rotation = new DoubleProperty(this, 'Rotation', 0.0);
                HAlign = new RadioProperty(this, 'HorizontalAlignment', new String[] {'left', 'center', 'right'}, 'left');
                VAlign = new RadioProperty(this, 'VerticalAlignment', new String[] {'top', 'middle', 'bottom', 'baseline'}, 'middle');
                Position = new VectorProperty(this, 'Position', 3, pos);
                PositionMode = new BooleanProperty(this, 'PositionMode', true);
                Units = new RadioProperty(this, 'Units', new String[] {'pixels', 'data', 'normalized',
                        'inches', 'centimeters', 'points'}, 'data');
                currentUnits = 'data';
                TextColor = new ColorProperty(this, 'Color', Color.black);
                TextString = new StringProperty(this, 'String', txt);
                BackgroundColor = new ColorProperty(this, 'BackgroundColor', (Color)null);
                EdgeColor = new ColorProperty(this, 'EdgeColor', (Color)null);
                LineWidth = new DoubleProperty(this, 'LineWidth', 0.5);
                Margin = new DoubleProperty(this, 'Margin', 2.0);
                LineStyle = new LineStyleProperty(this, 'LineStyle', '-');
                FontAngle = new RadioProperty(this, 'FontAngle', new String[] {'normal', 'oblique', 'italic'}, 'normal');
                FontName = new StringProperty(this, 'FontName', 'Helvetica');
                FontSize = new DoubleProperty(this, 'FontSize', 10);
                FontWeight = new RadioProperty(this, 'FontWeight', new String[] {'light', 'normal', 'demi', 'bold'}, 'normal');
                FontUnits = new RadioProperty(this, 'FontUnits', new String[] {'points', 'normalized', 'inches',
                        'centimeters', 'pixels'}, 'points');
                Clipping.reset('off');
                listen(Units);
                listen(TextString);
                listen(Rotation);
                listen(TextColor);
                listen(BackgroundColor);
                listen(EdgeColor);
                listen(Margin);
                listen(LineStyle);
                listen(LineWidth);
                listen(Position);
                listen(FontAngle);
                listen(FontName);
                listen(FontSize);
                listen(FontWeight);
                listen(FontUnits);
                listen(HAlign);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
void delete () [inline, inherited]
Reimplemented from PropertySet.
Reimplemented in FigureObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
References HandleObject.BeingDeleted, HandleObject.cachedData, HandleEventSourceHelper.delete(), HandleObject.deleteChildren(), HandleObject.DeleteFcn, HandleObjectListProperty.elementAt(), HandleObject.eventSource, HandleObject.eventSourceSet, CallbackProperty.execute(), HandleEventSourceHelper.fireEvent(), HandleObject.getHandle(), HandleObject.Parent, HandleObject.removeChild(), HandleObject.removeHandleEventSink(), HandleObject.removeHandleObject(), and Property.reset().
Referenced by HandleObject.deleteChildren(), AxesObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), and AxesObject.makeLegend().
        {
                BeingDeleted.reset('on');
                try { eventSource.fireEvent('ObjectDeleted'); }
                catch (PropertyException ex) {}
                DeleteFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
                removeHandleObject(getHandle());
                super.delete();
                Iterator it = eventSourceSet.iterator();
                while (it.hasNext())
                        ((HandleEventSource)it.next()).removeHandleEventSink(this);
                eventSource.delete();
                deleteChildren();
                if (cachedData != null)
                        cachedData.dispose();
                Parent.elementAt(0).removeChild(this);
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void draw (Rendererrenderer) [inline, virtual]
Implements GraphicObject.
References Renderer.draw(), TextObject.TextString, and StringProperty.toString().
        {
                if (TextString.toString() != '')
                        renderer.draw(this);
        }
void drawAsImage (Rendererrenderer) [inline]
References AxesObject.convertUnits(), TextObject.data, Renderer.draw(), VectorProperty.getArray(), GraphicObject.getAxes(), RadioProperty.getValue(), TextObject.h, TextObject.HAlign, RadioProperty.is(), TextObject.Position, TextObject.r, TextObject.T, TextObject.Units, TextObject.updateData(), TextObject.VAlign, TextObject.w, plt.x, and plt.y.
Referenced by GLRenderer.draw().
        {
                if (data == null)
                        updateData();
                AxesObject ax = getAxes();
                double[] pos = ax.convertUnits(Position.getArray(), Units.getValue());
                boolean dataUnits = Units.is('data');
                int x = 0, y = 0, margin = -r.x;
                if (HAlign.is('center')) x = (r.width-2*margin)/2;
                else if (HAlign.is('right')) x = (r.width-2*margin);
                if (VAlign.is('bottom')) y = (r.height-2*margin);
                else if (VAlign.is('middle')) y = (r.height-2*margin)/2;
                else if (VAlign.is('baseline')) y = (r.height+r.y-margin);
                Point2D.Double p1 = new Point2D.Double(x, y), p2 = new Point2D.Double();
                T.transform(p1, p2);
                int xOffset = (int)p2.getX(), yOffset = h-(int)p2.getY();
                renderer.draw(data, w, h, pos, xOffset, yOffset, false, dataUnits);
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxes () [inline, inherited]
References HandleObjectListProperty.elementAt(), and HandleObject.Parent.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), J2DRenderer.draw(), GLRenderer.draw(), TextObject.drawAsImage(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), SurfaceObject.getCData(), PatchObject.getCData(), TextObject.getExtent(), ImageObject.ImageObject(), BaseLineObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.SurfaceObject(), TextObject.toPostScript(), TextObject.updateData(), BaseLineObject.updateLine(), and TextObject.updateMinMax().
        {
                HandleObject obj = Parent.elementAt(0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                else
                        return ((GraphicObject)obj).getAxes();
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
java.awt.Component getComponent () [inline, inherited]
Reimplemented in FigureObject, UIPanelObject, and UIControlObject.
Referenced by UIControlObject.getParentComponent(), and UIPanelObject.getParentComponent().
        {
                System.out.println('Warning: no component associated with ' + getClass());
                return null;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
Rectangle getExtent () [inline]
References TextObject.content, TextObject.FontAngle, TextObject.FontName, TextObject.FontSize, TextObject.FontUnits, TextObject.FontWeight, GraphicObject.getAxes(), AxesObject.getCanvas(), Utils.getFont(), and RenderCanvas.getHeight().
Referenced by LegendObject.doLayout(), J2DRenderer.draw(), and TextObject.toPostScript().
        {
                RenderCanvas comp = getAxes().getCanvas();
                Font fnt = Utils.getFont(FontName, FontSize, FontUnits, FontAngle, FontWeight, comp.getHeight());
                return (Rectangle)content.layout(comp, fnt).clone();
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented from HandleObject.
Reimplemented in BaseLineObject.
References BooleanProperty.isSet(), and GraphicObject.LegendInclude.
        {
                return LegendInclude.isSet();
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from HandleObject.
References TextObject.BackgroundColor, TextObject.content, AxesObject.convertUnits(), TextObject.currentUnits, TextObject.data, TextObject.EdgeColor, TextObject.FontAngle, TextObject.FontName, TextObject.FontSize, TextObject.FontWeight, VectorProperty.getArray(), GraphicObject.getAxes(), RadioProperty.getValue(), TextObject.HAlign, RadioProperty.is(), TextObject.LineStyle, TextObject.LineWidth, TextObject.Margin, TextObject.Position, TextObject.PositionMode, Property.reset(), TextObject.Rotation, BooleanProperty.set(), TextObject.TextColor, TextObject.TextString, StringProperty.toString(), TextObject.Units, TextObject.updateContent(), and TextObject.updateMinMax().
        {
                super.propertyChanged(p);
                if (p == Units)
                {
                        AxesObject ax = getAxes();
                        Position.reset(ax.convertUnits(Position.getArray(), currentUnits, Units.getValue()));
                        currentUnits = Units.getValue();
                }
                else if (p == TextString)
                        updateContent();
                else if (p == Rotation || p == TextColor || p == BackgroundColor || p == EdgeColor ||
                                 p == Margin || p == LineStyle || p == LineWidth || p == FontAngle ||
                                 p == FontName || p == FontSize || p == FontWeight || (p == HAlign && TextString.toString().indexOf('\n') != -1))
                        data = null;
                if (p == HAlign)
                        content.align = (HAlign.is('left') ? 0 : (HAlign.is('center') ? 1 : 2));
                if (p == Units || p == Position)
                        PositionMode.set(new Boolean(false));
                if (p == Position)
                        updateMinMax();
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void render (Graphicsg) [inline]
References TextObject.content.
Referenced by J2DRenderer.draw().
        {
                content.render((Graphics2D)g);
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References FigureObject.__Dirty__, HandleObject.getAncestor(), and Property.reset().
Referenced by LegendObject.propertyChanged().
        {
                super.set(p, value);
                FigureObject fig = (FigureObject)getAncestor('figure');
                fig.__Dirty__.reset('on');
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
String toPostScript () [inline]
References TextObject.BackgroundColor, TextObject.content, ed(), TextObject.EdgeColor, DoubleProperty.floatValue(), TextObject.FontAngle, TextObject.FontName, TextObject.FontSize, TextObject.FontUnits, TextObject.FontWeight, GraphicObject.getAxes(), ColorProperty.getColor(), TextObject.getExtent(), Utils.getFontSize(), Utils.getScreenResolution(), TextObject.h, TextObject.HAlign, RadioProperty.is(), ColorProperty.isSet(), TextObject.LineStyle, TextObject.LineWidth, TextObject.Margin, TextObject.r, TextObject.Rotation, TextObject.TextColor, LineStyleProperty.toPostScript(), StringProperty.toString(), TextObject.VAlign, TextObject.w, plt.x, and plt.y.
Referenced by GLRenderer.draw().
        {
                StringBuffer buf = new StringBuffer();
                SimpleTextEngine.PSTextRenderer r = new SimpleTextEngine.PSTextRenderer(buf,
                                FontName.toString(), Utils.getFontSize(FontSize, FontUnits, getAxes().getCanvas().getHeight()),
                                (FontAngle.is('normal') ? 0 : Font.ITALIC)|(FontWeight.is('normal') ? 0 : Font.BOLD),
                                TextColor.getColor());
                /* save current state */
                buf.append('gsave\n');
                /* text rotation */
                float angle = Rotation.floatValue();
                if (angle != 0.0f)
                        buf.append(angle + ' rotate\n');
                /* text box */
                float f = 72.0f/Utils.getScreenResolution();
                Rectangle re = getExtent();
                if (BackgroundColor.isSet() || (EdgeColor.isSet() && !LineStyle.is('none')))
                {
                        float x = 0, y = 0, margin = Margin.floatValue(), w, h;
                        if (HAlign.is('center')) x = -re.width/2-margin;
                        else if (HAlign.is('right')) x = -re.width-2*margin;
                        else x = -margin;
                        if (VAlign.is('baseline')) y = re.height+re.y+margin;
                        else if (VAlign.is('bottom')) y = re.height+margin;
                        else if (VAlign.is('top')) y = margin;
                        else y = re.height/2+margin;
                        w = re.width+2*margin;
                        h = re.height+2*margin;
                        buf.append('gsave\n' + (f*x) + ' ' + (f*y) + ' rmoveto SP\n');
                        if (BackgroundColor.isSet())
                        {
                                float[] bk = BackgroundColor.getColor().getRGBColorComponents(null);
                                buf.append(bk[0] + ' ' + bk[1] + ' ' + bk[2] + ' C\n');
                                buf.append('newpath dup RP\n');
                                buf.append((f*w) + ' 0 rlineto\n');
                                buf.append('0 ' + (f*(-h)) + ' rlineto\n');
                                buf.append((f*(-w)) + ' 0 rlineto\n');
                                buf.append('0 ' + (f*h) + ' rlineto\nclosepath fill\n');
                        }
                        if (EdgeColor.isSet() && !LineStyle.is('none'))
                        {
                                float[] ed = EdgeColor.getColor().getRGBColorComponents(null);
                                buf.append(ed[0] + ' ' + ed[1] + ' ' + ed[2] + ' C\n');
                                buf.append(LineWidth.floatValue() + ' W\n');
                                buf.append(LineStyle.toPostScript() + '\n');
                                buf.append('newpath dup RP\n');
                                buf.append((f*w) + ' 0 rlineto\n');
                                buf.append('0 ' + (f*(-h)) + ' rlineto\n');
                                buf.append((f*(-w)) + ' 0 rlineto\n');
                                buf.append('0 ' + (f*h) + ' rlineto\nclosepath stroke\n');
                        }
                        buf.append('pop grestore\n');
                }
                /* text vertical alignment */
                if (!VAlign.is('baseline'))
                {
                        if (VAlign.is('top'))
                                buf.append('0 -' + (f*(re.height+re.y)) + ' rmoveto\n');
                        else if (VAlign.is('bottom'))
                                buf.append('0 ' + (f*(-re.y)) + ' rmoveto\n');
                        else
                                buf.append('0 ' + (f*(-re.height/2-re.y)) + ' rmoveto\n');
                }
                /* text content */
                content.render(r);
                /* restore state */
                buf.append('grestore\n');
                return buf.toString();
        }
void updateContent () [inline, private]
References TextObject.content, TextObject.data, TextObject.HAlign, RadioProperty.is(), TextObject.TextString, and StringProperty.toString().
Referenced by TextObject.propertyChanged(), and TextObject.validate().
        {
                content = new SimpleTextEngine.Content(TextString.toString());
                content.align = (HAlign.is('left') ? 0 : (HAlign.is('center') ? 1 : 2));
                data = null;
        }
void updateData () [inline, private]
References TextObject.BackgroundColor, TextObject.content, TextObject.data, DoubleProperty.doubleValue(), TextObject.EdgeColor, DoubleProperty.floatValue(), TextObject.FontAngle, TextObject.FontName, TextObject.FontSize, TextObject.FontUnits, TextObject.FontWeight, GraphicObject.getAxes(), AxesObject.getCanvas(), ColorProperty.getColor(), Utils.getFont(), RenderCanvas.getHeight(), LineStyleProperty.getStroke(), TextObject.h, DoubleProperty.intValue(), RadioProperty.is(), ColorProperty.isSet(), TextObject.LineStyle, TextObject.LineWidth, TextObject.Margin, TextObject.r, TextObject.Rotation, TextObject.T, TextObject.TextColor, and TextObject.w.
Referenced by TextObject.drawAsImage().
        {
                RenderCanvas comp = getAxes().getCanvas();
                double angle = Rotation.doubleValue()*Math.PI/180.0;
                int angleD = Rotation.intValue();
                int margin = Margin.intValue();
                int offset = (LineWidth.intValue()+1)/2;
                if (EdgeColor.isSet())
                        margin += LineWidth.intValue();
                Font fnt = Utils.getFont(FontName, FontSize, FontUnits, FontAngle, FontWeight, comp.getHeight());
                r = (Rectangle)content.layout(comp, fnt).clone();
                r.x -= margin;
                r.y -= margin;
                r.width += 2*margin;
                r.height += 2*margin;
                w = (int)Math.round(Math.abs(r.width*Math.cos(angle))+Math.abs(r.height*Math.sin(angle)));
                h = (int)Math.round(Math.abs(r.height*Math.cos(angle))+Math.abs(r.width*Math.sin(angle)));
                while (angleD < 0) angleD += 360;
                while (angleD > 360) angleD -= 360;
                BufferedImage img = new BufferedImage(w, h, BufferedImage.TYPE_4BYTE_ABGR);
                Graphics2D g = img.createGraphics();
                //g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
                g.setComposite(AlphaComposite.getInstance(AlphaComposite.CLEAR, 0.0f));
                g.fillRect(0, 0, w, h);
                g.setPaintMode();
                switch ((angleD/90)%4)
                {
                        case 0:
                                g.translate(0, r.width*Math.sin(angle));
                                break;
                        case 1:
                                g.translate(r.width*Math.sin(angle-Math.PI/2.0), h);
                                break;
                        case 2:
                                g.translate(w, h-r.width*Math.sin(angle-Math.PI));
                                break;
                        case 3:
                                g.translate(w-r.width*Math.sin(angle-3.0*Math.PI/2.0), 0);
                                break;
                }
                g.rotate(-angle);
                g.translate(margin, margin);
                T = g.getTransform();
                if (BackgroundColor.isSet())
                {
                        g.setColor(BackgroundColor.getColor());
                        g.fillRect(-margin+offset, -margin+offset, r.width-2*offset-1, r.height-2*offset-1);
                }
                if (EdgeColor.isSet() && !LineStyle.is('none'))
                {
                        Stroke oldS = g.getStroke();
                        g.setStroke(LineStyle.getStroke(LineWidth.floatValue()));
                        g.setColor(EdgeColor.getColor());
                        g.drawRect(-margin+offset, -margin+offset, r.width-2*offset-1, r.height-2*offset-1);
                        g.setStroke(oldS);
                }
                g.setColor(TextColor.getColor());
                g.setFont(fnt);
                content.render(g);
                g.dispose();
                com.sun.opengl.util.ImageUtil.flipImageVertically(img);
                data = ByteBuffer.wrap(((DataBufferByte)img.getData().getDataBuffer()).getData());
        }
void updateMinMax () [inline, protected]
References AxesObject.convertUnits(), VectorProperty.getArray(), GraphicObject.getAxes(), RadioProperty.getValue(), RadioProperty.is(), TextObject.Position, Property.set(), TextObject.Units, GraphicObject.XLim, GraphicObject.YLim, and GraphicObject.ZLim.
Referenced by TextObject.propertyChanged(), and TextObject.validate().
        {
                if (Units.is('data'))
                {
                        double[] p = getAxes().convertUnits(Position.getArray(), Units.getValue());
                        double xmin2 = (p[0] <= 0 ? Double.POSITIVE_INFINITY : p[0]);
                        double xmax2 = (p[0] <= 0 ? Double.MIN_VALUE : p[0]);
                        double ymin2 = (p[1] <= 0 ? Double.POSITIVE_INFINITY : p[1]);
                        double ymax2 = (p[1] <= 0 ? Double.MIN_VALUE : p[1]);
                        double zmin2 = (p[2] <= 0 ? Double.POSITIVE_INFINITY : p[2]);
                        double zmax2 = (p[2] <= 0 ? Double.MIN_VALUE : p[2]);
                        XLim.set(new double[] {p[0], p[0], xmin2, xmax2}, true);
                        YLim.set(new double[] {p[1], p[1], ymin2, ymax2}, true);
                        ZLim.set(new double[] {p[2], p[2], zmin2, zmax2}, true);
                }
                else
                {
                        double[] lims = new double[] {Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY,
                                Double.POSITIVE_INFINITY, Double.MIN_VALUE};
                        XLim.set(lims, true);
                        YLim.set(lims, true);
                        ZLim.set(lims, true);
                }
        }
void validate () [inline]
Reimplemented from HandleObject.
References TextObject.currentUnits, RadioProperty.getValue(), TextObject.Units, TextObject.updateContent(), and TextObject.updateMinMax().
Referenced by LegendObject.makeItemFromLine(), and AxesObject.makeTextObject().
        {
                currentUnits = Units.getValue();
                updateContent();
                updateMinMax();
                super.validate();
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
VectorProperty ALim [package, inherited]
Referenced by GroupObject.childValidated(), GraphicObject.GraphicObject(), and GroupObject.updateLimits().
BooleanProperty ALimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
ColorProperty BackgroundColor [package]
Referenced by TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
VectorProperty CLim [package, inherited]
Referenced by AxesObject.autoScaleC(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), SurfaceObject.updateColorMinMax(), GroupObject.updateLimits(), ImageObject.updateMinMax(), and PatchObject.updateMinMax().
BooleanProperty CLimInclude [package, inherited]
Referenced by AxesObject.autoScaleC(), BarseriesObject.BarseriesObject(), GraphicObject.GraphicObject(), ImageObject.ImageObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
SimpleTextEngine.Content content [private]
Referenced by TextObject.getExtent(), TextObject.propertyChanged(), TextObject.render(), TextObject.toPostScript(), TextObject.updateContent(), and TextObject.updateData().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
String currentUnits [private]
Referenced by TextObject.propertyChanged(), TextObject.TextObject(), and TextObject.validate().
ByteBuffer data [private]
Referenced by TextObject.drawAsImage(), TextObject.propertyChanged(), TextObject.updateContent(), and TextObject.updateData().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
ColorProperty EdgeColor [package]
Referenced by TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
Font font = null [private]
RadioProperty FontAngle [package]
Referenced by J2DRenderer.draw(), TextObject.getExtent(), LegendObject.makeItemFromLine(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
StringProperty FontName [package]
Referenced by J2DRenderer.draw(), TextObject.getExtent(), LegendObject.makeItemFromLine(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
DoubleProperty FontSize [package]
Referenced by J2DRenderer.draw(), TextObject.getExtent(), LegendObject.makeItemFromLine(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
RadioProperty FontUnits [package]
Referenced by J2DRenderer.draw(), TextObject.getExtent(), LegendObject.makeItemFromLine(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
RadioProperty FontWeight [package]
Referenced by J2DRenderer.draw(), TextObject.getExtent(), LegendObject.makeItemFromLine(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
int glID [protected, inherited]
Referenced by GraphicObject.GraphicObject().
int h [package]
Referenced by TextObject.drawAsImage(), TextObject.toPostScript(), and TextObject.updateData().
RadioProperty HAlign [package]
Referenced by J2DRenderer.draw(), AxesObject.draw(), TextObject.drawAsImage(), AxesObject.makeTextObject(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateContent().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
BooleanProperty LegendInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), GraphicObject.isLegendable(), and LineObject.LineObject().
LineStyleProperty LineStyle [package]
Referenced by TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
DoubleProperty LineWidth [package]
Referenced by TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
DoubleProperty Margin [package]
Referenced by TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
VectorProperty Position [package]
Referenced by LegendObject.doLayout(), J2DRenderer.draw(), AxesObject.draw(), GLRenderer.draw(), TextObject.drawAsImage(), TextObject.propertyChanged(), TextObject.TextObject(), and TextObject.updateMinMax().
BooleanProperty PositionMode [package]
Referenced by AxesObject.draw(), TextObject.propertyChanged(), and TextObject.TextObject().
Rectangle r [private]
Referenced by TextObject.drawAsImage(), TextObject.toPostScript(), and TextObject.updateData().
DoubleProperty Rotation [package]
Referenced by J2DRenderer.draw(), AxesObject.draw(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
AffineTransform T [private]
Referenced by TextObject.drawAsImage(), and TextObject.updateData().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
ColorProperty TextColor [package]
Referenced by J2DRenderer.draw(), LegendObject.makeItemFromLine(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.toPostScript(), and TextObject.updateData().
StringProperty TextString [package]
Referenced by TextObject.draw(), TextObject.propertyChanged(), TextObject.TextObject(), and TextObject.updateContent().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
RadioProperty Units [package]
Referenced by J2DRenderer.draw(), GLRenderer.draw(), TextObject.drawAsImage(), TextObject.propertyChanged(), TextObject.TextObject(), TextObject.updateMinMax(), and TextObject.validate().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
RadioProperty VAlign [package]
Referenced by J2DRenderer.draw(), AxesObject.draw(), TextObject.drawAsImage(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), TextObject.TextObject(), and TextObject.toPostScript().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
int w [private]
Referenced by TextObject.drawAsImage(), TextObject.toPostScript(), and TextObject.updateData().
VectorProperty XLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty XLimInclude [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
VectorProperty YLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty YLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
VectorProperty ZLim [package, inherited]
Referenced by GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty ZLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), LineObject.LineObject(), PatchObject.PatchObject(), LineObject.propertyChanged(), SurfaceObject.SurfaceObject(), and LineObject.validate().
Author
Generated automatically by Doxygen for Octave from the source code.