SimpleTextEngine.PSTextRenderer
NAME
SimpleTextEngine.PSTextRenderer -
SYNOPSIS
Inherits SimpleTextEngine.TextRenderer.
Classes
class PSState
Public Member Functions
void render (Content e)
void render (LineElement e)
void render (Element e)
void render (SubscriptElement e)
void render (SuperscriptElement e)
void render (ScriptElement e)
void render (TeXElement e)
void render (TeXFontCommand e)
Package Functions
PSTextRenderer (StringBuffer buffer, String fname, float fsize, int fstyle, Color fcolor)
Private Member Functions
PSState currentState ()
void pushState (String fontName, float fontSize, int fontStyle, Color fontColor, float yOffset)
void pushState ()
void popState ()
String fontModifier (int style)
String quote (String s)
float round (float d)
String colorCmd (Color c)
Private Attributes
StringBuffer buf
LinkedList stateList
float f
Constructor & Destructor Documentation
PSTextRenderer (StringBufferbuffer, Stringfname, floatfsize, intfstyle, Colorfcolor) [inline, package]
References SimpleTextEngine.PSTextRenderer.buf, SimpleTextEngine.PSTextRenderer.f, Utils.getScreenResolution(), SimpleTextEngine.PSTextRenderer.pushState(), and SimpleTextEngine.PSTextRenderer.stateList.
                {
                        buf = buffer;
                        stateList = new LinkedList();
                        f = 72.0f / Utils.getScreenResolution();
                        pushState(fname, fsize, fstyle, fcolor, 0);
                }
Member Function Documentation
String colorCmd (Colorc) [inline, private]
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        float[] cv = c.getRGBColorComponents(null);
                        return (cv[0] + ' ' + cv[1] + ' ' + cv[2] + ' C');
                }
PSState currentState () [inline, private]
References SimpleTextEngine.PSTextRenderer.stateList.
Referenced by SimpleTextEngine.PSTextRenderer.pushState(), and SimpleTextEngine.PSTextRenderer.render().
                {
                        return (PSState)stateList.get(0);
                }
String fontModifier (intstyle) [inline, private]
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        if ((style & Font.ITALIC) != 0 && (style & Font.BOLD) != 0)
                                return '-BoldOblique';
                        else if ((style & Font.ITALIC) != 0)
                                return '-Oblique';
                        else if ((style & Font.BOLD) != 0)
                                return '-Bold';
                        else return '';
                }
void popState () [inline, private]
References SimpleTextEngine.PSTextRenderer.stateList.
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        stateList.remove(0);
                }
void pushState (StringfontName, floatfontSize, intfontStyle, ColorfontColor, floatyOffset) [inline, private]
References SimpleTextEngine.PSTextRenderer.stateList.
                {
                        stateList.add(0, new PSState(fontName, fontSize, fontStyle, fontColor, yOffset));
                }
void pushState () [inline, private]
References SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.PSState.fontColor, SimpleTextEngine.PSTextRenderer.PSState.fontName, SimpleTextEngine.PSTextRenderer.PSState.fontSize, SimpleTextEngine.PSTextRenderer.PSState.fontStyle, and SimpleTextEngine.PSTextRenderer.PSState.yOffset.
Referenced by SimpleTextEngine.PSTextRenderer.PSTextRenderer(), and SimpleTextEngine.PSTextRenderer.render().
                {
                        PSState st = currentState();
                        pushState(st.fontName, st.fontSize, st.fontStyle, st.fontColor, st.yOffset);
                }
String quote (Strings) [inline, private]
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        return s.replaceAll('([()])', '\\$1');
                }
void render (Contente) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.Content.align, SimpleTextEngine.PSTextRenderer.buf, SimpleTextEngine.PSTextRenderer.colorCmd(), SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.f, SimpleTextEngine.Content.lines, SimpleTextEngine.Element.rect, SimpleTextEngine.LineElement.render(), and SimpleTextEngine.PSTextRenderer.round().
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        buf.append(colorCmd(currentState().fontColor) + '\n');
                        for (int i=0; i<e.lines.length; i++)
                        {
                                if (i > 0)
                                        buf.append('0 ' + round(f*(e.lines[i-1].rect.y-(e.lines[i].rect.height+e.lines[i].rect.y))) + ' rmoveto\n');
                                buf.append('[');
                                e.lines[i].render(this);
                                buf.append('] ' + (e.align == 0 ? 'LLshow' : (e.align == 1 ? 'LCshow' : 'LRshow')) + '\n');
                        }
                }
void render (LineElemente) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.PSTextRenderer.buf, SimpleTextEngine.PSTextRenderer.colorCmd(), SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.PSState.fontColor, SimpleTextEngine.LineElement.iterator(), SimpleTextEngine.PSTextRenderer.popState(), SimpleTextEngine.PSTextRenderer.pushState(), and SimpleTextEngine.Element.render().
                {
                        Iterator it = e.iterator();
                        Color c = currentState().fontColor;
                        pushState();
                        while (it.hasNext())
                        {
                                Element elem = (Element)it.next();
                                elem.render(this);
                        }
                        if (!currentState().fontColor.equals(c))
                                buf.append('{' + colorCmd(c) + '}\n');
                        popState();
                }
void render (Elemente) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.PSTextRenderer.buf, SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.fontModifier(), SimpleTextEngine.PSTextRenderer.PSState.fontName, SimpleTextEngine.PSTextRenderer.PSState.fontSize, SimpleTextEngine.PSTextRenderer.PSState.fontStyle, SimpleTextEngine.PSTextRenderer.quote(), SimpleTextEngine.PSTextRenderer.round(), SimpleTextEngine.Element.text, and SimpleTextEngine.PSTextRenderer.PSState.yOffset.
                {
                        PSState st = currentState();
                        buf.append('[/' + st.fontName + fontModifier(st.fontStyle) + ' ' + round(st.fontSize) +
                                        ' ' + round(st.yOffset) + ' (' + quote(e.text) + ')]\n');
                }
void render (SubscriptElemente) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.f, SimpleTextEngine.PSTextRenderer.PSState.fontColor, SimpleTextEngine.PSTextRenderer.PSState.fontName, SimpleTextEngine.PSTextRenderer.PSState.fontSize, SimpleTextEngine.PSTextRenderer.PSState.fontStyle, SimpleTextEngine.PSTextRenderer.popState(), SimpleTextEngine.PSTextRenderer.pushState(), SimpleTextEngine.Element.rect, SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.PSTextRenderer.PSState.yOffset.
                {
                        PSState st = currentState();
                        pushState(st.fontName, st.fontSize-2, st.fontStyle,
                                st.fontColor, st.yOffset-f*(e.rect.height+e.rect.y));
                        this.render((LineElement)e);
                        popState();
                }
void render (SuperscriptElemente) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.PSState.fontColor, SimpleTextEngine.PSTextRenderer.PSState.fontName, SimpleTextEngine.PSTextRenderer.PSState.fontSize, SimpleTextEngine.PSTextRenderer.PSState.fontStyle, SimpleTextEngine.PSTextRenderer.popState(), SimpleTextEngine.PSTextRenderer.pushState(), SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.PSTextRenderer.PSState.yOffset.
                {
                        PSState st = currentState();
                        pushState(st.fontName, st.fontSize-2, st.fontStyle,
                                st.fontColor, st.yOffset+st.fontSize/2.0f);
                        this.render((LineElement)e);
                        popState();
                }
void render (ScriptElemente) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.PSTextRenderer.buf, SimpleTextEngine.ScriptElement.elems, and SimpleTextEngine.Element.render().
                {
                        buf.append('{[');
                        e.elems[0].render(this);
                        e.elems[1].render(this);
                        buf.append('] PTshow}\n');
                }
void render (TeXElemente) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.PSTextRenderer.buf, SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.fontModifier(), SimpleTextEngine.PSTextRenderer.PSState.fontSize, SimpleTextEngine.PSTextRenderer.PSState.fontStyle, SimpleTextEngine.TeXElement.getSymbolCode(), SimpleTextEngine.PSTextRenderer.round(), SimpleTextEngine.TeXElement.symbol, and SimpleTextEngine.PSTextRenderer.PSState.yOffset.
                {
                        int code = TeXElement.getSymbolCode(e.symbol, 1);
                        PSState st = currentState();
                        if (code > 0)
                        {
                                String hx = Integer.toHexString(code&0xFF);
                                if (hx.length() == 1)
                                        hx = '0' + hx;
                                buf.append('[/Symbol' + fontModifier(st.fontStyle) + ' ' + round(st.fontSize) +
                                                ' ' + round(st.yOffset) + ' <' + hx + '>]\n');
                        }
                }
void render (TeXFontCommande) [inline]
Implements SimpleTextEngine.TextRenderer.
References SimpleTextEngine.PSTextRenderer.buf, SimpleTextEngine.PSTextRenderer.colorCmd(), SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.PSState.fontColor, SimpleTextEngine.PSTextRenderer.PSState.fontName, SimpleTextEngine.PSTextRenderer.PSState.fontSize, and SimpleTextEngine.PSTextRenderer.PSState.fontStyle.
                {
                        if (e instanceof TeXFontColorCommand)
                        {
                                Color c = ((TeXFontColorCommand)e).newColor;
                                buf.append('{' + colorCmd(c) + '}\n');
                                currentState().fontColor = c;
                        }
                        else if (e instanceof TeXFontSwitchCommand)
                                currentState().fontStyle = ((TeXFontSwitchCommand)e).newStyle;
                        else if (e instanceof TeXFontSizeCommand)
                                currentState().fontSize = ((TeXFontSizeCommand)e).newSize;
                        else if (e instanceof TeXFontNameCommand)
                                currentState().fontName = ((TeXFontNameCommand)e).newName;
                }
float round (floatd) [inline, private]
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        return Math.round(d*100)/100.0f;
                }
Member Data Documentation
StringBuffer buf [private]
Referenced by SimpleTextEngine.PSTextRenderer.PSTextRenderer(), and SimpleTextEngine.PSTextRenderer.render().
float f [private]
Referenced by SimpleTextEngine.PSTextRenderer.PSTextRenderer(), and SimpleTextEngine.PSTextRenderer.render().
LinkedList stateList [private]
Referenced by SimpleTextEngine.PSTextRenderer.currentState(), SimpleTextEngine.PSTextRenderer.popState(), SimpleTextEngine.PSTextRenderer.PSTextRenderer(), and SimpleTextEngine.PSTextRenderer.pushState().
Author
Generated automatically by Doxygen for Octave from the source code.