EditControl
NAME
EditControl -
SYNOPSIS
Inherits JTextField, UIControl, ActionListener, DocumentListener, and FocusListener.
Public Member Functions
EditControl (UIControlObject obj)
void setAlignment ()
void propertyChanged (Property p) throws PropertyException
void update ()
JComponent getComponent ()
void dispose ()
void actionPerformed (ActionEvent event)
void changedUpdate (DocumentEvent e)
void insertUpdate (DocumentEvent e)
void removeUpdate (DocumentEvent e)
void focusGained (FocusEvent e)
void focusLost (FocusEvent e)
Package Attributes
UIControlObject uiObj
HandleEventSinkAdapter sink
Private Attributes
boolean contentChanged = false
Constructor & Destructor Documentation
EditControl (UIControlObjectobj) [inline]
References HandleEvent.getProperty(), UIControlObject.HorizontalAlignment, EditControl.propertyChanged(), EditControl.setAlignment(), EditControl.sink, StringProperty.toString(), EditControl.uiObj, and UIControlObject.UIString.
        {
                super();
                addActionListener(this);
                addFocusListener(this);
                getDocument().addDocumentListener(this);
                uiObj = obj;
                setAlignment();
                setText(obj.UIString.toString());
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.UIString);
                sink.listen(obj.HorizontalAlignment);
        }
Member Function Documentation
void actionPerformed (ActionEventevent) [inline]
References EditControl.contentChanged, UIControlObject.controlActivated(), and EditControl.uiObj.
        {
                uiObj.controlActivated(new UIControlEvent(this));
                contentChanged = false;
        }
void changedUpdate (DocumentEvente) [inline]
{}
void dispose () [inline]
Implements UIControl.
References HandleEventSinkAdapter.dispose(), and EditControl.sink.
        {
                sink.dispose();
        }
void focusGained (FocusEvente) [inline]
References EditControl.contentChanged.
        {
                contentChanged = false;
        }
void focusLost (FocusEvente) [inline]
References EditControl.contentChanged, UIControlObject.controlActivated(), and EditControl.uiObj.
        {
                if (contentChanged)
                {
                        uiObj.controlActivated(new UIControlEvent(this));
                        contentChanged = false;
                }
        }
JComponent getComponent () [inline]
Implements UIControl.
        {
                return this;
        }
void insertUpdate (DocumentEvente) [inline]
References EditControl.contentChanged.
        {
                contentChanged = true;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References UIControlObject.HorizontalAlignment, EditControl.setAlignment(), StringProperty.toString(), EditControl.uiObj, and UIControlObject.UIString.
Referenced by EditControl.EditControl().
        {
                if (p == uiObj.UIString)
                        setText(uiObj.UIString.toString());
                else if (p == uiObj.HorizontalAlignment)
                        setAlignment();
        }
void removeUpdate (DocumentEvente) [inline]
References EditControl.contentChanged.
        {
                contentChanged = true;
        }
void setAlignment () [inline]
References UIControlObject.HorizontalAlignment, RadioProperty.is(), and EditControl.uiObj.
Referenced by EditControl.EditControl(), and EditControl.propertyChanged().
        {
                setHorizontalAlignment(
                        uiObj.HorizontalAlignment.is('center') ? JTextField.CENTER :
                        uiObj.HorizontalAlignment.is('left') ? JTextField.LEFT :
                        uiObj.HorizontalAlignment.is('right') ? JTextField.RIGHT :
                        JTextField.LEFT);
        }
void update () [inline]
Implements UIControl.
References Property.reset(), EditControl.uiObj, and UIControlObject.UIString.
        {
                uiObj.UIString.reset(getText());
        }
Member Data Documentation
boolean contentChanged = false [private]
Referenced by EditControl.actionPerformed(), EditControl.focusGained(), EditControl.focusLost(), EditControl.insertUpdate(), and EditControl.removeUpdate().
HandleEventSinkAdapter sink [package]
Referenced by EditControl.dispose(), and EditControl.EditControl().
UIControlObject uiObj [package]
Referenced by EditControl.actionPerformed(), EditControl.EditControl(), EditControl.focusLost(), EditControl.propertyChanged(), EditControl.setAlignment(), and EditControl.update().
Author
Generated automatically by Doxygen for Octave from the source code.