GL2PS
NAME
GL2PS -
SYNOPSIS
Classes
class GL2PSMarkerDrawer
Static Public Member Functions
static native int gl2psBeginPage (String title, String producer, int[] viewport, int format, int sort, int options, int colormode, int colorsize, Object[] colortable, int nr, int ng, int nb, int buffersize, String outputname, String filename)
static native int gl2psEndPage ()
static native int gl2psText (String string, String fontname, int fontsize)
static native int gl2psTextOpt (String string, String fontname, int fontsize, int align, float angle, float margin, boolean offsetmargin, float linewidth, float[] linecolor, short linepattern, int linefactor, float[] fillcolor)
static native int gl2psEnable (int mode)
static native int gl2psDisable (int mode)
static native int gl2psBeginViewport (int[] viewport)
static native int gl2psEndViewport ()
static native int gl2psLineWidth (float w)
static native int gl2psSpecial (int format, String str, int moveTo)
static GLRenderer.MarkerDrawer getMarkerDrawer (GL gl)
static String makeMarkerPSString (MarkerProperty p, DoubleProperty s, float lw)
Static Package Functions
[static initializer]
Static Package Attributes
static final int GL2PS_MAJOR_VERSION = 1
static final int GL2PS_MINOR_VERSION = 3
static final int GL2PS_PATCH_VERSION = 2
static final String GL2PS_EXTRA_VERSION = ''
static final double GL2PS_VERSION
static final String GL2PS_COPYRIGHT = '(C) 1999-2006 Christophe Geuzaine (geuz@geuz.org)'
static final int GL2PS_PS = 0
static final int GL2PS_EPS = 1
static final int GL2PS_TEX = 2
static final int GL2PS_PDF = 3
static final int GL2PS_SVG = 4
static final int GL2PS_PGF = 5
static final int GL2PS_NO_SORT = 1
static final int GL2PS_SIMPLE_SORT = 2
static final int GL2PS_BSP_SORT = 3
static final int GL2PS_SUCCESS = 0
static final int GL2PS_INFO = 1
static final int GL2PS_WARNING = 2
static final int GL2PS_ERROR = 3
static final int GL2PS_NO_FEEDBACK = 4
static final int GL2PS_OVERFLOW = 5
static final int GL2PS_UNINITIALIZED = 6
static final int GL2PS_NONE = 0
static final int GL2PS_DRAW_BACKGROUND = (1<<0)
static final int GL2PS_SIMPLE_LINE_OFFSET = (1<<1)
static final int GL2PS_SILENT = (1<<2)
static final int GL2PS_BEST_ROOT = (1<<3)
static final int GL2PS_OCCLUSION_CULL = (1<<4)
static final int GL2PS_NO_TEXT = (1<<5)
static final int GL2PS_LANDSCAPE = (1<<6)
static final int GL2PS_NO_PS3_SHADING = (1<<7)
static final int GL2PS_NO_PIXMAP = (1<<8)
static final int GL2PS_USE_CURRENT_VIEWPORT = (1<<9)
static final int GL2PS_COMPRESS = (1<<10)
static final int GL2PS_NO_BLENDING = (1<<11)
static final int GL2PS_TIGHT_BOUNDING_BOX = (1<<12)
static final int GL2PS_POLYGON_OFFSET_FILL = 1
static final int GL2PS_POLYGON_BOUNDARY = 2
static final int GL2PS_LINE_STIPPLE = 3
static final int GL2PS_BLEND = 4
static final int GL2PS_TEXT_C = 1
static final int GL2PS_TEXT_CL = 2
static final int GL2PS_TEXT_CR = 3
static final int GL2PS_TEXT_B = 4
static final int GL2PS_TEXT_BL = 5
static final int GL2PS_TEXT_BR = 6
static final int GL2PS_TEXT_T = 7
static final int GL2PS_TEXT_TL = 8
static final int GL2PS_TEXT_TR = 9
static final int GL2PS_TEXT_L = 10
static final int GL2PS_TEXT_LL = 11
static final int GL2PS_TEXT_LR = 12
Member Function Documentation
[static initializer] () [inline, static, package]
static GLRenderer.MarkerDrawer getMarkerDrawer (GLgl) [inline, static]
Referenced by GLRenderer.getMarkerDrawer().
        {
                return new GL2PSMarkerDrawer(gl);
        }
static native int gl2psBeginPage (Stringtitle, Stringproducer, int[]viewport, intformat, intsort, intoptions, intcolormode, intcolorsize, Object[]colortable, intnr, intng, intnb, intbuffersize, Stringoutputname, Stringfilename) [static]
Referenced by GLRenderCanvas.display().
static native int gl2psBeginViewport (int[]viewport) [static]
Referenced by GLRenderer.setXForm().
static native int gl2psDisable (intmode) [static]
Referenced by GLRenderer.setLineStyle(), and GLRenderer.setPolygonOffset().
static native int gl2psEnable (intmode) [static]
Referenced by GLRenderer.setLineStyle(), and GLRenderer.setPolygonOffset().
static native int gl2psEndPage () [static]
Referenced by GLRenderCanvas.display().
static native int gl2psEndViewport () [static]
Referenced by GLRenderer.setXForm().
static native int gl2psLineWidth (floatw) [static]
Referenced by GLRenderer.setLineWidth().
static native int gl2psSpecial (intformat, Stringstr, intmoveTo) [static]
Referenced by GL2PS.GL2PSMarkerDrawer.draw(), GLRenderer.draw(), and GLRenderer.drawText().
static native int gl2psText (Stringstring, Stringfontname, intfontsize) [static]
static native int gl2psTextOpt (Stringstring, Stringfontname, intfontsize, intalign, floatangle, floatmargin, booleanoffsetmargin, floatlinewidth, float[]linecolor, shortlinepattern, intlinefactor, float[]fillcolor) [static]
static String makeMarkerPSString (MarkerPropertyp, DoublePropertys, floatlw) [inline, static]
References DoubleProperty.doubleValue(), Utils.getHexagramPoints(), Utils.getPentagramPoints(), and RadioProperty.getValue().
Referenced by GL2PS.GL2PSMarkerDrawer.begin().
        {
                String str;
                double sz2 = s.doubleValue()/2, sz = s.doubleValue();
                str = (lw + ' W [] 0 setdash\n');
                switch (p.getValue().charAt(0))
                {
                        case 's':
                                str += ((-sz2) + ' ' + (-sz2) + ' rmoveto SP newpath RP\n');
                                str += ((-sz) + ' 0 0 ' + sz + ' ' + sz + ' 0 3 {rlineto} repeat closepath\n');
                                break;
                        case 'o':
                                str += ('currentpoint newpath ' + sz2 + ' 0 360 arc\n');
                                break;
                        case 'x':
                                str += ((-sz2) + ' ' + (-sz2) + ' rmoveto SP newpath RP\n');
                                str += (sz + ' ' + sz + ' rlineto\n0 ' + (-sz) + ' rmoveto ' + (-sz) + ' ' + sz + ' rlineto\n');
                                break;
                        case '+':
                                str += ((-sz2) + ' 0 rmoveto SP newpath RP\n');
                                str += (sz + ' 0 rlineto ' + (-sz2) + ' ' + (-sz2) + ' rmoveto\n');
                                str += ('0 ' + sz + ' rlineto\n');
                                break;
                        case '<':
                                str += ((-2*sz/3) + ' 0 rmoveto SP newpath RP\n');
                                str += (sz + ' ' + sz2 + ' rlineto 0 ' + (-sz) + ' rlineto closepath\n');
                                break;
                        case '>':
                                str += ((2*sz/3) + ' 0 rmoveto SP newpath RP\n');
                                str += ((-sz) + ' ' + sz2 + ' rlineto 0 ' + (-sz) + ' rlineto closepath\n');
                                break;
                        case '^':
                                str += ('0 ' + (2*sz/3) + ' rmoveto SP newpath RP\n');
                                str += ((-sz2) + ' ' + (-sz) + ' rlineto ' + sz + ' 0 rlineto closepath\n');
                                break;
                        case 'v':
                                str += ('0 ' + (-2*sz/3) + ' rmoveto SP newpath RP\n');
                                str += ((-sz2) + ' ' + sz + ' rlineto ' + sz + ' 0 rlineto closepath\n');
                                break;
                        case 'd':
                                str += ((-sz2) + ' 0 rmoveto SP newpath RP\n');
                                str += ((-sz2) + ' ' + (-sz2) + ' '+ sz2 + ' ' + (-sz2) + ' ' + sz2 + ' ' + sz2 + ' 3 {rlineto} repeat closepath\n');
                                break;
                        case '*':
                                str += ('0 ' + (-sz2) + ' rmoveto SP newpath RP\n');
                                str += ('0 ' + sz + ' rlineto\n');
                                str += ((-sz2) + ' ' + (-sz2) + ' rmoveto ' + sz + ' 0 rlineto\n');
                                str += ((-sz/6) + ' ' + (-sz/3) + ' rmoveto ' + (-2*sz/3) + ' ' + (2*sz/3) + ' rlineto\n');
                                str += ((2*sz/3) + ' 0 rmoveto ' + (-2*sz/3) + ' ' + (-2*sz/3) + ' rlineto\n');
                                break;
                        case '.':
                                str += ('currentpoint newpath 1 0 360 arc\n');
                                break;
                        case 'p':
                                double[][] pts = Utils.getPentagramPoints();
                                double pr = (sz/2+1), px = pr*pts[0][0], py = pr*pts[0][1];
                                str += (px + ' ' + py + ' rmoveto SP newpath RP\n');
                                for (int i=1; i<pts.length; i++)
                                {
                                        double x1 = pr*pts[i][0], y1 = pr*pts[i][1];
                                        str += ((x1-px) + ' ' + (y1-py) + ' rlineto\n');
                                        px = x1;
                                        py = y1;
                                }
                                str += 'closepath\n';
                                break;
                        case 'h':
                                double[][] hpts = Utils.getHexagramPoints();
                                double hr = (sz/2+1), hx = hr*hpts[0][0], hy = hr*hpts[0][1];
                                str += (hx + ' ' + hy + ' rmoveto SP newpath RP\n');
                                for (int i=1; i<hpts.length; i++)
                                {
                                        double x1 = hr*hpts[i][0], y1 = hr*hpts[i][1];
                                        str += ((x1-hx) + ' ' + (y1-hy) + ' rlineto\n');
                                        hx = x1;
                                        hy = y1;
                                }
                                str += 'closepath\n';
                                break;
                }
                return str;
        }
Member Data Documentation
final int GL2PS_BEST_ROOT = (1<<3) [static, package]
Referenced by GLRenderCanvas.display().
final int GL2PS_BLEND = 4 [static, package]
final int GL2PS_BSP_SORT = 3 [static, package]
Referenced by GLRenderCanvas.display().
final int GL2PS_COMPRESS = (1<<10) [static, package]
final String GL2PS_COPYRIGHT = '(C) 1999-2006 Christophe Geuzaine (geuz@geuz.org)' [static, package]
final int GL2PS_DRAW_BACKGROUND = (1<<0) [static, package]
final int GL2PS_EPS = 1 [static, package]
Referenced by GLRenderCanvas.display().
final int GL2PS_ERROR = 3 [static, package]
final String GL2PS_EXTRA_VERSION = '' [static, package]
final int GL2PS_INFO = 1 [static, package]
final int GL2PS_LANDSCAPE = (1<<6) [static, package]
final int GL2PS_LINE_STIPPLE = 3 [static, package]
Referenced by GLRenderer.setLineStyle().
final int GL2PS_MAJOR_VERSION = 1 [static, package]
final int GL2PS_MINOR_VERSION = 3 [static, package]
final int GL2PS_NO_BLENDING = (1<<11) [static, package]
final int GL2PS_NO_FEEDBACK = 4 [static, package]
final int GL2PS_NO_PIXMAP = (1<<8) [static, package]
final int GL2PS_NO_PS3_SHADING = (1<<7) [static, package]
final int GL2PS_NO_SORT = 1 [static, package]
final int GL2PS_NO_TEXT = (1<<5) [static, package]
final int GL2PS_NONE = 0 [static, package]
final int GL2PS_OCCLUSION_CULL = (1<<4) [static, package]
final int GL2PS_OVERFLOW = 5 [static, package]
final int GL2PS_PATCH_VERSION = 2 [static, package]
final int GL2PS_PDF = 3 [static, package]
final int GL2PS_PGF = 5 [static, package]
final int GL2PS_POLYGON_BOUNDARY = 2 [static, package]
final int GL2PS_POLYGON_OFFSET_FILL = 1 [static, package]
Referenced by GLRenderer.setPolygonOffset().
final int GL2PS_PS = 0 [static, package]
Referenced by GL2PS.GL2PSMarkerDrawer.draw(), GLRenderer.draw(), and GLRenderer.drawText().
final int GL2PS_SILENT = (1<<2) [static, package]
final int GL2PS_SIMPLE_LINE_OFFSET = (1<<1) [static, package]
final int GL2PS_SIMPLE_SORT = 2 [static, package]
final int GL2PS_SUCCESS = 0 [static, package]
final int GL2PS_SVG = 4 [static, package]
final int GL2PS_TEX = 2 [static, package]
final int GL2PS_TEXT_B = 4 [static, package]
final int GL2PS_TEXT_BL = 5 [static, package]
final int GL2PS_TEXT_BR = 6 [static, package]
final int GL2PS_TEXT_C = 1 [static, package]
final int GL2PS_TEXT_CL = 2 [static, package]
final int GL2PS_TEXT_CR = 3 [static, package]
final int GL2PS_TEXT_L = 10 [static, package]
final int GL2PS_TEXT_LL = 11 [static, package]
final int GL2PS_TEXT_LR = 12 [static, package]
final int GL2PS_TEXT_T = 7 [static, package]
final int GL2PS_TEXT_TL = 8 [static, package]
final int GL2PS_TEXT_TR = 9 [static, package]
final int GL2PS_TIGHT_BOUNDING_BOX = (1<<12) [static, package]
final int GL2PS_UNINITIALIZED = 6 [static, package]
final int GL2PS_USE_CURRENT_VIEWPORT = (1<<9) [static, package]
Referenced by GLRenderCanvas.display().
final double GL2PS_VERSION [static, package]"Initial value:
                (GL2PS_MAJOR_VERSION +
                 0.01 * GL2PS_MINOR_VERSION +
                 0.0001 * GL2PS_PATCH_VERSION)
final int GL2PS_WARNING = 2 [static, package]
Author
Generated automatically by Doxygen for Octave from the source code.