.TH "Positionable" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Positionable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUIControlAdapter\fP, and \fBUIPanelObject\&.PanelWrapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double[] \fBgetPosition\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "double [] \fBgetPosition\fP ()"
.PP
Implemented in \fBUIControlAdapter\fP, and \fBUIPanelObject\&.PanelWrapper\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
