Vector3D
NAME
Vector3D -
SYNOPSIS
Public Member Functions
Vector3D ()
Vector3D (double[] v)
Vector3D (double[] v, boolean copy)
Vector3D (Vector3D V)
void scale (double x, double y, double z)
void transform (Matrix3D m)
double get (int idx)
double[] getData ()
void normalize ()
void sub (Vector3D V)
void add (Vector3D V)
double norm ()
void print (String name)
Static Public Member Functions
static double dot (Vector3D v1, Vector3D v2)
static Vector3D cross (Vector3D v1, Vector3D v2)
static Vector3D normalize (Vector3D V)
Private Attributes
double[] v
Constructor & Destructor Documentation
Vector3D () [inline]
References Vector3D.v.
Referenced by Vector3D.cross(), and Vector3D.normalize().
        {
                v = new double[] {0, 0, 0};
        }
Vector3D (double[]v) [inline]
References Vector3D.v.
        {
                this(v, true);
        }
Vector3D (double[]v, booleancopy) [inline]
References Vector3D.v.
        {
                if (copy)
                        this.v = (double[])v.clone();
                else
                        this.v = v;
        }
Vector3D (Vector3DV) [inline]
References Vector3D.v.
        {
                this(V.v, true);
        }
Member Function Documentation
void add (Vector3DV) [inline]
References Vector3D.v.
Referenced by AxesObject.updateXFormMatrices().
        {
                for (int i=0; i<3; i++)
                                v[i] += V.v[i];
        }
static Vector3D cross (Vector3Dv1, Vector3Dv2) [inline, static]
References Vector3D.v, and Vector3D.Vector3D().
Referenced by AxesObject.updateXFormMatrices().
        {
                return new Vector3D(
                        new double[] {
                                v1.v[1]*v2.v[2]-v1.v[2]*v2.v[1],
                                v1.v[2]*v2.v[0]-v1.v[0]*v2.v[2],
                                v1.v[0]*v2.v[1]-v1.v[1]*v2.v[0]
                        },
                        false);
        }
static double dot (Vector3Dv1, Vector3Dv2) [inline, static]
References Vector3D.v.
Referenced by Vector3D.norm(), and AxesObject.updateXFormMatrices().
        {
                return (v1.v[0]*v2.v[0]+v1.v[1]*v2.v[1]+v1.v[2]*v2.v[2]);
        }
double get (intidx) [inline]
References Vector3D.v.
Referenced by AxesObject.updateXFormMatrices().
        {
                return v[idx];
        }
double [] getData () [inline]
References Vector3D.v.
Referenced by AxesObject.updateXFormMatrices().
        {
                return v;
        }
double norm () [inline]
References Vector3D.dot().
Referenced by AxesObject.updateXFormMatrices().
        {
                return Math.sqrt(dot(this, this));
        }
void normalize () [inline]
References Vector3D.scale(), and Vector3D.v.
Referenced by Vector3D.normalize(), and AxesObject.updateXFormMatrices().
        {
                double f = 1/Math.sqrt(v[0]*v[0]+v[1]*v[1]+v[2]*v[2]);
                scale(f, f, f);
        }
static Vector3D normalize (Vector3DV) [inline, static]
References Vector3D.normalize(), and Vector3D.Vector3D().
        {
                Vector3D newV = new Vector3D(V);
                newV.normalize();
                return newV;
        }
void print (Stringname) [inline]
References Vector3D.v.
        {
                System.out.println(name);
                for (int i=0; i<3; i++)
                        System.out.print(v[i] + ' ');
                System.out.println('');
        }
void scale (doublex, doubley, doublez) [inline]
References Vector3D.v, plt.x, and plt.y.
Referenced by Vector3D.normalize(), and AxesObject.updateXFormMatrices().
        {
                v[0] *= x;
                v[1] *= y;
                v[2] *= z;
        }
void sub (Vector3DV) [inline]
References Vector3D.v.
Referenced by AxesObject.updateXFormMatrices().
        {
                for (int i=0; i<3; i++)
                                v[i] -= V.v[i];
        }
void transform (Matrix3Dm) [inline]
References Matrix3D.getData(), and Vector3D.v.
Referenced by AxesObject.updateXFormMatrices().
        {
                double[] dm = m.getData();
                double[] vv = new double[3];
                for (int i=0; i<3; i++)
                        vv[i] = dm[i+0]*v[0]+dm[i+4]*v[1]+dm[i+8]*v[2]+dm[i+12]*1;
                v = vv;
        }
Member Data Documentation
double [] v [private]
Referenced by Vector3D.add(), Vector3D.cross(), Vector3D.dot(), Vector3D.get(), Vector3D.getData(), Vector3D.normalize(), Vector3D.print(), Vector3D.scale(), Vector3D.sub(), Vector3D.transform(), and Vector3D.Vector3D().
Author
Generated automatically by Doxygen for Octave from the source code.