.TH "AxesObject.LinearScaler" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AxesObject.LinearScaler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAxesObject\&.Scaler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBscale\fP (double x)"
.br
.ti -1c
.RI "double[] \fBscale\fP (double[] x)"
.br
.ti -1c
.RI "double[][] \fBscale\fP (double[][] x)"
.br
.ti -1c
.RI "double \fBunscale\fP (double x)"
.br
.ti -1c
.RI "boolean \fBisLinear\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean \fBisLinear\fP ()\fC [inline]\fP"
.PP
Implements \fBAxesObject\&.Scaler\fP\&.
.PP
.nf
{ return true; }
.fi
.SS "double \fBscale\fP (doublex)\fC [inline]\fP"
.PP
Implements \fBAxesObject\&.Scaler\fP\&.
.PP
References plt\&.x\&.
.PP
.nf
{ return x; }
.fi
.SS "double [] \fBscale\fP (double[]x)\fC [inline]\fP"
.PP
Implements \fBAxesObject\&.Scaler\fP\&.
.PP
References plt\&.x\&.
.PP
.nf
{ return x; }
.fi
.SS "double [][] \fBscale\fP (doublex[][])\fC [inline]\fP"
.PP
Implements \fBAxesObject\&.Scaler\fP\&.
.PP
References plt\&.x\&.
.PP
.nf
{ return x; }
.fi
.SS "double \fBunscale\fP (doublex)\fC [inline]\fP"
.PP
Implements \fBAxesObject\&.Scaler\fP\&.
.PP
References plt\&.x\&.
.PP
.nf
{ return x; }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
