.TH "SimpleTextEngine.PSTextRenderer.PSState" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleTextEngine.PSTextRenderer.PSState \- 
.SH SYNOPSIS
.br
.PP
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBPSState\fP (String \fBfontName\fP, float \fBfontSize\fP, int \fBfontStyle\fP, Color \fBfontColor\fP, float \fByOffset\fP)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBfontName\fP"
.br
.ti -1c
.RI "float \fBfontSize\fP"
.br
.ti -1c
.RI "int \fBfontStyle\fP"
.br
.ti -1c
.RI "Color \fBfontColor\fP"
.br
.ti -1c
.RI "float \fByOffset\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPSState\fP (StringfontName, floatfontSize, intfontStyle, ColorfontColor, floatyOffset)\fC [inline, package]\fP"
.PP
References SimpleTextEngine\&.PSTextRenderer\&.PSState\&.fontColor, SimpleTextEngine\&.PSTextRenderer\&.PSState\&.fontName, SimpleTextEngine\&.PSTextRenderer\&.PSState\&.fontSize, SimpleTextEngine\&.PSTextRenderer\&.PSState\&.fontStyle, and SimpleTextEngine\&.PSTextRenderer\&.PSState\&.yOffset\&.
.PP
.nf
                        {
                                this\&.fontName = fontName;
                                this\&.fontSize = fontSize;
                                this\&.fontStyle = fontStyle;
                                this\&.fontColor = fontColor;
                                this\&.yOffset = yOffset;
                        }
.fi
.SH "Member Data Documentation"
.PP 
.SS "Color \fBfontColor\fP\fC [package]\fP"
.PP
Referenced by SimpleTextEngine\&.PSTextRenderer\&.PSState\&.PSState(), SimpleTextEngine\&.PSTextRenderer\&.pushState(), and SimpleTextEngine\&.PSTextRenderer\&.render()\&.
.SS "String \fBfontName\fP\fC [package]\fP"
.PP
Referenced by SimpleTextEngine\&.PSTextRenderer\&.PSState\&.PSState(), SimpleTextEngine\&.PSTextRenderer\&.pushState(), and SimpleTextEngine\&.PSTextRenderer\&.render()\&.
.SS "float \fBfontSize\fP\fC [package]\fP"
.PP
Referenced by SimpleTextEngine\&.PSTextRenderer\&.PSState\&.PSState(), SimpleTextEngine\&.PSTextRenderer\&.pushState(), and SimpleTextEngine\&.PSTextRenderer\&.render()\&.
.SS "int \fBfontStyle\fP\fC [package]\fP"
.PP
Referenced by SimpleTextEngine\&.PSTextRenderer\&.PSState\&.PSState(), SimpleTextEngine\&.PSTextRenderer\&.pushState(), and SimpleTextEngine\&.PSTextRenderer\&.render()\&.
.SS "float \fByOffset\fP\fC [package]\fP"
.PP
Referenced by SimpleTextEngine\&.PSTextRenderer\&.PSState\&.PSState(), SimpleTextEngine\&.PSTextRenderer\&.pushState(), and SimpleTextEngine\&.PSTextRenderer\&.render()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
