Matrix3D
NAME
Matrix3D -
SYNOPSIS
Public Member Functions
Matrix3D ()
Matrix3D (double[] data)
void translate (double x, double y, double z)
void scale (double sx, double sy, double sz)
void rotate (double a, int ax)
void mult (double[] m)
void mult (Matrix3D m)
void eye ()
void transform (double[] in, double[] out, int n, int offi, int offo)
void transform (double[][] in, double[][] out, int n, int offi, int offo)
void transform (double x, double y, double z, double[] out, int offo)
void transform (double[] x, double[] y, double[] z, int n, double[] tx, double[] ty, double[] tz)
double[] getData ()
Matrix3D inv ()
void print (String name)
Private Attributes
double[] data
Constructor & Destructor Documentation
Matrix3D () [inline]
References Matrix3D.data.
Referenced by Matrix3D.inv().
        {
                        this.data = new double[] {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1};
        }
Matrix3D (double[]data) [inline]
        {
                        this.data = (double[])data.clone();
        }
Member Function Documentation
void eye () [inline]
References Matrix3D.data.
Referenced by AxesObject.updateXFormMatrices().
        {
                        data = new double[] {1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1};
        }
double [] getData () [inline]
References Matrix3D.data.
Referenced by GLRenderer.setXForm(), Vector3D.transform(), and AxesObject.updateXFormMatrices().
        {
                return data;
        }
Matrix3D inv () [inline]
References Matrix3D.data, and Matrix3D.Matrix3D().
Referenced by AxesObject.updateXFormMatrices().
        {
                Matrix3D ret = new Matrix3D();
                double[] d1 = (double[])data.clone();
                double[] d2 = ret.data;
                int i, j, k, swap;
                double p;
                for (i=0; i<4; i++)
                {
                        swap = i;
                        for (j=i+1; j<4; j++)
                                if (Math.abs(d1[j+i*4]) > Math.abs(d1[i+i*4]))
                                        swap = j;
                        if (swap != i)
                                for (k=0; k<4; k++)
                                {
                                        p = d1[i+k*4];
                                        d1[i+k*4] = d1[swap+k*4];
                                        d1[swap+k*4] = p;
                                        p = d2[i+k*4];
                                        d2[i+k*4] = d2[swap+k*4];
                                        d2[swap+k*4] = p;
                                }
                        if (d1[i+i*4] == 0)
                        {
                                System.out.println('WARNING: singular matrix, cannot invert');
                                break;
                        }
                        p = d1[i+i*4];
                        for (k=0; k<4; k++)
                        {
                                d1[i+k*4] /= p;
                                d2[i+k*4] /= p;
                        }
                        for (j=0; j<4; j++)
                                if (i != j)
                                {
                                        p = d1[j+i*4];
                                        for (k=0; k<4; k++)
                                        {
                                                d1[j+k*4] -= (d1[i+k*4]*p);
                                                d2[j+k*4] -= (d2[i+k*4]*p);
                                        }
                                }
                }
                return ret;
        }
void mult (double[]m) [inline]
References Matrix3D.data, and Matrix3D.transform().
Referenced by Matrix3D.mult(), and AxesObject.updateXFormMatrices().
        {
                double[] dd = new double[16];
                transform(m, dd, 4, 0, 0);
                data = dd;
        }
void mult (Matrix3Dm) [inline]
References Matrix3D.data, and Matrix3D.mult().
        {
                mult(m.data);
        }
void print (Stringname) [inline]
References Matrix3D.data.
        {
          System.out.println(name);
          for (int i=0; i<4; i++)
          {
            for (int j=0; j<4; j++)
              System.out.print(data[j*4+i] + ' ');
            System.out.println('');
          }
        }
void rotate (doublea, intax) [inline]
        {
                        /* not really needed actually */
        }
void scale (doublesx, doublesy, doublesz) [inline]
References Matrix3D.data.
Referenced by AxesObject.updateXFormMatrices().
        {
                        data[0] *= sx; data[1] *= sx; data[2] *= sx; data[3] *= sx;
                        data[4] *= sy; data[5] *= sy; data[6] *= sy; data[7] *= sy;
                        data[8] *= sz; data[9] *= sz; data[10] *= sz; data[11] *= sz;
        }
void transform (double[]in, double[]out, intn, intoffi, intoffo) [inline]
References Matrix3D.data.
Referenced by GLRenderer.GLMarkerDrawer.draw(), J2DRenderer.draw(), AxesObject.draw(), J2DRenderer.drawQuads(), J2DRenderer.drawSegments(), J2DRenderer.drawText(), Matrix3D.mult(), J2DRenderer.setClipBox(), AxesObject.transform(), AxesObject.unTransform(), and AxesObject.updateXFormMatrices().
        {
                        for (int i=0; i<n; i++, offi+=4, offo+=4)
                        {
                                        for (int k=0; k<4; k++)
                                        {
                                                        out[offo+k] =
                                                                data[k+0]*in[offi+0]+
                                                                data[k+4]*in[offi+1]+
                                                                data[k+8]*in[offi+2]+
                                                                data[k+12]*in[offi+3];
                                        }
                        }
        }
void transform (doublein[][], doubleout[][], intn, intoffi, intoffo) [inline]
References Matrix3D.data.
        {
                        for (int i=0; i<n; i++)
                        {
                                        for (int k=0; k<4; k++)
                                        {
                                                        out[offo+i][k] =
                                                                data[k+0]*in[offi+i][0]+
                                                                data[k+4]*in[offi+i][1]+
                                                                data[k+8]*in[offi+i][2]+
                                                                data[k+12]*in[offi+i][3];
                                        }
                        }
        }
void transform (doublex, doubley, doublez, double[]out, intoffo) [inline]
References Matrix3D.data.
        {
                for (int k=0; k<3; k++)
                {
                        out[offo+k] =
                                data[k+0]*x+
                                data[k+4]*y+
                                data[k+8]*z+
                                data[k+12]*1;
                }
        }
void transform (double[]x, double[]y, double[]z, intn, double[]tx, double[]ty, double[]tz) [inline]
References Matrix3D.data.
        {
                double a;
                for (int i=0; i<n; i++)
                {
                        a = data[3]*x[i]+data[7]*y[i]+data[11]*z[i]+data[15];
                        tx[i] = (data[0]*x[i]+data[4]*y[i]+data[8] *z[i]+data[12])/a;
                        ty[i] = (data[1]*x[i]+data[5]*y[i]+data[9] *z[i]+data[13])/a;
                        tz[i] = (data[2]*x[i]+data[6]*y[i]+data[10]*z[i]+data[14])/a;
                }
        }
void translate (doublex, doubley, doublez) [inline]
References Matrix3D.data.
Referenced by AxesObject.updateXFormMatrices().
        {
                        data[12] += data[0]*x+data[4]*y+data[8]*z;
                        data[13] += data[1]*x+data[5]*y+data[9]*z;
                        data[14] += data[2]*x+data[6]*y+data[10]*z;
                        data[15] += data[3]*x+data[7]*y+data[11]*z;
        }
Member Data Documentation
double [] data [private]
Referenced by Matrix3D.eye(), Matrix3D.getData(), Matrix3D.inv(), Matrix3D.Matrix3D(), Matrix3D.mult(), Matrix3D.print(), Matrix3D.scale(), Matrix3D.transform(), and Matrix3D.translate().
Author
Generated automatically by Doxygen for Octave from the source code.