HandleObjectListProperty
NAME
HandleObjectListProperty -
SYNOPSIS
Inherits Property.
Public Member Functions
HandleObjectListProperty (PropertySet parent, String name)
HandleObjectListProperty (PropertySet parent, String name, int maxCount)
Property cloneProperty ()
double[] getHandleArray ()
void addElement (HandleObject obj)
void removeElement (HandleObject obj)
HandleObject elementAt (int index)
int size ()
Iterator iterator ()
boolean contains (HandleObject obj)
void removeAllElements ()
String toString ()
PropertySet getParent ()
String getName ()
boolean isReadOnly ()
void setReadOnly (boolean flag)
boolean isVisible ()
void setVisible (boolean flag)
Object get ()
void set (Object value) throws PropertyException
void set (Object value, boolean warn_on_exception)
void reset (Object value)
void lock ()
void unLock ()
boolean isSameValue (Object value)
void delete ()
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
Static Public Member Functions
static Property createProperty (PropertySet parent, String name, String type) throws PropertyException
static Property createProperty (PropertySet parent, String name, String type, Object arg) throws PropertyException
Protected Member Functions
HandleObjectListProperty (HandleObjectListProperty p)
Object getInternal ()
Object convertValue (Object value) throws PropertyException
void initDefault ()
void setInternal (Object value) throws PropertyException
boolean isEqual (Object value)
Protected Attributes
Object pvalue
Package Attributes
int maxCount
Private Member Functions
List getVisibleObjects ()
Constructor & Destructor Documentation
HandleObjectListProperty (HandleObjectListPropertyp) [inline, protected]
Referenced by HandleObjectListProperty.cloneProperty().
        {
                super(p);
        }
HandleObjectListProperty (PropertySetparent, Stringname) [inline]
References Property.name, and Property.parent.
        {
                this(parent, name, -1);
        }
HandleObjectListProperty (PropertySetparent, Stringname, intmaxCount) [inline]
References HandleObjectListProperty.maxCount, and Property.pvalue.
        {
                super(parent, name);
                this.maxCount = maxCount;
                this.pvalue = new Vector();
        }
Member Function Documentation
void addElement (HandleObjectobj) [inline]
References HandleObjectListProperty.maxCount, and Property.pvalue.
Referenced by HandleObject.addChild(), BarseriesObject.BarseriesObject(), HandleObject.initProperties(), RootObject.removeChild(), and FigureObject.windowActivated().
        {
                Vector objectList = (Vector)pvalue;
                if (maxCount <= 0 || objectList.size() < maxCount)
                        objectList.add(obj);
                else
                        objectList.set(maxCount-1, obj);
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and Property.eventSource.
Referenced by HandleObject.listen(), and HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
Property cloneProperty () [inline, virtual]
Implements Property.
References HandleObjectListProperty.HandleObjectListProperty().
        {
                return new HandleObjectListProperty(this);
        }
boolean contains (HandleObjectobj) [inline]
References Property.pvalue.
Referenced by HandleObject.validate().
        {
                Vector objectList = (Vector)pvalue;
                return objectList.contains(obj);
        }
Object convertValue (Objectvalue) throws PropertyException 	 [inline, protected]
Reimplemented from Property.
References HandleObject.getHandleObject().
        {
                Vector v = new Vector();
                if (value == null)
                        return v;
                Class cls = value.getClass();
                if (value instanceof Number)
                {
                        double h = ((Number)value).doubleValue();
                        try
                        {
                                v.add(HandleObject.getHandleObject(h));
                        }
                        catch (Exception e)
                        {
                                throw new PropertyException('invalid handle value - ' + h);
                        }
                }
                else if (value instanceof HandleObject)
                        v.add(value);
                else if ((cls.isArray() && cls.getComponentType().equals(Double.TYPE)) ||
                         (value instanceof Matrix && ((Matrix)value).getClassName().equals('double')))
                {
                        double[] hv = (value instanceof Matrix ? ((Matrix)value).toDouble() : (double[])value);
                        try
                        {
                                for (int i=0; i<hv.length; i++)
                                        v.add(HandleObject.getHandleObject(hv[i]));
                        }
                        catch (Exception e)
                        {
                                throw new PropertyException('invalid handle value');
                        }
                }
                else
                        throw new PropertyException('invalid property value - ' + value);
                return v;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype) throws PropertyException 	 [inline, static, inherited]
References Property.name, and Property.parent.
Referenced by Property.createProperty().
        {
                if (type.equals('double'))
                        return new DoubleProperty(parent, name);
                else if (type.equals('string'))
                        return new StringProperty(parent, name);
                return null;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype, Objectarg) throws PropertyException 	 [inline, static, inherited]
References Property.createProperty(), Property.name, Property.parent, and Property.set().
        {
                if (type.equals('radio'))
                {
                        String[] values = ((String)arg).split('|');
                        return new RadioProperty(parent, name, values, '');
                }
                else
                {
                        Property p = createProperty(parent, name, type);
                        if (p != null)
                                p.set(arg);
                        return p;
                }
        }
void delete () [inline, inherited]
References HandleEventSourceHelper.delete(), and Property.eventSource.
        {
                eventSource.delete();
        }
HandleObject elementAt (intindex) [inline]
References Property.pvalue.
Referenced by AxesObject.autoScaleC(), HandleObject.delete(), HandleObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), BarseriesObject.doLayout(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), BarseriesObject.getBaseLine(), AxesObject.getCanvas(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), BarseriesObject.getPatch(), LegendObject.LegendObject(), RootObject.propertyChanged(), RootObject.removeChild(), FigureObject.removeChild(), ColorbarObject.updateImageFromColormap(), and HandleObject.validate().
        {
                Vector objectList = (Vector)pvalue;
                return (HandleObject)objectList.elementAt(index);
        }
Object get () [inline, inherited]
Reimplemented in NotImplProperty.
References Property.getInternal().
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), AxesObject.doZoom(), HandleObject.get(), LegendObject.LegendObject(), LegendObject.makeItemFromLine(), LegendObject.propertyChanged(), UnwindHandleObject.swapValues(), and CheckBoxControl.update().
        {
                /* TODO: needed?
                if (!lockNotify)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((PropertyListener)it.next()).propertyGetting(this);
                }
                */
                return getInternal();
        }
double [] getHandleArray () [inline]
References HandleObject.getHandle(), and HandleObjectListProperty.getVisibleObjects().
Referenced by HandleObjectListProperty.getInternal().
        {
                List l = getVisibleObjects();
                double[] hList = new double[l.size()];
                Iterator it = l.iterator();
                int index = 0;
                while (it.hasNext())
                {
                        HandleObject hObj = (HandleObject)it.next();
                        hList[index++] = hObj.getHandle();
                }
                return hList;
        }
Object getInternal () [inline, protected]
Reimplemented from Property.
References HandleObjectListProperty.getHandleArray().
        {
                return getHandleArray();
        }
String getName () [inline, inherited]
References Property.name.
Referenced by PropertySet.addProperty(), AxesObject.autoAxis(), NotImplProperty.get(), PropertySet.getNames(), NotImplProperty.set(), Property.set(), and PropertySet.show().
        {
                return name;
        }
PropertySet getParent () [inline, inherited]
References Property.parent.
Referenced by CallbackProperty.execute(), NotImplProperty.get(), Property.initDefault(), HandleObject.listen(), NotImplProperty.set(), and Property.set().
        {
                return parent;
        }
List getVisibleObjects () [inline, private]
References RootObject.getInstance(), HandleObject.HandleVisibility, RadioProperty.is(), RootObject.isCallbackMode(), BooleanProperty.isSet(), Property.pvalue, and RootObject.ShowHiddenHandles.
Referenced by HandleObjectListProperty.getHandleArray(), and HandleObjectListProperty.toString().
        {
                List l = new LinkedList();
                Iterator it = ((Vector)pvalue).iterator();
                boolean showAll = RootObject.getInstance().ShowHiddenHandles.isSet();
                boolean callbackMode = RootObject.getInstance().isCallbackMode();
                while (it.hasNext())
                {
                        HandleObject hObj = (HandleObject)it.next();
                        if (showAll || hObj.HandleVisibility.is('on') ||
                                        (callbackMode && hObj.HandleVisibility.is('callback')))
                                l.add(hObj);
                }
                return l;
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.hasHandleEvent().
        {
                return eventSource.hasHandleEvent(name);
        }
void initDefault () [inline, protected, inherited]
References HandleObject.getDefaultProperty(), Property.getParent(), HandleObject.getType(), Property.name, Property.parent, and Property.pvalue.
Referenced by Property.Property().
        {
                HandleObject parent = (HandleObject)getParent();
                String defname = 'default' + parent.getType() + name;
                Property p = parent.getDefaultProperty(defname);
                if (p != null)
                        pvalue = p.pvalue;
        }
boolean isEqual (Objectvalue) [inline, protected, inherited]
Reimplemented in TextProperty.
References Property.pvalue.
Referenced by Property.isSameValue(), and Property.set().
        {
                /*Object v = getInternal();*/
                Object v = pvalue;
                return (value == null ? v == null : value.equals(v));
        }
boolean isReadOnly () [inline, inherited]
References Property.readOnly.
        {
                return readOnly;
        }
boolean isSameValue (Objectvalue) [inline, inherited]
References Property.convertValue(), and Property.isEqual().
Referenced by HandleObject.waitFor().
        {
                try
                {
                        value = convertValue(value);
                        return isEqual(value);
                }
                catch (PropertyException e)
                {
                        return false;
                }
        }
boolean isVisible () [inline, inherited]
References Property.visible.
Referenced by PropertySet.getNames(), and PropertySet.show().
        {
                return visible;
        }
Iterator iterator () [inline]
References Property.pvalue.
Referenced by AxesObject.autoLegend(), LegendObject.buildLegend(), BarseriesObject.delete(), AxesContainer.display(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesContainer.getObjectForPoint(), BarseriesObject.propertyChanged(), AxesContainer.reshape(), GroupObject.updateLimits(), and GroupObject.validate().
        {
                Vector objectList = (Vector)pvalue;
                return objectList.iterator();
        }
void lock () [inline, inherited]
References Property.lockNotify.
        {
                lockNotify = true;
        }
void removeAllElements () [inline]
References Property.pvalue.
Referenced by RootObject.propertyChanged(), RootObject.removeChild(), and FigureObject.removeChild().
        {
                Vector objectList = (Vector)pvalue;
                objectList.removeAllElements();
        }
void removeElement (HandleObjectobj) [inline]
References Property.pvalue.
Referenced by BarseriesObject.delete(), and HandleObject.removeChild().
        {
                Vector objectList = (Vector)pvalue;
                objectList.remove(obj);
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
        {
                eventSource.removeHandleEventSink(sink);
        }
void reset (Objectvalue) [inline, inherited]
References Property.lockNotify.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), ColorbarObject.buildColorbar(), LegendObject.buildLegend(), ColorbarObject.ColorbarObject(), HandleObject.delete(), LegendObject.doLayout(), AxesObject.draw(), AxesObject.getBaseLine(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), PatchObject.PatchObject(), FigureObject.print(), LineObject.propertyChanged(), BarseriesObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.reset(), GraphicObject.set(), SurfaceObject.SurfaceObject(), UnwindHandleObject.swapValues(), TextObject.TextObject(), CheckBoxControl.update(), EditControl.update(), PopupMenuControl.update(), Edit2Control.update(), ListBoxControl.update(), AxesObject.updateXFormMatrices(), LineObject.validate(), SurfaceObject.validate(), and PatchObject.validate().
        {
                boolean oldLockNotify = lockNotify;
                lockNotify = true;
                try { set(value); }
                catch (PropertyException e)
                {
                        System.err.println('WARNING: exception during property reset: ' + e);
                }
                lockNotify = oldLockNotify;
        }
void set (Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in BooleanProperty, and NotImplProperty.
References Property.convertValue(), Property.eventSource, HandleEventSourceHelper.fireEvent(), Property.getName(), Property.getParent(), Property.isEqual(), Property.lockNotify, Property.readOnly, Property.setFlag, and Property.setInternal().
Referenced by HandleObject.autoSet(), BarseriesObject.BarseriesObject(), ColorbarObject.buildColorbar(), Property.createProperty(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), BarseriesObject.propertyChanged(), LegendObject.propertyChanged(), PatchObject.propertyChanged(), AxesObject.propertyChanged(), HandleObject.set(), AxesObject.unZoom(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), SurfaceObject.updateColorMinMax(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
        {
                if (readOnly)
                        throw new PropertyException('read-only property - ' + getName());
                value = convertValue(value);
                if (isEqual(value))
                {
                        //System.out.println(getName() + ': identical value, not setting - ' + value.toString());
                        return;
                }
                if (setFlag)
                {
                        System.out.println('WARNING: ' + getName() + '.set (' + ((HandleObject)getParent()).getHandle() + '): recursive behavior detected, not setting');
                        Thread.dumpStack();
                        return;
                }
                setFlag = true;
                try
                {
                        /* TODO: needed?
                        if (!lockNotify)
                        {
                                Iterator it = listenerList.iterator();
                                while (it.hasNext())
                                        ((PropertyListener)it.next()).propertySetting(this, value);
                        }
                        */
                        setInternal(value);
                        if (!lockNotify)
                        {
                                eventSource.fireEvent('PropertyChanged');
                        }
                        setFlag = false;
                }
                catch (Exception e)
                {
                        setFlag = false;
                        if (e instanceof PropertyException)
                                throw (PropertyException)e;
                        else
                                throw new PropertyException(e);
                }
        }
void set (Objectvalue, booleanwarn_on_exception) [inline, inherited]
References Property.getName().
        {
                try { set(value); }
                catch (PropertyException e)
                {
                        if (warn_on_exception)
                        {
                                System.out.println('WARNING: ' + getName() + '.set: exception occured');
                                e.printStackTrace();
                        }
                }
        }
void setInternal (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented in ArrayProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.set().
        {
                pvalue = value;
        }
void setReadOnly (booleanflag) [inline, inherited]
References Property.readOnly.
        {
                readOnly = flag;
        }
void setVisible (booleanflag) [inline, inherited]
References Property.visible.
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), FigureObject.FigureObject(), GraphicObject.GraphicObject(), and PatchObject.PatchObject().
        {
                visible = flag;
        }
int size () [inline]
References Property.pvalue.
Referenced by AxesObject.autoScaleC(), BarseriesObject.delete(), HandleObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), BarseriesObject.doLayout(), HandleObject.getAncestor(), AxesObject.getAxesContainer(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), RootObject.isCallbackMode(), RootObject.propertyChanged(), RootObject.removeChild(), FigureObject.removeChild(), and HandleObject.validate().
        {
                Vector objectList = (Vector)pvalue;
                return objectList.size();
        }
String toString () [inline]
References HandleObject.getHandle(), HandleObjectListProperty.getVisibleObjects(), and Utils.handleToString().
        {
                List objectList = getVisibleObjects();
                String buf = '[ ';
                Iterator it = objectList.iterator();
                while (it.hasNext())
                {
                        HandleObject hObj = (HandleObject)it.next();
                        buf += (Utils.handleToString(hObj.getHandle()) + ' ');
                        if (buf.length() > 64)
                                return ('[ 1 x ' + objectList.size() + ' handle array ]');
                }
                buf += ']';
                return buf;
        }
void unLock () [inline, inherited]
References Property.lockNotify.
Referenced by HandleObject.addProperty(), and PropertySet.validate().
        {
                lockNotify = false;
        }
Member Data Documentation
int maxCount [package]
Referenced by HandleObjectListProperty.addElement(), and HandleObjectListProperty.HandleObjectListProperty().
Object pvalue [protected, inherited]
Referenced by HandleObjectListProperty.addElement(), ArrayProperty.ArrayProperty(), BooleanProperty.BooleanProperty(), CallbackProperty.CallbackProperty(), ColorProperty.ColorProperty(), HandleObjectListProperty.contains(), DoubleProperty.DoubleProperty(), DoubleRadioProperty.DoubleRadioProperty(), DoubleProperty.doubleValue(), DoubleRadioProperty.doubleValue(), HandleObjectListProperty.elementAt(), DoubleProperty.floatValue(), StringArrayProperty.getArray(), CallbackProperty.getCallback(), ArrayProperty.getClassName(), ColorProperty.getColor(), ArrayProperty.getDim(), TextProperty.getInternal(), Property.getInternal(), ColorProperty.getInternal(), ArrayProperty.getMatrix(), ArrayProperty.getNDims(), ObjectProperty.getObject(), TextProperty.getText(), RadioProperty.getValue(), VectorProperty.getVector(), HandleObjectListProperty.getVisibleObjects(), HandleObjectListProperty.HandleObjectListProperty(), Property.initDefault(), DoubleProperty.intValue(), DoubleRadioProperty.is(), ColorProperty.is(), DoubleRadioProperty.isDouble(), ArrayProperty.isEmpty(), TextProperty.isEqual(), Property.isEqual(), ColorProperty.isSet(), HandleObjectListProperty.iterator(), LineStyleProperty.LineStyleProperty(), MarkerProperty.MarkerProperty(), ObjectProperty.ObjectProperty(), Property.Property(), RadioProperty.RadioProperty(), HandleObjectListProperty.removeAllElements(), HandleObjectListProperty.removeElement(), TextProperty.setInternal(), Property.setInternal(), HandleObjectListProperty.size(), StringArrayProperty.StringArrayProperty(), StringProperty.StringProperty(), TextProperty.TextProperty(), ObjectProperty.toString(), StringProperty.toString(), RadioProperty.toString(), DoubleRadioProperty.toString(), VectorProperty.toString(), ArrayProperty.toString(), ColorProperty.toString(), and VectorProperty.VectorProperty().
Author
Generated automatically by Doxygen for Octave from the source code.