PushButtonControl
NAME
PushButtonControl -
SYNOPSIS
Inherits JButton, UIControl, and ActionListener.
Public Member Functions
PushButtonControl (UIControlObject obj)
void propertyChanged (Property p) throws PropertyException
void update ()
JComponent getComponent ()
void dispose ()
void actionPerformed (ActionEvent event)
Package Attributes
UIControlObject uiObj
HandleEventSinkAdapter sink
Constructor & Destructor Documentation
PushButtonControl (UIControlObjectobj) [inline]
References HandleEvent.getProperty(), PushButtonControl.propertyChanged(), PushButtonControl.sink, StringProperty.toString(), PushButtonControl.uiObj, and UIControlObject.UIString.
        {
                super();
                setMargin(new Insets(2, 2, 2, 2));
                addActionListener(this);
                uiObj = obj;
                setText(obj.UIString.toString());
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.UIString);
        }
Member Function Documentation
void actionPerformed (ActionEventevent) [inline]
References UIControlObject.controlActivated(), and PushButtonControl.uiObj.
        {
                uiObj.controlActivated(new UIControlEvent(this));
        }
void dispose () [inline]
Implements UIControl.
References HandleEventSinkAdapter.dispose(), and PushButtonControl.sink.
        {
                sink.dispose();
        }
JComponent getComponent () [inline]
Implements UIControl.
        {
                return this;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References StringProperty.toString(), PushButtonControl.uiObj, and UIControlObject.UIString.
Referenced by PushButtonControl.PushButtonControl().
        {
                if (p == uiObj.UIString)
                        setText(uiObj.UIString.toString());
        }
void update () [inline]
Implements UIControl.
        {
        }
Member Data Documentation
HandleEventSinkAdapter sink [package]
Referenced by PushButtonControl.dispose(), and PushButtonControl.PushButtonControl().
UIControlObject uiObj [package]
Referenced by PushButtonControl.actionPerformed(), PushButtonControl.propertyChanged(), and PushButtonControl.PushButtonControl().
Author
Generated automatically by Doxygen for Octave from the source code.