ArrayProperty
NAME
ArrayProperty -
SYNOPSIS
Inherits Property.
Public Member Functions
ArrayProperty (PropertySet parent, String name, String[] types, int dims)
ArrayProperty (PropertySet parent, String name, Matrix matrix)
ArrayProperty (PropertySet parent, String name, String[] types, int dims, Matrix matrix)
Property cloneProperty ()
Matrix getMatrix ()
int getNDims ()
int getDim (int index)
String getClassName ()
boolean isType (String cls)
boolean isAllowedType (String cls)
boolean isEmpty ()
String toString ()
double[] asDoubleVector ()
double[][] asDoubleMatrix ()
double[][][] asDoubleMatrix3 ()
int[][] asIntMatrix ()
PropertySet getParent ()
String getName ()
boolean isReadOnly ()
void setReadOnly (boolean flag)
boolean isVisible ()
void setVisible (boolean flag)
Object get ()
void set (Object value) throws PropertyException
void set (Object value, boolean warn_on_exception)
void reset (Object value)
void lock ()
void unLock ()
boolean isSameValue (Object value)
void delete ()
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
Static Public Member Functions
static Property createProperty (PropertySet parent, String name, String type) throws PropertyException
static Property createProperty (PropertySet parent, String name, String type, Object arg) throws PropertyException
Protected Member Functions
ArrayProperty (ArrayProperty p)
Object convertValue (Object array) throws PropertyException
void setInternal (Object value) throws PropertyException
void initDefault ()
Object getInternal ()
boolean isEqual (Object value)
Protected Attributes
Object pvalue
Package Attributes
String[] allowedTypes
int allowedDims
Constructor & Destructor Documentation
ArrayProperty (ArrayPropertyp) [inline, protected]
References ArrayProperty.allowedDims, and ArrayProperty.allowedTypes.
Referenced by ArrayProperty.cloneProperty().
        {
                super(p);
                this.allowedTypes = p.allowedTypes;
                this.allowedDims = p.allowedDims;
        }
ArrayProperty (PropertySetparent, Stringname, String[]types, intdims) [inline]
References ArrayProperty.allowedDims, and ArrayProperty.allowedTypes.
        {
                super(parent, name);
                allowedTypes = types;
                allowedDims = dims;
        }
ArrayProperty (PropertySetparent, Stringname, Matrixmatrix) [inline]
References Property.name, Property.parent, and Property.pvalue.
        {
                this(parent, name, (String[])null, -1);
                this.pvalue = (matrix != null ? matrix : new Matrix(new double[0], new int[] {0, 0}));
        }
ArrayProperty (PropertySetparent, Stringname, String[]types, intdims, Matrixmatrix) [inline]
References Property.name, Property.parent, and Property.pvalue.
        {
                this(parent, name, types, dims);
                this.pvalue = (matrix != null ? matrix : new Matrix(new double[0], new int[] {0, 0}));
        }
Member Function Documentation
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and Property.eventSource.
Referenced by HandleObject.listen(), and HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
double [][] asDoubleMatrix () [inline]
References ArrayProperty.getMatrix().
Referenced by SurfaceObject.computeNormals(), PatchObject.computeNormals(), AxesObject.convertCData(), AxesObject.convertCDataToIndex(), GLRenderer.draw(), Utils.getAlphaData(), SurfaceObject.getAlphaData(), SurfaceObject.getCData(), PatchObject.getCData(), FigureObject.makeColormapTextureData(), PatchObject.updateCData(), PatchObject.updateFaceCount(), PatchObject.updateFVData(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and PatchObject.updateXYZData().
        {
                return getMatrix().asDoubleMatrix();
        }
double [][][] asDoubleMatrix3 () [inline]
References ArrayProperty.getMatrix().
Referenced by GLRenderer.draw(), and SurfaceObject.getCData().
        {
                return getMatrix().asDoubleMatrix3();
        }
double [] asDoubleVector () [inline]
References ArrayProperty.getMatrix().
Referenced by PatchObject.getCData(), PatchObject.updateFVCData(), and PatchObject.updateMinMax().
        {
                return getMatrix().asDoubleVector();
        }
int [][] asIntMatrix () [inline]
References ArrayProperty.getMatrix().
Referenced by Utils.getAlphaData().
        {
                return getMatrix().asIntMatrix();
        }
Property cloneProperty () [inline, virtual]
Implements Property.
References ArrayProperty.ArrayProperty().
        {
                return new ArrayProperty(this);
        }
Object convertValue (Objectarray) throws PropertyException 	 [inline, protected]
Reimplemented from Property.
References ArrayProperty.allowedDims, and ArrayProperty.isAllowedType().
        {
                if (array == null)
                        return new Matrix(new double[0], new int[] {0, 0});
                if (array instanceof Matrix)
                {
                        Matrix m = (Matrix)array;
                        if (!isAllowedType(m.getClassName()))
                                throw new PropertyException('invalid matrix class - ' + m.getClassName());
                        if (allowedDims != -1)
                        {
                                if (m.getNDims() != allowedDims)
                                        throw new PropertyException('invalid matrix number of dimensions - ' + m.getNDims());
                        }
                        return array;
                }
                else if (array instanceof Number)
                {
                        Number n = (Number)array;
                        if (n instanceof Double && isAllowedType('double'))
                                return new Matrix(new double[] {n.doubleValue()}, new int[] {1, 1});
                        else if (n instanceof Byte && isAllowedType('byte'))
                                return new Matrix(new byte[] {n.byteValue()}, new int[] {1, 1});
                        else
                                throw new PropertyException('invalid data type - ' + n.getClass().toString());
                }
                else
                {
                        try
                        {
                                double[] v = (double[]) array;
                                return new Matrix(v);
                        }
                        catch (ClassCastException e)
                        {
                                throw new PropertyException('invalid property value - ' + array.toString());
                        }
                }
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype) throws PropertyException 	 [inline, static, inherited]
References Property.name, and Property.parent.
Referenced by Property.createProperty().
        {
                if (type.equals('double'))
                        return new DoubleProperty(parent, name);
                else if (type.equals('string'))
                        return new StringProperty(parent, name);
                return null;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype, Objectarg) throws PropertyException 	 [inline, static, inherited]
References Property.createProperty(), Property.name, Property.parent, and Property.set().
        {
                if (type.equals('radio'))
                {
                        String[] values = ((String)arg).split('|');
                        return new RadioProperty(parent, name, values, '');
                }
                else
                {
                        Property p = createProperty(parent, name, type);
                        if (p != null)
                                p.set(arg);
                        return p;
                }
        }
void delete () [inline, inherited]
References HandleEventSourceHelper.delete(), and Property.eventSource.
        {
                eventSource.delete();
        }
Object get () [inline, inherited]
Reimplemented in NotImplProperty.
References Property.getInternal().
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), AxesObject.doZoom(), HandleObject.get(), LegendObject.LegendObject(), LegendObject.makeItemFromLine(), LegendObject.propertyChanged(), UnwindHandleObject.swapValues(), and CheckBoxControl.update().
        {
                /* TODO: needed?
                if (!lockNotify)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((PropertyListener)it.next()).propertyGetting(this);
                }
                */
                return getInternal();
        }
String getClassName () [inline]
References Property.pvalue.
Referenced by SurfaceObject.getAlphaData(), ArrayProperty.isType(), and GLRenderer.makeTextureFromCData().
        {
                return ((Matrix)pvalue).getClassName();
        }
int getDim (intindex) [inline]
References Property.pvalue.
Referenced by ColorbarObject.buildColorbar(), PatchObject.checkConsistency(), PatchObject.checkXYZData(), PatchObject.getCData(), ArrayProperty.isEmpty(), GLRenderer.makeTextureFromCData(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), ImageObject.updateMinMax(), PatchObject.updateMinMax(), PatchObject.updateXYZData(), and PatchObject.validate().
        {
                return ((Matrix)pvalue).getDim(index);
        }
Object getInternal () [inline, protected, inherited]
Reimplemented in ColorProperty, CallbackProperty, HandleObjectListProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.get().
        {
                return pvalue;
        }
Matrix getMatrix () [inline]
References Property.pvalue.
Referenced by ArrayProperty.asDoubleMatrix(), ArrayProperty.asDoubleMatrix3(), ArrayProperty.asDoubleVector(), ArrayProperty.asIntMatrix(), GLRenderer.makeTextureFromCData(), ColorbarObject.propertyChanged(), SurfaceObject.updateColorMinMax(), and ImageObject.updateMinMax().
        {
                return (Matrix)pvalue;
        }
String getName () [inline, inherited]
References Property.name.
Referenced by PropertySet.addProperty(), AxesObject.autoAxis(), NotImplProperty.get(), PropertySet.getNames(), NotImplProperty.set(), Property.set(), and PropertySet.show().
        {
                return name;
        }
int getNDims () [inline]
References Property.pvalue.
Referenced by PatchObject.checkXYZData(), Utils.getAlphaData(), SurfaceObject.getAlphaData(), SurfaceObject.getCData(), ArrayProperty.isEmpty(), GLRenderer.makeTextureFromCData(), PatchObject.updateFVCData(), and ImageObject.updateMinMax().
        {
                return ((Matrix)pvalue).getNDims();
        }
PropertySet getParent () [inline, inherited]
References Property.parent.
Referenced by CallbackProperty.execute(), NotImplProperty.get(), Property.initDefault(), HandleObject.listen(), NotImplProperty.set(), and Property.set().
        {
                return parent;
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.hasHandleEvent().
        {
                return eventSource.hasHandleEvent(name);
        }
void initDefault () [inline, protected, inherited]
References HandleObject.getDefaultProperty(), Property.getParent(), HandleObject.getType(), Property.name, Property.parent, and Property.pvalue.
Referenced by Property.Property().
        {
                HandleObject parent = (HandleObject)getParent();
                String defname = 'default' + parent.getType() + name;
                Property p = parent.getDefaultProperty(defname);
                if (p != null)
                        pvalue = p.pvalue;
        }
boolean isAllowedType (Stringcls) [inline]
References ArrayProperty.allowedTypes.
Referenced by ArrayProperty.convertValue().
        {
                if (allowedTypes != null)
                {
                        for (int i=0; i<allowedTypes.length; i++)
                                if (allowedTypes[i].equals(cls))
                                        return true;
                        return false;
                }
                return true;
        }
boolean isEmpty () [inline]
References ArrayProperty.getDim(), ArrayProperty.getNDims(), and Property.pvalue.
Referenced by PatchObject.checkXYZData(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), PatchObject.updateXYZData(), and PatchObject.validate().
        {
                if (pvalue == null)
                        return true;
                for (int i=0; i<getNDims(); i++)
                        if (getDim(i) > 0)
                                return false;
                return true;
        }
boolean isEqual (Objectvalue) [inline, protected, inherited]
Reimplemented in TextProperty.
References Property.pvalue.
Referenced by Property.isSameValue(), and Property.set().
        {
                /*Object v = getInternal();*/
                Object v = pvalue;
                return (value == null ? v == null : value.equals(v));
        }
boolean isReadOnly () [inline, inherited]
References Property.readOnly.
        {
                return readOnly;
        }
boolean isSameValue (Objectvalue) [inline, inherited]
References Property.convertValue(), and Property.isEqual().
Referenced by HandleObject.waitFor().
        {
                try
                {
                        value = convertValue(value);
                        return isEqual(value);
                }
                catch (PropertyException e)
                {
                        return false;
                }
        }
boolean isType (Stringcls) [inline]
References ArrayProperty.getClassName().
Referenced by Utils.getAlphaData(), and GLRenderer.makeTextureFromCData().
        {
                return getClassName().equals(cls);
        }
boolean isVisible () [inline, inherited]
References Property.visible.
Referenced by PropertySet.getNames(), and PropertySet.show().
        {
                return visible;
        }
void lock () [inline, inherited]
References Property.lockNotify.
        {
                lockNotify = true;
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
        {
                eventSource.removeHandleEventSink(sink);
        }
void reset (Objectvalue) [inline, inherited]
References Property.lockNotify.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), ColorbarObject.buildColorbar(), LegendObject.buildLegend(), ColorbarObject.ColorbarObject(), HandleObject.delete(), LegendObject.doLayout(), AxesObject.draw(), AxesObject.getBaseLine(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), PatchObject.PatchObject(), FigureObject.print(), LineObject.propertyChanged(), BarseriesObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.reset(), GraphicObject.set(), SurfaceObject.SurfaceObject(), UnwindHandleObject.swapValues(), TextObject.TextObject(), CheckBoxControl.update(), EditControl.update(), PopupMenuControl.update(), Edit2Control.update(), ListBoxControl.update(), AxesObject.updateXFormMatrices(), LineObject.validate(), SurfaceObject.validate(), and PatchObject.validate().
        {
                boolean oldLockNotify = lockNotify;
                lockNotify = true;
                try { set(value); }
                catch (PropertyException e)
                {
                        System.err.println('WARNING: exception during property reset: ' + e);
                }
                lockNotify = oldLockNotify;
        }
void set (Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in BooleanProperty, and NotImplProperty.
References Property.convertValue(), Property.eventSource, HandleEventSourceHelper.fireEvent(), Property.getName(), Property.getParent(), Property.isEqual(), Property.lockNotify, Property.readOnly, Property.setFlag, and Property.setInternal().
Referenced by HandleObject.autoSet(), BarseriesObject.BarseriesObject(), ColorbarObject.buildColorbar(), Property.createProperty(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), BarseriesObject.propertyChanged(), LegendObject.propertyChanged(), PatchObject.propertyChanged(), AxesObject.propertyChanged(), HandleObject.set(), AxesObject.unZoom(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), SurfaceObject.updateColorMinMax(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
        {
                if (readOnly)
                        throw new PropertyException('read-only property - ' + getName());
                value = convertValue(value);
                if (isEqual(value))
                {
                        //System.out.println(getName() + ': identical value, not setting - ' + value.toString());
                        return;
                }
                if (setFlag)
                {
                        System.out.println('WARNING: ' + getName() + '.set (' + ((HandleObject)getParent()).getHandle() + '): recursive behavior detected, not setting');
                        Thread.dumpStack();
                        return;
                }
                setFlag = true;
                try
                {
                        /* TODO: needed?
                        if (!lockNotify)
                        {
                                Iterator it = listenerList.iterator();
                                while (it.hasNext())
                                        ((PropertyListener)it.next()).propertySetting(this, value);
                        }
                        */
                        setInternal(value);
                        if (!lockNotify)
                        {
                                eventSource.fireEvent('PropertyChanged');
                        }
                        setFlag = false;
                }
                catch (Exception e)
                {
                        setFlag = false;
                        if (e instanceof PropertyException)
                                throw (PropertyException)e;
                        else
                                throw new PropertyException(e);
                }
        }
void set (Objectvalue, booleanwarn_on_exception) [inline, inherited]
References Property.getName().
        {
                try { set(value); }
                catch (PropertyException e)
                {
                        if (warn_on_exception)
                        {
                                System.out.println('WARNING: ' + getName() + '.set: exception occured');
                                e.printStackTrace();
                        }
                }
        }
void setInternal (Objectvalue) throws PropertyException 	 [inline, protected]
Reimplemented from Property.
        {
                super.setInternal(value);
        }
void setReadOnly (booleanflag) [inline, inherited]
References Property.readOnly.
        {
                readOnly = flag;
        }
void setVisible (booleanflag) [inline, inherited]
References Property.visible.
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), FigureObject.FigureObject(), GraphicObject.GraphicObject(), and PatchObject.PatchObject().
        {
                visible = flag;
        }
String toString () [inline]
References Property.pvalue.
        {
                return pvalue.toString();
        }
void unLock () [inline, inherited]
References Property.lockNotify.
Referenced by HandleObject.addProperty(), and PropertySet.validate().
        {
                lockNotify = false;
        }
Member Data Documentation
int allowedDims [package]
Referenced by ArrayProperty.ArrayProperty(), and ArrayProperty.convertValue().
String [] allowedTypes [package]
Referenced by ArrayProperty.ArrayProperty(), and ArrayProperty.isAllowedType().
Object pvalue [protected, inherited]
Referenced by HandleObjectListProperty.addElement(), ArrayProperty.ArrayProperty(), BooleanProperty.BooleanProperty(), CallbackProperty.CallbackProperty(), ColorProperty.ColorProperty(), HandleObjectListProperty.contains(), DoubleProperty.DoubleProperty(), DoubleRadioProperty.DoubleRadioProperty(), DoubleProperty.doubleValue(), DoubleRadioProperty.doubleValue(), HandleObjectListProperty.elementAt(), DoubleProperty.floatValue(), StringArrayProperty.getArray(), CallbackProperty.getCallback(), ArrayProperty.getClassName(), ColorProperty.getColor(), ArrayProperty.getDim(), TextProperty.getInternal(), Property.getInternal(), ColorProperty.getInternal(), ArrayProperty.getMatrix(), ArrayProperty.getNDims(), ObjectProperty.getObject(), TextProperty.getText(), RadioProperty.getValue(), VectorProperty.getVector(), HandleObjectListProperty.getVisibleObjects(), HandleObjectListProperty.HandleObjectListProperty(), Property.initDefault(), DoubleProperty.intValue(), DoubleRadioProperty.is(), ColorProperty.is(), DoubleRadioProperty.isDouble(), ArrayProperty.isEmpty(), TextProperty.isEqual(), Property.isEqual(), ColorProperty.isSet(), HandleObjectListProperty.iterator(), LineStyleProperty.LineStyleProperty(), MarkerProperty.MarkerProperty(), ObjectProperty.ObjectProperty(), Property.Property(), RadioProperty.RadioProperty(), HandleObjectListProperty.removeAllElements(), HandleObjectListProperty.removeElement(), TextProperty.setInternal(), Property.setInternal(), HandleObjectListProperty.size(), StringArrayProperty.StringArrayProperty(), StringProperty.StringProperty(), TextProperty.TextProperty(), ObjectProperty.toString(), StringProperty.toString(), RadioProperty.toString(), DoubleRadioProperty.toString(), VectorProperty.toString(), ArrayProperty.toString(), ColorProperty.toString(), and VectorProperty.VectorProperty().
Author
Generated automatically by Doxygen for Octave from the source code.