UIControl
NAME
UIControl -
SYNOPSIS
Inherited by CheckBoxControl, Edit2Control, EditControl, ListBoxControl, PopupMenuControl, PushButtonControl, and TextControl.
Public Member Functions
void update ()
JComponent getComponent ()
void dispose ()
Member Function Documentation
void dispose ()
Implemented in ListBoxControl, TextControl, Edit2Control, PopupMenuControl, EditControl, CheckBoxControl, and PushButtonControl.
Referenced by UIControlAdapter.dispose().
JComponent getComponent ()
Implemented in ListBoxControl, TextControl, Edit2Control, PopupMenuControl, EditControl, CheckBoxControl, and PushButtonControl.
Referenced by UIControlAdapter.getComponent(), UIControlAdapter.init(), and UIControlAdapter.propertyChanged().
void update ()
Implemented in ListBoxControl, TextControl, Edit2Control, PopupMenuControl, EditControl, CheckBoxControl, and PushButtonControl.
Referenced by UIControlAdapter.update().
Author
Generated automatically by Doxygen for Octave from the source code.