.TH "RenderCanvas.Container" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderCanvas.Container \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAxesContainer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderCanvas\fP \fBgetCanvas\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBRenderCanvas\fP \fBgetCanvas\fP ()"
.PP
Implemented in \fBAxesContainer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
