GLRenderCanvas
NAME
GLRenderCanvas -
SYNOPSIS
Inherits GLCanvas, GLEventListener, and RenderCanvas.
Public Member Functions
GLRenderCanvas ()
void display (GLAutoDrawable d)
void init (GLAutoDrawable d)
void reshape (GLAutoDrawable d, int x, int y, int width, int height)
void displayChanged (GLAutoDrawable d, boolean deviceChanged, boolean modeChanged)
Renderer getRenderer ()
Component getComponent ()
void redraw ()
void addRenderEventListener (RenderEventListener l)
void removeRenderEventListener (RenderEventListener l)
BufferedImage toImage ()
void toPostScript (String filename)
void addMouseListener (MouseListener l)
void removeMouseListener (MouseListener l)
void addMouseMotionListener (MouseMotionListener l)
void removeMouseMotionListener (MouseMotionListener l)
int getWidth ()
int getHeight ()
int getX ()
int getY ()
Font getFont ()
FontMetrics getFontMetrics (Font fnt)
Private Attributes
GLRenderer r
java.util.List rListeners
String gl2psFileName = null
boolean reshapeDone = false
Constructor & Destructor Documentation
GLRenderCanvas () [inline]
References GLRenderCanvas.r, and GLRenderCanvas.rListeners.
        {
                r = null;
                rListeners = new LinkedList();
                addGLEventListener(this);
        }
Member Function Documentation
void addMouseListener (MouseListenerl) [inherited]
Referenced by AxesContainer.createCanvas().
void addMouseMotionListener (MouseMotionListenerl) [inherited]
Referenced by AxesContainer.createCanvas().
void addRenderEventListener (RenderEventListenerl) [inline]
Implements RenderCanvas.
References GLRenderCanvas.rListeners.
        {
                rListeners.add(l);
        }
void display (GLAutoDrawabled) [inline]
References GL2PS.GL2PS_BEST_ROOT, GL2PS.GL2PS_BSP_SORT, GL2PS.GL2PS_EPS, GL2PS.GL2PS_USE_CURRENT_VIEWPORT, GL2PS.gl2psBeginPage(), GL2PS.gl2psEndPage(), GLRenderCanvas.gl2psFileName, GLRenderCanvas.r, GLRenderCanvas.rListeners, and GLRenderer.setGL2PS().
Referenced by GLRenderCanvas.redraw(), GLRenderCanvas.toImage(), and GLRenderCanvas.toPostScript().
        {
                if (gl2psFileName != null)
                {
                        int result;
                        result = GL2PS.gl2psBeginPage('Title', 'JHandles', null, GL2PS.GL2PS_EPS, GL2PS.GL2PS_BSP_SORT,
                                /*GL2PS.GL2PS_SILENT|*/GL2PS.GL2PS_BEST_ROOT|GL2PS.GL2PS_USE_CURRENT_VIEWPORT/*|GL2PS.GL2PS_OCCLUSION_CULL*/,
                                GL.GL_RGBA, 0, null, 0, 0, 0, 1024*1024,
                                gl2psFileName, '');
                        r.setGL2PS(true);
                        System.out.println('gl2psBeginPage: ' + result);
                }
                Iterator it = rListeners.iterator();
                while (it.hasNext())
                        ((RenderEventListener)it.next()).display(this);
                if (gl2psFileName != null)
                {
                        int result = GL2PS.gl2psEndPage();
                        r.setGL2PS(false);
                        System.out.println('gl2psEndPage: ' + result);
                }
        }
void displayChanged (GLAutoDrawabled, booleandeviceChanged, booleanmodeChanged) [inline]
{}
Component getComponent () [inline]
Implements RenderCanvas.
        {
                return this;
        }
Font getFont () [inherited]
Referenced by LegendObject.doLayout(), and J2DRenderer.drawText().
FontMetrics getFontMetrics (Fontfnt) [inherited]
Referenced by LegendObject.doLayout(), SimpleTextEngine.Layouter.getFontMetrics(), AxesObject.updateOuterPosition(), and AxesObject.updatePosition().
int getHeight () [inherited]
Referenced by ColorbarObject.buildColorbar(), J2DRenderer.clear(), AxesObject.convertUnits(), LegendObject.doLayout(), J2DRenderer.draw(), TextObject.getExtent(), AxesContainer.getObjectForPoint(), GLRenderCanvas.toImage(), TextObject.updateData(), and AxesObject.updateXFormMatrices().
Renderer getRenderer () [inline]
Implements RenderCanvas.
References GLRenderCanvas.r.
        {
                return r;
        }
int getWidth () [inherited]
Referenced by ColorbarObject.buildColorbar(), J2DRenderer.clear(), LegendObject.doLayout(), and GLRenderCanvas.toImage().
int getX () [inherited]
Referenced by AxesContainer.getMouseLocation(), and AxesContainer.getObjectForPoint().
int getY () [inherited]
Referenced by AxesContainer.getMouseLocation(), and AxesContainer.getObjectForPoint().
void init (GLAutoDrawabled) [inline]
References GLRenderCanvas.r.
        {
                GL gl = d.getGL();
                r = new GLRenderer(d);
                gl.glEnable(GL.GL_DEPTH_TEST);
                gl.glDepthFunc(GL.GL_LEQUAL);
                gl.glBlendFunc(GL.GL_SRC_ALPHA, GL.GL_ONE_MINUS_SRC_ALPHA);
                gl.glEnable(GL.GL_NORMALIZE);
                //gl.glFrontFace(GL.GL_CW);
                //gl.glCullFace(GL.GL_BACK);
                //gl.glEnable(GL.GL_CULL_FACE);
        }
void redraw () [inline]
Implements RenderCanvas.
References GLRenderCanvas.display().
        {
                display();
                //repaint();
        }
void removeMouseListener (MouseListenerl) [inherited]
Referenced by AxesContainer.updateCanvas().
void removeMouseMotionListener (MouseMotionListenerl) [inherited]
Referenced by AxesContainer.updateCanvas().
void removeRenderEventListener (RenderEventListenerl) [inline]
Implements RenderCanvas.
References GLRenderCanvas.rListeners.
        {
                rListeners.remove(l);
        }
void reshape (GLAutoDrawabled, intx, inty, intwidth, intheight) [inline]
References GLRenderCanvas.r, GLRenderCanvas.reshapeDone, GLRenderCanvas.rListeners, and GLRenderer.setViewport().
        {
                r.setViewport(width, height);
                Iterator it = rListeners.iterator();
                while (it.hasNext())
                        ((RenderEventListener)it.next()).reshape(this, x, y, width, height);
                
                if (reshapeDone && !Threading.isSingleThreaded())
                {
                        GL gl = d.getGL();
                        gl.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT);
                        d.swapBuffers();
                }
                reshapeDone = true;
        }
BufferedImage toImage () [inline]
Implements RenderCanvas.
References GLRenderCanvas.display(), RenderCanvas.getHeight(), and RenderCanvas.getWidth().
        {
                display();
                getContext().makeCurrent();
                GL gl = getGL();
                ByteBuffer buf = ByteBuffer.allocate(getWidth()*getHeight()*3);
                gl.glReadBuffer(GL.GL_FRONT);
                gl.glReadPixels(0, 0, getWidth(), getHeight(), GL.GL_RGB, GL.GL_UNSIGNED_BYTE, buf);
                gl.glReadBuffer(GL.GL_BACK);
                BufferedImage img = new BufferedImage(getWidth(), getHeight(), BufferedImage.TYPE_3BYTE_BGR);
                img.getRaster().setDataElements(0, 0, getWidth(), getHeight(), buf.array());
                com.sun.opengl.util.ImageUtil.flipImageVertically(img);
                getContext().release();
                return img;
        }
void toPostScript (Stringfilename) [inline]
Implements RenderCanvas.
References GLRenderCanvas.display(), and GLRenderCanvas.gl2psFileName.
        {
                gl2psFileName = filename;
                display();
                gl2psFileName = null;
        }
Member Data Documentation
String gl2psFileName = null [private]
Referenced by GLRenderCanvas.display(), and GLRenderCanvas.toPostScript().
GLRenderer r [private]
Referenced by GLRenderCanvas.display(), GLRenderCanvas.getRenderer(), GLRenderCanvas.GLRenderCanvas(), GLRenderCanvas.init(), and GLRenderCanvas.reshape().
boolean reshapeDone = false [private]
Referenced by GLRenderCanvas.reshape().
java.util.List rListeners [private]
Referenced by GLRenderCanvas.addRenderEventListener(), GLRenderCanvas.display(), GLRenderCanvas.GLRenderCanvas(), GLRenderCanvas.removeRenderEventListener(), and GLRenderCanvas.reshape().
Author
Generated automatically by Doxygen for Octave from the source code.