AxesObject.Scaler
NAME
AxesObject.Scaler -
SYNOPSIS
Inherited by AxesObject.LinearScaler, and AxesObject.LogScaler.
Public Member Functions
double scale (double x)
double[] scale (double[] x)
double[][] scale (double[][] x)
double unscale (double x)
boolean isLinear ()
Member Function Documentation
boolean isLinear ()
Implemented in AxesObject.LogScaler, and AxesObject.LinearScaler.
double scale (doublex)
Implemented in AxesObject.LogScaler, and AxesObject.LinearScaler.
Referenced by AxesObject.draw(), AxesObject.transform(), and AxesObject.updateXFormMatrices().
double [] scale (double[]x)
Implemented in AxesObject.LogScaler, and AxesObject.LinearScaler.
double [][] scale (doublex[][])
Implemented in AxesObject.LogScaler, and AxesObject.LinearScaler.
double unscale (doublex)
Implemented in AxesObject.LogScaler, and AxesObject.LinearScaler.
Referenced by AxesObject.unTransform().
Author
Generated automatically by Doxygen for Octave from the source code.