PopupMenuControl
NAME
PopupMenuControl -
SYNOPSIS
Inherits JComboBox, UIControl, and ActionListener.
Public Member Functions
PopupMenuControl (UIControlObject obj)
void propertyChanged (Property p) throws PropertyException
void update ()
JComponent getComponent ()
void dispose ()
void actionPerformed (ActionEvent event)
Package Attributes
UIControlObject uiObj
HandleEventSinkAdapter sink
Private Member Functions
void updateItems ()
void updateValue ()
Constructor & Destructor Documentation
PopupMenuControl (UIControlObjectobj) [inline]
References HandleEvent.getProperty(), HandleEventSinkAdapter.listen(), PopupMenuControl.propertyChanged(), PopupMenuControl.sink, PopupMenuControl.uiObj, UIControlObject.UIString, PopupMenuControl.updateItems(), PopupMenuControl.updateValue(), and UIControlObject.Value.
        {
                super();
                addActionListener(this);
                uiObj = obj;
                updateItems();
                updateValue();
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.UIString);
                sink.listen(obj.Value);
        }
Member Function Documentation
void actionPerformed (ActionEventevent) [inline]
References UIControlObject.controlActivated(), and PopupMenuControl.uiObj.
        {
                uiObj.controlActivated(new UIControlEvent(this));
        }
void dispose () [inline]
Implements UIControl.
References HandleEventSinkAdapter.dispose(), and PopupMenuControl.sink.
        {
                sink.dispose();
        }
JComponent getComponent () [inline]
Implements UIControl.
        {
                return this;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References PopupMenuControl.uiObj, UIControlObject.UIString, PopupMenuControl.updateItems(), PopupMenuControl.updateValue(), and UIControlObject.Value.
Referenced by PopupMenuControl.PopupMenuControl().
        {
                if (p == uiObj.UIString)
                        updateItems();
                else if (p == uiObj.Value)
                        updateValue();
        }
void update () [inline]
Implements UIControl.
References Property.reset(), PopupMenuControl.uiObj, and UIControlObject.Value.
        {
                uiObj.Value.reset(new double[] {getSelectedIndex()+1});
        }
void updateItems () [inline, private]
References StringProperty.toString(), PopupMenuControl.uiObj, and UIControlObject.UIString.
Referenced by PopupMenuControl.PopupMenuControl(), and PopupMenuControl.propertyChanged().
        {
                String[] items = uiObj.UIString.toString().split('\|');
                removeAllItems();
                for (int i=0; i<items.length; i++)
                        addItem(items[i]);
        }
void updateValue () [inline, private]
References VectorProperty.getArray(), PopupMenuControl.uiObj, and UIControlObject.Value.
Referenced by PopupMenuControl.PopupMenuControl(), and PopupMenuControl.propertyChanged().
        {
                if (uiObj.Value.getArray().length > 0)
                {
                        int index = (int)uiObj.Value.getArray()[0];
                        if (index > 0 && index <= getItemCount())
                                setSelectedIndex(index-1);
                }
        }
Member Data Documentation
HandleEventSinkAdapter sink [package]
Referenced by PopupMenuControl.dispose(), and PopupMenuControl.PopupMenuControl().
UIControlObject uiObj [package]
Referenced by PopupMenuControl.actionPerformed(), PopupMenuControl.PopupMenuControl(), PopupMenuControl.propertyChanged(), PopupMenuControl.update(), PopupMenuControl.updateItems(), and PopupMenuControl.updateValue().
Author
Generated automatically by Doxygen for Octave from the source code.