J2DRenderCanvas
NAME
J2DRenderCanvas -
SYNOPSIS
Inherits Canvas, and RenderCanvas.
Public Member Functions
J2DRenderCanvas ()
void paint (Graphics g)
void update (Graphics g)
void setBounds (int x, int y, int w, int h)
void addRenderEventListener (RenderEventListener l)
void removeRenderEventListener (RenderEventListener l)
void redraw ()
Renderer getRenderer ()
Component getComponent ()
BufferedImage toImage ()
void toPostScript (String filename)
void addMouseListener (MouseListener l)
void removeMouseListener (MouseListener l)
void addMouseMotionListener (MouseMotionListener l)
void removeMouseMotionListener (MouseMotionListener l)
int getWidth ()
int getHeight ()
int getX ()
int getY ()
Font getFont ()
FontMetrics getFontMetrics (Font fnt)
Private Attributes
List listenerList
J2DRenderer r
Image buffer
Constructor & Destructor Documentation
J2DRenderCanvas () [inline]
References J2DRenderCanvas.listenerList, and J2DRenderCanvas.r.
        {
                listenerList = new LinkedList();
                r = new J2DRenderer(this);
        }
Member Function Documentation
void addMouseListener (MouseListenerl) [inherited]
Referenced by AxesContainer.createCanvas().
void addMouseMotionListener (MouseMotionListenerl) [inherited]
Referenced by AxesContainer.createCanvas().
void addRenderEventListener (RenderEventListenerl) [inline]
Implements RenderCanvas.
References J2DRenderCanvas.listenerList.
        {
                listenerList.add(l);
        }
Component getComponent () [inline]
Implements RenderCanvas.
        {
                return this;
        }
Font getFont () [inherited]
Referenced by LegendObject.doLayout(), and J2DRenderer.drawText().
FontMetrics getFontMetrics (Fontfnt) [inherited]
Referenced by LegendObject.doLayout(), SimpleTextEngine.Layouter.getFontMetrics(), AxesObject.updateOuterPosition(), and AxesObject.updatePosition().
int getHeight () [inherited]
Referenced by ColorbarObject.buildColorbar(), J2DRenderer.clear(), AxesObject.convertUnits(), LegendObject.doLayout(), J2DRenderer.draw(), TextObject.getExtent(), AxesContainer.getObjectForPoint(), GLRenderCanvas.toImage(), TextObject.updateData(), and AxesObject.updateXFormMatrices().
Renderer getRenderer () [inline]
Implements RenderCanvas.
References J2DRenderCanvas.r.
        {
                return r;
        }
int getWidth () [inherited]
Referenced by ColorbarObject.buildColorbar(), J2DRenderer.clear(), LegendObject.doLayout(), and GLRenderCanvas.toImage().
int getX () [inherited]
Referenced by AxesContainer.getMouseLocation(), and AxesContainer.getObjectForPoint().
int getY () [inherited]
Referenced by AxesContainer.getMouseLocation(), and AxesContainer.getObjectForPoint().
void paint (Graphicsg) [inline]
References J2DRenderCanvas.buffer, J2DRenderCanvas.listenerList, J2DRenderCanvas.r, and J2DRenderer.setGraphics().
Referenced by J2DRenderCanvas.update().
        {
                if (buffer != null)
                {
                        Graphics bufferGC = buffer.getGraphics();
                        r.setGraphics(bufferGC);
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((RenderEventListener)it.next()).display(this);
                        r.setGraphics(null);
                        bufferGC.dispose();
                        g.drawImage(buffer, 0, 0, this);
                }
        }
void redraw () [inline]
Implements RenderCanvas.
        {
                repaint();
        }
void removeMouseListener (MouseListenerl) [inherited]
Referenced by AxesContainer.updateCanvas().
void removeMouseMotionListener (MouseMotionListenerl) [inherited]
Referenced by AxesContainer.updateCanvas().
void removeRenderEventListener (RenderEventListenerl) [inline]
Implements RenderCanvas.
References J2DRenderCanvas.listenerList.
        {
                listenerList.remove(l);
        }
void setBounds (intx, inty, intw, inth) [inline]
References J2DRenderCanvas.buffer, and J2DRenderCanvas.listenerList.
        {
                super.setBounds(x, y, w, h);
                if (buffer != null)
                {
                        buffer.flush();
                        buffer = null;
                }
                if (w > 0 && h > 0)
                        buffer = createImage(w, h);
                Iterator it = listenerList.iterator();
                while (it.hasNext())
                        ((RenderEventListener)it.next()).reshape(this, x, y, w, h);
        }
BufferedImage toImage () [inline]
Implements RenderCanvas.
        {
                return null;
        }
void toPostScript (Stringfilename) [inline]
Implements RenderCanvas.
        {
        }
void update (Graphicsg) [inline]
References J2DRenderCanvas.paint().
        {
                paint(g);
        }
Member Data Documentation
Image buffer [private]
Referenced by J2DRenderCanvas.paint(), and J2DRenderCanvas.setBounds().
List listenerList [private]
Referenced by J2DRenderCanvas.addRenderEventListener(), J2DRenderCanvas.J2DRenderCanvas(), J2DRenderCanvas.paint(), J2DRenderCanvas.removeRenderEventListener(), and J2DRenderCanvas.setBounds().
J2DRenderer r [private]
Referenced by J2DRenderCanvas.getRenderer(), J2DRenderCanvas.J2DRenderCanvas(), and J2DRenderCanvas.paint().
Author
Generated automatically by Doxygen for Octave from the source code.