Utils
NAME
Utils -
SYNOPSIS
Static Public Member Functions
static void crossProduct (double ax, double ay, double az, double bx, double by, double bz, double[] res)
static void crossProduct (double ax, double ay, double az, double bx, double by, double bz, double[] res, int offset, int ldr)
static void printCpuTime ()
static double[][] getAlphaData (ArrayProperty adata, RadioProperty mapping, AxesObject axes)
static float getFontSize (DoubleProperty FontSize, RadioProperty FontUnits, double h)
static Font getFont (StringProperty FontName, DoubleProperty FontSize, RadioProperty FontUnits, RadioProperty FontAngle, RadioProperty FontWeight, double h)
static Rectangle getScreenRectangle ()
static Dimension getScreenSize ()
static int getScreenResolution ()
static double[] convertPosition (double[] pos, String fromUnits, String toUnits, Component parent)
static Color getBackgroundColor ()
static Color getShadowColor ()
static Color getHighlightColor ()
static String join (String[] items, String sepstr)
static Icon loadIcon (String name)
static boolean isNaNorInf (double x)
static boolean isNaNorInf (double x, double y, double z)
static String handleToString (double handle)
static double[][] getPentagramPoints ()
static double[][] getHexagramPoints ()
Static Private Member Functions
static Color getUIColor (String name, Color def)
Static Private Attributes
static java.text.DecimalFormat hFmt = new java.text.DecimalFormat('0.0000')
static double[][] pentagramPoints
static double[][] hexagramPoints
Member Function Documentation
static double [] convertPosition (double[]pos, StringfromUnits, StringtoUnits, Componentparent) [inline, static]
References Utils.getScreenRectangle(), and Utils.getScreenResolution().
Referenced by ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.getBoundingBox(), AxesObject.getOuterBoundingBox(), UIControlObject.getPosition(), UIPanelObject.getPosition(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), AxesObject.propertyChanged(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), FigureObject.updateFramePosition(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), and AxesObject.updatePosition().
        {
                double[] p = null;
                boolean isContainer = (parent != null && parent instanceof Container);
                if (fromUnits.equalsIgnoreCase('pixels'))
                        p = (double[])pos.clone();
                else if (fromUnits.equalsIgnoreCase('normalized'))
                {
                        Insets ir = (isContainer ? ((Container)parent).getInsets() : new Insets(0, 0, 0, 0));
                        Rectangle r = (parent != null ? parent.getBounds() : getScreenRectangle());
                        int w = r.width-ir.left-ir.right, h = r.height-ir.top-ir.bottom;
                        p = new double[] {pos[0]*w+1, pos[1]*h+1, pos[2]*w, pos[3]*h};
                }
                else if (fromUnits.equalsIgnoreCase('characters'))
                {
                        FontMetrics fm = (parent != null ? parent.getFontMetrics(Font.decode('')) :
                                        Toolkit.getDefaultToolkit().getFontMetrics(Font.decode('')));
                        double f = 1.0;
                        double w = fm.charWidth('x')*f, h = fm.getHeight()*f;
                        
                        p = new double[] {pos[0]*w+1, pos[1]*h+1, pos[2]*w, pos[3]*h};
                }
                else if (fromUnits.equalsIgnoreCase('points'))
                {
                        double f = getScreenResolution()/72.0;
                        p = new double[] {pos[0]*f+1, pos[1]*f+1, pos[2]*f, pos[3]*f};
                }
                else if (fromUnits.equalsIgnoreCase('inches'))
                {
                        double f = getScreenResolution();
                        p = new double[] {pos[0]*f+1, pos[1]*f+1, pos[2]*f, pos[3]*f};
                }
                else if (fromUnits.equalsIgnoreCase('centimeters'))
                {
                        double f = getScreenResolution()/2.54;
                        p = new double[] {pos[0]*f+1, pos[1]*f+1, pos[2]*f, pos[3]*f};
                }
                if (!toUnits.equalsIgnoreCase('pixels'))
                {
                        if (toUnits.equalsIgnoreCase('normalized'))
                        {
                                Insets ir = (isContainer ? ((Container)parent).getInsets() : new Insets(0, 0, 0, 0));
                                Rectangle r = (parent != null ? parent.getBounds() : getScreenRectangle());
                                int w = r.width-ir.left-ir.right, h = r.height-ir.top-ir.bottom;
                                p[0] = (p[0]-1)/w;
                                p[1] = (p[1]-1)/h;
                                p[2] /= w;
                                p[3] /= h;
                        }
                        else if (toUnits.equalsIgnoreCase('characters'))
                        {
                                FontMetrics fm = (parent != null ? parent.getFontMetrics(Font.decode('')) :
                                                Toolkit.getDefaultToolkit().getFontMetrics(Font.decode('')));
                                double f = 1.0;
                                double w = fm.charWidth('x')*f, h = fm.getHeight()*f;
                                p[0] = (p[0]-1)/w;
                                p[1] = (p[1]-1)/h;
                                p[2] /= w;
                                p[3] /= h;
                        }
                        else if (toUnits.equalsIgnoreCase('inches'))
                        {
                                double f = getScreenResolution();
                                p[0] = (p[0]-1)/f;
                                p[1] = (p[1]-1)/f;
                                p[2] /= f;
                                p[3] /= f;
                        }
                        else if (toUnits.equalsIgnoreCase('centimeters'))
                        {
                                double f = getScreenResolution()/2.54;
                                p[0] = (p[0]-1)/f;
                                p[1] = (p[1]-1)/f;
                                p[2] /= f;
                                p[3] /= f;
                        }
                        else if (toUnits.equalsIgnoreCase('inches'))
                        {
                                double f = getScreenResolution()/72.0;
                                p[0] = (p[0]-1)/f;
                                p[1] = (p[1]-1)/f;
                                p[2] /= f;
                                p[3] /= f;
                        }
                }
                return p;
        }
static void crossProduct (doubleax, doubleay, doubleaz, doublebx, doubleby, doublebz, double[]res) [inline, static]
Referenced by SurfaceObject.computeNormals(), and PatchObject.computeNormals().
        {
                crossProduct(ax, ay, az, bx, by, bz, res, 0, 1);
        }
static void crossProduct (doubleax, doubleay, doubleaz, doublebx, doubleby, doublebz, double[]res, intoffset, intldr) [inline, static]
        {
                res[offset+0*ldr] += (ay*bz-az*by);
                res[offset+1*ldr] += (az*bx-ax*bz);
                res[offset+2*ldr] += (ax*by-ay*bx);
        }
static double [][] getAlphaData (ArrayPropertyadata, RadioPropertymapping, AxesObjectaxes) [inline, static]
References AxesObject.ALim, FigureObject.Alphamap, ArrayProperty.asDoubleMatrix(), ArrayProperty.asIntMatrix(), VectorProperty.getArray(), AxesObject.getFigure(), ArrayProperty.getNDims(), RadioProperty.is(), and ArrayProperty.isType().
        {
                if (adata.getNDims() != 2)
                        return null;
                if (mapping.is('none'))
                {
                        if (adata.isType('double'))
                                return adata.asDoubleMatrix();
                }
                else if (mapping.is('direct'))
                {
                        double[] amap = axes.getFigure().Alphamap.getArray();
                        if (adata.isType('double'))
                        {
                                double[][] aa = adata.asDoubleMatrix();
                                double[][] res = new double[aa.length][aa[0].length];
                                for (int i=0; i<res.length; i++)
                                        for (int j=0; j<res[i].length; j++)
                                                res[i][j] = amap[(int)Math.min(Math.max(1, aa[i][j]), amap.length)-1];
                                return res;
                        }
                        else if (adata.isType('integer'))
                        {
                                int[][] aa = adata.asIntMatrix();
                                double[][] res = new double[aa.length][aa[0].length];
                                
                                for (int i=0; i<res.length; i++)
                                        for (int j=0; j<res[i].length; j++)
                                                res[i][j] = amap[Math.min(Math.max(0, aa[i][j]), amap.length-1)];
                                return res;
                        }
                }
                else if (mapping.is('scaled'))
                {
                        double[] amap = axes.getFigure().Alphamap.getArray();
                        double[] alim = axes.ALim.getArray();
                        if (adata.isType('double'))
                        {
                                double[][] aa = adata.asDoubleMatrix();
                                double[][] res = new double[aa.length][aa[0].length];
                                for (int i=0; i<aa.length; i++)
                                        for (int j=0; j<aa[0].length; j++)
                                        {
                                                double s = (aa[i][j]-alim[0])/(alim[1]-alim[0]);
                                                res[i][j] = amap[(int)Math.round((amap.length-1)*s)];
                                        }
                                return res;
                        }
                }
                return null;
        }
static Color getBackgroundColor () [inline, static]
References Utils.getUIColor().
Referenced by FigureObject.FigureObject(), Factory.initUIControlProperties(), and UIPanelObject.UIPanelObject().
        {
                return getUIColor('control', Color.lightGray);
        }
static Font getFont (StringPropertyFontName, DoublePropertyFontSize, RadioPropertyFontUnits, RadioPropertyFontAngle, RadioPropertyFontWeight, doubleh) [inline, static]
References Utils.getFontSize(), Utils.getScreenResolution(), RadioProperty.is(), and StringProperty.toString().
Referenced by J2DRenderer.draw(), AxesObject.draw(), TextObject.getExtent(), UIControlAdapter.init(), UIPanelObject.makePanel(), UIControlAdapter.propertyChanged(), UIPanelObject.propertyChanged(), TextObject.updateData(), AxesObject.updateOuterPosition(), and AxesObject.updatePosition().
        {
                Map map = new HashMap();
                map.put(TextAttribute.FAMILY, FontName.toString());
                map.put(TextAttribute.POSTURE,
                        FontAngle.is('normal') ? TextAttribute.POSTURE_REGULAR : TextAttribute.POSTURE_OBLIQUE);
                map.put(TextAttribute.WEIGHT,
                        FontWeight.is('normal') ? TextAttribute.WEIGHT_REGULAR :
                        FontWeight.is('light') ? TextAttribute.WEIGHT_LIGHT :
                        FontWeight.is('demi') ? TextAttribute.WEIGHT_SEMIBOLD : TextAttribute.WEIGHT_BOLD);
                float fs = getFontSize(FontSize, FontUnits, h);
                map.put(TextAttribute.SIZE, new Float(Math.round(fs*Utils.getScreenResolution()/72.0)));
                
                return new Font(map);
        }
static float getFontSize (DoublePropertyFontSize, RadioPropertyFontUnits, doubleh) [inline, static]
References DoubleProperty.doubleValue(), DoubleProperty.floatValue(), Utils.getScreenResolution(), RadioProperty.getValue(), and RadioProperty.is().
Referenced by Utils.getFont(), and TextObject.toPostScript().
        {
                float fs = 12;
                if (FontUnits.is('points'))
                        fs = FontSize.floatValue();
                else if (FontUnits.is('normalized'))
                        fs = (float)(FontSize.doubleValue()*h*72.0/Utils.getScreenResolution());
                else if (FontUnits.is('inches'))
                        fs = FontSize.floatValue()*72;
                else if (FontUnits.is('centimeters'))
                        fs = (FontSize.floatValue()/2.54f)*72;
                else
                        System.out.println('Warning: ignoring FontUnits (' + FontUnits.getValue() + ')');
                return fs;
        }
static double [][] getHexagramPoints () [inline, static]
References Utils.hexagramPoints.
Referenced by GLRenderer.makeMarkerList(), and GL2PS.makeMarkerPSString().
        {
                if (hexagramPoints == null)
                {
                        hexagramPoints = new double[12][2];
                        double f = 1/Math.sqrt(3);
                        boolean flag = true;
                        for (int i=0; i<12; i++, flag=!flag)
                        {
                                double ang = Math.PI/2 + 2*i*Math.PI/12;
                                double r = (flag ? 1 : f);
                                hexagramPoints[i][0] = r*Math.cos(ang);
                                hexagramPoints[i][1] = r*Math.sin(ang);
                        }
                }
                return hexagramPoints;
        }
static Color getHighlightColor () [inline, static]
References Utils.getUIColor().
Referenced by UIPanelObject.UIPanelObject().
        {
                return getUIColor('controlLtHighlight', Color.white);
        }
static double [][] getPentagramPoints () [inline, static]
References Utils.pentagramPoints.
Referenced by GLRenderer.makeMarkerList(), and GL2PS.makeMarkerPSString().
        {
                if (pentagramPoints == null)
                {
                        pentagramPoints = new double[10][2];
                        double f = Math.sin(Math.PI/10)/Math.sin(3*Math.PI/10);
                        boolean flag = true;
                        for (int i=0; i<10; i++, flag=!flag)
                        {
                                double ang = Math.PI/2 + 2*i*Math.PI/10;
                                double r = (flag ? 1 : f);
                                pentagramPoints[i][0] = r*Math.cos(ang);
                                pentagramPoints[i][1] = r*Math.sin(ang);
                        }
                }
                return pentagramPoints;
        }
static Rectangle getScreenRectangle () [inline, static]
Referenced by Utils.convertPosition().
        {
                return new Rectangle(Toolkit.getDefaultToolkit().getScreenSize());
        }
static int getScreenResolution () [inline, static]
Referenced by Utils.convertPosition(), AxesObject.convertUnits(), MarkerProperty.drawMarker(), GLRenderer.drawText(), Utils.getFont(), Utils.getFontSize(), MarkerProperty.makeMarker(), GLRenderer.makeMarkerList(), SimpleTextEngine.PSTextRenderer.PSTextRenderer(), and TextObject.toPostScript().
        {
                return Toolkit.getDefaultToolkit().getScreenResolution();
        }
static Dimension getScreenSize () [inline, static]
Referenced by FigureObject.FigureObject(), RootObject.RootObject(), FigureObject.updateFramePosition(), and FigureObject.updatePosition().
        {
                return Toolkit.getDefaultToolkit().getScreenSize();
        }
static Color getShadowColor () [inline, static]
References Utils.getUIColor().
Referenced by UIPanelObject.UIPanelObject().
        {
                return getUIColor('controlShadow', Color.gray);
        }
static Color getUIColor (Stringname, Colordef) [inline, static, private]
Referenced by Utils.getBackgroundColor(), Utils.getHighlightColor(), and Utils.getShadowColor().
        {
                try { return (Color)UIManager.get(name); }
                catch (Exception e) { return def; }
        }
static String handleToString (doublehandle) [inline, static]
References Utils.hFmt.
Referenced by TextProperty.toString(), and HandleObjectListProperty.toString().
        {
                return hFmt.format(handle);
        }
static boolean isNaNorInf (doublex) [inline, static]
Referenced by J2DRenderer.draw(), and LineObject.updateMinMax().
        {
                return (Double.isInfinite(x) || Double.isNaN(x));
        }
static boolean isNaNorInf (doublex, doubley, doublez) [inline, static]
        {
                return (Double.isInfinite(x) || Double.isNaN(x) ||
                                Double.isInfinite(y) || Double.isNaN(y) ||
                                Double.isInfinite(z) || Double.isNaN(z));
        }
static String join (String[]items, Stringsepstr) [inline, static]
Referenced by UIControlObject.set().
        {
                String new_str = '';
                for (int i=0; i<items.length; i++)
                {
                        if (i != 0)
                                new_str += sepstr;
                        new_str += items[i];
                }
                return new_str;
        }
static Icon loadIcon (Stringname) [inline, static]
Referenced by FigureObject.createFigure().
        {
                return new ImageIcon(Utils.class.getResource('/org/octave/graphics/images/' + name + '.png'));
        }
static void printCpuTime () [inline, static]
        {
                System.out.println(java.lang.management.ManagementFactory.getThreadMXBean().getCurrentThreadCpuTime());
        }
Member Data Documentation
double [][] hexagramPoints [static, private]
Referenced by Utils.getHexagramPoints().
java.text.DecimalFormat hFmt = new java.text.DecimalFormat('0.0000') [static, private]
Referenced by Utils.handleToString().
double [][] pentagramPoints [static, private]
Referenced by Utils.getPentagramPoints().
Author
Generated automatically by Doxygen for Octave from the source code.