ListBoxControl
NAME
ListBoxControl -
SYNOPSIS
Inherits JScrollPane, UIControl, and ListSelectionListener.
Public Member Functions
ListBoxControl (UIControlObject obj)
void propertyChanged (Property p) throws PropertyException
void update ()
JComponent getComponent ()
void dispose ()
void valueChanged (ListSelectionEvent event)
Package Attributes
UIControlObject uiObj
HandleEventSinkAdapter sink
JList list
Private Member Functions
void updateItems ()
void updateValue ()
void updateSelectionMode ()
void updateColors ()
void updateTop ()
Constructor & Destructor Documentation
ListBoxControl (UIControlObjectobj) [inline]
References UIControlObject.BackgroundColor, UIControlObject.ForegroundColor, HandleEvent.getProperty(), ListBoxControl.list, UIControlObject.ListboxTop, HandleEventSinkAdapter.listen(), UIControlObject.Max, UIControlObject.Min, ListBoxControl.propertyChanged(), ListBoxControl.sink, ListBoxControl.uiObj, UIControlObject.UIString, ListBoxControl.updateColors(), ListBoxControl.updateItems(), ListBoxControl.updateSelectionMode(), ListBoxControl.updateTop(), ListBoxControl.updateValue(), and UIControlObject.Value.
        {
                super();
                uiObj = obj;
                list = new JList();
                list.getSelectionModel().addListSelectionListener(this);
                getViewport().setView(list);
                updateItems();
                updateSelectionMode();
                updateColors();
                updateTop();
                updateValue();
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.UIString);
                sink.listen(obj.Value);
                sink.listen(obj.Min);
                sink.listen(obj.Max);
                sink.listen(obj.BackgroundColor);
                sink.listen(obj.ForegroundColor);
                sink.listen(obj.ListboxTop);
        }
Member Function Documentation
void dispose () [inline]
Implements UIControl.
References HandleEventSinkAdapter.dispose(), and ListBoxControl.sink.
        {
                sink.dispose();
        }
JComponent getComponent () [inline]
Implements UIControl.
        {
                return this;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References UIControlObject.BackgroundColor, UIControlObject.ForegroundColor, UIControlObject.ListboxTop, UIControlObject.Max, UIControlObject.Min, ListBoxControl.uiObj, UIControlObject.UIString, ListBoxControl.updateColors(), ListBoxControl.updateItems(), ListBoxControl.updateSelectionMode(), ListBoxControl.updateTop(), ListBoxControl.updateValue(), and UIControlObject.Value.
Referenced by ListBoxControl.ListBoxControl().
        {
                if (p == uiObj.UIString)
                        updateItems();
                else if (p == uiObj.Value)
                        updateValue();
                else if (p == uiObj.Min || p == uiObj.Max)
                        updateSelectionMode();
                else if (p == uiObj.BackgroundColor || p == uiObj.ForegroundColor)
                        updateColors();
                else if (p == uiObj.ListboxTop)
                        updateTop();
        }
void update () [inline]
Implements UIControl.
References ListBoxControl.list, UIControlObject.ListboxTop, Property.reset(), ListBoxControl.uiObj, and UIControlObject.Value.
        {
                int[] sel = list.getSelectedIndices();
                double[] val = new double[sel.length];
                for (int i=0; i<sel.length; i++)
                        val[i] = sel[i]+1;
                uiObj.Value.reset(val);
                uiObj.ListboxTop.reset(new Double(list.getFirstVisibleIndex()+1));
        }
void updateColors () [inline, private]
References UIControlObject.BackgroundColor, UIControlObject.ForegroundColor, ColorProperty.getColor(), ListBoxControl.list, and ListBoxControl.uiObj.
Referenced by ListBoxControl.ListBoxControl(), and ListBoxControl.propertyChanged().
        {
                setBackground(uiObj.BackgroundColor.getColor());
                setForeground(uiObj.ForegroundColor.getColor());
                list.setBackground(uiObj.BackgroundColor.getColor());
                list.setForeground(uiObj.ForegroundColor.getColor());
        }
void updateItems () [inline, private]
References ListBoxControl.list, StringProperty.toString(), ListBoxControl.uiObj, and UIControlObject.UIString.
Referenced by ListBoxControl.ListBoxControl(), and ListBoxControl.propertyChanged().
        {
                String[] items = uiObj.UIString.toString().split('\|');
                list.setListData(items);
        }
void updateSelectionMode () [inline, private]
References DoubleProperty.doubleValue(), ListBoxControl.list, UIControlObject.Max, UIControlObject.Min, and ListBoxControl.uiObj.
Referenced by ListBoxControl.ListBoxControl(), and ListBoxControl.propertyChanged().
        {
                if ((uiObj.Max.doubleValue() - uiObj.Min.doubleValue()) <= 1)
                        list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                else
                        list.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        }
void updateTop () [inline, private]
References DoubleProperty.intValue(), ListBoxControl.list, UIControlObject.ListboxTop, and ListBoxControl.uiObj.
Referenced by ListBoxControl.ListBoxControl(), and ListBoxControl.propertyChanged().
        {
                list.ensureIndexIsVisible(uiObj.ListboxTop.intValue()-1);
                /*
                Point pt = list.indexToLocation(uiObj.ListboxTop.intValue()-1);
                if (pt != null)
                        getViewport().setViewPosition(pt);
                        */
        }
void updateValue () [inline, private]
References VectorProperty.getArray(), ListBoxControl.list, ListBoxControl.uiObj, and UIControlObject.Value.
Referenced by ListBoxControl.ListBoxControl(), and ListBoxControl.propertyChanged().
        {
                if (uiObj.Value.getArray().length > 0)
                {
                        double[] val = uiObj.Value.getArray();
                        int[] sel = new int[val.length];
                        for (int i=0; i<val.length; i++)
                                sel[i] = (int)val[i]-1;
                        list.setSelectedIndices(sel);
                }
                else
                        list.clearSelection();
        }
void valueChanged (ListSelectionEventevent) [inline]
References UIControlObject.controlActivated(), and ListBoxControl.uiObj.
        {
                if (!event.getValueIsAdjusting())
                {
                        uiObj.controlActivated(new UIControlEvent(this));
                }
        }
Member Data Documentation
JList list [package]
Referenced by ListBoxControl.ListBoxControl(), ListBoxControl.update(), ListBoxControl.updateColors(), ListBoxControl.updateItems(), ListBoxControl.updateSelectionMode(), ListBoxControl.updateTop(), and ListBoxControl.updateValue().
HandleEventSinkAdapter sink [package]
Referenced by ListBoxControl.dispose(), and ListBoxControl.ListBoxControl().
UIControlObject uiObj [package]
Referenced by ListBoxControl.ListBoxControl(), ListBoxControl.propertyChanged(), ListBoxControl.update(), ListBoxControl.updateColors(), ListBoxControl.updateItems(), ListBoxControl.updateSelectionMode(), ListBoxControl.updateTop(), ListBoxControl.updateValue(), and ListBoxControl.valueChanged().
Author
Generated automatically by Doxygen for Octave from the source code.