MarkerProperty
NAME
MarkerProperty -
SYNOPSIS
Inherits RadioProperty.
Classes
class Marker
Public Member Functions
MarkerProperty (PropertySet parent, String name)
MarkerProperty (PropertySet parent, String name, String marker)
Property cloneProperty ()
void drawMarker (Graphics g, int x, int y, double markerSize)
boolean isSet ()
void setMarker (String s)
Marker makeMarker (double markerSize, double lineWidth)
String getValue ()
boolean is (String val)
String toString ()
PropertySet getParent ()
String getName ()
boolean isReadOnly ()
void setReadOnly (boolean flag)
boolean isVisible ()
void setVisible (boolean flag)
Object get ()
void set (Object value) throws PropertyException
void set (Object value, boolean warn_on_exception)
void reset (Object value)
void lock ()
void unLock ()
boolean isSameValue (Object value)
void delete ()
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
Static Public Member Functions
static Property createProperty (PropertySet parent, String name, String type) throws PropertyException
static Property createProperty (PropertySet parent, String name, String type, Object arg) throws PropertyException
Protected Member Functions
MarkerProperty (MarkerProperty p)
Object convertValue (Object value) throws PropertyException
void initDefault ()
Object getInternal ()
void setInternal (Object value) throws PropertyException
boolean isEqual (Object value)
Protected Attributes
Object pvalue
Static Private Attributes
static boolean done_warn = false
Constructor & Destructor Documentation
MarkerProperty (MarkerPropertyp) [inline, protected]
Referenced by MarkerProperty.cloneProperty().
        {
                super(p);
        }
MarkerProperty (PropertySetparent, Stringname) [inline]
        {
                super(parent, name, new String[] {
                        'o', 's', 'x', '+', '*', 'd',
                        '^', '>', '<', 'v', '.', 'p', 'h', 'none'});
        }
MarkerProperty (PropertySetparent, Stringname, Stringmarker) [inline]
References Property.name, Property.parent, and Property.pvalue.
        {
                this(parent, name);
                this.pvalue = marker;
        }
Member Function Documentation
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and Property.eventSource.
Referenced by HandleObject.listen(), and HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
Property cloneProperty () [inline, virtual]
Reimplemented from RadioProperty.
References MarkerProperty.MarkerProperty().
        {
                return new MarkerProperty(this);
        }
Object convertValue (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented from Property.
References RadioProperty.valueSet.
        {
                if (value instanceof String && valueSet.containsKey(value))
                        return valueSet.get(value);
                else
                        throw new PropertyException('invalid property value - ' + value.toString());
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype) throws PropertyException 	 [inline, static, inherited]
References Property.name, and Property.parent.
Referenced by Property.createProperty().
        {
                if (type.equals('double'))
                        return new DoubleProperty(parent, name);
                else if (type.equals('string'))
                        return new StringProperty(parent, name);
                return null;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype, Objectarg) throws PropertyException 	 [inline, static, inherited]
References Property.createProperty(), Property.name, Property.parent, and Property.set().
        {
                if (type.equals('radio'))
                {
                        String[] values = ((String)arg).split('|');
                        return new RadioProperty(parent, name, values, '');
                }
                else
                {
                        Property p = createProperty(parent, name, type);
                        if (p != null)
                                p.set(arg);
                        return p;
                }
        }
void delete () [inline, inherited]
References HandleEventSourceHelper.delete(), and Property.eventSource.
        {
                eventSource.delete();
        }
void drawMarker (Graphicsg, intx, inty, doublemarkerSize) [inline]
References Utils.getScreenResolution(), RadioProperty.getValue(), plt.x, and plt.y.
Referenced by J2DRenderer.draw().
        {
                /* convert marker size from point size to pixel size */
                markerSize = (markerSize * Utils.getScreenResolution() / 72.0);
                int size = (int)markerSize, size2 = (int)(markerSize/2);
                int size3 = (int)(markerSize/3), size23 = (int)((markerSize*2)/3);
                switch (getValue().charAt(0))
                {
                case 'o':
                        g.drawOval(x-size2, y-size2, size-1, size-1);
                        break;
                case 's':
                        g.drawRect(x-size2, y-size2, size-1, size-1);
                        break;
                case 'x':
                        g.drawLine(x-size2, y-size2, x+size2, y+size2);
                        g.drawLine(x+size2, y-size2, x-size2, y+size2);
                        break;
                case '+':
                        g.drawLine(x-size2, y, x+size2, y);
                        g.drawLine(x, y-size2, x, y+size2);
                        break;
                case '*':
                        g.drawLine(x-size2, y, x+size2, y);
                        g.drawLine(x, y-size2, x, y+size2);
                        g.drawLine(x-size3, y-size3, x+size3, y+size3);
                        g.drawLine(x+size3, y-size3, x-size3, y+size3);
                        break;
                case 'd':
                        g.drawPolygon(
                                new int[] {x-size2, x, x+size2, x},
                                new int[] {y, y-size2, y, y+size2},
                                4);
                        break;
                case '^':
                        g.drawPolygon(
                                new int[] {x-size2, x, x+size2},
                                new int[] {y+size3, y-size23, y+size3},
                                3);
                        break;
                case '>':
                        g.drawPolygon(
                                new int[] {x-size3, x+size23, x-size3},
                                new int[] {y-size2, y, y+size2},
                                3);
                        break;
                case '<':
                        g.drawPolygon(
                                new int[] {x-size23, x+size3, x+size3},
                                new int[] {y, y-size2, y+size2},
                                3);
                        break;
                case 'v':
                        g.drawPolygon(
                                new int[] {x-size2, x, x+size2},
                                new int[] {y-size3, y+size23, y-size3},
                                3);
                        break;
                case '.':
                        g.fillOval(x-1, y-1, 3, 3);
                        break;
                }
        }
Object get () [inline, inherited]
Reimplemented in NotImplProperty.
References Property.getInternal().
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), AxesObject.doZoom(), HandleObject.get(), LegendObject.LegendObject(), LegendObject.makeItemFromLine(), LegendObject.propertyChanged(), UnwindHandleObject.swapValues(), and CheckBoxControl.update().
        {
                /* TODO: needed?
                if (!lockNotify)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((PropertyListener)it.next()).propertyGetting(this);
                }
                */
                return getInternal();
        }
Object getInternal () [inline, protected, inherited]
Reimplemented in ColorProperty, CallbackProperty, HandleObjectListProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.get().
        {
                return pvalue;
        }
String getName () [inline, inherited]
References Property.name.
Referenced by PropertySet.addProperty(), AxesObject.autoAxis(), NotImplProperty.get(), PropertySet.getNames(), NotImplProperty.set(), Property.set(), and PropertySet.show().
        {
                return name;
        }
PropertySet getParent () [inline, inherited]
References Property.parent.
Referenced by CallbackProperty.execute(), NotImplProperty.get(), Property.initDefault(), HandleObject.listen(), NotImplProperty.set(), and Property.set().
        {
                return parent;
        }
String getValue () [inline, inherited]
References Property.pvalue.
Referenced by ColorbarObject.buildColorbar(), ColorbarObject.doLocate(), LegendObject.doLocate(), J2DRenderer.draw(), GLRenderer.draw(), AxesObject.draw(), TextObject.drawAsImage(), MarkerProperty.drawMarker(), FigureObject.FigureObject(), BooleanProperty.getBoolean(), AxesObject.getBoundingBox(), SurfaceObject.getCData(), PatchObject.getCData(), Utils.getFontSize(), AxesObject.getOuterBoundingBox(), UIControlObject.getPosition(), UIPanelObject.getPosition(), LineStyleProperty.getStroke(), RadioProperty.is(), LegendObject.LegendObject(), MarkerProperty.makeMarker(), GLRenderer.makeMarkerList(), GL2PS.makeMarkerPSString(), UIPanelObject.makePanel(), GLRenderer.makeTextureFromCData(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), TextObject.propertyChanged(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), TextControl.stringToHTML(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), FigureObject.updateFramePosition(), TextObject.updateMinMax(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), TextObject.validate(), UIControlObject.validate(), and UIPanelObject.validate().
        {
                return (String)pvalue;
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.hasHandleEvent().
        {
                return eventSource.hasHandleEvent(name);
        }
void initDefault () [inline, protected, inherited]
References HandleObject.getDefaultProperty(), Property.getParent(), HandleObject.getType(), Property.name, Property.parent, and Property.pvalue.
Referenced by Property.Property().
        {
                HandleObject parent = (HandleObject)getParent();
                String defname = 'default' + parent.getType() + name;
                Property p = parent.getDefaultProperty(defname);
                if (p != null)
                        pvalue = p.pvalue;
        }
boolean is (Stringval) [inline, inherited]
References RadioProperty.getValue().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.autoScaleX(), AxesObject.autoScaleY(), AxesObject.autoScaleZ(), AxesObject.autoTickLabelX(), AxesObject.autoTickLabelY(), AxesObject.autoTickLabelZ(), GL2PS.GL2PSMarkerDrawer.begin(), AxesObject.computeAutoTickLabels(), AxesObject.computeMinorTicks(), UIControlObject.controlActivated(), AxesContainer.createCanvas(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), J2DRenderer.draw(), GLRenderer.draw(), AxesObject.draw(), TextObject.drawAsImage(), UIControlObject.get(), TextControl.getAlignment(), Utils.getAlphaData(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), Utils.getFont(), Utils.getFontSize(), HandleObjectListProperty.getVisibleObjects(), UIControlAdapter.init(), MarkerProperty.isSet(), UIPanelObject.makeBorder(), UIControlAdapter.mousePressed(), BaseLineObject.propertyChanged(), UIControlAdapter.propertyChanged(), TextObject.propertyChanged(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), UIControlObject.set(), EditControl.setAlignment(), Edit2Control.setAlignment(), TextObject.toPostScript(), AxesObject.updateActivePosition(), TextObject.updateContent(), TextObject.updateData(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), PatchObject.updateMinMax(), TextObject.updateMinMax(), AxesObject.updateScalers(), FigureObject.updateToolbars(), and AxesObject.updateXFormMatrices().
        {
                return getValue().equalsIgnoreCase(val);
        }
boolean isEqual (Objectvalue) [inline, protected, inherited]
Reimplemented in TextProperty.
References Property.pvalue.
Referenced by Property.isSameValue(), and Property.set().
        {
                /*Object v = getInternal();*/
                Object v = pvalue;
                return (value == null ? v == null : value.equals(v));
        }
boolean isReadOnly () [inline, inherited]
References Property.readOnly.
        {
                return readOnly;
        }
boolean isSameValue (Objectvalue) [inline, inherited]
References Property.convertValue(), and Property.isEqual().
Referenced by HandleObject.waitFor().
        {
                try
                {
                        value = convertValue(value);
                        return isEqual(value);
                }
                catch (PropertyException e)
                {
                        return false;
                }
        }
boolean isSet () [inline]
References RadioProperty.is().
Referenced by PatchObject.checkConsistency(), and GLRenderer.draw().
        {
                return !is('none');
        }
boolean isVisible () [inline, inherited]
References Property.visible.
Referenced by PropertySet.getNames(), and PropertySet.show().
        {
                return visible;
        }
void lock () [inline, inherited]
References Property.lockNotify.
        {
                lockNotify = true;
        }
Marker makeMarker (doublemarkerSize, doublelineWidth) [inline]
References plt.data, MarkerProperty.done_warn, Utils.getScreenResolution(), and RadioProperty.getValue().
Referenced by GLRenderer.draw().
        {
                /* convert marker size from point size to pixel size */
                markerSize = (markerSize * Utils.getScreenResolution() / 72.0);
                int size = (int)Math.round(markerSize), size2 = (int)Math.round(markerSize/2);
                int size3 = (int)Math.round(markerSize/3), size23 = (int)Math.round((markerSize*2)/3);
                BufferedImage img = new BufferedImage(size, size, BufferedImage.TYPE_BYTE_BINARY);
                Graphics2D g = img.createGraphics();
                int xhot = 0, yhot = 0;
                g.setColor(Color.black);
                g.fillRect(0, 0, size, size);
                g.setColor(Color.white);
                g.setStroke(new BasicStroke((float)lineWidth));
                switch (getValue().charAt(0))
                {
                case 'o':
                        xhot = yhot = size2;
                        g.drawArc(0, 0, size-1, size-1, 0, 360);
                        break;
                case 'h':
                case 'p':
                        if (!done_warn)
                        {
                                System.out.println('WARNING: pentagram/hexagram markers not supported, using square instead');
                                done_warn = true;
                        }
                case 's':
                        xhot = yhot = size2;
                        g.drawRect(0, 0, size-1, size-1);
                        break;
                case 'x':
                        xhot = yhot = size2;
                        g.drawLine(0, 0, size-1, size-1);
                        g.drawLine(size-1, 0, 0, size-1);
                        break;
                case '+':
                        xhot = yhot = size2;
                        g.drawLine(size2, 0, size2, size-1);
                        g.drawLine(0, size2, size-1, size2);
                        break;
                case '*':
                        xhot = yhot = size2;
                        g.drawLine(size2, 0, size2, size-1);
                        g.drawLine(0, size2, size-1, size2);
                        g.drawLine(size2-size3, size2-size3, size2+size3, size2+size3);
                        g.drawLine(size2+size3, size2-size3, size2-size3, size2+size3);
                        break;
                case 'd':
                        xhot = yhot = size2;
                        g.drawLine(size2, 0, 0, size2);
                        g.drawLine(0, size2, size2, size-1);
                        g.drawLine(size2, 0, size-1, size2);
                        g.drawLine(size-1, size2, size2, size-1);
                        break;
                case '^':
                        xhot = size2; yhot = size3;
                        g.drawLine(size2, 0, 0, size-1);
                        g.drawLine(size2, 0, size-1, size-1);
                        g.drawLine(0, size-1, size-1, size-1);
                        break;
                case '>':
                        xhot = size3; yhot = size2;
                        g.drawPolygon(
                                new int[] {0, size-1, 0},
                                new int[] {0, size2, size-1},
                                3);
                        break;
                case '<':
                        xhot = size23; yhot = size2;
                        g.drawPolygon(
                                new int[] {size-1, 0, size-1},
                                new int[] {0, size2, size-1},
                                3);
                        break;
                case 'v':
                        xhot = size2; yhot = size23;
                        g.drawLine(0, 0, size2, size-1);
                        g.drawLine(size-1, 0, size2, size-1);
                        g.drawLine(0, 0, size-1, 0);
                        break;
                case '.':
                        xhot = yhot = size2;
                        g.fillOval(size2-1, size2-1, 3, 3);
                        break;
                }
                g.dispose();
                com.sun.opengl.util.ImageUtil.flipImageVertically(img);
                byte[] data = ((DataBufferByte)img.getData().getDataBuffer()).getData();
                return new Marker(data, size, size, xhot, yhot);
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
        {
                eventSource.removeHandleEventSink(sink);
        }
void reset (Objectvalue) [inline, inherited]
References Property.lockNotify.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), ColorbarObject.buildColorbar(), LegendObject.buildLegend(), ColorbarObject.ColorbarObject(), HandleObject.delete(), LegendObject.doLayout(), AxesObject.draw(), AxesObject.getBaseLine(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), PatchObject.PatchObject(), FigureObject.print(), LineObject.propertyChanged(), BarseriesObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.reset(), GraphicObject.set(), SurfaceObject.SurfaceObject(), UnwindHandleObject.swapValues(), TextObject.TextObject(), CheckBoxControl.update(), EditControl.update(), PopupMenuControl.update(), Edit2Control.update(), ListBoxControl.update(), AxesObject.updateXFormMatrices(), LineObject.validate(), SurfaceObject.validate(), and PatchObject.validate().
        {
                boolean oldLockNotify = lockNotify;
                lockNotify = true;
                try { set(value); }
                catch (PropertyException e)
                {
                        System.err.println('WARNING: exception during property reset: ' + e);
                }
                lockNotify = oldLockNotify;
        }
void set (Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in BooleanProperty, and NotImplProperty.
References Property.convertValue(), Property.eventSource, HandleEventSourceHelper.fireEvent(), Property.getName(), Property.getParent(), Property.isEqual(), Property.lockNotify, Property.readOnly, Property.setFlag, and Property.setInternal().
Referenced by HandleObject.autoSet(), BarseriesObject.BarseriesObject(), ColorbarObject.buildColorbar(), Property.createProperty(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), BarseriesObject.propertyChanged(), LegendObject.propertyChanged(), PatchObject.propertyChanged(), AxesObject.propertyChanged(), HandleObject.set(), AxesObject.unZoom(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), SurfaceObject.updateColorMinMax(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
        {
                if (readOnly)
                        throw new PropertyException('read-only property - ' + getName());
                value = convertValue(value);
                if (isEqual(value))
                {
                        //System.out.println(getName() + ': identical value, not setting - ' + value.toString());
                        return;
                }
                if (setFlag)
                {
                        System.out.println('WARNING: ' + getName() + '.set (' + ((HandleObject)getParent()).getHandle() + '): recursive behavior detected, not setting');
                        Thread.dumpStack();
                        return;
                }
                setFlag = true;
                try
                {
                        /* TODO: needed?
                        if (!lockNotify)
                        {
                                Iterator it = listenerList.iterator();
                                while (it.hasNext())
                                        ((PropertyListener)it.next()).propertySetting(this, value);
                        }
                        */
                        setInternal(value);
                        if (!lockNotify)
                        {
                                eventSource.fireEvent('PropertyChanged');
                        }
                        setFlag = false;
                }
                catch (Exception e)
                {
                        setFlag = false;
                        if (e instanceof PropertyException)
                                throw (PropertyException)e;
                        else
                                throw new PropertyException(e);
                }
        }
void set (Objectvalue, booleanwarn_on_exception) [inline, inherited]
References Property.getName().
        {
                try { set(value); }
                catch (PropertyException e)
                {
                        if (warn_on_exception)
                        {
                                System.out.println('WARNING: ' + getName() + '.set: exception occured');
                                e.printStackTrace();
                        }
                }
        }
void setInternal (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented in ArrayProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.set().
        {
                pvalue = value;
        }
void setMarker (Strings) [inline]
        {
                try { set(s); }
                catch (PropertyException e) { }
        }
void setReadOnly (booleanflag) [inline, inherited]
References Property.readOnly.
        {
                readOnly = flag;
        }
void setVisible (booleanflag) [inline, inherited]
References Property.visible.
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), FigureObject.FigureObject(), GraphicObject.GraphicObject(), and PatchObject.PatchObject().
        {
                visible = flag;
        }
String toString () [inline, inherited]
References Property.pvalue.
        {
                return (String)pvalue;
        }
void unLock () [inline, inherited]
References Property.lockNotify.
Referenced by HandleObject.addProperty(), and PropertySet.validate().
        {
                lockNotify = false;
        }
Member Data Documentation
boolean done_warn = false [static, private]
Referenced by MarkerProperty.makeMarker().
Object pvalue [protected, inherited]
Referenced by HandleObjectListProperty.addElement(), ArrayProperty.ArrayProperty(), BooleanProperty.BooleanProperty(), CallbackProperty.CallbackProperty(), ColorProperty.ColorProperty(), HandleObjectListProperty.contains(), DoubleProperty.DoubleProperty(), DoubleRadioProperty.DoubleRadioProperty(), DoubleProperty.doubleValue(), DoubleRadioProperty.doubleValue(), HandleObjectListProperty.elementAt(), DoubleProperty.floatValue(), StringArrayProperty.getArray(), CallbackProperty.getCallback(), ArrayProperty.getClassName(), ColorProperty.getColor(), ArrayProperty.getDim(), TextProperty.getInternal(), Property.getInternal(), ColorProperty.getInternal(), ArrayProperty.getMatrix(), ArrayProperty.getNDims(), ObjectProperty.getObject(), TextProperty.getText(), RadioProperty.getValue(), VectorProperty.getVector(), HandleObjectListProperty.getVisibleObjects(), HandleObjectListProperty.HandleObjectListProperty(), Property.initDefault(), DoubleProperty.intValue(), DoubleRadioProperty.is(), ColorProperty.is(), DoubleRadioProperty.isDouble(), ArrayProperty.isEmpty(), TextProperty.isEqual(), Property.isEqual(), ColorProperty.isSet(), HandleObjectListProperty.iterator(), LineStyleProperty.LineStyleProperty(), MarkerProperty.MarkerProperty(), ObjectProperty.ObjectProperty(), Property.Property(), RadioProperty.RadioProperty(), HandleObjectListProperty.removeAllElements(), HandleObjectListProperty.removeElement(), TextProperty.setInternal(), Property.setInternal(), HandleObjectListProperty.size(), StringArrayProperty.StringArrayProperty(), StringProperty.StringProperty(), TextProperty.TextProperty(), ObjectProperty.toString(), StringProperty.toString(), RadioProperty.toString(), DoubleRadioProperty.toString(), VectorProperty.toString(), ArrayProperty.toString(), ColorProperty.toString(), and VectorProperty.VectorProperty().
Author
Generated automatically by Doxygen for Octave from the source code.