OctaveSink
NAME
OctaveSink -
SYNOPSIS
Public Member Functions
OctaveSink (OctaveReference ref, HandleObject h, String[] pnames, HandleObject hp)
void doInvoke (HandleEvent evt)
void dispose ()
Private Attributes
OctaveReference ref
HandleEventSinkAdapter sink
HandleObject parent
Constructor & Destructor Documentation
OctaveSink (OctaveReferenceref, HandleObjecth, String[]pnames, HandleObjecthp) [inline]
References OctaveSink.dispose(), OctaveSink.doInvoke(), HandleEvent.getHandleObject(), HandleEvent.getName(), PropertySet.getProperty(), HandleObject.hasHandleEvent(), HandleEventSinkAdapter.listen(), OctaveSink.parent, OctaveSink.ref, OctaveSink.sink, StringProperty.toString(), and HandleObject.Type.
        {
                this.ref = ref;
                this.sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        {
                                if (OctaveSink.this.parent == null || !evt.getName().equals('ObjectDeleted') ||
                                                evt.getHandleObject() != OctaveSink.this.parent)
                                        OctaveSink.this.doInvoke(evt);
                        }
                        public void sourceDeleted(Object source)
                        {
                                super.sourceDeleted(source);
                                if (source == OctaveSink.this.parent)
                                        OctaveSink.this.dispose();
                        }
                };
                this.parent = (hp != null && hp != h ? hp : null);
                for (int i=0; i<pnames.length; i++)
                {
                        Property p = h.getProperty(pnames[i]);
                        if (p != null)
                                this.sink.listen(p);
                        else if (h.hasHandleEvent(pnames[i]))
                                this.sink.listen(h, pnames[i]);
                        else
                                System.out.println('WARNING: `' + pnames[i] + '' is not a valid property name of ' + h.Type.toString());
                }
                if (this.parent != null)
                        this.sink.listen(this.parent, 'ObjectDeleted');
        }
Member Function Documentation
void dispose () [inline]
References HandleEventSinkAdapter.dispose(), and OctaveSink.sink.
Referenced by OctaveSink.OctaveSink().
        {
                sink.dispose();
        }
void doInvoke (HandleEventevt) [inline]
References HandleObject.getHandle(), HandleEvent.getHandleObject(), and OctaveSink.ref.
Referenced by OctaveSink.OctaveSink().
        {
                HandleObject h = evt.getHandleObject();
                if (h != null)
                        ref.invokeAndWait(new Object[] {new Double(h.getHandle()), null});
                else
                        ref.invokeAndWait(new Object[] {null, evt});
        }
Member Data Documentation
HandleObject parent [private]
Referenced by OctaveSink.OctaveSink().
OctaveReference ref [private]
Referenced by OctaveSink.doInvoke(), and OctaveSink.OctaveSink().
HandleEventSinkAdapter sink [private]
Referenced by OctaveSink.dispose(), and OctaveSink.OctaveSink().
Author
Generated automatically by Doxygen for Octave from the source code.