NotImplProperty
NAME
NotImplProperty -
SYNOPSIS
Inherits ObjectProperty.
Public Member Functions
NotImplProperty (PropertySet parent, String name)
NotImplProperty (PropertySet parent, String name, Object value)
Property cloneProperty ()
Object get ()
void set (Object value) throws PropertyException
String toString ()
Object getObject ()
PropertySet getParent ()
String getName ()
boolean isReadOnly ()
void setReadOnly (boolean flag)
boolean isVisible ()
void setVisible (boolean flag)
void set (Object value, boolean warn_on_exception)
void reset (Object value)
void lock ()
void unLock ()
boolean isSameValue (Object value)
void delete ()
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
Static Public Member Functions
static Property createProperty (PropertySet parent, String name, String type) throws PropertyException
static Property createProperty (PropertySet parent, String name, String type, Object arg) throws PropertyException
Protected Member Functions
NotImplProperty (NotImplProperty p)
void initDefault ()
Object getInternal ()
void setInternal (Object value) throws PropertyException
boolean isEqual (Object value)
Object convertValue (Object value) throws PropertyException
Protected Attributes
Object pvalue
Constructor & Destructor Documentation
NotImplProperty (NotImplPropertyp) [inline, protected]
Referenced by NotImplProperty.cloneProperty().
        {
                super(p);
        }
NotImplProperty (PropertySetparent, Stringname) [inline]
        {
                super(parent, name);
        }
NotImplProperty (PropertySetparent, Stringname, Objectvalue) [inline]
        {
                super(parent, name, value);
        }
Member Function Documentation
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and Property.eventSource.
Referenced by HandleObject.listen(), and HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
Property cloneProperty () [inline, virtual]
Reimplemented from ObjectProperty.
References NotImplProperty.NotImplProperty().
        {
                return new NotImplProperty(this);
        }
Object convertValue (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented in ColorProperty, RadioProperty, VectorProperty, ArrayProperty, DoubleRadioProperty, HandleObjectListProperty, StringProperty, DoubleProperty, StringArrayProperty, CallbackProperty, and TextProperty.
Referenced by Property.isSameValue(), and Property.set().
        {
                return value;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype) throws PropertyException 	 [inline, static, inherited]
References Property.name, and Property.parent.
Referenced by Property.createProperty().
        {
                if (type.equals('double'))
                        return new DoubleProperty(parent, name);
                else if (type.equals('string'))
                        return new StringProperty(parent, name);
                return null;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype, Objectarg) throws PropertyException 	 [inline, static, inherited]
References Property.createProperty(), Property.name, Property.parent, and Property.set().
        {
                if (type.equals('radio'))
                {
                        String[] values = ((String)arg).split('|');
                        return new RadioProperty(parent, name, values, '');
                }
                else
                {
                        Property p = createProperty(parent, name, type);
                        if (p != null)
                                p.set(arg);
                        return p;
                }
        }
void delete () [inline, inherited]
References HandleEventSourceHelper.delete(), and Property.eventSource.
        {
                eventSource.delete();
        }
Object get () [inline]
Reimplemented from Property.
References Property.getName(), and Property.getParent().
        {
                System.out.println('WARNING: get: property `' + getName() + '' in object `' +
                                ((HandleObject)getParent()).Type.toString() + ''not implemented, returning dummy value');
                return super.get();
        }
Object getInternal () [inline, protected, inherited]
Reimplemented in ColorProperty, CallbackProperty, HandleObjectListProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.get().
        {
                return pvalue;
        }
String getName () [inline, inherited]
References Property.name.
Referenced by PropertySet.addProperty(), AxesObject.autoAxis(), NotImplProperty.get(), PropertySet.getNames(), NotImplProperty.set(), Property.set(), and PropertySet.show().
        {
                return name;
        }
Object getObject () [inline, inherited]
References Property.pvalue.
        {
                return pvalue;
        }
PropertySet getParent () [inline, inherited]
References Property.parent.
Referenced by CallbackProperty.execute(), NotImplProperty.get(), Property.initDefault(), HandleObject.listen(), NotImplProperty.set(), and Property.set().
        {
                return parent;
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.hasHandleEvent().
        {
                return eventSource.hasHandleEvent(name);
        }
void initDefault () [inline, protected, inherited]
References HandleObject.getDefaultProperty(), Property.getParent(), HandleObject.getType(), Property.name, Property.parent, and Property.pvalue.
Referenced by Property.Property().
        {
                HandleObject parent = (HandleObject)getParent();
                String defname = 'default' + parent.getType() + name;
                Property p = parent.getDefaultProperty(defname);
                if (p != null)
                        pvalue = p.pvalue;
        }
boolean isEqual (Objectvalue) [inline, protected, inherited]
Reimplemented in TextProperty.
References Property.pvalue.
Referenced by Property.isSameValue(), and Property.set().
        {
                /*Object v = getInternal();*/
                Object v = pvalue;
                return (value == null ? v == null : value.equals(v));
        }
boolean isReadOnly () [inline, inherited]
References Property.readOnly.
        {
                return readOnly;
        }
boolean isSameValue (Objectvalue) [inline, inherited]
References Property.convertValue(), and Property.isEqual().
Referenced by HandleObject.waitFor().
        {
                try
                {
                        value = convertValue(value);
                        return isEqual(value);
                }
                catch (PropertyException e)
                {
                        return false;
                }
        }
boolean isVisible () [inline, inherited]
References Property.visible.
Referenced by PropertySet.getNames(), and PropertySet.show().
        {
                return visible;
        }
void lock () [inline, inherited]
References Property.lockNotify.
        {
                lockNotify = true;
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
        {
                eventSource.removeHandleEventSink(sink);
        }
void reset (Objectvalue) [inline, inherited]
References Property.lockNotify.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), ColorbarObject.buildColorbar(), LegendObject.buildLegend(), ColorbarObject.ColorbarObject(), HandleObject.delete(), LegendObject.doLayout(), AxesObject.draw(), AxesObject.getBaseLine(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), PatchObject.PatchObject(), FigureObject.print(), LineObject.propertyChanged(), BarseriesObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.reset(), GraphicObject.set(), SurfaceObject.SurfaceObject(), UnwindHandleObject.swapValues(), TextObject.TextObject(), CheckBoxControl.update(), EditControl.update(), PopupMenuControl.update(), Edit2Control.update(), ListBoxControl.update(), AxesObject.updateXFormMatrices(), LineObject.validate(), SurfaceObject.validate(), and PatchObject.validate().
        {
                boolean oldLockNotify = lockNotify;
                lockNotify = true;
                try { set(value); }
                catch (PropertyException e)
                {
                        System.err.println('WARNING: exception during property reset: ' + e);
                }
                lockNotify = oldLockNotify;
        }
void set (Objectvalue) throws PropertyException 	 [inline]
Reimplemented from Property.
References Property.getName(), and Property.getParent().
        {
                System.out.println('WARNING: set: property `' + getName() + '' in object `' +
                                ((HandleObject)getParent()).Type.toString() + ''not implemented, setting value has no effect');
                super.set(value);
        }
void set (Objectvalue, booleanwarn_on_exception) [inline, inherited]
References Property.getName().
        {
                try { set(value); }
                catch (PropertyException e)
                {
                        if (warn_on_exception)
                        {
                                System.out.println('WARNING: ' + getName() + '.set: exception occured');
                                e.printStackTrace();
                        }
                }
        }
void setInternal (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented in ArrayProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.set().
        {
                pvalue = value;
        }
void setReadOnly (booleanflag) [inline, inherited]
References Property.readOnly.
        {
                readOnly = flag;
        }
void setVisible (booleanflag) [inline, inherited]
References Property.visible.
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), FigureObject.FigureObject(), GraphicObject.GraphicObject(), and PatchObject.PatchObject().
        {
                visible = flag;
        }
String toString () [inline, inherited]
References Property.pvalue.
        {
                if (pvalue != null)
                        return pvalue.toString();
                else
                        return '';
        }
void unLock () [inline, inherited]
References Property.lockNotify.
Referenced by HandleObject.addProperty(), and PropertySet.validate().
        {
                lockNotify = false;
        }
Member Data Documentation
Object pvalue [protected, inherited]
Referenced by HandleObjectListProperty.addElement(), ArrayProperty.ArrayProperty(), BooleanProperty.BooleanProperty(), CallbackProperty.CallbackProperty(), ColorProperty.ColorProperty(), HandleObjectListProperty.contains(), DoubleProperty.DoubleProperty(), DoubleRadioProperty.DoubleRadioProperty(), DoubleProperty.doubleValue(), DoubleRadioProperty.doubleValue(), HandleObjectListProperty.elementAt(), DoubleProperty.floatValue(), StringArrayProperty.getArray(), CallbackProperty.getCallback(), ArrayProperty.getClassName(), ColorProperty.getColor(), ArrayProperty.getDim(), TextProperty.getInternal(), Property.getInternal(), ColorProperty.getInternal(), ArrayProperty.getMatrix(), ArrayProperty.getNDims(), ObjectProperty.getObject(), TextProperty.getText(), RadioProperty.getValue(), VectorProperty.getVector(), HandleObjectListProperty.getVisibleObjects(), HandleObjectListProperty.HandleObjectListProperty(), Property.initDefault(), DoubleProperty.intValue(), DoubleRadioProperty.is(), ColorProperty.is(), DoubleRadioProperty.isDouble(), ArrayProperty.isEmpty(), TextProperty.isEqual(), Property.isEqual(), ColorProperty.isSet(), HandleObjectListProperty.iterator(), LineStyleProperty.LineStyleProperty(), MarkerProperty.MarkerProperty(), ObjectProperty.ObjectProperty(), Property.Property(), RadioProperty.RadioProperty(), HandleObjectListProperty.removeAllElements(), HandleObjectListProperty.removeElement(), TextProperty.setInternal(), Property.setInternal(), HandleObjectListProperty.size(), StringArrayProperty.StringArrayProperty(), StringProperty.StringProperty(), TextProperty.TextProperty(), StringProperty.toString(), ObjectProperty.toString(), RadioProperty.toString(), DoubleRadioProperty.toString(), VectorProperty.toString(), ArrayProperty.toString(), ColorProperty.toString(), and VectorProperty.VectorProperty().
Author
Generated automatically by Doxygen for Octave from the source code.