UIControlAdapter
NAME
UIControlAdapter -
SYNOPSIS
Inherits Panel, Positionable, and MouseListener.
Public Member Functions
UIControlAdapter (UIControlObject obj) throws IllegalArgumentException
void update ()
void dispose ()
Component getComponent ()
void propertyChanged (Property p) throws PropertyException
double[] getPosition ()
void mouseClicked (MouseEvent e)
void mouseEntered (MouseEvent e)
void mouseExited (MouseEvent e)
void mousePressed (MouseEvent e)
void mouseReleased (MouseEvent e)
Private Member Functions
void init ()
Private Attributes
UIControl ctrl
UIControlObject uiObj
HandleEventSinkAdapter sink
Constructor & Destructor Documentation
UIControlAdapter (UIControlObjectobj) throws IllegalArgumentException 	 [inline]
References UIControlAdapter.ctrl, HandleEvent.getProperty(), UIControlAdapter.init(), HandleEventSinkAdapter.listen(), UIControlAdapter.propertyChanged(), UIControlAdapter.sink, and UIControlAdapter.uiObj.
        {
                super(new BorderLayout());
                String style = obj.Style.toString();
                if (style.equalsIgnoreCase('pushbutton'))
                        this.ctrl = new PushButtonControl(obj);
                else if (style.equalsIgnoreCase('edit'))
                {
                        if ((obj.Max.doubleValue()-obj.Min.doubleValue()) <= 1.0)
                                this.ctrl = new EditControl(obj);
                        else
                                this.ctrl = new Edit2Control(obj);
                }
                else if (style.equalsIgnoreCase('popupmenu'))
                        this.ctrl = new PopupMenuControl(obj);
                else if (style.equalsIgnoreCase('text'))
                        this.ctrl = new TextControl(obj);
                else if (style.equalsIgnoreCase('listbox'))
                        this.ctrl = new ListBoxControl(obj);
                else if (style.equalsIgnoreCase('checkbox'))
                        this.ctrl = new CheckBoxControl(obj);
                else
                        throw new IllegalArgumentException('unsupported UI style `' + style + ''');
                this.uiObj = obj;
                init();
                add((JComponent)ctrl, BorderLayout.CENTER);
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.Position);
                sink.listen(obj.BackgroundColor);
                sink.listen(obj.ForegroundColor);
                sink.listen(obj.FontAngle);
                sink.listen(obj.FontName);
                sink.listen(obj.FontSize);
                sink.listen(obj.FontWeight);
                sink.listen(obj.TooltipString);
                sink.listen(obj.Enable);
        }
Member Function Documentation
void dispose () [inline]
References UIControlAdapter.ctrl, UIControl.dispose(), HandleEventSinkAdapter.dispose(), and UIControlAdapter.sink.
Referenced by UIControlObject.deleteComponent().
        {
                if (ctrl != null)
                        ctrl.dispose();
                if (getParent() != null)
                        getParent().remove(this);
                sink.dispose();
        }
Component getComponent () [inline]
References UIControlAdapter.ctrl, and UIControl.getComponent().
Referenced by UIControlObject.getComponent().
        {
                return ctrl.getComponent();
        }
double [] getPosition () [inline]
Implements Positionable.
References UIControlObject.getPosition(), and UIControlAdapter.uiObj.
        {
                return uiObj.getPosition();
        }
void init () [inline, private]
References UIControlObject.BackgroundColor, UIControlAdapter.ctrl, UIControlObject.Enable, UIControlObject.FontAngle, UIControlObject.FontName, UIControlObject.FontSize, UIControlObject.FontUnits, UIControlObject.FontWeight, UIControlObject.ForegroundColor, ColorProperty.getColor(), UIControl.getComponent(), Utils.getFont(), UIControlObject.getPosition(), RadioProperty.is(), UIControlObject.TooltipString, StringProperty.toString(), and UIControlAdapter.uiObj.
Referenced by UIControlAdapter.UIControlAdapter().
        {
                JComponent comp1 = ctrl.getComponent();
                comp1.setBackground(uiObj.BackgroundColor.getColor());
                comp1.setForeground(uiObj.ForegroundColor.getColor());
                double[] pos = uiObj.getPosition();
                setBounds((int)pos[0], (int)pos[1], (int)pos[2], (int)pos[3]);
                if (uiObj.TooltipString.toString().length() > 0)
                        comp1.setToolTipText(uiObj.TooltipString.toString());
                comp1.setFont(Utils.getFont(uiObj.FontName, uiObj.FontSize, uiObj.FontUnits,
                                uiObj.FontAngle, uiObj.FontWeight, getHeight()));
                comp1.setEnabled(!uiObj.Enable.is('off'));
                comp1.addMouseListener(this);
        }
void mouseClicked (MouseEvente) [inline]
{}
void mouseEntered (MouseEvente) [inline]
{}
void mouseExited (MouseEvente) [inline]
{}
void mousePressed (MouseEvente) [inline]
References HandleObject.doButtonDownFcn(), UIControlObject.Enable, RadioProperty.is(), and UIControlAdapter.uiObj.
        {
                boolean doCB = false;
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                        case MouseEvent.BUTTON3:
                                doCB = true;
                                break;
                        case MouseEvent.BUTTON1:
                                doCB = !uiObj.Enable.is('on');
                                break;
                }
                if (doCB)
                        uiObj.doButtonDownFcn(e);
        }
void mouseReleased (MouseEvente) [inline]
{}
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References UIControlObject.BackgroundColor, UIControlAdapter.ctrl, UIControlObject.Enable, UIControlObject.FontAngle, UIControlObject.FontName, UIControlObject.FontSize, UIControlObject.FontUnits, UIControlObject.FontWeight, UIControlObject.ForegroundColor, ColorProperty.getColor(), UIControl.getComponent(), Utils.getFont(), RadioProperty.is(), UIControlObject.Position, UIControlObject.TooltipString, StringProperty.toString(), and UIControlAdapter.uiObj.
Referenced by UIControlAdapter.UIControlAdapter().
        {
                if (ctrl != null)
                {
                        JComponent comp1 = ctrl.getComponent();
                        if (p == uiObj.BackgroundColor)
                                comp1.setBackground(uiObj.BackgroundColor.getColor());
                        else if (p == uiObj.ForegroundColor)
                                comp1.setForeground(uiObj.ForegroundColor.getColor());
                        else if (p == uiObj.Position)
                        {
                                getParent().doLayout();
                                getParent().validate();
                                if (uiObj.FontUnits.is('normalized'))
                                        comp1.setFont(Utils.getFont(uiObj.FontName, uiObj.FontSize, uiObj.FontUnits,
                                                uiObj.FontAngle, uiObj.FontWeight, getHeight()));
                        }
                        else if (p == uiObj.FontAngle || p == uiObj.FontSize || p == uiObj.FontWeight || p == uiObj.FontName)
                                comp1.setFont(Utils.getFont(uiObj.FontName, uiObj.FontSize, uiObj.FontUnits,
                                        uiObj.FontAngle, uiObj.FontWeight, getHeight()));
                        else if (p == uiObj.TooltipString)
                        {
                                if (uiObj.TooltipString.toString().length() > 0)
                                        comp1.setToolTipText(uiObj.TooltipString.toString());
                                else
                                        comp1.setToolTipText(null);
                        }
                        else if (p == uiObj.Enable)
                                comp1.setEnabled(!uiObj.Enable.is('off'));
                }
        }
void update () [inline]
References UIControlAdapter.ctrl, and UIControl.update().
Referenced by UIControlObject.get(), and UIControlObject.set().
{ if (ctrl != null) ctrl.update(); }
Member Data Documentation
UIControl ctrl [private]
Referenced by UIControlAdapter.dispose(), UIControlAdapter.getComponent(), UIControlAdapter.init(), UIControlAdapter.propertyChanged(), UIControlAdapter.UIControlAdapter(), and UIControlAdapter.update().
HandleEventSinkAdapter sink [private]
Referenced by UIControlAdapter.dispose(), and UIControlAdapter.UIControlAdapter().
UIControlObject uiObj [private]
Referenced by UIControlAdapter.getPosition(), UIControlAdapter.init(), UIControlAdapter.mousePressed(), UIControlAdapter.propertyChanged(), and UIControlAdapter.UIControlAdapter().
Author
Generated automatically by Doxygen for Octave from the source code.