.TH "SimpleTextEngine.SuperscriptElement" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleTextEngine.SuperscriptElement \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSimpleTextEngine\&.LineElement\fP\&.
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBSuperscriptElement\fP (String txt)"
.br
.ti -1c
.RI "Font \fBgetSuperscriptFont\fP (Font f)"
.br
.ti -1c
.RI "Rectangle \fBlayout\fP (\fBLayouter\fP l)"
.br
.ti -1c
.RI "void \fBrender\fP (Graphics2D g)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBTextRenderer\fP r)"
.br
.ti -1c
.RI "Rectangle \fBlayout\fP (\fBRenderCanvas\fP comp, Font font)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBElement\fP e)"
.br
.ti -1c
.RI "Iterator \fBiterator\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fBtext\fP"
.br
.ti -1c
.RI "Rectangle \fBrect\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSuperscriptElement\fP (Stringtxt)\fC [inline, package]\fP"
.PP
.nf
                {
                        super(txt);
                }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void \fBadd\fP (\fBElement\fPe)\fC [inline, package, inherited]\fP"
.PP
References SimpleTextEngine\&.LineElement\&.elements\&.
.PP
.nf
                {
                        elements\&.add(e);
                }
.fi
.SS "Font \fBgetSuperscriptFont\fP (Fontf)\fC [inline, package]\fP"
.PP
Referenced by SimpleTextEngine\&.SuperscriptElement\&.layout(), and SimpleTextEngine\&.SuperscriptElement\&.render()\&.
.PP
.nf
                {
                        return new Font(f\&.getFamily(), f\&.getStyle(), f\&.getSize()-2);
                }
.fi
.SS "Iterator \fBiterator\fP ()\fC [inline, package, inherited]\fP"
.PP
References SimpleTextEngine\&.LineElement\&.elements\&.
.PP
Referenced by SimpleTextEngine\&.PSTextRenderer\&.render()\&.
.PP
.nf
                {
                        return elements\&.iterator();
                }
.fi
.SS "Rectangle \fBlayout\fP (\fBRenderCanvas\fPcomp, Fontfont)\fC [inline, package, inherited]\fP"
.PP
Referenced by SimpleTextEngine\&.LineElement\&.layout(), and SimpleTextEngine\&.ScriptElement\&.layout()\&.
.PP
.nf
                {
                        return layout(new Layouter(comp, font));
                }
.fi
.SS "Rectangle \fBlayout\fP (\fBLayouter\fPl)\fC [inline, package]\fP"
.PP
Reimplemented from \fBSimpleTextEngine\&.LineElement\fP\&.
.PP
References SimpleTextEngine\&.Layouter\&.font, SimpleTextEngine\&.Layouter\&.getFontMetrics(), SimpleTextEngine\&.SuperscriptElement\&.getSuperscriptFont(), and SimpleTextEngine\&.Element\&.rect\&.
.PP
.nf
                {
                        Font currentFont = l\&.font;

                        l\&.font = getSuperscriptFont(currentFont);
                        super\&.layout(l);
                        FontMetrics fm = l\&.getFontMetrics();
                        rect\&.y += fm\&.getMaxAscent()/2;
                        l\&.font = currentFont;

                        return rect;
                }
.fi
.SS "void \fBrender\fP (Graphics2Dg)\fC [inline, package]\fP"
.PP
Reimplemented from \fBSimpleTextEngine\&.LineElement\fP\&.
.PP
References SimpleTextEngine\&.SuperscriptElement\&.getSuperscriptFont(), and SimpleTextEngine\&.Element\&.rect\&.
.PP
.nf
                {
                        Font currentFont = g\&.getFont();
                        FontMetrics fm = g\&.getFontMetrics();
                        int ascent = fm\&.getMaxAscent();
                        Font subscriptFont = getSuperscriptFont(currentFont);

                        g\&.setFont(subscriptFont);
                        g\&.translate(0, -(rect\&.height+rect\&.y)-ascent/2);
                        super\&.render(g);
                        g\&.translate(0, (rect\&.height+rect\&.y)+ascent/2);
                        g\&.setFont(currentFont);
                }
.fi
.SS "void \fBrender\fP (\fBTextRenderer\fPr)\fC [inline, package]\fP"
.PP
Reimplemented from \fBSimpleTextEngine\&.LineElement\fP\&.
.PP
References SimpleTextEngine\&.TextRenderer\&.render()\&.
.PP
.nf
{ r\&.render(this); }
.fi
.SH "Member Data Documentation"
.PP 
.SS "Rectangle \fBrect\fP\fC [package, inherited]\fP"
.PP
Referenced by SimpleTextEngine\&.Element\&.Element(), SimpleTextEngine\&.Element\&.layout(), SimpleTextEngine\&.LineElement\&.layout(), SimpleTextEngine\&.SubscriptElement\&.layout(), SimpleTextEngine\&.SuperscriptElement\&.layout(), SimpleTextEngine\&.ScriptElement\&.layout(), SimpleTextEngine\&.TeXFontCommand\&.layout(), SimpleTextEngine\&.TeXElement\&.layout(), SimpleTextEngine\&.Content\&.layout(), SimpleTextEngine\&.PSTextRenderer\&.render(), SimpleTextEngine\&.LineElement\&.render(), SimpleTextEngine\&.SuperscriptElement\&.render(), and SimpleTextEngine\&.Content\&.render()\&.
.SS "String \fBtext\fP\fC [package, inherited]\fP"
.PP
Referenced by SimpleTextEngine\&.Element\&.Element(), SimpleTextEngine\&.Element\&.layout(), SimpleTextEngine\&.PSTextRenderer\&.render(), and SimpleTextEngine\&.Element\&.render()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
