SurfaceObject
NAME
SurfaceObject -
SYNOPSIS
Inherits GraphicObject.
Public Member Functions
SurfaceObject (HandleObject parent, Matrix xdata, Matrix ydata, Matrix zdata)
void validate ()
void draw (Renderer r)
void propertyChanged (Property p) throws PropertyException
AxesObject getAxes ()
void set (Property p, Object value) throws PropertyException
void set (String name, Object value) throws PropertyException
boolean isLegendable ()
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
void delete ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
java.awt.Component getComponent ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
Object get (Property p)
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Protected Member Functions
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
int glID
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Functions
Matrix computeNormals ()
double[][][] getCData ()
double[][] getAlphaData ()
Package Attributes
ArrayProperty XData
ArrayProperty YData
ArrayProperty ZData
ArrayProperty CData
RadioProperty CDataMapping
ColorProperty EdgeColor
ColorProperty FaceColor
DoubleProperty AmbientStrength
DoubleProperty DiffuseStrength
DoubleProperty SpecularStrength
DoubleProperty SpecularExponent
RadioProperty EdgeLighting
RadioProperty FaceLighting
DoubleRadioProperty FaceAlpha
DoubleRadioProperty EdgeAlpha
ArrayProperty VertexNormals
ArrayProperty AlphaData
RadioProperty AlphaDataMapping
MarkerProperty Marker
ColorProperty MarkerEdgeColor
ColorProperty MarkerFaceColor
DoubleProperty MarkerSize
LineStyleProperty LineStyle
DoubleProperty LineWidth
VectorProperty XLim
VectorProperty YLim
VectorProperty ZLim
VectorProperty CLim
VectorProperty ALim
BooleanProperty XLimInclude
BooleanProperty YLimInclude
BooleanProperty ZLimInclude
BooleanProperty CLimInclude
BooleanProperty ALimInclude
BooleanProperty LegendInclude
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
void updateMinMax ()
void updateColorMinMax ()
Private Attributes
boolean callListValid
Constructor & Destructor Documentation
SurfaceObject (HandleObjectparent, Matrixxdata, Matrixydata, Matrixzdata) [inline]
References GraphicObject.ALimInclude, SurfaceObject.AlphaData, SurfaceObject.AlphaDataMapping, SurfaceObject.AmbientStrength, SurfaceObject.callListValid, SurfaceObject.CData, SurfaceObject.CDataMapping, GraphicObject.CLimInclude, SurfaceObject.DiffuseStrength, SurfaceObject.EdgeAlpha, SurfaceObject.EdgeColor, SurfaceObject.EdgeLighting, SurfaceObject.FaceAlpha, SurfaceObject.FaceColor, SurfaceObject.FaceLighting, GraphicObject.getAxes(), SurfaceObject.LineStyle, SurfaceObject.LineWidth, HandleObject.listen(), SurfaceObject.Marker, SurfaceObject.MarkerEdgeColor, SurfaceObject.MarkerFaceColor, SurfaceObject.MarkerSize, Property.reset(), SurfaceObject.SpecularExponent, SurfaceObject.SpecularStrength, SurfaceObject.VertexNormals, SurfaceObject.XData, SurfaceObject.YData, SurfaceObject.ZData, and GraphicObject.ZLimInclude.
        {
                super(parent, 'surface');
                callListValid = false;
                XData = new ArrayProperty(this, 'XData', new String[] {'double'}, 2, xdata);
                YData = new ArrayProperty(this, 'YData', new String[] {'double'}, 2, ydata);
                ZData = new ArrayProperty(this, 'ZData', new String[] {'double'}, 2, zdata);
                CData = new ArrayProperty(this, 'CData', new String[] {'double', 'byte'}, -1, zdata);
                CDataMapping = new RadioProperty(this, 'CDataMapping', new String[] {'direct', 'scaled'}, 'scaled');
                EdgeColor = new ColorProperty(this, 'EdgeColor', new String[] {'none', 'flat', 'interp'}, Color.black);
                FaceColor = new ColorProperty(this, 'FaceColor', new String[] {'none', 'flat', 'interp', 'texturemap'}, 'flat');
                AmbientStrength = new DoubleProperty(this, 'AmbientStrength', 0.3);
                DiffuseStrength = new DoubleProperty(this, 'DiffuseStrength', 0.6);
                SpecularStrength = new DoubleProperty(this, 'SpecularStrength', 0.9);
                SpecularExponent = new DoubleProperty(this, 'SpecularExponent', 10);
                EdgeLighting = new RadioProperty(this, 'EdgeLighting', new String[] {'none', 'flat', 'gouraud', 'phong'}, 'none');
                FaceLighting = new RadioProperty(this, 'FaceLighting', new String[] {'none', 'flat', 'gouraud', 'phong'}, 'none');
                FaceAlpha = new DoubleRadioProperty(this, 'FaceAlpha', new String[] {'flat', 'interp'}, 1.0);
                EdgeAlpha = new DoubleRadioProperty(this, 'EdgeAlpha', new String[] {'flat', 'interp'}, 1.0);
                VertexNormals = new ArrayProperty(this, 'VertexNormals', new String[] {'double'}, 3, null);
                AlphaData = new ArrayProperty(this, 'AlphaData', new String[] {'double', 'byte'}, 2, null);
                AlphaDataMapping = new RadioProperty(this, 'AlphaDataMapping', new String[] {'none', 'scaled', 'direct'}, 'scaled');
                Marker = new MarkerProperty(this, 'Marker', 'none');
                MarkerSize = new DoubleProperty(this, 'MarkerSize', 7.0);
                MarkerEdgeColor = new ColorProperty(this, 'MarkerEdgeColor', new String[] {'none', 'auto', 'flat'}, 'auto');
                MarkerFaceColor = new ColorProperty(this, 'MarkerFaceColor', new String[] {'none', 'auto', 'flat'}, 'none');
                LineStyle = new LineStyleProperty(this, 'LineStyle', '-');
                LineWidth = new DoubleProperty(this, 'LineWidth', 0.5);
                ZLimInclude.reset(new Boolean(true));
                CLimInclude.reset(new Boolean(true));
                ALimInclude.reset(new Boolean(true));
                listen(XData);
                listen(YData);
                listen(ZData);
                listen(CData);
                listen(getAxes().getFigure().Colormap);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
Matrix computeNormals () [inline, package]
References ArrayProperty.asDoubleMatrix(), Utils.crossProduct(), plt.x, SurfaceObject.XData, plt.y, SurfaceObject.YData, and SurfaceObject.ZData.
Referenced by SurfaceObject.validate().
        {
                double[][] x = XData.asDoubleMatrix();
                double[][] y = YData.asDoubleMatrix();
                double[][] z = ZData.asDoubleMatrix();
                int p = z.length;
                int q = (z.length > 0 ? z[0].length : 0);
                double[][][] n = new double[p][q][3];
                // TODO: normal computation at boundaries
                for (int i=1; i<p-1; i++)
                {
                        for (int j=1; j<q-1; j++)
                        {
                                n[i][j][0] = n[i][j][1] = n[i][j][2] = 0;
                                Utils.crossProduct(
                                        x[i][j+1]-x[i][j], y[i][j+1]-y[i][j], z[i][j+1]-z[i][j],
                                        x[i+1][j]-x[i][j], y[i+1][j]-y[i][j], z[i+1][j]-z[i][j],
                                        n[i][j]);
                                Utils.crossProduct(
                                        x[i-1][j]-x[i][j], y[i-1][j]-y[i][j], z[i-1][j]-z[i][j],
                                        x[i][j+1]-x[i][j], y[i][j+1]-y[i][j], z[i][j+1]-z[i][j],
                                        n[i][j]);
                                Utils.crossProduct(
                                        x[i][j-1]-x[i][j], y[i][j-1]-y[i][j], z[i][j-1]-z[i][j],
                                        x[i-1][j]-x[i][j], y[i-1][j]-y[i][j], z[i-1][j]-z[i][j],
                                        n[i][j]);
                                Utils.crossProduct(
                                        x[i+1][j]-x[i][j], y[i+1][j]-y[i][j], z[i+1][j]-z[i][j],
                                        x[i][j-1]-x[i][j], y[i][j-1]-y[i][j], z[i][j-1]-z[i][j],
                                        n[i][j]);
                                n[i][j][0] /= 4;
                                n[i][j][1] /= 4;
                                n[i][j][2] /= 4;
                                double d = Math.sqrt(n[i][j][0]*n[i][j][0]+n[i][j][1]*n[i][j][1]+n[i][j][2]*n[i][j][2]);
                                n[i][j][0] /= d;
                                n[i][j][1] /= d;
                                n[i][j][2] /= d;
                        }
                }
                return new Matrix(n);
        }
void delete () [inline, inherited]
Reimplemented from PropertySet.
Reimplemented in FigureObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
References HandleObject.BeingDeleted, HandleObject.cachedData, HandleEventSourceHelper.delete(), HandleObject.deleteChildren(), HandleObject.DeleteFcn, HandleObjectListProperty.elementAt(), HandleObject.eventSource, HandleObject.eventSourceSet, CallbackProperty.execute(), HandleEventSourceHelper.fireEvent(), HandleObject.getHandle(), HandleObject.Parent, HandleObject.removeChild(), HandleObject.removeHandleEventSink(), HandleObject.removeHandleObject(), and Property.reset().
Referenced by HandleObject.deleteChildren(), AxesObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), and AxesObject.makeLegend().
        {
                BeingDeleted.reset('on');
                try { eventSource.fireEvent('ObjectDeleted'); }
                catch (PropertyException ex) {}
                DeleteFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
                removeHandleObject(getHandle());
                super.delete();
                Iterator it = eventSourceSet.iterator();
                while (it.hasNext())
                        ((HandleEventSource)it.next()).removeHandleEventSink(this);
                eventSource.delete();
                deleteChildren();
                if (cachedData != null)
                        cachedData.dispose();
                Parent.elementAt(0).removeChild(this);
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void draw (Rendererr) [inline, virtual]
Implements GraphicObject.
References Renderer.draw().
        {
                r.draw(this);
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
double [][] getAlphaData () [inline, package]
References AxesObject.ALim, SurfaceObject.AlphaData, SurfaceObject.AlphaDataMapping, FigureObject.Alphamap, ArrayProperty.asDoubleMatrix(), VectorProperty.getArray(), GraphicObject.getAxes(), ArrayProperty.getClassName(), AxesObject.getFigure(), ArrayProperty.getNDims(), and RadioProperty.is().
Referenced by GLRenderer.draw().
        {
                if (AlphaData.getNDims() != 2)
                        return null;
                if (AlphaData.getClassName().equals('double'))
                {
                        double[][] aa = AlphaData.asDoubleMatrix();
                        if (AlphaDataMapping.is('none'))
                                return aa;
                        else if (AlphaDataMapping.is('scaled'))
                        {
                                double[][] res = new double[aa.length][aa[0].length];
                                double[] amap = getAxes().getFigure().Alphamap.getArray();
                                double[] alim = getAxes().ALim.getArray();
                                for (int i=0; i<res.length; i++)
                                        for (int j=0; j<res[i].length; j++)
                                        {
                                                int s = (int)Math.round((amap.length-1)*(aa[i][j]-alim[0])/(alim[1]-alim[0]));
                                                s = Math.min(Math.max(0, s), amap.length-1);
                                                res[i][j] = amap[s];
                                        }
                                return res;
                        }
                        else if (AlphaDataMapping.is('direct'))
                        {
                                double[][] res = new double[aa.length][aa[0].length];
                                double[] amap = getAxes().getFigure().Alphamap.getArray();
                                
                                for (int i=0; i<res.length; i++)
                                        for (int j=0; j<res[i].length; j++)
                                        {
                                                int s = (int)Math.round(aa[i][j])-1;
                                                s = Math.min(Math.max(0, s), amap.length-1);
                                                res[i][j] = amap[s];
                                        }
                                return res;
                        }
                }
                return null;
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxes () [inline, inherited]
References HandleObjectListProperty.elementAt(), and HandleObject.Parent.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), J2DRenderer.draw(), GLRenderer.draw(), TextObject.drawAsImage(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), SurfaceObject.getCData(), PatchObject.getCData(), TextObject.getExtent(), ImageObject.ImageObject(), BaseLineObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.SurfaceObject(), TextObject.toPostScript(), TextObject.updateData(), BaseLineObject.updateLine(), and TextObject.updateMinMax().
        {
                HandleObject obj = Parent.elementAt(0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                else
                        return ((GraphicObject)obj).getAxes();
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
double [][][] getCData () [inline, package]
References ArrayProperty.asDoubleMatrix(), ArrayProperty.asDoubleMatrix3(), SurfaceObject.CData, SurfaceObject.CDataMapping, AxesObject.convertCData(), GraphicObject.getAxes(), ArrayProperty.getNDims(), and RadioProperty.getValue().
Referenced by GLRenderer.draw().
        {
                if (CData.getNDims() == 2)
                        return getAxes().convertCData(CData.asDoubleMatrix(), CDataMapping.getValue());
                else
                        return CData.asDoubleMatrix3();
        }
java.awt.Component getComponent () [inline, inherited]
Reimplemented in FigureObject, UIPanelObject, and UIControlObject.
Referenced by UIControlObject.getParentComponent(), and UIPanelObject.getParentComponent().
        {
                System.out.println('Warning: no component associated with ' + getClass());
                return null;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented from HandleObject.
Reimplemented in BaseLineObject.
References BooleanProperty.isSet(), and GraphicObject.LegendInclude.
        {
                return LegendInclude.isSet();
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from HandleObject.
References SurfaceObject.CData, Property.reset(), HandleObject.setCachedData(), SurfaceObject.updateColorMinMax(), SurfaceObject.updateMinMax(), SurfaceObject.VertexNormals, SurfaceObject.XData, SurfaceObject.YData, and SurfaceObject.ZData.
        {
                super.propertyChanged(p);
                if (p == XData || p == YData || p == ZData)
                {
                        VertexNormals.reset(null);
                        updateMinMax();
                }
                else if (p == CData)
                        updateColorMinMax();
                else if (p.getName().equalsIgnoreCase('colormap'))
                        setCachedData(null);
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References FigureObject.__Dirty__, HandleObject.getAncestor(), and Property.reset().
Referenced by LegendObject.propertyChanged().
        {
                super.set(p, value);
                FigureObject fig = (FigureObject)getAncestor('figure');
                fig.__Dirty__.reset('on');
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void updateColorMinMax () [inline, private]
References SurfaceObject.CData, GraphicObject.CLim, ArrayProperty.getMatrix(), and Property.set().
Referenced by SurfaceObject.propertyChanged(), and SurfaceObject.validate().
        {
                Matrix m = CData.getMatrix();
                CLim.set(new double[] {m.minValue(), m.maxValue()}, true);
        }
void updateMinMax () [inline, private]
References ArrayProperty.asDoubleMatrix(), Property.set(), plt.x, SurfaceObject.XData, GraphicObject.XLim, plt.y, SurfaceObject.YData, GraphicObject.YLim, SurfaceObject.ZData, and GraphicObject.ZLim.
Referenced by SurfaceObject.propertyChanged(), and SurfaceObject.validate().
        {
                double xmin, xmax, ymin, ymax, zmin, zmax;
                double xmin2, xmax2, ymin2, ymax2, zmin2, zmax2;
                double[][] x = XData.asDoubleMatrix();
                double[][] y = YData.asDoubleMatrix();
                double[][] z = ZData.asDoubleMatrix();
                int m = Math.min(Math.min(x.length, y.length), z.length);
                int n = (m > 0 ? Math.min(Math.min(x[0].length, y[0].length), z[0].length) : 0);
                xmin = ymin = zmin = Double.POSITIVE_INFINITY;
                xmax = ymax = zmax = Double.NEGATIVE_INFINITY;
                xmin2 = ymin2 = zmin2 = Double.POSITIVE_INFINITY;
                xmax2 = ymax2 = zmax2 = Double.MIN_VALUE;
                for (int i=0; i<m; i++)
                        for (int j=0; j<n; j++)
                        {
                                if (x[i][j] < xmin) xmin = x[i][j];
                                if (x[i][j] > xmax) xmax = x[i][j];
                                if (x[i][j] > 0)
                                {
                                        if (x[i][j] < xmin2) xmin2 = x[i][j];
                                        if (x[i][j] > xmax2) xmax2 = x[i][j];
                                }
                                if (y[i][j] < ymin) ymin = y[i][j];
                                if (y[i][j] > ymax) ymax = y[i][j];
                                if (y[i][j] > 0)
                                {
                                        if (y[i][j] < ymin2) ymin2 = y[i][j];
                                        if (y[i][j] > ymax2) ymax2 = y[i][j];
                                }
                                if (z[i][j] < zmin) zmin = z[i][j];
                                if (z[i][j] > zmax) zmax = z[i][j];
                                if (z[i][j] > 0)
                                {
                                        if (z[i][j] < zmin2) zmin2 = z[i][j];
                                        if (z[i][j] > zmax2) zmax2 = z[i][j];
                                }
                        }
                XLim.set(new double[] {xmin, xmax, xmin2, xmax2}, true);
                YLim.set(new double[] {ymin, ymax, ymin2, ymax2}, true);
                ZLim.set(new double[] {zmin, zmax, zmin2, zmax2}, true);
        }
void validate () [inline]
Reimplemented from HandleObject.
References SurfaceObject.computeNormals(), Property.reset(), SurfaceObject.updateColorMinMax(), SurfaceObject.updateMinMax(), and SurfaceObject.VertexNormals.
        {
                updateMinMax();
                updateColorMinMax();
                VertexNormals.reset(computeNormals());
                super.validate();
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
VectorProperty ALim [package, inherited]
Referenced by GroupObject.childValidated(), GraphicObject.GraphicObject(), and GroupObject.updateLimits().
BooleanProperty ALimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
ArrayProperty AlphaData [package]
Referenced by SurfaceObject.getAlphaData(), and SurfaceObject.SurfaceObject().
RadioProperty AlphaDataMapping [package]
Referenced by SurfaceObject.getAlphaData(), and SurfaceObject.SurfaceObject().
DoubleProperty AmbientStrength [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
boolean callListValid [private]
Referenced by SurfaceObject.SurfaceObject().
ArrayProperty CData [package]
Referenced by SurfaceObject.getCData(), SurfaceObject.propertyChanged(), SurfaceObject.SurfaceObject(), and SurfaceObject.updateColorMinMax().
RadioProperty CDataMapping [package]
Referenced by SurfaceObject.getCData(), and SurfaceObject.SurfaceObject().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
VectorProperty CLim [package, inherited]
Referenced by AxesObject.autoScaleC(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), SurfaceObject.updateColorMinMax(), GroupObject.updateLimits(), ImageObject.updateMinMax(), and PatchObject.updateMinMax().
BooleanProperty CLimInclude [package, inherited]
Referenced by AxesObject.autoScaleC(), BarseriesObject.BarseriesObject(), GraphicObject.GraphicObject(), ImageObject.ImageObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
DoubleProperty DiffuseStrength [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
DoubleRadioProperty EdgeAlpha [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
ColorProperty EdgeColor [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
RadioProperty EdgeLighting [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
DoubleRadioProperty FaceAlpha [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
ColorProperty FaceColor [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
RadioProperty FaceLighting [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
int glID [protected, inherited]
Referenced by GraphicObject.GraphicObject().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
BooleanProperty LegendInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), GraphicObject.isLegendable(), and LineObject.LineObject().
LineStyleProperty LineStyle [package]
Referenced by SurfaceObject.SurfaceObject().
DoubleProperty LineWidth [package]
Referenced by SurfaceObject.SurfaceObject().
MarkerProperty Marker [package]
Referenced by SurfaceObject.SurfaceObject().
ColorProperty MarkerEdgeColor [package]
Referenced by SurfaceObject.SurfaceObject().
ColorProperty MarkerFaceColor [package]
Referenced by SurfaceObject.SurfaceObject().
DoubleProperty MarkerSize [package]
Referenced by SurfaceObject.SurfaceObject().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
DoubleProperty SpecularExponent [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
DoubleProperty SpecularStrength [package]
Referenced by GLRenderer.draw(), and SurfaceObject.SurfaceObject().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
ArrayProperty VertexNormals [package]
Referenced by GLRenderer.draw(), SurfaceObject.propertyChanged(), SurfaceObject.SurfaceObject(), and SurfaceObject.validate().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
ArrayProperty XData [package]
Referenced by SurfaceObject.computeNormals(), GLRenderer.draw(), SurfaceObject.propertyChanged(), SurfaceObject.SurfaceObject(), and SurfaceObject.updateMinMax().
VectorProperty XLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty XLimInclude [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
ArrayProperty YData [package]
Referenced by SurfaceObject.computeNormals(), GLRenderer.draw(), SurfaceObject.propertyChanged(), SurfaceObject.SurfaceObject(), and SurfaceObject.updateMinMax().
VectorProperty YLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty YLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
ArrayProperty ZData [package]
Referenced by SurfaceObject.computeNormals(), GLRenderer.draw(), SurfaceObject.propertyChanged(), SurfaceObject.SurfaceObject(), and SurfaceObject.updateMinMax().
VectorProperty ZLim [package, inherited]
Referenced by GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty ZLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), LineObject.LineObject(), PatchObject.PatchObject(), LineObject.propertyChanged(), SurfaceObject.SurfaceObject(), and LineObject.validate().
Author
Generated automatically by Doxygen for Octave from the source code.