.TH "AxesObject.Scaler" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AxesObject.Scaler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAxesObject\&.LinearScaler\fP, and \fBAxesObject\&.LogScaler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBscale\fP (double x)"
.br
.ti -1c
.RI "double[] \fBscale\fP (double[] x)"
.br
.ti -1c
.RI "double[][] \fBscale\fP (double[][] x)"
.br
.ti -1c
.RI "double \fBunscale\fP (double x)"
.br
.ti -1c
.RI "boolean \fBisLinear\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean \fBisLinear\fP ()"
.PP
Implemented in \fBAxesObject\&.LogScaler\fP, and \fBAxesObject\&.LinearScaler\fP\&.
.SS "double \fBscale\fP (doublex)"
.PP
Implemented in \fBAxesObject\&.LogScaler\fP, and \fBAxesObject\&.LinearScaler\fP\&.
.PP
Referenced by AxesObject\&.draw(), AxesObject\&.transform(), and AxesObject\&.updateXFormMatrices()\&.
.SS "double [] \fBscale\fP (double[]x)"
.PP
Implemented in \fBAxesObject\&.LogScaler\fP, and \fBAxesObject\&.LinearScaler\fP\&.
.SS "double [][] \fBscale\fP (doublex[][])"
.PP
Implemented in \fBAxesObject\&.LogScaler\fP, and \fBAxesObject\&.LinearScaler\fP\&.
.SS "double \fBunscale\fP (doublex)"
.PP
Implemented in \fBAxesObject\&.LogScaler\fP, and \fBAxesObject\&.LinearScaler\fP\&.
.PP
Referenced by AxesObject\&.unTransform()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
