LineStyleProperty
NAME
LineStyleProperty -
SYNOPSIS
Inherits RadioProperty.
Public Member Functions
LineStyleProperty (PropertySet parent, String name)
LineStyleProperty (PropertySet parent, String name, String style)
Property cloneProperty ()
Stroke getStroke (float width)
void setStyle (String s)
int getStyle ()
boolean isSet ()
String toPostScript ()
String getValue ()
boolean is (String val)
String toString ()
PropertySet getParent ()
String getName ()
boolean isReadOnly ()
void setReadOnly (boolean flag)
boolean isVisible ()
void setVisible (boolean flag)
Object get ()
void set (Object value) throws PropertyException
void set (Object value, boolean warn_on_exception)
void reset (Object value)
void lock ()
void unLock ()
boolean isSameValue (Object value)
void delete ()
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
Static Public Member Functions
static Property createProperty (PropertySet parent, String name, String type) throws PropertyException
static Property createProperty (PropertySet parent, String name, String type, Object arg) throws PropertyException
Protected Member Functions
LineStyleProperty (LineStyleProperty p)
Object convertValue (Object value) throws PropertyException
void initDefault ()
Object getInternal ()
void setInternal (Object value) throws PropertyException
boolean isEqual (Object value)
Protected Attributes
Object pvalue
Constructor & Destructor Documentation
LineStyleProperty (LineStylePropertyp) [inline, protected]
Referenced by LineStyleProperty.cloneProperty().
        {
                super(p);
        }
LineStyleProperty (PropertySetparent, Stringname) [inline]
        {
                super(parent, name, new String[] {'-', ':', '--', '-.', 'none', ''});
        }
LineStyleProperty (PropertySetparent, Stringname, Stringstyle) [inline]
References Property.name, Property.parent, and Property.pvalue.
        {
                this(parent, name);
                this.pvalue = style;
        }
Member Function Documentation
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and Property.eventSource.
Referenced by HandleObject.listen(), and HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
Property cloneProperty () [inline, virtual]
Reimplemented from RadioProperty.
References LineStyleProperty.LineStyleProperty().
        {
                return new LineStyleProperty(this);
        }
Object convertValue (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented from Property.
References RadioProperty.valueSet.
        {
                if (value instanceof String && valueSet.containsKey(value))
                        return valueSet.get(value);
                else
                        throw new PropertyException('invalid property value - ' + value.toString());
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype) throws PropertyException 	 [inline, static, inherited]
References Property.name, and Property.parent.
Referenced by Property.createProperty().
        {
                if (type.equals('double'))
                        return new DoubleProperty(parent, name);
                else if (type.equals('string'))
                        return new StringProperty(parent, name);
                return null;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype, Objectarg) throws PropertyException 	 [inline, static, inherited]
References Property.createProperty(), Property.name, Property.parent, and Property.set().
        {
                if (type.equals('radio'))
                {
                        String[] values = ((String)arg).split('|');
                        return new RadioProperty(parent, name, values, '');
                }
                else
                {
                        Property p = createProperty(parent, name, type);
                        if (p != null)
                                p.set(arg);
                        return p;
                }
        }
void delete () [inline, inherited]
References HandleEventSourceHelper.delete(), and Property.eventSource.
        {
                eventSource.delete();
        }
Object get () [inline, inherited]
Reimplemented in NotImplProperty.
References Property.getInternal().
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), AxesObject.doZoom(), HandleObject.get(), LegendObject.LegendObject(), LegendObject.makeItemFromLine(), LegendObject.propertyChanged(), UnwindHandleObject.swapValues(), and CheckBoxControl.update().
        {
                /* TODO: needed?
                if (!lockNotify)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((PropertyListener)it.next()).propertyGetting(this);
                }
                */
                return getInternal();
        }
Object getInternal () [inline, protected, inherited]
Reimplemented in ColorProperty, CallbackProperty, HandleObjectListProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.get().
        {
                return pvalue;
        }
String getName () [inline, inherited]
References Property.name.
Referenced by PropertySet.addProperty(), AxesObject.autoAxis(), NotImplProperty.get(), PropertySet.getNames(), NotImplProperty.set(), Property.set(), and PropertySet.show().
        {
                return name;
        }
PropertySet getParent () [inline, inherited]
References Property.parent.
Referenced by CallbackProperty.execute(), NotImplProperty.get(), Property.initDefault(), HandleObject.listen(), NotImplProperty.set(), and Property.set().
        {
                return parent;
        }
Stroke getStroke (floatwidth) [inline]
References RadioProperty.getValue().
Referenced by TextObject.updateData().
        {
                String ls = getValue();
                if (ls.equals(':'))
                        return new BasicStroke(width, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 1.0f,
                                        new float[] {2.0f, 3.0f}, 0.0f);
                else if (ls.equals('-'))
                        return new BasicStroke(width);
                else if (ls.equals('--'))
                        return new BasicStroke(width, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 1.0f,
                                        new float[] {10.0f, 5.0f}, 0.0f);
                else if (ls.equals('-.'))
                        return new BasicStroke(width, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 1.0f,
                                        new float[] {5.0f, 5.0f, 1.0f, 5.0f}, 0.0f);
                else
                        return null;
        }
int getStyle () [inline]
References Renderer.LS_DASHDOT, Renderer.LS_DASHED, Renderer.LS_DOTTED, Renderer.LS_NONE, and Renderer.LS_SOLID.
        {
                String ls = getValue();
                if (ls.equals('-'))
                        return Renderer.LS_SOLID;
                else if (ls.equals(':'))
                        return Renderer.LS_DOTTED;
                else if (ls.equals('--'))
                        return Renderer.LS_DASHED;
                else if (ls.equals('-.'))
                        return Renderer.LS_DASHDOT;
                return Renderer.LS_NONE;
        }
String getValue () [inline, inherited]
References Property.pvalue.
Referenced by ColorbarObject.buildColorbar(), ColorbarObject.doLocate(), LegendObject.doLocate(), J2DRenderer.draw(), GLRenderer.draw(), AxesObject.draw(), TextObject.drawAsImage(), MarkerProperty.drawMarker(), FigureObject.FigureObject(), BooleanProperty.getBoolean(), AxesObject.getBoundingBox(), SurfaceObject.getCData(), PatchObject.getCData(), Utils.getFontSize(), AxesObject.getOuterBoundingBox(), UIControlObject.getPosition(), UIPanelObject.getPosition(), LineStyleProperty.getStroke(), RadioProperty.is(), LegendObject.LegendObject(), MarkerProperty.makeMarker(), GLRenderer.makeMarkerList(), GL2PS.makeMarkerPSString(), UIPanelObject.makePanel(), GLRenderer.makeTextureFromCData(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), TextObject.propertyChanged(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), TextControl.stringToHTML(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), FigureObject.updateFramePosition(), TextObject.updateMinMax(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), TextObject.validate(), UIControlObject.validate(), and UIPanelObject.validate().
        {
                return (String)pvalue;
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.hasHandleEvent().
        {
                return eventSource.hasHandleEvent(name);
        }
void initDefault () [inline, protected, inherited]
References HandleObject.getDefaultProperty(), Property.getParent(), HandleObject.getType(), Property.name, Property.parent, and Property.pvalue.
Referenced by Property.Property().
        {
                HandleObject parent = (HandleObject)getParent();
                String defname = 'default' + parent.getType() + name;
                Property p = parent.getDefaultProperty(defname);
                if (p != null)
                        pvalue = p.pvalue;
        }
boolean is (Stringval) [inline, inherited]
References RadioProperty.getValue().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.autoScaleX(), AxesObject.autoScaleY(), AxesObject.autoScaleZ(), AxesObject.autoTickLabelX(), AxesObject.autoTickLabelY(), AxesObject.autoTickLabelZ(), GL2PS.GL2PSMarkerDrawer.begin(), AxesObject.computeAutoTickLabels(), AxesObject.computeMinorTicks(), UIControlObject.controlActivated(), AxesContainer.createCanvas(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), J2DRenderer.draw(), GLRenderer.draw(), AxesObject.draw(), TextObject.drawAsImage(), UIControlObject.get(), TextControl.getAlignment(), Utils.getAlphaData(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), Utils.getFont(), Utils.getFontSize(), HandleObjectListProperty.getVisibleObjects(), UIControlAdapter.init(), MarkerProperty.isSet(), UIPanelObject.makeBorder(), UIControlAdapter.mousePressed(), BaseLineObject.propertyChanged(), UIControlAdapter.propertyChanged(), TextObject.propertyChanged(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), UIControlObject.set(), Edit2Control.setAlignment(), EditControl.setAlignment(), TextObject.toPostScript(), AxesObject.updateActivePosition(), TextObject.updateContent(), TextObject.updateData(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), PatchObject.updateMinMax(), TextObject.updateMinMax(), AxesObject.updateScalers(), FigureObject.updateToolbars(), and AxesObject.updateXFormMatrices().
        {
                return getValue().equalsIgnoreCase(val);
        }
boolean isEqual (Objectvalue) [inline, protected, inherited]
Reimplemented in TextProperty.
References Property.pvalue.
Referenced by Property.isSameValue(), and Property.set().
        {
                /*Object v = getInternal();*/
                Object v = pvalue;
                return (value == null ? v == null : value.equals(v));
        }
boolean isReadOnly () [inline, inherited]
References Property.readOnly.
        {
                return readOnly;
        }
boolean isSameValue (Objectvalue) [inline, inherited]
References Property.convertValue(), and Property.isEqual().
Referenced by HandleObject.waitFor().
        {
                try
                {
                        value = convertValue(value);
                        return isEqual(value);
                }
                catch (PropertyException e)
                {
                        return false;
                }
        }
boolean isSet () [inline]
Referenced by J2DRenderer.draw(), and GLRenderer.draw().
        {
                return !(is('none') || is(''));
        }
boolean isVisible () [inline, inherited]
References Property.visible.
Referenced by PropertySet.getNames(), and PropertySet.show().
        {
                return visible;
        }
void lock () [inline, inherited]
References Property.lockNotify.
        {
                lockNotify = true;
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
        {
                eventSource.removeHandleEventSink(sink);
        }
void reset (Objectvalue) [inline, inherited]
References Property.lockNotify.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), ColorbarObject.buildColorbar(), LegendObject.buildLegend(), ColorbarObject.ColorbarObject(), HandleObject.delete(), LegendObject.doLayout(), AxesObject.draw(), AxesObject.getBaseLine(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), PatchObject.PatchObject(), FigureObject.print(), LineObject.propertyChanged(), BarseriesObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.reset(), GraphicObject.set(), SurfaceObject.SurfaceObject(), UnwindHandleObject.swapValues(), TextObject.TextObject(), CheckBoxControl.update(), EditControl.update(), PopupMenuControl.update(), Edit2Control.update(), ListBoxControl.update(), AxesObject.updateXFormMatrices(), LineObject.validate(), SurfaceObject.validate(), and PatchObject.validate().
        {
                boolean oldLockNotify = lockNotify;
                lockNotify = true;
                try { set(value); }
                catch (PropertyException e)
                {
                        System.err.println('WARNING: exception during property reset: ' + e);
                }
                lockNotify = oldLockNotify;
        }
void set (Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in BooleanProperty, and NotImplProperty.
References Property.convertValue(), Property.eventSource, HandleEventSourceHelper.fireEvent(), Property.getName(), Property.getParent(), Property.isEqual(), Property.lockNotify, Property.readOnly, Property.setFlag, and Property.setInternal().
Referenced by HandleObject.autoSet(), BarseriesObject.BarseriesObject(), ColorbarObject.buildColorbar(), Property.createProperty(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), BarseriesObject.propertyChanged(), LegendObject.propertyChanged(), PatchObject.propertyChanged(), AxesObject.propertyChanged(), HandleObject.set(), AxesObject.unZoom(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), SurfaceObject.updateColorMinMax(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
        {
                if (readOnly)
                        throw new PropertyException('read-only property - ' + getName());
                value = convertValue(value);
                if (isEqual(value))
                {
                        //System.out.println(getName() + ': identical value, not setting - ' + value.toString());
                        return;
                }
                if (setFlag)
                {
                        System.out.println('WARNING: ' + getName() + '.set (' + ((HandleObject)getParent()).getHandle() + '): recursive behavior detected, not setting');
                        Thread.dumpStack();
                        return;
                }
                setFlag = true;
                try
                {
                        /* TODO: needed?
                        if (!lockNotify)
                        {
                                Iterator it = listenerList.iterator();
                                while (it.hasNext())
                                        ((PropertyListener)it.next()).propertySetting(this, value);
                        }
                        */
                        setInternal(value);
                        if (!lockNotify)
                        {
                                eventSource.fireEvent('PropertyChanged');
                        }
                        setFlag = false;
                }
                catch (Exception e)
                {
                        setFlag = false;
                        if (e instanceof PropertyException)
                                throw (PropertyException)e;
                        else
                                throw new PropertyException(e);
                }
        }
void set (Objectvalue, booleanwarn_on_exception) [inline, inherited]
References Property.getName().
        {
                try { set(value); }
                catch (PropertyException e)
                {
                        if (warn_on_exception)
                        {
                                System.out.println('WARNING: ' + getName() + '.set: exception occured');
                                e.printStackTrace();
                        }
                }
        }
void setInternal (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented in ArrayProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.set().
        {
                pvalue = value;
        }
void setReadOnly (booleanflag) [inline, inherited]
References Property.readOnly.
        {
                readOnly = flag;
        }
void setStyle (Strings) [inline]
        {
                try { set(s); }
                catch (PropertyException e) { }
        }
void setVisible (booleanflag) [inline, inherited]
References Property.visible.
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), FigureObject.FigureObject(), GraphicObject.GraphicObject(), and PatchObject.PatchObject().
        {
                visible = flag;
        }
String toPostScript () [inline]
Referenced by TextObject.toPostScript().
        {
                if (is(':'))
                        return '[0 3 1 3 1 3 1 3 1 0] 0 setdash';
                else if (is('-'))
                        return '[] 0 setdash';
                else if (is('--'))
                        return '[11 5] 0 setdash';
                else if (is('-.'))
                        return '[4 5 1 6] 0 setdash';
                else
                        return '[0 16] 0 setdash';
        }
String toString () [inline, inherited]
References Property.pvalue.
        {
                return (String)pvalue;
        }
void unLock () [inline, inherited]
References Property.lockNotify.
Referenced by HandleObject.addProperty(), and PropertySet.validate().
        {
                lockNotify = false;
        }
Member Data Documentation
Object pvalue [protected, inherited]
Referenced by HandleObjectListProperty.addElement(), ArrayProperty.ArrayProperty(), BooleanProperty.BooleanProperty(), CallbackProperty.CallbackProperty(), ColorProperty.ColorProperty(), HandleObjectListProperty.contains(), DoubleProperty.DoubleProperty(), DoubleRadioProperty.DoubleRadioProperty(), DoubleProperty.doubleValue(), DoubleRadioProperty.doubleValue(), HandleObjectListProperty.elementAt(), DoubleProperty.floatValue(), StringArrayProperty.getArray(), CallbackProperty.getCallback(), ArrayProperty.getClassName(), ColorProperty.getColor(), ArrayProperty.getDim(), TextProperty.getInternal(), Property.getInternal(), ColorProperty.getInternal(), ArrayProperty.getMatrix(), ArrayProperty.getNDims(), ObjectProperty.getObject(), TextProperty.getText(), RadioProperty.getValue(), VectorProperty.getVector(), HandleObjectListProperty.getVisibleObjects(), HandleObjectListProperty.HandleObjectListProperty(), Property.initDefault(), DoubleProperty.intValue(), DoubleRadioProperty.is(), ColorProperty.is(), DoubleRadioProperty.isDouble(), ArrayProperty.isEmpty(), TextProperty.isEqual(), Property.isEqual(), ColorProperty.isSet(), HandleObjectListProperty.iterator(), LineStyleProperty.LineStyleProperty(), MarkerProperty.MarkerProperty(), ObjectProperty.ObjectProperty(), Property.Property(), RadioProperty.RadioProperty(), HandleObjectListProperty.removeAllElements(), HandleObjectListProperty.removeElement(), TextProperty.setInternal(), Property.setInternal(), HandleObjectListProperty.size(), StringArrayProperty.StringArrayProperty(), StringProperty.StringProperty(), TextProperty.TextProperty(), StringProperty.toString(), ObjectProperty.toString(), RadioProperty.toString(), DoubleRadioProperty.toString(), VectorProperty.toString(), ArrayProperty.toString(), ColorProperty.toString(), and VectorProperty.VectorProperty().
Author
Generated automatically by Doxygen for Octave from the source code.