J2DRenderer
NAME
J2DRenderer -
SYNOPSIS
Inherits Renderer.
Public Member Functions
J2DRenderer (J2DRenderCanvas c)
void end ()
void setClipping (boolean flag)
boolean hasClipping ()
void setClipBox (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
void setCamera (double[] pos, double[] target)
void setColor (Color c)
void setFont (Font f)
void setLineStyle (String s, boolean forceStippling)
void setLineWidth (float w)
void draw (LineObject line)
void draw (LightObject light)
void draw (ByteBuffer data, int w, int h, double[] pos, int xOffset, int yOffset, boolean useClipping, boolean useZBuffer)
void drawBitmap (BufferedImage img, double[] pos, int xOffset, int yOffset)
void draw (PatchObject patch)
void draw (SurfaceObject surf)
void draw (ImageObject image)
void draw (TextObject text)
Rectangle drawText (String txt, double[] pos, int halign, int valign)
void setXForm (AxesObject ax)
void setViewport (int width, int height)
void clear (Color c)
void drawRubberBox (int[][] b)
void drawSegments (java.util.List pts)
void drawQuads (java.util.List pts, double zoffset)
Static Public Attributes
static final int LS_SOLID = 0
static final int LS_DOTTED = 1
static final int LS_DASHED = 2
static final int LS_DASHDOT = 3
static final int LS_NONE = 4
Package Functions
void setGraphics (Graphics g)
Package Attributes
AxesObject.Scaler sy
AxesObject.Scaler sz
Private Member Functions
void updateStroke ()
Private Attributes
Graphics2D g
boolean clipping
Matrix3D xForm
AxesObject.Scaler sx
J2DRenderCanvas canvas
float lineWidth
float[] linePattern
Rectangle clipRect
Constructor & Destructor Documentation
J2DRenderer (J2DRenderCanvasc) [inline]
References J2DRenderer.canvas, J2DRenderer.clipping, J2DRenderer.g, J2DRenderer.linePattern, and J2DRenderer.lineWidth.
        {
                g = null;
                clipping = false;
                canvas = c;
                lineWidth = 0.0f;
                linePattern = null;
        }
Member Function Documentation
void clear (Colorc) [inline]
Implements Renderer.
References J2DRenderer.canvas, J2DRenderer.g, RenderCanvas.getHeight(), and RenderCanvas.getWidth().
        {
                if (g != null)
                        g.clearRect(0, 0, canvas.getWidth(), canvas.getHeight());
        }
void draw (LineObjectline) [inline]
Implements Renderer.
References DoubleProperty.doubleValue(), MarkerProperty.drawMarker(), DoubleProperty.floatValue(), J2DRenderer.g, VectorProperty.getArray(), ColorProperty.getColor(), RadioProperty.getValue(), RadioProperty.is(), Utils.isNaNorInf(), LineStyleProperty.isSet(), LineObject.LineColor, LineObject.LineStyle, LineObject.LineWidth, LineObject.Marker, LineObject.MarkerSize, J2DRenderer.setColor(), J2DRenderer.setLineStyle(), J2DRenderer.setLineWidth(), J2DRenderer.sx, J2DRenderer.sy, J2DRenderer.sz, Matrix3D.transform(), plt.x, LineObject.XData, J2DRenderer.xForm, plt.y, LineObject.YData, and LineObject.ZData.
        {
                if (g != null)
                {
                        double[] x = sx.scale(line.XData.getArray());
                        double[] y = sy.scale(line.YData.getArray());
                        double[] z = sz.scale(line.ZData.getArray());
                        int n = Math.min(Math.min(x.length, y.length), (z.length == 0 ? Integer.MAX_VALUE : z.length));
                        double[] tx = new double[n];
                        double[] ty = new double[n];
                        double[] tz = new double[n];
                        if (z.length == 0)
                                xForm.transform(x, y, new double[n], n, tx, ty, tz);
                        else
                                xForm.transform(x, y, z, n, tx, ty, tz);
                        int[] xp = new int[n], yp = new int[n];
                        for (int i=0; i<n; i++)
                        {
                                xp[i] = (int)Math.round(tx[i]);
                                yp[i] = (int)Math.round(ty[i]);
                        }
                        if (line.LineStyle.isSet())
                        {
                                setColor(line.LineColor.getColor());
                                setLineStyle(line.LineStyle.getValue(), false);
                                setLineWidth(line.LineWidth.floatValue());
                                int index = 0;
                                for (int i=0; i<n; i++)
                                {
                                        if (!Utils.isNaNorInf(tx[i], ty[i], 0))
                                        {
                                                xp[index] = (int)Math.round(tx[i]);
                                                yp[index] = (int)Math.round(ty[i]);
                                                index++;
                                        }
                                        else if (index > 1)
                                        {
                                                g.drawPolyline(xp, yp, index);
                                                index = 0;
                                        }
                                }
                                if (index > 1)
                                        g.drawPolyline(xp, yp, index);
                        }
                        if (!line.Marker.is('none'))
                        {
                                setColor(line.LineColor.getColor());
                                setLineStyle(line.LineStyle.getValue(), false);
                                setLineWidth(line.LineWidth.floatValue());
                                for (int i=0; i<n; i++)
                                        if (!Utils.isNaNorInf(tx[i], ty[i], 0))
                                                line.Marker.drawMarker(g,
                                                        (int)Math.round(tx[i]),
                                                        (int)Math.round(ty[i]),
                                                        line.MarkerSize.doubleValue());
                        }
                }
        }
void draw (LightObjectlight) [inline]
Implements Renderer.
        {
                System.out.println('WARNING: lighting not supported under Java2D renderer');
        }
void draw (ByteBufferdata, intw, inth, double[]pos, intxOffset, intyOffset, booleanuseClipping, booleanuseZBuffer) [inline]
Implements Renderer.
        {
        }
void draw (PatchObjectpatch) [inline]
Implements Renderer.
        {
        }
void draw (SurfaceObjectsurf) [inline]
Implements Renderer.
        {
        }
void draw (ImageObjectimage) [inline]
Implements Renderer.
        {
        }
void draw (TextObjecttext) [inline]
Implements Renderer.
References J2DRenderer.canvas, AxesObject.convertUnits(), DoubleProperty.doubleValue(), TextObject.FontAngle, TextObject.FontName, TextObject.FontSize, TextObject.FontUnits, TextObject.FontWeight, J2DRenderer.g, VectorProperty.getArray(), GraphicObject.getAxes(), ColorProperty.getColor(), TextObject.getExtent(), Utils.getFont(), RenderCanvas.getHeight(), RadioProperty.getValue(), TextObject.HAlign, RadioProperty.is(), TextObject.Position, TextObject.render(), TextObject.Rotation, J2DRenderer.setColor(), TextObject.TextColor, Matrix3D.transform(), TextObject.Units, TextObject.VAlign, and J2DRenderer.xForm.
        {
                if (g != null)
                {
                        AxesObject ax = text.getAxes();
                        double[] pos = ax.convertUnits(text.Position.getArray(), text.Units.getValue());
                        double[] tpos = new double[4];
                        AffineTransform af = g.getTransform();
                        Rectangle r = text.getExtent();
                        xForm.transform(pos[0], pos[1], pos[2], tpos, 0);
                        g.translate((int)Math.round(tpos[0]), (int)Math.round(tpos[1]));
                        g.rotate(-text.Rotation.doubleValue()*Math.PI/180.0);
                        g.setFont(Utils.getFont(text.FontName, text.FontSize, text.FontUnits,
                                        text.FontAngle, text.FontWeight, canvas.getHeight()));
                        setColor(text.TextColor.getColor());
                        int xoff = 0, yoff = 0;
                        if (text.HAlign.is('right'))
                                xoff = -r.width;
                        else if (text.HAlign.is('center'))
                                xoff = -r.width/2;
                        if (text.VAlign.is('bottom'))
                                yoff = -r.height;
                        else if (text.VAlign.is('middle'))
                                yoff = -r.height/2;
                        else if (text.VAlign.is('baseline'))
                                yoff = -(r.height+r.y);
                        g.translate(xoff, yoff);
                        text.render(g);
                        g.setTransform(af);
                }
        }
void drawBitmap (BufferedImageimg, double[]pos, intxOffset, intyOffset) [inline]
Implements Renderer.
        {
        }
void drawQuads (java.util.Listpts, doublezoffset) [inline]
Implements Renderer.
References J2DRenderer.g, Matrix3D.transform(), plt.x, Point3D.x, J2DRenderer.xForm, plt.y, Point3D.y, and Point3D.z.
        {
                if (g != null)
                {
                        Iterator it = pts.iterator();
                        int count = 0;
                        int[] x = new int[4], y = new int[4];
                        double[] tmp = new double[4];
                        while (it.hasNext())
                        {
                                Point3D pt = (Point3D)it.next();
                                xForm.transform(pt.x, pt.y, pt.z, tmp, 0);
                                x[count] = (int)Math.round(tmp[0]);
                                y[count] = (int)Math.round(tmp[1]);
                                if (++count == 4)
                                {
                                        count = 0;
                                        g.fillPolygon(x, y, 4);
                                }
                        }
                }
        }
void drawRubberBox (intb[][]) [inline]
Implements Renderer.
References J2DRenderer.canvas, J2DRenderer.g, plt.x, and plt.y.
        {
                Graphics GC;
                if (g != null)
                        GC = g;
                else
                        GC = canvas.getGraphics();
                GC.setColor(Color.lightGray);
                GC.setXORMode(Color.white);
                for (int i=0; i<b.length; i++)
                {
                        int x = Math.min(b[i][0], b[i][2]), y = Math.min(b[i][1], b[i][3]);
                        int w = Math.abs(b[i][2]-b[i][0]), h = Math.abs(b[i][3]-b[i][1]);
                        GC.drawRect(x, y, w, h);
                }
                GC.setPaintMode();
                if (g == null)
                        GC.dispose();
        }
void drawSegments (java.util.Listpts) [inline]
Implements Renderer.
References J2DRenderer.g, Matrix3D.transform(), Point3D.x, J2DRenderer.xForm, Point3D.y, and Point3D.z.
        {
                if (g != null)
                {
                        Iterator it = pts.iterator();
                        int count = 0, x1 = 0, y1 = 0;
                        double[] tmp = new double[4];
                        while (it.hasNext())
                        {
                                Point3D pt = (Point3D)it.next();
                                xForm.transform(pt.x, pt.y, pt.z, tmp, 0);
                                if (count == 0)
                                {
                                        count = 1;
                                        x1 = (int)Math.round(tmp[0]);
                                        y1 = (int)Math.round(tmp[1]);
                                }
                                else
                                {
                                        count = 0;
                                        g.drawLine(x1, y1, (int)Math.round(tmp[0]), (int)Math.round(tmp[1]));
                                }
                        }
                }
        }
Rectangle drawText (Stringtxt, double[]pos, inthalign, intvalign) [inline]
Implements Renderer.
References J2DRenderer.canvas, J2DRenderer.g, RenderCanvas.getFont(), Matrix3D.transform(), and J2DRenderer.xForm.
        {
                if (g != null)
                {
                        SimpleTextEngine.Content content = new SimpleTextEngine.Content(txt);
                        Rectangle r = (Rectangle)content.layout(canvas, canvas.getFont()).clone();
                        double[] tpos = new double[4];
                        if (r.width > 0 && r.height > 0)
                        {
                                int xoff = 0, yoff = 0;
                                switch (halign)
                                {
                                        case 1: xoff = -r.width/2; break;
                                        case 2: xoff = -r.width; break;
                                }
                                switch (valign)
                                {
                                        case 1: yoff = -r.height/2; break;
                                        case 0: yoff = -r.height; break;
                                }
                                xForm.transform(pos[0], pos[1], pos[2], tpos, 0);
                                xoff = (int)Math.round(tpos[0])+xoff;
                                yoff = (int)Math.round(tpos[1])+yoff;
                                g.translate(xoff, yoff);
                                content.render(g);
                                g.translate(-xoff, -yoff);
                                return r;
                        }
                }
                return new Rectangle();
        }
void end () [inline]
Implements Renderer.
        {
        }
boolean hasClipping () [inline]
Implements Renderer.
References J2DRenderer.clipping.
        {
                return clipping;
        }
void setCamera (double[]pos, double[]target) [inline]
Implements Renderer.
        {
        }
void setClipBox (doublexmin, doublexmax, doubleymin, doubleymax, doublezmin, doublezmax) [inline]
Implements Renderer.
References J2DRenderer.clipRect, Matrix3D.transform(), plt.x, J2DRenderer.xForm, and plt.y.
        {
                double[] x = new double[] {xmin, xmin, xmin, xmin, xmax, xmax, xmax, xmax};
                double[] y = new double[] {ymin, ymin, ymax, ymax, ymin, ymin, ymax, ymax};
                double[] z = new double[] {zmin, zmax, zmin, zmax, zmin, zmax, zmin, zmax};
                double[] tx = new double[8];
                double[] ty = new double[8];
                double[] tz = new double[8];
                double _xmin, _xmax, _ymin, _ymax;
                xForm.transform(x, y, z, 8, tx, ty, tz);
                _xmin = _xmax = tx[0];
                _ymin = _ymax = ty[0];
                for (int i=1; i<8; i++)
                {
                        if (tx[i] < _xmin) _xmin = tx[i];
                        if (tx[i] > _xmax) _xmax = tx[i];
                        if (ty[i] < _ymin) _ymin = ty[i];
                        if (ty[i] > _ymax) _ymax = ty[i];
                }
                clipRect = new Rectangle((int)Math.round(_xmin)+1, (int)Math.round(_ymin)+1,
                                (int)Math.round(_xmax)-(int)Math.round(_xmin)-1, (int)Math.round(_ymax)-(int)Math.round(_ymin)-1);
        }
void setClipping (booleanflag) [inline]
Implements Renderer.
References J2DRenderer.clipping, J2DRenderer.clipRect, and J2DRenderer.g.
        {
                clipping = flag;
                if (flag && g != null)
                        g.setClip(clipRect);
                else
                        g.setClip(null);
        }
void setColor (Colorc) [inline]
Implements Renderer.
References J2DRenderer.g.
Referenced by J2DRenderer.draw().
        {
                if (g != null)
                        g.setColor(c);
        }
void setFont (Fontf) [inline]
Implements Renderer.
References J2DRenderer.g.
        {
                if (g != null)
                        g.setFont(f);
        }
void setGraphics (Graphicsg) [inline, package]
Referenced by J2DRenderCanvas.paint().
        {
                this.g = (Graphics2D)g;
                if (g != null)
                {
                        //this.g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                        //this.g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_OFF);
                }
        }
void setLineStyle (Strings, booleanforceStippling) [inline]
Implements Renderer.
References J2DRenderer.linePattern, and J2DRenderer.updateStroke().
Referenced by J2DRenderer.draw().
        {
                if (s.equals('-'))
                        linePattern = null;
                else if (s.equals(':'))
                        linePattern = new float[] {2.0f, 4.0f};
                else if (s.equals('--'))
                        linePattern = new float[] {10.0f, 5.0f};
                else if (s.equals('-.'))
                        linePattern = new float[] {5.0f, 5.0f, 1.0f, 5.0f};
                else
                        linePattern = null;
                updateStroke();
        }
void setLineWidth (floatw) [inline]
Implements Renderer.
References J2DRenderer.lineWidth, and J2DRenderer.updateStroke().
Referenced by J2DRenderer.draw().
        {
                lineWidth = w;
                updateStroke();
        }
void setViewport (intwidth, intheight) [inline]
Implements Renderer.
        {
        }
void setXForm (AxesObjectax) [inline]
Implements Renderer.
References FigureObject.__Antialias__, J2DRenderer.g, AxesObject.getFigure(), BooleanProperty.isSet(), J2DRenderer.sx, AxesObject.sx, J2DRenderer.sy, AxesObject.sy, J2DRenderer.sz, AxesObject.sz, AxesObject.x_render, and J2DRenderer.xForm.
        {
                xForm = ax.x_render;
                sx = ax.sx;
                sy = ax.sy;
                sz = ax.sz;
                if (g != null)
                {
                        boolean use_antialias = ax.getFigure().__Antialias__.isSet();
                        if (use_antialias)
                        {
                                g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                                g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_OFF);
                        }
                        else
                        {
                                g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_OFF);
                        }
                }
        }
void updateStroke () [inline, private]
References J2DRenderer.g, J2DRenderer.linePattern, and J2DRenderer.lineWidth.
Referenced by J2DRenderer.setLineStyle(), and J2DRenderer.setLineWidth().
        {
                if (g != null)
                        if (linePattern == null)
                                g.setStroke(new BasicStroke(lineWidth));
                        else
                                g.setStroke(new BasicStroke(lineWidth, BasicStroke.CAP_BUTT,
                                                        BasicStroke.JOIN_BEVEL, 1.0f, linePattern, 0.0f));
        }
Member Data Documentation
J2DRenderCanvas canvas [private]
Referenced by J2DRenderer.clear(), J2DRenderer.draw(), J2DRenderer.drawRubberBox(), J2DRenderer.drawText(), and J2DRenderer.J2DRenderer().
boolean clipping [private]
Referenced by J2DRenderer.hasClipping(), J2DRenderer.J2DRenderer(), and J2DRenderer.setClipping().
Rectangle clipRect [private]
Referenced by J2DRenderer.setClipBox(), and J2DRenderer.setClipping().
Graphics2D g [private]
Referenced by J2DRenderer.clear(), J2DRenderer.draw(), J2DRenderer.drawQuads(), J2DRenderer.drawRubberBox(), J2DRenderer.drawSegments(), J2DRenderer.drawText(), J2DRenderer.J2DRenderer(), J2DRenderer.setClipping(), J2DRenderer.setColor(), J2DRenderer.setFont(), J2DRenderer.setXForm(), and J2DRenderer.updateStroke().
float [] linePattern [private]
Referenced by J2DRenderer.J2DRenderer(), J2DRenderer.setLineStyle(), and J2DRenderer.updateStroke().
float lineWidth [private]
Referenced by J2DRenderer.J2DRenderer(), J2DRenderer.setLineWidth(), and J2DRenderer.updateStroke().
final int LS_DASHDOT = 3 [static, inherited]
Referenced by LineStyleProperty.getStyle().
final int LS_DASHED = 2 [static, inherited]
Referenced by LineStyleProperty.getStyle().
final int LS_DOTTED = 1 [static, inherited]
Referenced by LineStyleProperty.getStyle().
final int LS_NONE = 4 [static, inherited]
Referenced by LineStyleProperty.getStyle().
final int LS_SOLID = 0 [static, inherited]
Referenced by LineStyleProperty.getStyle().
AxesObject.Scaler sx [private]
Referenced by J2DRenderer.draw(), and J2DRenderer.setXForm().
AxesObject.Scaler sy [package]
Referenced by J2DRenderer.draw(), and J2DRenderer.setXForm().
AxesObject.Scaler sz [package]
Referenced by J2DRenderer.draw(), and J2DRenderer.setXForm().
Matrix3D xForm [private]
Referenced by J2DRenderer.draw(), J2DRenderer.drawQuads(), J2DRenderer.drawSegments(), J2DRenderer.drawText(), J2DRenderer.setClipBox(), and J2DRenderer.setXForm().
Author
Generated automatically by Doxygen for Octave from the source code.