HandleEventSourceHelper
NAME
HandleEventSourceHelper -
SYNOPSIS
Public Member Functions
HandleEventSourceHelper (Object source, String[] events)
boolean hasHandleEvent (String name)
void fireEvent (String name) throws PropertyException
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
void delete ()
Protected Attributes
Map eventMap
Private Attributes
Object source
Constructor & Destructor Documentation
HandleEventSourceHelper (Objectsource, String[]events) [inline]
References HandleEventSourceHelper.eventMap, and HandleEventSourceHelper.source.
        {
                this.source = source;
                this.eventMap = Collections.synchronizedMap(new HashMap());
                for (int i=0; i<events.length; i++)
                        eventMap.put(events[i], null);
        }
Member Function Documentation
void addHandleEventSink (Stringname, HandleEventSinksink) [inline]
References HandleEventSourceHelper.eventMap, and HandleEventSourceHelper.source.
Referenced by Property.addHandleEventSink(), and HandleObject.addHandleEventSink().
        {
                if (eventMap.containsKey(name))
                {
                        List l = (List)eventMap.get(name);
                        if (l == null)
                        {
                                l = new LinkedList();
                                eventMap.put(name, l);
                        }
                        l.add(sink);
                }
                else
                        System.out.println('ERROR: unknown event `' + name + '' for objects of type ' + source.getClass());
        }
void delete () [inline]
References HandleEventSourceHelper.eventMap, and HandleEventSourceHelper.source.
Referenced by HandleObject.delete(), and Property.delete().
        {
                Iterator it = eventMap.values().iterator();
                while (it.hasNext())
                {
                        List l = (List)it.next();
                        if (l != null)
                        {
                                Iterator lit = l.iterator();
                                while (lit.hasNext())
                                        ((HandleEventSink)lit.next()).sourceDeleted(source);
                        }
                }
        }
void fireEvent (Stringname) throws PropertyException 	 [inline]
References HandleEventSourceHelper.eventMap, HandleEventSink.eventOccured(), HandleEventSink.executeOnce(), and HandleEventSourceHelper.source.
Referenced by HandleObject.delete(), and Property.set().
        {
                if (eventMap.containsKey(name))
                {
                        LinkedList l = (LinkedList)eventMap.get(name);
                        if (l != null)
                                synchronized (l)
                                {
                                        HandleEvent evt = new HandleEvent(source, name);
                                        Iterator it = l.iterator();
                                        while (it.hasNext())
                                        {
                                                HandleEventSink sink = (HandleEventSink)it.next();
                                                sink.eventOccured(evt);
                                                if (sink.executeOnce())
                                                        it.remove();
                                        }
                                }
                }
                else
                        System.out.println('ERROR: unknown event `' + name + '' for objects of type ' + source.getClass());
        }
boolean hasHandleEvent (Stringname) [inline]
References HandleEventSourceHelper.eventMap.
Referenced by Property.hasHandleEvent(), and HandleObject.hasHandleEvent().
        {
                return eventMap.containsKey(name);
        }
void removeHandleEventSink (HandleEventSinksink) [inline]
References HandleEventSourceHelper.eventMap.
Referenced by Property.removeHandleEventSink(), and HandleObject.removeHandleEventSink().
        {
                Iterator it = eventMap.values().iterator();
                while (it.hasNext())
                {
                        List l = (List)it.next();
                        if (l != null)
                                while (l.remove(sink));
                }
        }
Member Data Documentation
Map eventMap [protected]
Referenced by HandleEventSourceHelper.addHandleEventSink(), HandleEventSourceHelper.delete(), HandleEventSourceHelper.fireEvent(), HandleEventSourceHelper.HandleEventSourceHelper(), HandleEventSourceHelper.hasHandleEvent(), and HandleEventSourceHelper.removeHandleEventSink().
Object source [private]
Referenced by HandleEventSourceHelper.addHandleEventSink(), HandleEventSourceHelper.delete(), HandleEventSourceHelper.fireEvent(), and HandleEventSourceHelper.HandleEventSourceHelper().
Author
Generated automatically by Doxygen for Octave from the source code.