OctaveCallback
NAME
OctaveCallback -
SYNOPSIS
Inherits Callback.
Public Member Functions
OctaveCallback (OctaveReference ref)
OctaveCallback (String cmd)
void execute (HandleObject parent, Object[] args)
Object get ()
String toString ()
void addCallbackListener (CallbackListener l)
void removeCallbackListener (CallbackListener l)
void unwind (Property p, Object value)
void execute (HandleObject parent)
Static Public Member Functions
static Callback makeCallback (Object obj)
Protected Member Functions
void fireCallbackExecuted ()
Protected Attributes
UnwindHandleObject unwinder
Package Attributes
OctaveReference ref
String cmd
Constructor & Destructor Documentation
OctaveCallback (OctaveReferenceref) [inline]
References OctaveCallback.cmd, and OctaveCallback.ref.
        {
                this.ref = ref;
                this.cmd = null;
        }
OctaveCallback (Stringcmd) [inline]
References OctaveCallback.cmd, and OctaveCallback.ref.
        {
                this.ref = null;
                this.cmd = cmd;
        }
Member Function Documentation
void addCallbackListener (CallbackListenerl) [inline, inherited]
References Callback.listenerList.
        {
                synchronized(listenerList)
                {
                        listenerList.add(l);
                }
        }
void execute (HandleObjectparent, Object[]args) [inline, virtual]
Implements Callback.
References RootObject.CallbackObject, OctaveCallback.cmd, UnwindHandleObject.end(), Callback.fireCallbackExecuted(), RootObject.getInstance(), OctaveCallback.ref, UnwindHandleObject.start(), Callback.unwind(), and Callback.unwinder.
        {
                if (ref == null && (cmd == null || cmd.length() == 0))
                {
                        fireCallbackExecuted();
                        return;
                }
                unwind(RootObject.getInstance().CallbackObject, parent);
                final RootObject root = RootObject.getInstance();
                final Object[] theArgs = args;
                final HandleObject theParent = parent;
                final UnwindHandleObject theUnwinder = unwinder;
                Octave.invokeLater(new Runnable() {
                        public void run()
                        {
                                try
                                {
                                        if (theUnwinder != null)
                                                theUnwinder.start();
                                        if (ref != null)
                                                Octave.doInvoke(ref.getID(), theArgs);
                                        else if (cmd != null && cmd.length() > 0)
                                                Octave.doEvalString(cmd);
                                }
                                catch (Exception e)
                                {
                                        System.err.println('Exception occured during callback execution: ' + e.toString());
                                        e.printStackTrace();
                                }
                                finally
                                {
                                        if (theUnwinder != null)
                                                theUnwinder.end();
                                }
                                fireCallbackExecuted();
                        }
                });
                unwinder = null;
        }
void execute (HandleObjectparent) [inline, inherited]
References Callback.execute().
        {
                execute(parent, new Object[0]);
        }
void fireCallbackExecuted () [inline, protected, inherited]
References Callback.listenerList.
Referenced by OctaveCallback.execute().
        {
                synchronized(listenerList)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((CallbackListener)it.next()).callbackExecuted(this);
                }
        }
Object get () [inline, virtual]
Implements Callback.
References OctaveCallback.cmd, and OctaveCallback.ref.
        {
                if (ref != null)
                        return ref;
                else
                        return cmd;
        }
static Callback makeCallback (Objectobj) [inline, static, inherited]
Referenced by CallbackProperty.CallbackProperty(), and CallbackProperty.convertValue().
        {
                if (obj instanceof OctaveReference)
                        return new OctaveCallback((OctaveReference)obj);
                else if (obj instanceof String)
                        return new OctaveCallback((String)obj);
                return null;
        }
void removeCallbackListener (CallbackListenerl) [inline, inherited]
References Callback.listenerList.
        {
                synchronized(listenerList)
                {
                        listenerList.remove(l);
                }
        }
String toString () [inline]
References OctaveCallback.cmd, and OctaveCallback.ref.
        {
                if (ref != null)
                        return ref.toString();
                else
                        return cmd;
        }
void unwind (Propertyp, Objectvalue) [inline, inherited]
References UnwindHandleObject.unwind(), and Callback.unwinder.
Referenced by OctaveCallback.execute(), and CallbackProperty.unwind().
        {
                if (unwinder == null)
                        unwinder = new UnwindHandleObject();
                unwinder.unwind(p, value);
        }
Member Data Documentation
String cmd [package]
Referenced by OctaveCallback.execute(), OctaveCallback.get(), OctaveCallback.OctaveCallback(), and OctaveCallback.toString().
OctaveReference ref [package]
Referenced by OctaveCallback.execute(), OctaveCallback.get(), OctaveCallback.OctaveCallback(), and OctaveCallback.toString().
UnwindHandleObject unwinder [protected, inherited]
Referenced by Callback.Callback(), OctaveCallback.execute(), and Callback.unwind().
Author
Generated automatically by Doxygen for Octave from the source code.