PropertySet
NAME
PropertySet -
SYNOPSIS
Inherits TreeMap.
Inherited by Factory, and HandleObject.
Public Member Functions
PropertySet ()
void addProperty (Property p)
Property getProperty (String name)
boolean hasProperty (String name)
Object get (String name) throws PropertyException
Object get (Property p)
void set (String name, Object value) throws PropertyException
void set (Property p, Object value) throws PropertyException
void show ()
void validate ()
String[] getNames ()
void delete ()
Constructor & Destructor Documentation
PropertySet () [inline]
        {
                super();
        }
Member Function Documentation
void addProperty (Propertyp) [inline]
Reimplemented in HandleObject.
References Property.getName().
Referenced by Property.Property(), and HandleObject.set().
        {
                put(p.getName().toLowerCase(), p);
        }
void delete () [inline]
Reimplemented in FigureObject, HandleObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                        ((Property)it.next()).delete();
        }
Object get (Stringname) throws PropertyException 	 [inline]
Reimplemented in HandleObject.
References PropertySet.getProperty().
        {
                Property p = getProperty(name);
                if (p != null)
                        return get(p);
                throw new PropertyException('property not found - ' + name);
        }
Object get (Propertyp) [inline]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
String [] getNames () [inline]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Property getProperty (Stringname) [inline]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
boolean hasProperty (Stringname) [inline]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline]
Reimplemented in HandleObject.
References PropertySet.getProperty().
        {
                Property p = getProperty(name);
                if (p != null)
                        set(p, value);
                else
                        throw new PropertyException('property not found - ' + name);
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline]
Reimplemented in UIControlObject, and GraphicObject.
        {
                p.set(value);
        }
void show () [inline]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
void validate () [inline]
Reimplemented in AxesObject, HandleObject, FigureObject, UIPanelObject, GroupObject, UIControlObject, PatchObject, TextObject, SurfaceObject, ImageObject, BarseriesObject, LineObject, and LightObject.
References Property.unLock().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        p.unLock();
                }
        }
Author
Generated automatically by Doxygen for Octave from the source code.