SimpleTextEngine.LineElement
NAME
SimpleTextEngine.LineElement -
SYNOPSIS
Inherits SimpleTextEngine.Element.
Inherited by SimpleTextEngine.SubscriptElement, and SimpleTextEngine.SuperscriptElement.
Package Functions
LineElement (String txt)
LineElement (String txt, boolean toplevel)
Rectangle layout (Layouter l)
void render (Graphics2D g)
void add (Element e)
Iterator iterator ()
void render (TextRenderer r)
Rectangle layout (RenderCanvas comp, Font font)
Package Attributes
String text
Rectangle rect
Private Attributes
LinkedList elements = new LinkedList()
boolean toplevel
Constructor & Destructor Documentation
LineElement (Stringtxt) [inline, package]
                {
                        this(txt, true);
                }
LineElement (Stringtxt, booleantoplevel) [inline, package]
References SimpleTextEngine.LineElement.elements, SimpleTextEngine.SimpleFactory.parse(), and SimpleTextEngine.LineElement.toplevel.
                {
                        super(txt);
                        this.toplevel = toplevel;
                        SimpleFactory f = new SimpleFactory(txt, elements);
                        f.parse();
                }
Member Function Documentation
void add (Elemente) [inline, package]
References SimpleTextEngine.LineElement.elements.
                {
                        elements.add(e);
                }
Iterator iterator () [inline, package]
References SimpleTextEngine.LineElement.elements.
Referenced by SimpleTextEngine.PSTextRenderer.render().
                {
                        return elements.iterator();
                }
Rectangle layout (RenderCanvascomp, Fontfont) [inline, package, inherited]
Referenced by SimpleTextEngine.LineElement.layout(), and SimpleTextEngine.ScriptElement.layout().
                {
                        return layout(new Layouter(comp, font));
                }
Rectangle layout (Layouterl) [inline, package]
Reimplemented from SimpleTextEngine.Element.
Reimplemented in SimpleTextEngine.SuperscriptElement, and SimpleTextEngine.SubscriptElement.
References SimpleTextEngine.Element.Element(), SimpleTextEngine.LineElement.elements, SimpleTextEngine.Layouter.font, SimpleTextEngine.Layouter.getFontMetrics(), SimpleTextEngine.Element.layout(), and SimpleTextEngine.Element.rect.
Referenced by SimpleTextEngine.Content.layout().
                {
                        Iterator it = elements.iterator();
                        FontMetrics fm = l.getFontMetrics();
                        Font currentFont = l.font;
                        rect = new Rectangle(0, -fm.getMaxDescent(), 0, fm.getMaxAscent()+fm.getMaxDescent());
                        while (it.hasNext())
                        {
                                Element e = (Element)it.next();
                                Rectangle eRect = e.layout(l);
                                eRect.x = rect.width;
                                rect = rect.union(eRect);
                        }
                        l.font = currentFont;
                        return rect;
                }
void render (Graphics2Dg) [inline, package]
Reimplemented from SimpleTextEngine.Element.
Reimplemented in SimpleTextEngine.SuperscriptElement, and SimpleTextEngine.SubscriptElement.
References SimpleTextEngine.Element.Element(), SimpleTextEngine.LineElement.elements, SimpleTextEngine.Element.rect, SimpleTextEngine.Element.render(), and SimpleTextEngine.LineElement.toplevel.
Referenced by SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.Content.render().
                {
                        Iterator it = elements.iterator();
                        int xoffset = 0, yoffset = (toplevel ? (rect.height + rect.y) : 0);
                        Font currentFont = g.getFont();
                        Color currentColor = g.getColor();
                        g.translate(0, yoffset);
                        while (it.hasNext())
                        {
                                Element e = (Element)it.next();
                                e.render(g);
                                g.translate(e.rect.width, 0);
                                xoffset += e.rect.width;
                        }
                        g.translate(-xoffset, -yoffset);
                        g.setColor(currentColor);
                        g.setFont(currentFont);
                }
void render (TextRendererr) [inline, package]
Reimplemented from SimpleTextEngine.Element.
Reimplemented in SimpleTextEngine.SuperscriptElement, and SimpleTextEngine.SubscriptElement.
References SimpleTextEngine.TextRenderer.render().
{ r.render(this); }
Member Data Documentation
LinkedList elements = new LinkedList() [private]
Referenced by SimpleTextEngine.LineElement.add(), SimpleTextEngine.LineElement.iterator(), SimpleTextEngine.LineElement.layout(), SimpleTextEngine.LineElement.LineElement(), and SimpleTextEngine.LineElement.render().
Rectangle rect [package, inherited]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.LineElement.layout(), SimpleTextEngine.SubscriptElement.layout(), SimpleTextEngine.SuperscriptElement.layout(), SimpleTextEngine.ScriptElement.layout(), SimpleTextEngine.TeXFontCommand.layout(), SimpleTextEngine.TeXElement.layout(), SimpleTextEngine.Content.layout(), SimpleTextEngine.PSTextRenderer.render(), SimpleTextEngine.LineElement.render(), SimpleTextEngine.SuperscriptElement.render(), and SimpleTextEngine.Content.render().
String text [package, inherited]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.Element.render().
boolean toplevel [private]
Referenced by SimpleTextEngine.LineElement.LineElement(), and SimpleTextEngine.LineElement.render().
Author
Generated automatically by Doxygen for Octave from the source code.