Renderer
NAME
Renderer -
SYNOPSIS
Inherited by GLRenderer, and J2DRenderer.
Classes
interface CachedData
Public Member Functions
void setClipping (boolean flag)
boolean hasClipping ()
void setClipBox (double xmin, double xmax, double ymin, double ymax, double zmin, double zmax)
void setCamera (double[] pos, double[] target)
void setColor (Color c)
void setLineStyle (String s, boolean forceStippling)
void setLineWidth (float w)
void setFont (Font f)
void end ()
void draw (LineObject line)
void draw (LightObject light)
void draw (ByteBuffer data, int w, int h, double[] pos, int xOffset, int yOffset, boolean useClipping, boolean useZBuffer)
void drawBitmap (BufferedImage img, double[] pos, int xOffset, int yOffset)
Rectangle drawText (String txt, double[] pos, int halign, int valign)
void draw (PatchObject patch)
void draw (SurfaceObject surf)
void draw (ImageObject image)
void draw (TextObject text)
void setXForm (AxesObject ax)
void setViewport (int width, int height)
void clear (Color c)
void drawRubberBox (int[][] b)
void drawSegments (java.util.List pts)
void drawQuads (java.util.List pts, double zoffset)
Static Public Attributes
static final int LS_SOLID = 0
static final int LS_DOTTED = 1
static final int LS_DASHED = 2
static final int LS_DASHDOT = 3
static final int LS_NONE = 4
Member Function Documentation
void clear (Colorc)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesContainer.display().
void draw (LineObjectline)
Implemented in GLRenderer, and J2DRenderer.
Referenced by LightObject.draw(), ImageObject.draw(), LineObject.draw(), TextObject.draw(), SurfaceObject.draw(), PatchObject.draw(), and TextObject.drawAsImage().
void draw (LightObjectlight)
Implemented in GLRenderer, and J2DRenderer.
void draw (ByteBufferdata, intw, inth, double[]pos, intxOffset, intyOffset, booleanuseClipping, booleanuseZBuffer)
Implemented in GLRenderer, and J2DRenderer.
void draw (PatchObjectpatch)
Implemented in GLRenderer, and J2DRenderer.
void draw (SurfaceObjectsurf)
Implemented in GLRenderer, and J2DRenderer.
void draw (ImageObjectimage)
Implemented in GLRenderer, and J2DRenderer.
void draw (TextObjecttext)
Implemented in GLRenderer, and J2DRenderer.
void drawBitmap (BufferedImageimg, double[]pos, intxOffset, intyOffset)
Implemented in GLRenderer, and J2DRenderer.
Referenced by SimpleTextEngine.drawAsImage().
void drawQuads (java.util.Listpts, doublezoffset)
Implemented in J2DRenderer.
Referenced by AxesObject.draw().
void drawRubberBox (intb[][])
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.drawZoomBox().
void drawSegments (java.util.Listpts)
Implemented in J2DRenderer.
Referenced by AxesObject.draw().
Rectangle drawText (Stringtxt, double[]pos, inthalign, intvalign)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void end ()
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
boolean hasClipping ()
Implemented in GLRenderer, and J2DRenderer.
void setCamera (double[]pos, double[]target)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void setClipBox (doublexmin, doublexmax, doubleymin, doubleymax, doublezmin, doublezmax)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void setClipping (booleanflag)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void setColor (Colorc)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void setFont (Fontf)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void setLineStyle (Strings, booleanforceStippling)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void setLineWidth (floatw)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
void setViewport (intwidth, intheight)
Implemented in GLRenderer, and J2DRenderer.
void setXForm (AxesObjectax)
Implemented in GLRenderer, and J2DRenderer.
Referenced by AxesObject.draw().
Member Data Documentation
final int LS_DASHDOT = 3 [static]
Referenced by LineStyleProperty.getStyle().
final int LS_DASHED = 2 [static]
Referenced by LineStyleProperty.getStyle().
final int LS_DOTTED = 1 [static]
Referenced by LineStyleProperty.getStyle().
final int LS_NONE = 4 [static]
Referenced by LineStyleProperty.getStyle().
final int LS_SOLID = 0 [static]
Referenced by LineStyleProperty.getStyle().
Author
Generated automatically by Doxygen for Octave from the source code.