.TH "GLRenderer.MarkerDrawer" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLRenderer.MarkerDrawer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGL2PS\&.GL2PSMarkerDrawer\fP, and \fBGLRenderer\&.GLMarkerDrawer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbegin\fP (\fBMarkerProperty\fP m, \fBDoubleProperty\fP ms, float lw)"
.br
.ti -1c
.RI "void \fBend\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (double x, double y, double z, double[] lc, double[] fc)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBbegin\fP (\fBMarkerProperty\fPm, \fBDoubleProperty\fPms, floatlw)"
.PP
Implemented in \fBGL2PS\&.GL2PSMarkerDrawer\fP, and \fBGLRenderer\&.GLMarkerDrawer\fP\&.
.PP
Referenced by GLRenderer\&.drawMarkers()\&.
.SS "void \fBdraw\fP (doublex, doubley, doublez, double[]lc, double[]fc)"
.PP
Implemented in \fBGL2PS\&.GL2PSMarkerDrawer\fP, and \fBGLRenderer\&.GLMarkerDrawer\fP\&.
.PP
Referenced by GLRenderer\&.drawMarkers()\&.
.SS "void \fBend\fP ()"
.PP
Implemented in \fBGL2PS\&.GL2PSMarkerDrawer\fP, and \fBGLRenderer\&.GLMarkerDrawer\fP\&.
.PP
Referenced by GLRenderer\&.drawMarkers()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
