GLRenderer.MarkerDrawer
NAME
GLRenderer.MarkerDrawer -
SYNOPSIS
Inherited by GL2PS.GL2PSMarkerDrawer, and GLRenderer.GLMarkerDrawer.
Public Member Functions
void begin (MarkerProperty m, DoubleProperty ms, float lw)
void end ()
void draw (double x, double y, double z, double[] lc, double[] fc)
Member Function Documentation
void begin (MarkerPropertym, DoublePropertyms, floatlw)
Implemented in GL2PS.GL2PSMarkerDrawer, and GLRenderer.GLMarkerDrawer.
Referenced by GLRenderer.drawMarkers().
void draw (doublex, doubley, doublez, double[]lc, double[]fc)
Implemented in GL2PS.GL2PSMarkerDrawer, and GLRenderer.GLMarkerDrawer.
Referenced by GLRenderer.drawMarkers().
void end ()
Implemented in GL2PS.GL2PSMarkerDrawer, and GLRenderer.GLMarkerDrawer.
Referenced by GLRenderer.drawMarkers().
Author
Generated automatically by Doxygen for Octave from the source code.