.TH "UIControl" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIControl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCheckBoxControl\fP, \fBEdit2Control\fP, \fBEditControl\fP, \fBListBoxControl\fP, \fBPopupMenuControl\fP, \fBPushButtonControl\fP, and \fBTextControl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.ti -1c
.RI "JComponent \fBgetComponent\fP ()"
.br
.ti -1c
.RI "void \fBdispose\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBdispose\fP ()"
.PP
Implemented in \fBListBoxControl\fP, \fBTextControl\fP, \fBEdit2Control\fP, \fBPopupMenuControl\fP, \fBEditControl\fP, \fBCheckBoxControl\fP, and \fBPushButtonControl\fP\&.
.PP
Referenced by UIControlAdapter\&.dispose()\&.
.SS "JComponent \fBgetComponent\fP ()"
.PP
Implemented in \fBListBoxControl\fP, \fBTextControl\fP, \fBEdit2Control\fP, \fBPopupMenuControl\fP, \fBEditControl\fP, \fBCheckBoxControl\fP, and \fBPushButtonControl\fP\&.
.PP
Referenced by UIControlAdapter\&.getComponent(), UIControlAdapter\&.init(), and UIControlAdapter\&.propertyChanged()\&.
.SS "void \fBupdate\fP ()"
.PP
Implemented in \fBListBoxControl\fP, \fBTextControl\fP, \fBEdit2Control\fP, \fBPopupMenuControl\fP, \fBEditControl\fP, \fBCheckBoxControl\fP, and \fBPushButtonControl\fP\&.
.PP
Referenced by UIControlAdapter\&.update()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
