.TH "SimpleTextEngine.TextRenderer" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleTextEngine.TextRenderer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrender\fP (\fBElement\fP e)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBLineElement\fP e)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBSubscriptElement\fP e)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBSuperscriptElement\fP e)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBScriptElement\fP e)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBTeXElement\fP e)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBTeXFontCommand\fP e)"
.br
.ti -1c
.RI "void \fBrender\fP (\fBContent\fP e)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBrender\fP (\fBElement\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.PP
Referenced by SimpleTextEngine\&.Element\&.render(), SimpleTextEngine\&.LineElement\&.render(), SimpleTextEngine\&.SubscriptElement\&.render(), SimpleTextEngine\&.SuperscriptElement\&.render(), SimpleTextEngine\&.ScriptElement\&.render(), SimpleTextEngine\&.TeXFontCommand\&.render(), SimpleTextEngine\&.TeXElement\&.render(), and SimpleTextEngine\&.Content\&.render()\&.
.SS "void \fBrender\fP (\fBLineElement\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.SS "void \fBrender\fP (\fBSubscriptElement\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.SS "void \fBrender\fP (\fBSuperscriptElement\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.SS "void \fBrender\fP (\fBScriptElement\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.SS "void \fBrender\fP (\fBTeXElement\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.SS "void \fBrender\fP (\fBTeXFontCommand\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.
.SS "void \fBrender\fP (\fBContent\fPe)"
.PP
Implemented in \fBSimpleTextEngine\&.PSTextRenderer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
