SimpleTextEngine.SimpleFactory
NAME
SimpleTextEngine.SimpleFactory -
SYNOPSIS
Package Functions
SimpleFactory (String txt, LinkedList lst)
int matchBrace (int start)
String getArgument (int start)
String getParameter (int start, char startChar, char endChar)
String getTeXCommand (int start)
void flush ()
void parse ()
Package Attributes
int current = 0
Private Attributes
String buffer
LinkedList list
int anchor = 0
StringBuilder builder
Constructor & Destructor Documentation
SimpleFactory (Stringtxt, LinkedListlst) [inline, package]
References SimpleTextEngine.SimpleFactory.buffer, SimpleTextEngine.SimpleFactory.builder, and SimpleTextEngine.SimpleFactory.list.
                {
                        buffer = txt;
                        list = lst;
                        builder = new StringBuilder();
                }
Member Function Documentation
void flush () [inline, package]
References SimpleTextEngine.SimpleFactory.anchor, SimpleTextEngine.SimpleFactory.builder, SimpleTextEngine.SimpleFactory.current, and SimpleTextEngine.SimpleFactory.list.
Referenced by SimpleTextEngine.SimpleFactory.parse().
                {
                        if (/*current > anchor &&*/ builder.length() > 0)
                        {
                                list.add(new Element(builder.toString()));
                                anchor = current;
                                builder.setLength(0);
                        }
                }
String getArgument (intstart) [inline, package]
References SimpleTextEngine.SimpleFactory.anchor, SimpleTextEngine.SimpleFactory.buffer, and SimpleTextEngine.SimpleFactory.matchBrace().
Referenced by SimpleTextEngine.SimpleFactory.parse().
                {
                        if (start >= buffer.length())
                                return null;
                        if (buffer.charAt(start) == '{')
                        {
                                int pos = matchBrace(start);
                                if (pos < 0)
                                        return null;
                                else
                                {
                                        anchor = pos+1;
                                        return buffer.substring(start+1, pos);
                                }
                        }
                        else
                        {
                                anchor = start+1;
                                return buffer.substring(start, start+1);
                        }
                }
String getParameter (intstart, charstartChar, charendChar) [inline, package]
References SimpleTextEngine.SimpleFactory.anchor, and SimpleTextEngine.SimpleFactory.buffer.
Referenced by SimpleTextEngine.SimpleFactory.parse().
                {
                        if (start >= buffer.length() || buffer.charAt(start) != startChar)
                                return null;
                        int pos = buffer.indexOf(endChar, start);
                        if (pos == -1)
                                return null;
                        else
                        {
                                anchor = pos+1;
                                return buffer.substring(start+1, pos);
                        }
                }
String getTeXCommand (intstart) [inline, package]
References SimpleTextEngine.SimpleFactory.anchor, and SimpleTextEngine.SimpleFactory.buffer.
Referenced by SimpleTextEngine.SimpleFactory.parse().
                {
                        int end = start;
                        while (end < buffer.length())
                        {
                                char c = buffer.charAt(end);
                                if (!Character.isLetterOrDigit(c))
                                        break;
                                end++;
                        }
                        anchor = end;
                        return buffer.substring(start, end);
                }
int matchBrace (intstart) [inline, package]
References SimpleTextEngine.SimpleFactory.buffer.
Referenced by SimpleTextEngine.SimpleFactory.getArgument().
                {
                        int depth = 0;
                        while (start < buffer.length())
                        {
                                switch (buffer.charAt(start))
                                {
                                case '{': depth++; break;
                                case '}': depth--; if (depth == 0) return start; break;
                                default: break;
                                }
                                start++;
                        }
                        return -1;
                }
void parse () [inline, package]
References SimpleTextEngine.SimpleFactory.anchor, SimpleTextEngine.SimpleFactory.buffer, SimpleTextEngine.SimpleFactory.builder, SimpleTextEngine.SimpleFactory.current, SimpleTextEngine.SimpleFactory.flush(), SimpleTextEngine.SimpleFactory.getArgument(), SimpleTextEngine.SimpleFactory.getParameter(), SimpleTextEngine.SimpleFactory.getTeXCommand(), SimpleTextEngine.TeXElement.isSymbol(), and SimpleTextEngine.SimpleFactory.list.
Referenced by SimpleTextEngine.LineElement.LineElement().
                {
                        String arg;
                        current = anchor;
                        while (current < buffer.length())
                        {
                                switch (buffer.charAt(current))
                                {
                                case '^':
                                case '_':
                                        flush();
                                        arg = getArgument(current+1);
                                        if (arg != null)
                                        {
                                                if (buffer.charAt(current) == '_')
                                                        list.add(new SubscriptElement(arg));
                                                else if (buffer.charAt(current) == '^')
                                                        list.add(new SuperscriptElement(arg));
                                                current = anchor;
                                                if (list.size() > 1)
                                                {
                                                        Element e1 = (Element)list.get(list.size()-2);
                                                        Element e2 = (Element)list.get(list.size()-1);
                                                        if ((e1 instanceof SubscriptElement && e2 instanceof SuperscriptElement) ||
                                                            (e2 instanceof SubscriptElement && e1 instanceof SuperscriptElement))
                                                        {
                                                                list.remove(list.size()-2);
                                                                list.remove(list.size()-1);
                                                                list.add(new ScriptElement(e1, e2));
                                                        }
                                                }
                                        }
                                        else
                                                current++;
                                        break;
                                case '{':
                                        flush();
                                        arg = getArgument(current);
                                        if (arg != null)
                                                list.add(new LineElement(arg, false));
                                        else
                                                System.err.println('WARNING: unmatched brace '{'');
                                        current = anchor;
                                        break;
                                case '\':
                                        if (current+1 < buffer.length())
                                                switch (buffer.charAt(current+1))
                                                {
                                                        case '\':
                                                        case '{':
                                                        case '}':
                                                        case '_':
                                                        case '^':
                                                                builder.append(buffer.charAt(current+1));
                                                                current = anchor = current+2;
                                                                break;
                                                        default:
                                                                flush();
                                                                arg = getTeXCommand(current+1);
                                                                if (arg != null && arg.length() > 0)
                                                                {
                                                                        if (TeXElement.isSymbol(arg))
                                                                                list.add(new TeXElement(arg));
                                                                        else if (arg.startsWith('it') || arg.startsWith('sl'))
                                                                        {
                                                                                list.add(new TeXFontSwitchCommand(Font.ITALIC));
                                                                                anchor = current+3;
                                                                        }
                                                                        else if (arg.startsWith('bf'))
                                                                        {
                                                                                list.add(new TeXFontSwitchCommand(Font.BOLD));
                                                                                anchor = current+3;
                                                                        }
                                                                        else if (arg.startsWith('rm'))
                                                                        {
                                                                                list.add(new TeXFontSwitchCommand(Font.PLAIN));
                                                                                anchor = current+3;
                                                                        }
                                                                        else if (arg.equals('color'))
                                                                        {
                                                                                String mode = getParameter(anchor, '[', ']');
                                                                                String color = getParameter(anchor, '{', '}');
                                                                                list.add(new TeXFontColorCommand(mode, color));
                                                                        }
                                                                        else if (arg.equals('fontsize'))
                                                                        {
                                                                                String sz = getParameter(anchor, '{', '}');
                                                                                list.add(new TeXFontSizeCommand(sz));
                                                                        }
                                                                        else if (arg.equals('fontname'))
                                                                        {
                                                                                String name = getParameter(anchor, '{', '}');
                                                                                list.add(new TeXFontNameCommand(name));
                                                                        }
                                                                }
                                                                else
                                                                        System.err.println('WARNING: unable to interpret TeX command: ' + buffer.substring(current));
                                                                current = anchor;
                                                                break;
                                                }
                                        else
                                                System.err.println('WARNING: unable to interpret TeX command: ' + buffer.substring(current));
                                        break;
                                default:
                                        builder.append(buffer.charAt(current++));
                                        break;
                                }
                        }
                        flush();
                }
Member Data Documentation
int anchor = 0 [private]
Referenced by SimpleTextEngine.SimpleFactory.flush(), SimpleTextEngine.SimpleFactory.getArgument(), SimpleTextEngine.SimpleFactory.getParameter(), SimpleTextEngine.SimpleFactory.getTeXCommand(), and SimpleTextEngine.SimpleFactory.parse().
String buffer [private]
Referenced by SimpleTextEngine.SimpleFactory.getArgument(), SimpleTextEngine.SimpleFactory.getParameter(), SimpleTextEngine.SimpleFactory.getTeXCommand(), SimpleTextEngine.SimpleFactory.matchBrace(), SimpleTextEngine.SimpleFactory.parse(), and SimpleTextEngine.SimpleFactory.SimpleFactory().
StringBuilder builder [private]
Referenced by SimpleTextEngine.SimpleFactory.flush(), SimpleTextEngine.SimpleFactory.parse(), and SimpleTextEngine.SimpleFactory.SimpleFactory().
int current = 0 [package]
Referenced by SimpleTextEngine.SimpleFactory.flush(), and SimpleTextEngine.SimpleFactory.parse().
LinkedList list [private]
Referenced by SimpleTextEngine.SimpleFactory.flush(), SimpleTextEngine.SimpleFactory.parse(), and SimpleTextEngine.SimpleFactory.SimpleFactory().
Author
Generated automatically by Doxygen for Octave from the source code.