ColorProperty
NAME
ColorProperty -
SYNOPSIS
Inherits Property.
Public Member Functions
ColorProperty (PropertySet parent, String name)
ColorProperty (PropertySet parent, String name, String[] values)
ColorProperty (PropertySet parent, String name, Color color)
ColorProperty (PropertySet parent, String name, String[] values, Object color)
Property cloneProperty ()
Color getColor ()
boolean isSet ()
boolean is (String s)
double[] getArray ()
String toString ()
PropertySet getParent ()
String getName ()
boolean isReadOnly ()
void setReadOnly (boolean flag)
boolean isVisible ()
void setVisible (boolean flag)
Object get ()
void set (Object value) throws PropertyException
void set (Object value, boolean warn_on_exception)
void reset (Object value)
void lock ()
void unLock ()
boolean isSameValue (Object value)
void delete ()
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
Static Public Member Functions
static Property createProperty (PropertySet parent, String name, String type) throws PropertyException
static Property createProperty (PropertySet parent, String name, String type, Object arg) throws PropertyException
Protected Member Functions
ColorProperty (ColorProperty p)
Object convertValue (Object value) throws PropertyException
Object getInternal ()
void initDefault ()
void setInternal (Object value) throws PropertyException
boolean isEqual (Object value)
Protected Attributes
Object pvalue
Private Member Functions
Color decodeColor (String name)
Private Attributes
Set valueSet
Constructor & Destructor Documentation
ColorProperty (ColorPropertyp) [inline, protected]
References ColorProperty.valueSet.
Referenced by ColorProperty.cloneProperty().
        {
                super(p);
                if (p.valueSet != null)
                        this.valueSet = Collections.synchronizedSet(new HashSet(p.valueSet));
        }
ColorProperty (PropertySetparent, Stringname) [inline]
        {
                super(parent, name);
        }
ColorProperty (PropertySetparent, Stringname, String[]values) [inline]
References Property.name, Property.parent, and ColorProperty.valueSet.
        {
                this(parent, name);
                if (values != null)
                {
                        this.valueSet = Collections.synchronizedSet(new HashSet());
                        for (int i=0; i<values.length; i++)
                                this.valueSet.add(values[i]);
                }
                else
                        this.valueSet = null;
        }
ColorProperty (PropertySetparent, Stringname, Colorcolor) [inline]
References Property.name, Property.parent, and Property.pvalue.
        {
                this(parent, name);
                this.pvalue = color;
        }
ColorProperty (PropertySetparent, Stringname, String[]values, Objectcolor) [inline]
References Property.name, Property.parent, and Property.pvalue.
        {
                this(parent, name, values);
                this.pvalue = color;
        }
Member Function Documentation
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and Property.eventSource.
Referenced by HandleObject.listen(), and HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
Property cloneProperty () [inline, virtual]
Implements Property.
References ColorProperty.ColorProperty().
        {
                return new ColorProperty(this);
        }
Object convertValue (Objectvalue) throws PropertyException 	 [inline, protected]
Reimplemented from Property.
References ColorProperty.decodeColor(), and ColorProperty.valueSet.
        {
                Object c = null;
                if (value == null)
                        c = null;
                else if (value instanceof Color)
                        c = value;
                else if (value instanceof String)
                {
                        c = decodeColor((String)value);
                        if (c == null)
                        {
                                if (valueSet.contains((String)value))
                                        c = value;
                                else
                                        throw new PropertyException('invalid color name - ' + value.toString());
                        }
                }
                else if (value instanceof Matrix)
                {
                        Matrix m = (Matrix)value;
                        if (m.isVector() && m.getClassName().equals('double') && m.getLength() == 3)
                        {
                                double[] cv = m.toDouble();
                                c = new Color((float)cv[0], (float)cv[1], (float)cv[2]);
                        }
                        else
                                throw new PropertyException('invalid color value - ' + value.toString());
                }
                else
                {
                        try
                        {
                                double[] cv = (double[])value;
                                if (cv.length == 3)
                                        c = new Color((float)cv[0], (float)cv[1], (float)cv[2]);
                        }
                        catch (ClassCastException e) { }
                        if (c == null)
                                throw new PropertyException('invalid color value - ' + value.toString());
                }
                
                return c;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype) throws PropertyException 	 [inline, static, inherited]
References Property.name, and Property.parent.
Referenced by Property.createProperty().
        {
                if (type.equals('double'))
                        return new DoubleProperty(parent, name);
                else if (type.equals('string'))
                        return new StringProperty(parent, name);
                return null;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype, Objectarg) throws PropertyException 	 [inline, static, inherited]
References Property.createProperty(), Property.name, Property.parent, and Property.set().
        {
                if (type.equals('radio'))
                {
                        String[] values = ((String)arg).split('|');
                        return new RadioProperty(parent, name, values, '');
                }
                else
                {
                        Property p = createProperty(parent, name, type);
                        if (p != null)
                                p.set(arg);
                        return p;
                }
        }
Color decodeColor (Stringname) [inline, private]
Referenced by ColorProperty.convertValue().
        {
                if (name.length() == 1)
                        switch (name.charAt(0))
                        {
                        case 'r': return Color.red;
                        case 'c': return Color.cyan;
                        case 'y': return Color.yellow;
                        case 'g': return Color.green;
                        case 'm': return Color.magenta;
                        case 'k': return Color.black;
                        case 'b': return Color.blue;
                        case 'w': return Color.white;
                        }
                else
                {
                        name = name.toLowerCase();
                        if ('white'.startsWith(name))
                                return Color.white;
                        else if ('red'.startsWith(name))
                                return Color.red;
                        else if ('yellow'.startsWith(name))
                                return Color.yellow;
                        else if ('blue'.startsWith(name))
                                return Color.blue;
                        else if ('magenta'.startsWith(name))
                                return Color.magenta;
                        else if ('green'.startsWith(name))
                                return Color.green;
                        else if ('cyan'.startsWith(name))
                                return Color.cyan;
                }
                return null;
        }
void delete () [inline, inherited]
References HandleEventSourceHelper.delete(), and Property.eventSource.
        {
                eventSource.delete();
        }
Object get () [inline, inherited]
Reimplemented in NotImplProperty.
References Property.getInternal().
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), AxesObject.doZoom(), HandleObject.get(), LegendObject.LegendObject(), LegendObject.makeItemFromLine(), LegendObject.propertyChanged(), UnwindHandleObject.swapValues(), and CheckBoxControl.update().
        {
                /* TODO: needed?
                if (!lockNotify)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((PropertyListener)it.next()).propertyGetting(this);
                }
                */
                return getInternal();
        }
double [] getArray () [inline]
References ColorProperty.getColor(), and ColorProperty.isSet().
Referenced by GLRenderer.draw(), and ColorProperty.getInternal().
        {
                if (isSet())
                {
                        Color c = getColor();
                        return new double[] {c.getRed()/255.0, c.getGreen()/255.0, c.getBlue()/255.0};
                }
                else
                        return null;
        }
Color getColor () [inline]
References ColorProperty.isSet(), and Property.pvalue.
Referenced by FigureObject.createFigure(), J2DRenderer.draw(), GLRenderer.draw(), AxesObject.draw(), Edit2Control.Edit2Control(), ColorProperty.getArray(), UIPanelObject.getBackgroundColor(), FigureObject.getBackgroundColor(), UIControlAdapter.init(), UIPanelObject.makeBorder(), UIPanelObject.makePanel(), FigureObject.print(), Edit2Control.propertyChanged(), UIControlAdapter.propertyChanged(), UIPanelObject.propertyChanged(), TextObject.toPostScript(), ListBoxControl.updateColors(), and TextObject.updateData().
        {
                return (isSet() ? (Color)pvalue : null);
        }
Object getInternal () [inline, protected]
Reimplemented from Property.
References ColorProperty.getArray(), ColorProperty.isSet(), and Property.pvalue.
        {
                return (isSet() ? getArray() : pvalue);
        }
String getName () [inline, inherited]
References Property.name.
Referenced by PropertySet.addProperty(), AxesObject.autoAxis(), NotImplProperty.get(), PropertySet.getNames(), NotImplProperty.set(), Property.set(), and PropertySet.show().
        {
                return name;
        }
PropertySet getParent () [inline, inherited]
References Property.parent.
Referenced by CallbackProperty.execute(), NotImplProperty.get(), Property.initDefault(), HandleObject.listen(), NotImplProperty.set(), and Property.set().
        {
                return parent;
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.hasHandleEvent().
        {
                return eventSource.hasHandleEvent(name);
        }
void initDefault () [inline, protected, inherited]
References HandleObject.getDefaultProperty(), Property.getParent(), HandleObject.getType(), Property.name, Property.parent, and Property.pvalue.
Referenced by Property.Property().
        {
                HandleObject parent = (HandleObject)getParent();
                String defname = 'default' + parent.getType() + name;
                Property p = parent.getDefaultProperty(defname);
                if (p != null)
                        pvalue = p.pvalue;
        }
boolean is (Strings) [inline]
References ColorProperty.isSet(), and Property.pvalue.
Referenced by PatchObject.checkConsistency(), GLRenderer.draw(), and AxesObject.draw().
        {
                return (!isSet() && pvalue != null && ((String)pvalue).equalsIgnoreCase(s));
        }
boolean isEqual (Objectvalue) [inline, protected, inherited]
Reimplemented in TextProperty.
References Property.pvalue.
Referenced by Property.isSameValue(), and Property.set().
        {
                /*Object v = getInternal();*/
                Object v = pvalue;
                return (value == null ? v == null : value.equals(v));
        }
boolean isReadOnly () [inline, inherited]
References Property.readOnly.
        {
                return readOnly;
        }
boolean isSameValue (Objectvalue) [inline, inherited]
References Property.convertValue(), and Property.isEqual().
Referenced by HandleObject.waitFor().
        {
                try
                {
                        value = convertValue(value);
                        return isEqual(value);
                }
                catch (PropertyException e)
                {
                        return false;
                }
        }
boolean isSet () [inline]
References Property.pvalue.
Referenced by PatchObject.checkConsistency(), GLRenderer.draw(), ColorProperty.getArray(), ColorProperty.getColor(), ColorProperty.getInternal(), ColorProperty.is(), TextObject.toPostScript(), ColorProperty.toString(), and TextObject.updateData().
        {
                return (pvalue instanceof Color);
        }
boolean isVisible () [inline, inherited]
References Property.visible.
Referenced by PropertySet.getNames(), and PropertySet.show().
        {
                return visible;
        }
void lock () [inline, inherited]
References Property.lockNotify.
        {
                lockNotify = true;
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
        {
                eventSource.removeHandleEventSink(sink);
        }
void reset (Objectvalue) [inline, inherited]
References Property.lockNotify.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), ColorbarObject.buildColorbar(), LegendObject.buildLegend(), ColorbarObject.ColorbarObject(), HandleObject.delete(), LegendObject.doLayout(), AxesObject.draw(), AxesObject.getBaseLine(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), PatchObject.PatchObject(), FigureObject.print(), LineObject.propertyChanged(), BarseriesObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.reset(), GraphicObject.set(), SurfaceObject.SurfaceObject(), UnwindHandleObject.swapValues(), TextObject.TextObject(), CheckBoxControl.update(), EditControl.update(), PopupMenuControl.update(), Edit2Control.update(), ListBoxControl.update(), AxesObject.updateXFormMatrices(), LineObject.validate(), SurfaceObject.validate(), and PatchObject.validate().
        {
                boolean oldLockNotify = lockNotify;
                lockNotify = true;
                try { set(value); }
                catch (PropertyException e)
                {
                        System.err.println('WARNING: exception during property reset: ' + e);
                }
                lockNotify = oldLockNotify;
        }
void set (Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in BooleanProperty, and NotImplProperty.
References Property.convertValue(), Property.eventSource, HandleEventSourceHelper.fireEvent(), Property.getName(), Property.getParent(), Property.isEqual(), Property.lockNotify, Property.readOnly, Property.setFlag, and Property.setInternal().
Referenced by HandleObject.autoSet(), BarseriesObject.BarseriesObject(), ColorbarObject.buildColorbar(), Property.createProperty(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), BarseriesObject.propertyChanged(), LegendObject.propertyChanged(), PatchObject.propertyChanged(), AxesObject.propertyChanged(), HandleObject.set(), AxesObject.unZoom(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), SurfaceObject.updateColorMinMax(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
        {
                if (readOnly)
                        throw new PropertyException('read-only property - ' + getName());
                value = convertValue(value);
                if (isEqual(value))
                {
                        //System.out.println(getName() + ': identical value, not setting - ' + value.toString());
                        return;
                }
                if (setFlag)
                {
                        System.out.println('WARNING: ' + getName() + '.set (' + ((HandleObject)getParent()).getHandle() + '): recursive behavior detected, not setting');
                        Thread.dumpStack();
                        return;
                }
                setFlag = true;
                try
                {
                        /* TODO: needed?
                        if (!lockNotify)
                        {
                                Iterator it = listenerList.iterator();
                                while (it.hasNext())
                                        ((PropertyListener)it.next()).propertySetting(this, value);
                        }
                        */
                        setInternal(value);
                        if (!lockNotify)
                        {
                                eventSource.fireEvent('PropertyChanged');
                        }
                        setFlag = false;
                }
                catch (Exception e)
                {
                        setFlag = false;
                        if (e instanceof PropertyException)
                                throw (PropertyException)e;
                        else
                                throw new PropertyException(e);
                }
        }
void set (Objectvalue, booleanwarn_on_exception) [inline, inherited]
References Property.getName().
        {
                try { set(value); }
                catch (PropertyException e)
                {
                        if (warn_on_exception)
                        {
                                System.out.println('WARNING: ' + getName() + '.set: exception occured');
                                e.printStackTrace();
                        }
                }
        }
void setInternal (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented in ArrayProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.set().
        {
                pvalue = value;
        }
void setReadOnly (booleanflag) [inline, inherited]
References Property.readOnly.
        {
                readOnly = flag;
        }
void setVisible (booleanflag) [inline, inherited]
References Property.visible.
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), FigureObject.FigureObject(), GraphicObject.GraphicObject(), and PatchObject.PatchObject().
        {
                visible = flag;
        }
String toString () [inline]
References ColorProperty.isSet(), and Property.pvalue.
        {
                if (isSet())
                {
                        DecimalFormat fmt = new DecimalFormat('0.0000 ');
                        Color c = (Color)pvalue;
                        return (
                                '[ ' +
                                fmt.format(c.getRed()/255.0) +
                                fmt.format(c.getGreen()/255.0) +
                                fmt.format(c.getBlue()/255.0) +
                                ']');
                }
                else if (pvalue != null)
                        return pvalue.toString();
                else
                        return '<not set>';
        }
void unLock () [inline, inherited]
References Property.lockNotify.
Referenced by HandleObject.addProperty(), and PropertySet.validate().
        {
                lockNotify = false;
        }
Member Data Documentation
Object pvalue [protected, inherited]
Referenced by HandleObjectListProperty.addElement(), ArrayProperty.ArrayProperty(), BooleanProperty.BooleanProperty(), CallbackProperty.CallbackProperty(), ColorProperty.ColorProperty(), HandleObjectListProperty.contains(), DoubleProperty.DoubleProperty(), DoubleRadioProperty.DoubleRadioProperty(), DoubleProperty.doubleValue(), DoubleRadioProperty.doubleValue(), HandleObjectListProperty.elementAt(), DoubleProperty.floatValue(), StringArrayProperty.getArray(), CallbackProperty.getCallback(), ArrayProperty.getClassName(), ColorProperty.getColor(), ArrayProperty.getDim(), TextProperty.getInternal(), Property.getInternal(), ColorProperty.getInternal(), ArrayProperty.getMatrix(), ArrayProperty.getNDims(), ObjectProperty.getObject(), TextProperty.getText(), RadioProperty.getValue(), VectorProperty.getVector(), HandleObjectListProperty.getVisibleObjects(), HandleObjectListProperty.HandleObjectListProperty(), Property.initDefault(), DoubleProperty.intValue(), DoubleRadioProperty.is(), ColorProperty.is(), DoubleRadioProperty.isDouble(), ArrayProperty.isEmpty(), TextProperty.isEqual(), Property.isEqual(), ColorProperty.isSet(), HandleObjectListProperty.iterator(), LineStyleProperty.LineStyleProperty(), MarkerProperty.MarkerProperty(), ObjectProperty.ObjectProperty(), Property.Property(), RadioProperty.RadioProperty(), HandleObjectListProperty.removeAllElements(), HandleObjectListProperty.removeElement(), TextProperty.setInternal(), Property.setInternal(), HandleObjectListProperty.size(), StringArrayProperty.StringArrayProperty(), StringProperty.StringProperty(), TextProperty.TextProperty(), StringProperty.toString(), ObjectProperty.toString(), RadioProperty.toString(), DoubleRadioProperty.toString(), VectorProperty.toString(), ArrayProperty.toString(), ColorProperty.toString(), and VectorProperty.VectorProperty().
Set valueSet [private]
Referenced by ColorProperty.ColorProperty(), and ColorProperty.convertValue().
Author
Generated automatically by Doxygen for Octave from the source code.