SimpleTextEngine
NAME
SimpleTextEngine -
SYNOPSIS
Classes
class Content
class Element
class Layouter
class LineElement
class PSTextRenderer
class ScriptElement
class SimpleFactory
class SubscriptElement
class SuperscriptElement
class TeXElement
class TeXFontColorCommand
class TeXFontCommand
class TeXFontNameCommand
class TeXFontSizeCommand
class TeXFontSwitchCommand
interface TextRenderer
Static Public Member Functions
static Rectangle drawAsImage (RenderCanvas comp, Font f, String txt, double[] pos, int halign, int valign)
Member Function Documentation
static Rectangle drawAsImage (RenderCanvascomp, Fontf, Stringtxt, double[]pos, inthalign, intvalign) [inline, static]
References Renderer.drawBitmap(), RenderCanvas.getRenderer(), SimpleTextEngine.Content.layout(), and SimpleTextEngine.Content.render().
Referenced by GLRenderer.drawText().
        {
                // create internal image
                int margin = 0;
                Content content = new Content(txt);
                Rectangle r = (Rectangle)content.layout(comp, f).clone();
                if (r.width <=0 || r.height <= 0)
                        return new Rectangle();
                r.width += 2*margin;
                r.height += 2*margin;
                BufferedImage img = new BufferedImage(r.width, r.height, BufferedImage.TYPE_BYTE_BINARY);
                // draw string
                Graphics g = img.getGraphics();
                g.setFont(f);
                g.translate(margin, margin);
                content.render((Graphics2D)g);
                g.dispose();
                com.sun.opengl.util.ImageUtil.flipImageVertically(img);
                // compute offsets
                int xoff, yoff;
                switch (halign)
                {
                default:
                case 0: xoff = 0; break;
                case 1: xoff = -r.width/2; break;
                case 2: xoff = -r.width; break;
                }
                switch (valign)
                {
                default:
                case 0: yoff = 0; break;
                case 1: yoff = -r.height/2; break;
                case 2: yoff = -r.height; break;
                }
                // render to canvas
                comp.getRenderer().drawBitmap(img, pos, xoff, yoff);
                // return value
                return r;
        }
Author
Generated automatically by Doxygen for Octave from the source code.