.TH "RadioProperty.StringComparator" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RadioProperty.StringComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComparator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBcompare\fP (Object o1, Object o2)"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBStringComparator\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBStringComparator\fP ()\fC [inline, package]\fP"
.PP
.nf
                {
                }
.fi
.SH "Member Function Documentation"
.PP 
.SS "int \fBcompare\fP (Objecto1, Objecto2)\fC [inline]\fP"
.PP
.nf
                {
                        return ((String)o1)\&.compareToIgnoreCase((String)o2);
                }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
