RenderCanvas
NAME
RenderCanvas -
SYNOPSIS
Inherited by GLRenderCanvas, and J2DRenderCanvas.
Classes
interface Container
Public Member Functions
void addRenderEventListener (RenderEventListener l)
void removeRenderEventListener (RenderEventListener l)
void addMouseListener (MouseListener l)
void removeMouseListener (MouseListener l)
void addMouseMotionListener (MouseMotionListener l)
void removeMouseMotionListener (MouseMotionListener l)
void redraw ()
int getWidth ()
int getHeight ()
int getX ()
int getY ()
Renderer getRenderer ()
Component getComponent ()
BufferedImage toImage ()
void toPostScript (String filename)
Font getFont ()
FontMetrics getFontMetrics (Font fnt)
Member Function Documentation
void addMouseListener (MouseListenerl)
Referenced by AxesContainer.createCanvas().
void addMouseMotionListener (MouseMotionListenerl)
Referenced by AxesContainer.createCanvas().
void addRenderEventListener (RenderEventListenerl)
Implemented in GLRenderCanvas, and J2DRenderCanvas.
Referenced by AxesContainer.createCanvas().
Component getComponent ()
Implemented in GLRenderCanvas, and J2DRenderCanvas.
Referenced by AxesContainer.createCanvas(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.getBoundingBox(), AxesObject.getOuterBoundingBox(), AxesObject.propertyChanged(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), AxesContainer.updateCanvas(), AxesObject.updateOuterPosition(), and AxesObject.updatePosition().
Font getFont ()
Referenced by LegendObject.doLayout(), and J2DRenderer.drawText().
FontMetrics getFontMetrics (Fontfnt)
Referenced by LegendObject.doLayout(), SimpleTextEngine.Layouter.getFontMetrics(), AxesObject.updateOuterPosition(), and AxesObject.updatePosition().
int getHeight ()
Referenced by ColorbarObject.buildColorbar(), J2DRenderer.clear(), AxesObject.convertUnits(), LegendObject.doLayout(), J2DRenderer.draw(), TextObject.getExtent(), AxesContainer.getObjectForPoint(), GLRenderCanvas.toImage(), TextObject.updateData(), and AxesObject.updateXFormMatrices().
Renderer getRenderer ()
Implemented in GLRenderCanvas, and J2DRenderCanvas.
Referenced by AxesContainer.display(), SimpleTextEngine.drawAsImage(), and AxesObject.drawZoomBox().
int getWidth ()
Referenced by ColorbarObject.buildColorbar(), J2DRenderer.clear(), LegendObject.doLayout(), and GLRenderCanvas.toImage().
int getX ()
Referenced by AxesContainer.getMouseLocation(), and AxesContainer.getObjectForPoint().
int getY ()
Referenced by AxesContainer.getMouseLocation(), and AxesContainer.getObjectForPoint().
void redraw ()
Implemented in GLRenderCanvas, and J2DRenderCanvas.
Referenced by AxesObject.doZoom(), AxesObject.operation(), FigureObject.print(), and AxesObject.unZoom().
void removeMouseListener (MouseListenerl)
Referenced by AxesContainer.updateCanvas().
void removeMouseMotionListener (MouseMotionListenerl)
Referenced by AxesContainer.updateCanvas().
void removeRenderEventListener (RenderEventListenerl)
Implemented in GLRenderCanvas, and J2DRenderCanvas.
Referenced by AxesContainer.updateCanvas().
BufferedImage toImage ()
Implemented in GLRenderCanvas, and J2DRenderCanvas.
Referenced by FigureObject.print().
void toPostScript (Stringfilename)
Implemented in GLRenderCanvas, and J2DRenderCanvas.
Referenced by FigureObject.print().
Author
Generated automatically by Doxygen for Octave from the source code.