VectorProperty
NAME
VectorProperty -
SYNOPSIS
Inherits Property.
Public Member Functions
VectorProperty (PropertySet parent, String name, int size)
VectorProperty (PropertySet parent, String name, int size, double[] data)
VectorProperty (PropertySet parent, String name, int size, Matrix data)
Property cloneProperty ()
boolean isEmpty ()
double[] getVector ()
double[] getArray ()
double elementAt (int index)
String toString ()
PropertySet getParent ()
String getName ()
boolean isReadOnly ()
void setReadOnly (boolean flag)
boolean isVisible ()
void setVisible (boolean flag)
Object get ()
void set (Object value) throws PropertyException
void set (Object value, boolean warn_on_exception)
void reset (Object value)
void lock ()
void unLock ()
boolean isSameValue (Object value)
void delete ()
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
Static Public Member Functions
static Property createProperty (PropertySet parent, String name, String type) throws PropertyException
static Property createProperty (PropertySet parent, String name, String type, Object arg) throws PropertyException
Protected Member Functions
VectorProperty (VectorProperty p)
Object convertValue (Object value) throws PropertyException
void initDefault ()
Object getInternal ()
void setInternal (Object value) throws PropertyException
boolean isEqual (Object value)
Protected Attributes
Object pvalue
Package Attributes
int fixedSize
Constructor & Destructor Documentation
VectorProperty (VectorPropertyp) [inline, protected]
References VectorProperty.fixedSize.
Referenced by VectorProperty.cloneProperty().
        {
                super(p);
                this.fixedSize = p.fixedSize;
        }
VectorProperty (PropertySetparent, Stringname, intsize) [inline]
References VectorProperty.fixedSize.
        {
                super(parent, name);
                this.fixedSize = size;
        }
VectorProperty (PropertySetparent, Stringname, intsize, double[]data) [inline]
References Property.name, and Property.parent.
        {
                this(parent, name, size, new Matrix(data));
        }
VectorProperty (PropertySetparent, Stringname, intsize, Matrixdata) [inline]
References Property.name, Property.parent, and Property.pvalue.
        {
                this(parent, name, size);
                if (data.isVector())
                        this.pvalue = data;
                else
                {
                        System.out.println('Warning: ' + name + ': assigning non-vector to vector property');
                        this.pvalue = new Matrix(new double[0]);
                }
        }
Member Function Documentation
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and Property.eventSource.
Referenced by HandleObject.listen(), and HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
Property cloneProperty () [inline, virtual]
Implements Property.
References VectorProperty.VectorProperty().
        {
                return new VectorProperty(this);
        }
Object convertValue (Objectvalue) throws PropertyException 	 [inline, protected]
Reimplemented from Property.
References VectorProperty.fixedSize.
        {
                if (value instanceof Number)
                        return new Matrix(new double[] {((Number)value).doubleValue()}, new int[] {1, 1});
                else if (value instanceof Matrix)
                {
                        Matrix m = (Matrix)value;
                        if (m.getClassName().equals('double'))
                        {
                                if (m.getNDims() == 1 ||
                                    (m.getNDims() == 2 && (m.getDim(0) == 1 || m.getDim(1) == 1)))
                                {
                                        if (fixedSize == -1 || fixedSize == m.toDouble().length)
                                                return m;
                                        else
                                                throw new PropertyException('invalid vector length - ' + value.toString());
                                }
                                else
                                        throw new PropertyException('invalid vector value - ' + value.toString());
                        }
                        else
                                throw new PropertyException('invalid vector element type - ' + value.toString());
                }
                try
                {
                        double[] v = (value == null ? new double[0] : (double[])value);
                        if (fixedSize == -1 || fixedSize == v.length)
                                return new Matrix(v);
                        else
                                throw new PropertyException('invalid vector length (' + v.length + ') - ' + value.toString());
                }
                catch (ClassCastException e)
                {
                        throw new PropertyException('invalid vector value - ' + value.toString());
                }
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype) throws PropertyException 	 [inline, static, inherited]
References Property.name, and Property.parent.
Referenced by Property.createProperty().
        {
                if (type.equals('double'))
                        return new DoubleProperty(parent, name);
                else if (type.equals('string'))
                        return new StringProperty(parent, name);
                return null;
        }
static Property createProperty (PropertySetparent, Stringname, Stringtype, Objectarg) throws PropertyException 	 [inline, static, inherited]
References Property.createProperty(), Property.name, Property.parent, and Property.set().
        {
                if (type.equals('radio'))
                {
                        String[] values = ((String)arg).split('|');
                        return new RadioProperty(parent, name, values, '');
                }
                else
                {
                        Property p = createProperty(parent, name, type);
                        if (p != null)
                                p.set(arg);
                        return p;
                }
        }
void delete () [inline, inherited]
References HandleEventSourceHelper.delete(), and Property.eventSource.
        {
                eventSource.delete();
        }
double elementAt (intindex) [inline]
References VectorProperty.getVector().
Referenced by AxesObject.autoAspectRatio().
        {
                return getVector()[index];
        }
Object get () [inline, inherited]
Reimplemented in NotImplProperty.
References Property.getInternal().
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), AxesObject.doZoom(), HandleObject.get(), LegendObject.LegendObject(), LegendObject.makeItemFromLine(), LegendObject.propertyChanged(), UnwindHandleObject.swapValues(), and CheckBoxControl.update().
        {
                /* TODO: needed?
                if (!lockNotify)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((PropertyListener)it.next()).propertyGetting(this);
                }
                */
                return getInternal();
        }
double [] getArray () [inline]
References VectorProperty.getVector().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), ColorbarObject.buildColorbar(), AxesObject.computeAutoTickLabels(), AxesObject.computeMinorTicks(), AxesObject.convertCData(), AxesObject.convertCDataToIndex(), BarseriesObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), J2DRenderer.draw(), GLRenderer.draw(), AxesObject.draw(), TextObject.drawAsImage(), Utils.getAlphaData(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), AxesObject.getBoundingBox(), AxesObject.getOuterBoundingBox(), UIControlObject.getPosition(), UIPanelObject.getPosition(), LineObject.LineObject(), AxesObject.operation(), CheckBoxControl.propertyChanged(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), TextObject.propertyChanged(), AxesObject.propertyChanged(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), TextObject.updateMinMax(), AxesObject.updateOuterPosition(), AxesObject.updatePosition(), PopupMenuControl.updateValue(), ListBoxControl.updateValue(), and AxesObject.updateXFormMatrices().
        {
                return getVector();
        }
Object getInternal () [inline, protected, inherited]
Reimplemented in ColorProperty, CallbackProperty, HandleObjectListProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.get().
        {
                return pvalue;
        }
String getName () [inline, inherited]
References Property.name.
Referenced by PropertySet.addProperty(), AxesObject.autoAxis(), NotImplProperty.get(), PropertySet.getNames(), NotImplProperty.set(), Property.set(), and PropertySet.show().
        {
                return name;
        }
PropertySet getParent () [inline, inherited]
References Property.parent.
Referenced by CallbackProperty.execute(), NotImplProperty.get(), Property.initDefault(), HandleObject.listen(), NotImplProperty.set(), and Property.set().
        {
                return parent;
        }
double [] getVector () [inline]
References Property.pvalue.
Referenced by VectorProperty.elementAt(), VectorProperty.getArray(), VectorProperty.isEmpty(), and FigureObject.updateFramePosition().
        {
                return ((Matrix)pvalue).toDouble();
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.hasHandleEvent().
        {
                return eventSource.hasHandleEvent(name);
        }
void initDefault () [inline, protected, inherited]
References HandleObject.getDefaultProperty(), Property.getParent(), HandleObject.getType(), Property.name, Property.parent, and Property.pvalue.
Referenced by Property.Property().
        {
                HandleObject parent = (HandleObject)getParent();
                String defname = 'default' + parent.getType() + name;
                Property p = parent.getDefaultProperty(defname);
                if (p != null)
                        pvalue = p.pvalue;
        }
boolean isEmpty () [inline]
References VectorProperty.getVector().
Referenced by LineObject.propertyChanged(), and LineObject.validate().
        {
                double[] v = getVector();
                return (v == null || v.length <= 0);
        }
boolean isEqual (Objectvalue) [inline, protected, inherited]
Reimplemented in TextProperty.
References Property.pvalue.
Referenced by Property.isSameValue(), and Property.set().
        {
                /*Object v = getInternal();*/
                Object v = pvalue;
                return (value == null ? v == null : value.equals(v));
        }
boolean isReadOnly () [inline, inherited]
References Property.readOnly.
        {
                return readOnly;
        }
boolean isSameValue (Objectvalue) [inline, inherited]
References Property.convertValue(), and Property.isEqual().
Referenced by HandleObject.waitFor().
        {
                try
                {
                        value = convertValue(value);
                        return isEqual(value);
                }
                catch (PropertyException e)
                {
                        return false;
                }
        }
boolean isVisible () [inline, inherited]
References Property.visible.
Referenced by PropertySet.getNames(), and PropertySet.show().
        {
                return visible;
        }
void lock () [inline, inherited]
References Property.lockNotify.
        {
                lockNotify = true;
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References Property.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
        {
                eventSource.removeHandleEventSink(sink);
        }
void reset (Objectvalue) [inline, inherited]
References Property.lockNotify.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), ColorbarObject.buildColorbar(), LegendObject.buildLegend(), ColorbarObject.ColorbarObject(), HandleObject.delete(), LegendObject.doLayout(), AxesObject.draw(), AxesObject.getBaseLine(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), LegendObject.makeItemFromLine(), AxesObject.makeTextObject(), PatchObject.PatchObject(), FigureObject.print(), LineObject.propertyChanged(), BarseriesObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.reset(), GraphicObject.set(), SurfaceObject.SurfaceObject(), UnwindHandleObject.swapValues(), TextObject.TextObject(), CheckBoxControl.update(), EditControl.update(), PopupMenuControl.update(), Edit2Control.update(), ListBoxControl.update(), AxesObject.updateXFormMatrices(), LineObject.validate(), SurfaceObject.validate(), and PatchObject.validate().
        {
                boolean oldLockNotify = lockNotify;
                lockNotify = true;
                try { set(value); }
                catch (PropertyException e)
                {
                        System.err.println('WARNING: exception during property reset: ' + e);
                }
                lockNotify = oldLockNotify;
        }
void set (Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in BooleanProperty, and NotImplProperty.
References Property.convertValue(), Property.eventSource, HandleEventSourceHelper.fireEvent(), Property.getName(), Property.getParent(), Property.isEqual(), Property.lockNotify, Property.readOnly, Property.setFlag, and Property.setInternal().
Referenced by HandleObject.autoSet(), BarseriesObject.BarseriesObject(), ColorbarObject.buildColorbar(), Property.createProperty(), BarseriesObject.doLayout(), LegendObject.doLayout(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), UIControlObject.propertyChanged(), UIPanelObject.propertyChanged(), BarseriesObject.propertyChanged(), LegendObject.propertyChanged(), PatchObject.propertyChanged(), AxesObject.propertyChanged(), HandleObject.set(), AxesObject.unZoom(), ColorbarObject.updateActivePosition(), LegendObject.updateActivePosition(), SurfaceObject.updateColorMinMax(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
        {
                if (readOnly)
                        throw new PropertyException('read-only property - ' + getName());
                value = convertValue(value);
                if (isEqual(value))
                {
                        //System.out.println(getName() + ': identical value, not setting - ' + value.toString());
                        return;
                }
                if (setFlag)
                {
                        System.out.println('WARNING: ' + getName() + '.set (' + ((HandleObject)getParent()).getHandle() + '): recursive behavior detected, not setting');
                        Thread.dumpStack();
                        return;
                }
                setFlag = true;
                try
                {
                        /* TODO: needed?
                        if (!lockNotify)
                        {
                                Iterator it = listenerList.iterator();
                                while (it.hasNext())
                                        ((PropertyListener)it.next()).propertySetting(this, value);
                        }
                        */
                        setInternal(value);
                        if (!lockNotify)
                        {
                                eventSource.fireEvent('PropertyChanged');
                        }
                        setFlag = false;
                }
                catch (Exception e)
                {
                        setFlag = false;
                        if (e instanceof PropertyException)
                                throw (PropertyException)e;
                        else
                                throw new PropertyException(e);
                }
        }
void set (Objectvalue, booleanwarn_on_exception) [inline, inherited]
References Property.getName().
        {
                try { set(value); }
                catch (PropertyException e)
                {
                        if (warn_on_exception)
                        {
                                System.out.println('WARNING: ' + getName() + '.set: exception occured');
                                e.printStackTrace();
                        }
                }
        }
void setInternal (Objectvalue) throws PropertyException 	 [inline, protected, inherited]
Reimplemented in ArrayProperty, and TextProperty.
References Property.pvalue.
Referenced by Property.set().
        {
                pvalue = value;
        }
void setReadOnly (booleanflag) [inline, inherited]
References Property.readOnly.
        {
                readOnly = flag;
        }
void setVisible (booleanflag) [inline, inherited]
References Property.visible.
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), FigureObject.FigureObject(), GraphicObject.GraphicObject(), and PatchObject.PatchObject().
        {
                visible = flag;
        }
String toString () [inline]
References Property.pvalue.
        {
                return pvalue.toString();
        }
void unLock () [inline, inherited]
References Property.lockNotify.
Referenced by HandleObject.addProperty(), and PropertySet.validate().
        {
                lockNotify = false;
        }
Member Data Documentation
int fixedSize [package]
Referenced by VectorProperty.convertValue(), and VectorProperty.VectorProperty().
Object pvalue [protected, inherited]
Referenced by HandleObjectListProperty.addElement(), ArrayProperty.ArrayProperty(), BooleanProperty.BooleanProperty(), CallbackProperty.CallbackProperty(), ColorProperty.ColorProperty(), HandleObjectListProperty.contains(), DoubleProperty.DoubleProperty(), DoubleRadioProperty.DoubleRadioProperty(), DoubleProperty.doubleValue(), DoubleRadioProperty.doubleValue(), HandleObjectListProperty.elementAt(), DoubleProperty.floatValue(), StringArrayProperty.getArray(), CallbackProperty.getCallback(), ArrayProperty.getClassName(), ColorProperty.getColor(), ArrayProperty.getDim(), TextProperty.getInternal(), Property.getInternal(), ColorProperty.getInternal(), ArrayProperty.getMatrix(), ArrayProperty.getNDims(), ObjectProperty.getObject(), TextProperty.getText(), RadioProperty.getValue(), VectorProperty.getVector(), HandleObjectListProperty.getVisibleObjects(), HandleObjectListProperty.HandleObjectListProperty(), Property.initDefault(), DoubleProperty.intValue(), DoubleRadioProperty.is(), ColorProperty.is(), DoubleRadioProperty.isDouble(), ArrayProperty.isEmpty(), TextProperty.isEqual(), Property.isEqual(), ColorProperty.isSet(), HandleObjectListProperty.iterator(), LineStyleProperty.LineStyleProperty(), MarkerProperty.MarkerProperty(), ObjectProperty.ObjectProperty(), Property.Property(), RadioProperty.RadioProperty(), HandleObjectListProperty.removeAllElements(), HandleObjectListProperty.removeElement(), TextProperty.setInternal(), Property.setInternal(), HandleObjectListProperty.size(), StringArrayProperty.StringArrayProperty(), StringProperty.StringProperty(), TextProperty.TextProperty(), ObjectProperty.toString(), StringProperty.toString(), RadioProperty.toString(), DoubleRadioProperty.toString(), VectorProperty.toString(), ArrayProperty.toString(), ColorProperty.toString(), and VectorProperty.VectorProperty().
Author
Generated automatically by Doxygen for Octave from the source code.