SimpleTextEngine.Element
NAME
SimpleTextEngine.Element -
SYNOPSIS
Inherited by SimpleTextEngine.Content, SimpleTextEngine.LineElement, SimpleTextEngine.ScriptElement, SimpleTextEngine.TeXElement, and SimpleTextEngine.TeXFontCommand.
Package Functions
Element (String txt)
void render (Graphics2D g)
Rectangle layout (RenderCanvas comp, Font font)
Rectangle layout (Layouter l)
void render (TextRenderer r)
Package Attributes
String text
Rectangle rect
Constructor & Destructor Documentation
Element (Stringtxt) [inline, package]
References SimpleTextEngine.Element.rect, and SimpleTextEngine.Element.text.
Referenced by SimpleTextEngine.LineElement.layout(), and SimpleTextEngine.LineElement.render().
                {
                        text = txt;
                        rect = new Rectangle();
                }
Member Function Documentation
Rectangle layout (RenderCanvascomp, Fontfont) [inline, package]
Referenced by SimpleTextEngine.LineElement.layout(), and SimpleTextEngine.ScriptElement.layout().
                {
                        return layout(new Layouter(comp, font));
                }
Rectangle layout (Layouterl) [inline, package]
Reimplemented in SimpleTextEngine.Content, SimpleTextEngine.TeXElement, SimpleTextEngine.TeXFontCommand, SimpleTextEngine.ScriptElement, SimpleTextEngine.SuperscriptElement, SimpleTextEngine.SubscriptElement, and SimpleTextEngine.LineElement.
References SimpleTextEngine.Layouter.getFontMetrics(), SimpleTextEngine.Element.rect, and SimpleTextEngine.Element.text.
                {
                        FontMetrics fm = l.getFontMetrics();
                        rect = new Rectangle(0, -fm.getMaxDescent(), fm.stringWidth(text), fm.getMaxDescent()+fm.getMaxAscent());
                        return rect;
                }
void render (Graphics2Dg) [inline, package]
Reimplemented in SimpleTextEngine.Content, SimpleTextEngine.TeXElement, SimpleTextEngine.TeXFontCommand, SimpleTextEngine.ScriptElement, SimpleTextEngine.SuperscriptElement, SimpleTextEngine.SubscriptElement, and SimpleTextEngine.LineElement.
References SimpleTextEngine.Element.text.
Referenced by SimpleTextEngine.PSTextRenderer.render(), SimpleTextEngine.LineElement.render(), and SimpleTextEngine.ScriptElement.render().
                {
                        g.drawString(text, 0, 0);
                }
void render (TextRendererr) [inline, package]
Reimplemented in SimpleTextEngine.Content, SimpleTextEngine.TeXElement, SimpleTextEngine.TeXFontCommand, SimpleTextEngine.ScriptElement, SimpleTextEngine.SuperscriptElement, SimpleTextEngine.SubscriptElement, and SimpleTextEngine.LineElement.
References SimpleTextEngine.TextRenderer.render().
{ r.render(this); }
Member Data Documentation
Rectangle rect [package]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.LineElement.layout(), SimpleTextEngine.SubscriptElement.layout(), SimpleTextEngine.SuperscriptElement.layout(), SimpleTextEngine.ScriptElement.layout(), SimpleTextEngine.TeXFontCommand.layout(), SimpleTextEngine.TeXElement.layout(), SimpleTextEngine.Content.layout(), SimpleTextEngine.PSTextRenderer.render(), SimpleTextEngine.LineElement.render(), SimpleTextEngine.SuperscriptElement.render(), and SimpleTextEngine.Content.render().
String text [package]
Referenced by SimpleTextEngine.Element.Element(), SimpleTextEngine.Element.layout(), SimpleTextEngine.PSTextRenderer.render(), and SimpleTextEngine.Element.render().
Author
Generated automatically by Doxygen for Octave from the source code.