BaseLineObject
NAME
BaseLineObject -
SYNOPSIS
Inherits LineObject.
Public Member Functions
BaseLineObject (HandleObject parent, double value)
double getXMin ()
double getXMax ()
void draw (Renderer r)
boolean isLegendable ()
void updateLine ()
void propertyChanged (Property p) throws PropertyException
void validate ()
AxesObject getAxes ()
void set (Property p, Object value) throws PropertyException
void set (String name, Object value) throws PropertyException
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
void delete ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
java.awt.Component getComponent ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
Object get (Property p)
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Protected Member Functions
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
int glID
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
DoubleProperty BaseValue
RadioProperty Orientation
VectorProperty XData
VectorProperty YData
VectorProperty ZData
ColorProperty LineColor
LineStyleProperty LineStyle
DoubleProperty LineWidth
StringProperty KeyLabel
MarkerProperty Marker
DoubleProperty MarkerSize
ColorProperty MarkerEdgeColor
ColorProperty MarkerFaceColor
VectorProperty XLim
VectorProperty YLim
VectorProperty ZLim
VectorProperty CLim
VectorProperty ALim
BooleanProperty XLimInclude
BooleanProperty YLimInclude
BooleanProperty ZLimInclude
BooleanProperty CLimInclude
BooleanProperty ALimInclude
BooleanProperty LegendInclude
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Constructor & Destructor Documentation
BaseLineObject (HandleObjectparent, doublevalue) [inline]
References BaseLineObject.BaseValue, GraphicObject.getAxes(), HandleObject.listen(), BaseLineObject.Orientation, Property.reset(), Property.setVisible(), GraphicObject.XLim, GraphicObject.XLimInclude, LineObject.YData, and GraphicObject.YLim.
        {
                super(parent);
                BaseValue = new DoubleProperty(this, 'BaseValue', value);
                Orientation = new RadioProperty(this, 'Orientation', new String[] {'X', 'Y'}, 'X');
                XLimInclude.reset(new Boolean(false));
                YData.reset(new double[] {value, value});
                Orientation.setVisible(false);
                listen(BaseValue);
                listen(Orientation);
                listen(getAxes().XLim);
                listen(getAxes().YLim);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
void delete () [inline, inherited]
Reimplemented from PropertySet.
Reimplemented in FigureObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
References HandleObject.BeingDeleted, HandleObject.cachedData, HandleEventSourceHelper.delete(), HandleObject.deleteChildren(), HandleObject.DeleteFcn, HandleObjectListProperty.elementAt(), HandleObject.eventSource, HandleObject.eventSourceSet, CallbackProperty.execute(), HandleEventSourceHelper.fireEvent(), HandleObject.getHandle(), HandleObject.Parent, HandleObject.removeChild(), HandleObject.removeHandleEventSink(), HandleObject.removeHandleObject(), and Property.reset().
Referenced by HandleObject.deleteChildren(), AxesObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), and AxesObject.makeLegend().
        {
                BeingDeleted.reset('on');
                try { eventSource.fireEvent('ObjectDeleted'); }
                catch (PropertyException ex) {}
                DeleteFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
                removeHandleObject(getHandle());
                super.delete();
                Iterator it = eventSourceSet.iterator();
                while (it.hasNext())
                        ((HandleEventSource)it.next()).removeHandleEventSink(this);
                eventSource.delete();
                deleteChildren();
                if (cachedData != null)
                        cachedData.dispose();
                Parent.elementAt(0).removeChild(this);
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void draw (Rendererr) [inline, virtual]
Reimplemented from LineObject.
        {
                super.draw(r);
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxes () [inline, inherited]
References HandleObjectListProperty.elementAt(), and HandleObject.Parent.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), J2DRenderer.draw(), GLRenderer.draw(), TextObject.drawAsImage(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), SurfaceObject.getCData(), PatchObject.getCData(), TextObject.getExtent(), ImageObject.ImageObject(), BaseLineObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.SurfaceObject(), TextObject.toPostScript(), TextObject.updateData(), BaseLineObject.updateLine(), and TextObject.updateMinMax().
        {
                HandleObject obj = Parent.elementAt(0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                else
                        return ((GraphicObject)obj).getAxes();
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
java.awt.Component getComponent () [inline, inherited]
Reimplemented in FigureObject, UIPanelObject, and UIControlObject.
Referenced by UIControlObject.getParentComponent(), and UIPanelObject.getParentComponent().
        {
                System.out.println('Warning: no component associated with ' + getClass());
                return null;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
double getXMax () [inline]
        {
                return Double.NEGATIVE_INFINITY;
        }
double getXMin () [inline]
        {
                return Double.POSITIVE_INFINITY;
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline]
Reimplemented from GraphicObject.
        {
                return false;
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from LineObject.
References BaseLineObject.BaseValue, GraphicObject.getAxes(), RadioProperty.is(), BaseLineObject.Orientation, BooleanProperty.set(), BaseLineObject.updateLine(), GraphicObject.XLimInclude, and GraphicObject.YLimInclude.
        {
                super.propertyChanged(p);
                if (p == BaseValue)
                        updateLine();
                else if (p == Orientation)
                {
                        boolean isX = Orientation.is('X');
                        XLimInclude.set(new Boolean(!isX));
                        YLimInclude.set(new Boolean(isX));
                        updateLine();
                }
                if (p.getParent() == getAxes())
                {
                        String name = p.getName();
                        if ((name.equals('XLim') && Orientation.is('X')) ||
                                (name.equals('YLim') && Orientation.is('Y')))
                                updateLine();
                }
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References FigureObject.__Dirty__, HandleObject.getAncestor(), and Property.reset().
Referenced by LegendObject.propertyChanged().
        {
                super.set(p, value);
                FigureObject fig = (FigureObject)getAncestor('figure');
                fig.__Dirty__.reset('on');
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void updateLine () [inline]
References BaseLineObject.BaseValue, DoubleProperty.doubleValue(), VectorProperty.getArray(), GraphicObject.getAxes(), RadioProperty.is(), BaseLineObject.Orientation, Property.set(), LineObject.XData, GraphicObject.XLim, LineObject.YData, and GraphicObject.YLim.
Referenced by BaseLineObject.propertyChanged().
        {
                double b = BaseValue.doubleValue();
                if (Orientation.is('X'))
                {
                        XData.set(getAxes().XLim.getArray().clone(), true);
                        YData.set(new double[] {b, b}, true);
                }
                else
                {
                        XData.set(new double[] {b, b}, true);
                        YData.set(getAxes().YLim.getArray().clone(), true);
                }
        }
void validate () [inline, inherited]
Reimplemented from HandleObject.
References VectorProperty.isEmpty(), Property.reset(), LineObject.updateMinMax(), LineObject.ZData, and GraphicObject.ZLimInclude.
Referenced by AxesObject.getBaseLine(), and LegendObject.makeItemFromLine().
        {
                ZLimInclude.reset(ZData.isEmpty() ? 'off' : 'on');
                updateMinMax();
                super.validate();
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
VectorProperty ALim [package, inherited]
Referenced by GroupObject.childValidated(), GraphicObject.GraphicObject(), and GroupObject.updateLimits().
BooleanProperty ALimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
DoubleProperty BaseValue [package]
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), BaseLineObject.propertyChanged(), BarseriesObject.propertyChanged(), and BaseLineObject.updateLine().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
VectorProperty CLim [package, inherited]
Referenced by AxesObject.autoScaleC(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), SurfaceObject.updateColorMinMax(), GroupObject.updateLimits(), ImageObject.updateMinMax(), and PatchObject.updateMinMax().
BooleanProperty CLimInclude [package, inherited]
Referenced by AxesObject.autoScaleC(), BarseriesObject.BarseriesObject(), GraphicObject.GraphicObject(), ImageObject.ImageObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
int glID [protected, inherited]
Referenced by GraphicObject.GraphicObject().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
StringProperty KeyLabel [package, inherited]
Referenced by LineObject.LineObject().
BooleanProperty LegendInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), GraphicObject.isLegendable(), and LineObject.LineObject().
ColorProperty LineColor [package, inherited]
Referenced by J2DRenderer.draw(), GLRenderer.draw(), AxesObject.getBaseLine(), LineObject.LineObject(), and LegendObject.makeItemFromLine().
LineStyleProperty LineStyle [package, inherited]
Referenced by J2DRenderer.draw(), GLRenderer.draw(), LineObject.LineObject(), and LegendObject.makeItemFromLine().
DoubleProperty LineWidth [package, inherited]
Referenced by J2DRenderer.draw(), GLRenderer.draw(), LineObject.LineObject(), and LegendObject.makeItemFromLine().
MarkerProperty Marker [package, inherited]
Referenced by J2DRenderer.draw(), GLRenderer.draw(), LineObject.LineObject(), and LegendObject.makeItemFromLine().
ColorProperty MarkerEdgeColor [package, inherited]
Referenced by GLRenderer.draw(), LineObject.LineObject(), and LegendObject.makeItemFromLine().
ColorProperty MarkerFaceColor [package, inherited]
Referenced by GLRenderer.draw(), LineObject.LineObject(), and LegendObject.makeItemFromLine().
DoubleProperty MarkerSize [package, inherited]
Referenced by J2DRenderer.draw(), GLRenderer.draw(), and LineObject.LineObject().
RadioProperty Orientation [package]
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), BaseLineObject.propertyChanged(), BarseriesObject.propertyChanged(), and BaseLineObject.updateLine().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
VectorProperty XData [package, inherited]
Referenced by LegendObject.doLayout(), J2DRenderer.draw(), GLRenderer.draw(), LineObject.LineObject(), LineObject.propertyChanged(), BaseLineObject.updateLine(), and LineObject.updateMinMax().
VectorProperty XLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty XLimInclude [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
VectorProperty YData [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), LegendObject.doLayout(), J2DRenderer.draw(), GLRenderer.draw(), LineObject.LineObject(), LineObject.propertyChanged(), BaseLineObject.updateLine(), and LineObject.updateMinMax().
VectorProperty YLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty YLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
VectorProperty ZData [package, inherited]
Referenced by J2DRenderer.draw(), GLRenderer.draw(), LineObject.LineObject(), LineObject.propertyChanged(), LineObject.updateMinMax(), and LineObject.validate().
VectorProperty ZLim [package, inherited]
Referenced by GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty ZLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), LineObject.LineObject(), PatchObject.PatchObject(), LineObject.propertyChanged(), SurfaceObject.SurfaceObject(), and LineObject.validate().
Author
Generated automatically by Doxygen for Octave from the source code.