SimpleTextEngine.TextRenderer
NAME
SimpleTextEngine.TextRenderer -
SYNOPSIS
Inherited by SimpleTextEngine.PSTextRenderer.
Public Member Functions
void render (Element e)
void render (LineElement e)
void render (SubscriptElement e)
void render (SuperscriptElement e)
void render (ScriptElement e)
void render (TeXElement e)
void render (TeXFontCommand e)
void render (Content e)
Member Function Documentation
void render (Elemente)
Implemented in SimpleTextEngine.PSTextRenderer.
Referenced by SimpleTextEngine.Element.render(), SimpleTextEngine.LineElement.render(), SimpleTextEngine.SubscriptElement.render(), SimpleTextEngine.SuperscriptElement.render(), SimpleTextEngine.ScriptElement.render(), SimpleTextEngine.TeXFontCommand.render(), SimpleTextEngine.TeXElement.render(), and SimpleTextEngine.Content.render().
void render (LineElemente)
Implemented in SimpleTextEngine.PSTextRenderer.
void render (SubscriptElemente)
Implemented in SimpleTextEngine.PSTextRenderer.
void render (SuperscriptElemente)
Implemented in SimpleTextEngine.PSTextRenderer.
void render (ScriptElemente)
Implemented in SimpleTextEngine.PSTextRenderer.
void render (TeXElemente)
Implemented in SimpleTextEngine.PSTextRenderer.
void render (TeXFontCommande)
Implemented in SimpleTextEngine.PSTextRenderer.
void render (Contente)
Implemented in SimpleTextEngine.PSTextRenderer.
Author
Generated automatically by Doxygen for Octave from the source code.