HandleEvent
NAME
HandleEvent -
SYNOPSIS
Inherits EventObject.
Public Member Functions
HandleEvent (Object source, String name)
String getName ()
HandleObject getHandleObject ()
Property getProperty ()
Private Attributes
String name
Constructor & Destructor Documentation
HandleEvent (Objectsource, Stringname) [inline]
References HandleEvent.name.
        {
                super(source);
                this.name = name;
        }
Member Function Documentation
HandleObject getHandleObject () [inline]
Referenced by OctaveSink.doInvoke(), and OctaveSink.OctaveSink().
        {
                Object obj = getSource();
                if (obj instanceof HandleObject)
                        return (HandleObject)obj;
                else if (obj instanceof Property)
                {
                        obj = ((Property)obj).getParent();
                        if (obj instanceof HandleObject)
                                return (HandleObject)obj;
                }
                return null;
        }
String getName () [inline]
References HandleEvent.name.
Referenced by OctaveSink.OctaveSink(), and HandleObject.waitFor().
        {
                return name;
        }
Property getProperty () [inline]
Referenced by CheckBoxControl.CheckBoxControl(), Edit2Control.Edit2Control(), EditControl.EditControl(), ListBoxControl.ListBoxControl(), PopupMenuControl.PopupMenuControl(), PushButtonControl.PushButtonControl(), TextControl.TextControl(), and UIControlAdapter.UIControlAdapter().
        {
                Object obj = getSource();
                if (obj instanceof Property)
                        return (Property)obj;
                return null;
        }
Member Data Documentation
String name [private]
Referenced by HandleEvent.getName(), and HandleEvent.HandleEvent().
Author
Generated automatically by Doxygen for Octave from the source code.