CheckBoxControl
NAME
CheckBoxControl -
SYNOPSIS
Inherits JCheckBox, UIControl, and ActionListener.
Public Member Functions
CheckBoxControl (UIControlObject obj)
void propertyChanged (Property p) throws PropertyException
void update ()
JComponent getComponent ()
void dispose ()
void actionPerformed (ActionEvent event)
Private Attributes
UIControlObject uiObj
HandleEventSinkAdapter sink
Constructor & Destructor Documentation
CheckBoxControl (UIControlObjectobj) [inline]
References HandleEvent.getProperty(), CheckBoxControl.propertyChanged(), CheckBoxControl.sink, StringProperty.toString(), CheckBoxControl.uiObj, UIControlObject.UIString, and UIControlObject.Value.
        {
                super();
                addActionListener(this);
                uiObj = obj;
                setText(obj.UIString.toString());
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.UIString);
                sink.listen(obj.Value);
        }
Member Function Documentation
void actionPerformed (ActionEventevent) [inline]
References UIControlObject.controlActivated(), and CheckBoxControl.uiObj.
        {
                uiObj.controlActivated(new UIControlEvent(this));
        }
void dispose () [inline]
Implements UIControl.
References HandleEventSinkAdapter.dispose(), and CheckBoxControl.sink.
        {
                sink.dispose();
        }
JComponent getComponent () [inline]
Implements UIControl.
        {
                return this;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References DoubleProperty.doubleValue(), VectorProperty.getArray(), UIControlObject.Max, StringProperty.toString(), CheckBoxControl.uiObj, UIControlObject.UIString, and UIControlObject.Value.
Referenced by CheckBoxControl.CheckBoxControl().
        {
                if (p == uiObj.UIString)
                        setText(uiObj.UIString.toString());
                else if (p == uiObj.Value)
                {
                        double v = uiObj.Value.getArray()[0];
                        setSelected(v == uiObj.Max.doubleValue());
                }
        }
void update () [inline]
Implements UIControl.
References Property.get(), UIControlObject.Max, UIControlObject.Min, Property.reset(), CheckBoxControl.uiObj, and UIControlObject.Value.
        {
                uiObj.Value.reset(isSelected() ? uiObj.Max.get() : uiObj.Min.get());
        }
Member Data Documentation
HandleEventSinkAdapter sink [private]
Referenced by CheckBoxControl.CheckBoxControl(), and CheckBoxControl.dispose().
UIControlObject uiObj [private]
Referenced by CheckBoxControl.actionPerformed(), CheckBoxControl.CheckBoxControl(), CheckBoxControl.propertyChanged(), and CheckBoxControl.update().
Author
Generated automatically by Doxygen for Octave from the source code.