BarseriesObject
NAME
BarseriesObject -
SYNOPSIS
Inherits GroupObject.
Public Member Functions
BarseriesObject (HandleObject parent, double[] x, double[] y)
BarseriesObject (HandleObject parent, double[] x, double[] y, boolean horizontal)
void validate ()
void delete ()
void updateBars ()
void propertyChanged (Property p) throws PropertyException
void childValidated (HandleObject child)
void removeChild (HandleObject child)
void draw (Renderer r)
AxesObject getAxes ()
void set (Property p, Object value) throws PropertyException
void set (String name, Object value) throws PropertyException
boolean isLegendable ()
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
void addChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
java.awt.Component getComponent ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
Object get (Property p)
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Protected Member Functions
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
int glID
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
DoubleProperty BarWidth
RadioProperty BarLayout
VectorProperty XData
VectorProperty YData
DoubleProperty BaseValue
HandleObjectListProperty BaseLine
ColorProperty EdgeColor
ColorProperty FaceColor
HandleObjectListProperty BarGroup
BooleanProperty Horizontal
VectorProperty XLim
VectorProperty YLim
VectorProperty ZLim
VectorProperty CLim
VectorProperty ALim
BooleanProperty XLimInclude
BooleanProperty YLimInclude
BooleanProperty ZLimInclude
BooleanProperty CLimInclude
BooleanProperty ALimInclude
BooleanProperty LegendInclude
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
PatchObject getPatch ()
void doLayout (boolean doValidate)
BaseLineObject getBaseLine ()
Constructor & Destructor Documentation
BarseriesObject (HandleObjectparent, double[]x, double[]y) [inline]
References plt.x, and plt.y.
Referenced by BarseriesObject.doLayout().
        {
                this(parent, x, y, false);
        }
BarseriesObject (HandleObjectparent, double[]x, double[]y, booleanhorizontal) [inline]
References HandleObjectListProperty.addElement(), BarseriesObject.BarGroup, BarseriesObject.BarLayout, BarseriesObject.BarWidth, BarseriesObject.BaseLine, BaseLineObject.BaseValue, BarseriesObject.BaseValue, GraphicObject.CLimInclude, DoubleProperty.doubleValue(), BarseriesObject.EdgeColor, PatchObject.EdgeColor, BarseriesObject.FaceColor, PatchObject.FaceColor, Property.get(), GraphicObject.getAxes(), AxesObject.getBaseLine(), BarseriesObject.Horizontal, HandleObject.listen(), BaseLineObject.Orientation, Property.reset(), Property.set(), Property.setVisible(), BarseriesObject.XData, and BarseriesObject.YData.
        {
                super(parent);
                PatchObject patch = new PatchObject(this);
                BaseLineObject base = getAxes().getBaseLine();
                try { base.Orientation.set(horizontal ? 'Y' : 'X'); }
                catch (PropertyException e) {}
                BarWidth = new DoubleProperty(this, 'BarWidth', 0.8);
                BarLayout = new RadioProperty(this, 'BarLayout', new String[] {'grouped', 'stacked'}, 'grouped');
                XData = new VectorProperty(this, 'XData', -1, x);
                YData = new VectorProperty(this, 'YData', -1, y);
                BaseLine = new HandleObjectListProperty(this, 'BaseLine', -1);
                BaseLine.addElement(base);
                BaseValue = new DoubleProperty(this, 'BaseValue', base.BaseValue.doubleValue());
                EdgeColor = new ColorProperty(this, 'EdgeColor', new String[] {'none'}, Color.black);
                FaceColor = new ColorProperty(this, 'FaceColor', new String[] {'none', 'flat'}, 'flat');
                BarGroup = new HandleObjectListProperty(this, 'BarGroup', -1);
                Horizontal = new BooleanProperty(this, 'Horizontal', horizontal);
                RadioProperty mapping = new RadioProperty(this, 'CDataMapping', new String[] {'direct', 'scaled'}, 'scaled');
                BarGroup.setVisible(false);
                mapping.setVisible(false);
                Horizontal.setVisible(false);
                
                patch.EdgeColor.reset(EdgeColor.get());
                patch.FaceColor.reset(FaceColor.get());
                CLimInclude.reset(new Boolean(true));
                listen(BaseValue);
                listen(base.BaseValue);
                listen(BarWidth);
                listen(BarLayout);
                listen(EdgeColor);
                listen(FaceColor);
                listen(Horizontal);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void childValidated (HandleObjectchild) [inline, inherited]
Reimplemented from HandleObject.
References GraphicObject.ALim, GraphicObject.CLim, GraphicObject.GraphicObject(), HandleObject.listen(), GroupObject.updateLimits(), GraphicObject.XLim, GraphicObject.YLim, and GraphicObject.ZLim.
        {
                super.childValidated(child);
                updateLimits();
                if (child instanceof GraphicObject)
                {
                        GraphicObject g = (GraphicObject)child;
                        listen(g.XLim);
                        listen(g.YLim);
                        listen(g.ZLim);
                        listen(g.CLim);
                        listen(g.ALim);
                }
        }
void delete () [inline]
Reimplemented from HandleObject.
References BarseriesObject.BarGroup, HandleObjectListProperty.iterator(), HandleObjectListProperty.removeElement(), HandleObjectListProperty.size(), and BarseriesObject.updateBars().
        {
                BarGroup.removeElement(this);
                Iterator it = BarGroup.iterator();
                while (it.hasNext())
                        ((BarseriesObject)it.next()).BarGroup.removeElement(this);
                if (BarGroup.size() > 0)
                        updateBars();
                super.delete();
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void doLayout (booleandoValidate) [inline, private]
References BarseriesObject.BarGroup, BarseriesObject.BarLayout, BarseriesObject.BarseriesObject(), BarseriesObject.BarWidth, BarseriesObject.BaseValue, GraphicObject.CLim, DoubleProperty.doubleValue(), HandleObjectListProperty.elementAt(), PatchObject.Faces, PatchObject.FaceVertexCData, Property.get(), VectorProperty.getArray(), BarseriesObject.getPatch(), BarseriesObject.Horizontal, RadioProperty.is(), BooleanProperty.isSet(), Property.set(), HandleObjectListProperty.size(), PatchObject.Vertices, plt.x, BarseriesObject.XData, GraphicObject.XLim, plt.y, BarseriesObject.YData, GraphicObject.YLim, and GraphicObject.ZLim.
Referenced by BarseriesObject.updateBars(), and BarseriesObject.validate().
        {
                if (BarGroup.size() == 0)
                        return;
                double B = BaseValue.doubleValue();
                int n = BarGroup.size();
                double[] x = XData.getArray();
                double w = (x.length > 1 ? Double.POSITIVE_INFINITY : 1);
                boolean horizontal = Horizontal.isSet();
                
                for (int i=1; i<x.length; i++)
                        w = Math.min(w, x[i]-x[i-1]);
                if (BarLayout.is('stacked'))
                {
                        double bw = w*BarWidth.doubleValue();
                        double[] bv = new double[x.length];
                        Arrays.fill(bv, B);
                        for (int i=0; i<n; i++)
                        {
                                BarseriesObject bar = (BarseriesObject)BarGroup.elementAt(i);
                                PatchObject patch = bar.getPatch();
                                double[][] v = new double[x.length*4][];
                                double[][] f = new double[x.length][];
                                double[] y = bar.YData.getArray();
                                double[] fvc = new double[x.length*4];
                                for (int k=0; k<x.length; k++)
                                {
                                        f[k] = new double[] {4*k+1, 4*k+2, 4*k+3, 4*k+4};
                                        if (horizontal)
                                        {
                                                v[4*k] = new double[] {bv[k], x[k]-bw/2, 0};
                                                v[4*k+1] = new double[] {bv[k], x[k]+bw/2, 0};
                                                v[4*k+2] = new double[] {bv[k]+y[k], x[k]+bw/2, 0};
                                                v[4*k+3] = new double[] {bv[k]+y[k], x[k]-bw/2, 0};
                                        }
                                        else
                                        {
                                                v[4*k] = new double[] {x[k]-bw/2, bv[k], 0};
                                                v[4*k+1] = new double[] {x[k]+bw/2, bv[k], 0};
                                                v[4*k+2] = new double[] {x[k]+bw/2, bv[k]+y[k], 0};
                                                v[4*k+3] = new double[] {x[k]-bw/2, bv[k]+y[k], 0};
                                        }
                                        fvc[4*k] = i+1;
                                        fvc[4*k+1] = i+1;
                                        fvc[4*k+2] = i+1;
                                        fvc[4*k+3] = i+1;
                                        bv[k] += y[k];
                                }
                                patch.Vertices.set(null, true); /* just in case, to avoid computing normals in PatchObject */
                                patch.Faces.set(new Matrix(f), true);
                                patch.Vertices.set(new Matrix(v), true);
                                patch.FaceVertexCData.set(new Matrix(fvc, new int[] {fvc.length, 1}), true);
                                /* TODO: needed?
                                if (doValidate)
                                        patch.validate();
                                */
                                bar.XLim.set(patch.XLim.get(), true);
                                bar.YLim.set(patch.YLim.get(), true);
                                bar.ZLim.set(patch.ZLim.get(), true);
                                bar.CLim.set(patch.CLim.get(), true);
                        }
                }
                else if (BarLayout.is('grouped'))
                {
                        double gw, bw;
                        if (n == 1)
                                gw = bw = w*BarWidth.doubleValue();
                        else
                        {
                                gw = 0.8*w;
                                bw = (gw/n)*BarWidth.doubleValue();
                        }
                        for (int i=0; i<n; i++)
                        {
                                BarseriesObject bar = (BarseriesObject)BarGroup.elementAt(i);
                                PatchObject patch = bar.getPatch();
                                double bo = (n == 1 ? 0 : -gw/2+(gw/n)*(i+0.5));
                                double[][] v = new double[x.length*4][];
                                double[][] f = new double[x.length][];
                                double[] y = bar.YData.getArray();
                                double[] fvc = new double[x.length*4];
                                for (int k=0; k<x.length; k++)
                                {
                                        f[k] = new double[] {4*k+1, 4*k+2, 4*k+3, 4*k+4};
                                        if (horizontal)
                                        {
                                                v[4*k] = new double[] {B, x[k]+bo-bw/2, 0};
                                                v[4*k+1] = new double[] {B, x[k]+bo+bw/2, 0};
                                                v[4*k+2] = new double[] {y[k], x[k]+bo+bw/2, 0};
                                                v[4*k+3] = new double[] {y[k], x[k]+bo-bw/2, 0};
                                        }
                                        else
                                        {
                                                v[4*k] = new double[] {x[k]+bo-bw/2, B, 0};
                                                v[4*k+1] = new double[] {x[k]+bo+bw/2, B, 0};
                                                v[4*k+2] = new double[] {x[k]+bo+bw/2, y[k], 0};
                                                v[4*k+3] = new double[] {x[k]+bo-bw/2, y[k], 0};
                                        }
                                        fvc[4*k] = i+1;
                                        fvc[4*k+1] = i+1;
                                        fvc[4*k+2] = i+1;
                                        fvc[4*k+3] = i+1;
                                }
                                patch.Vertices.set(null, true); /* just in case, to avoid computing normals in PatchObject */
                                patch.Faces.set(new Matrix(f), true);
                                patch.Vertices.set(new Matrix(v), true);
                                patch.FaceVertexCData.set(new Matrix(fvc, new int[] {fvc.length, 1}), true);
                                /* TODO: needed?
                                if (doValidate)
                                        patch.validate();
                                */
                                bar.XLim.set(patch.XLim.get(), true);
                                bar.YLim.set(patch.YLim.get(), true);
                                bar.ZLim.set(patch.ZLim.get(), true);
                                bar.CLim.set(patch.CLim.get(), true);
                        }
                }
        }
void draw (Rendererr) [inline, virtual, inherited]
Implements GraphicObject.
References HandleObject.Children, GraphicObject.draw(), GraphicObject.GraphicObject(), and HandleObjectListProperty.iterator().
        {
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        while (it.hasNext())
                        {
                                GraphicObject obj = (GraphicObject)it.next();
                                obj.draw(r);
                        }
                }
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxes () [inline, inherited]
References HandleObjectListProperty.elementAt(), and HandleObject.Parent.
Referenced by BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), J2DRenderer.draw(), GLRenderer.draw(), TextObject.drawAsImage(), SurfaceObject.getAlphaData(), PatchObject.getAlphaData(), SurfaceObject.getCData(), PatchObject.getCData(), TextObject.getExtent(), ImageObject.ImageObject(), BaseLineObject.propertyChanged(), TextObject.propertyChanged(), SurfaceObject.SurfaceObject(), TextObject.toPostScript(), TextObject.updateData(), BaseLineObject.updateLine(), and TextObject.updateMinMax().
        {
                HandleObject obj = Parent.elementAt(0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                else
                        return ((GraphicObject)obj).getAxes();
        }
BaseLineObject getBaseLine () [inline, private]
References BarseriesObject.BaseLine, and HandleObjectListProperty.elementAt().
Referenced by BarseriesObject.propertyChanged().
        {
                return (BaseLineObject)BaseLine.elementAt(0);
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
java.awt.Component getComponent () [inline, inherited]
Reimplemented in FigureObject, UIPanelObject, and UIControlObject.
Referenced by UIControlObject.getParentComponent(), and UIPanelObject.getParentComponent().
        {
                System.out.println('Warning: no component associated with ' + getClass());
                return null;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
PatchObject getPatch () [inline, private]
References HandleObject.Children, and HandleObjectListProperty.elementAt().
Referenced by BarseriesObject.doLayout(), and BarseriesObject.propertyChanged().
        {
                return (PatchObject)Children.elementAt(0);
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented from HandleObject.
Reimplemented in BaseLineObject.
References BooleanProperty.isSet(), and GraphicObject.LegendInclude.
        {
                return LegendInclude.isSet();
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from GroupObject.
References BarseriesObject.BarGroup, BarseriesObject.BarLayout, BarseriesObject.BarWidth, BaseLineObject.BaseValue, BarseriesObject.BaseValue, BarseriesObject.EdgeColor, PatchObject.EdgeColor, BarseriesObject.FaceColor, PatchObject.FaceColor, BarseriesObject.getBaseLine(), BarseriesObject.getPatch(), BarseriesObject.Horizontal, BooleanProperty.isSet(), HandleObjectListProperty.iterator(), BaseLineObject.Orientation, Property.reset(), Property.set(), and BarseriesObject.updateBars().
        {
                super.propertyChanged(p);
                if (p == BaseValue)
                        getBaseLine().BaseValue.set(p.get());
                else if (p.getName().equals('BaseValue'))
                {
                        Iterator it = BarGroup.iterator();
                        while (it.hasNext())
                                ((BarseriesObject)it.next()).BaseValue.reset(p.get());
                        updateBars();
                }
                else if (p == BarWidth)
                {
                        Iterator it = BarGroup.iterator();
                        while (it.hasNext())
                                ((BarseriesObject)it.next()).BarWidth.reset(p.get());
                        updateBars();
                }
                else if (p == BarLayout)
                {
                        Iterator it = BarGroup.iterator();
                        while (it.hasNext())
                                ((BarseriesObject)it.next()).BarLayout.reset(p.get());
                        updateBars();
                }
                else if (p == Horizontal)
                {
                        Iterator it = BarGroup.iterator();
                        while (it.hasNext())
                                ((BarseriesObject)it.next()).Horizontal.reset(p.get());
                        updateBars();
                        getBaseLine().Orientation.set(Horizontal.isSet() ? 'Y' : 'X');
                }
                else if (p == EdgeColor)
                        getPatch().EdgeColor.reset(p.get());
                else if (p == FaceColor)
                        getPatch().FaceColor.reset(p.get());
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented from HandleObject.
References GroupObject.updateLimits().
        {
                super.removeChild(child);
                updateLimits();
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References FigureObject.__Dirty__, HandleObject.getAncestor(), and Property.reset().
Referenced by LegendObject.propertyChanged().
        {
                super.set(p, value);
                FigureObject fig = (FigureObject)getAncestor('figure');
                fig.__Dirty__.reset('on');
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void updateBars () [inline]
References BarseriesObject.doLayout().
Referenced by BarseriesObject.delete(), and BarseriesObject.propertyChanged().
        {
                doLayout(false);
        }
void validate () [inline]
Reimplemented from GroupObject.
References BarseriesObject.doLayout().
        {
                super.validate();
                doLayout(false);
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
VectorProperty ALim [package, inherited]
Referenced by GroupObject.childValidated(), GraphicObject.GraphicObject(), and GroupObject.updateLimits().
BooleanProperty ALimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
HandleObjectListProperty BarGroup [package]
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.delete(), BarseriesObject.doLayout(), and BarseriesObject.propertyChanged().
RadioProperty BarLayout [package]
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), and BarseriesObject.propertyChanged().
DoubleProperty BarWidth [package]
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), and BarseriesObject.propertyChanged().
HandleObjectListProperty BaseLine [package]
Referenced by BarseriesObject.BarseriesObject(), and BarseriesObject.getBaseLine().
DoubleProperty BaseValue [package]
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), and BarseriesObject.propertyChanged().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
VectorProperty CLim [package, inherited]
Referenced by AxesObject.autoScaleC(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), SurfaceObject.updateColorMinMax(), GroupObject.updateLimits(), ImageObject.updateMinMax(), and PatchObject.updateMinMax().
BooleanProperty CLimInclude [package, inherited]
Referenced by AxesObject.autoScaleC(), BarseriesObject.BarseriesObject(), GraphicObject.GraphicObject(), ImageObject.ImageObject(), PatchObject.PatchObject(), and SurfaceObject.SurfaceObject().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
ColorProperty EdgeColor [package]
Referenced by BarseriesObject.BarseriesObject(), and BarseriesObject.propertyChanged().
ColorProperty FaceColor [package]
Referenced by BarseriesObject.BarseriesObject(), and BarseriesObject.propertyChanged().
int glID [protected, inherited]
Referenced by GraphicObject.GraphicObject().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
BooleanProperty Horizontal [package]
Referenced by BarseriesObject.BarseriesObject(), BarseriesObject.doLayout(), and BarseriesObject.propertyChanged().
BooleanProperty LegendInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), GraphicObject.isLegendable(), and LineObject.LineObject().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
VectorProperty XData [package]
Referenced by BarseriesObject.BarseriesObject(), and BarseriesObject.doLayout().
VectorProperty XLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty XLimInclude [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
VectorProperty YData [package]
Referenced by BarseriesObject.BarseriesObject(), and BarseriesObject.doLayout().
VectorProperty YLim [package, inherited]
Referenced by BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), BaseLineObject.updateLine(), ImageObject.updateMinMax(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty YLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), AxesObject.makeTextObject(), and BaseLineObject.propertyChanged().
VectorProperty ZLim [package, inherited]
Referenced by GroupObject.childValidated(), AxesObject.childValidated(), BarseriesObject.doLayout(), GraphicObject.GraphicObject(), GroupObject.updateLimits(), LineObject.updateMinMax(), SurfaceObject.updateMinMax(), PatchObject.updateMinMax(), and TextObject.updateMinMax().
BooleanProperty ZLimInclude [package, inherited]
Referenced by GraphicObject.GraphicObject(), LineObject.LineObject(), PatchObject.PatchObject(), LineObject.propertyChanged(), SurfaceObject.SurfaceObject(), and LineObject.validate().
Author
Generated automatically by Doxygen for Octave from the source code.