Edit2Control
NAME
Edit2Control -
SYNOPSIS
Inherits JScrollPane, UIControl, and KeyListener.
Public Member Functions
Edit2Control (UIControlObject obj)
void setAlignment ()
void propertyChanged (Property p) throws PropertyException
void update ()
JComponent getComponent ()
void dispose ()
void keyPressed (KeyEvent event)
void keyReleased (KeyEvent event)
void keyTyped (KeyEvent event)
Package Attributes
UIControlObject uiObj
HandleEventSinkAdapter sink
JTextPane text
Constructor & Destructor Documentation
Edit2Control (UIControlObjectobj) [inline]
References UIControlObject.BackgroundColor, UIControlObject.ForegroundColor, ColorProperty.getColor(), HandleEvent.getProperty(), UIControlObject.HorizontalAlignment, Edit2Control.propertyChanged(), Edit2Control.setAlignment(), Edit2Control.sink, Edit2Control.text, StringProperty.toString(), Edit2Control.uiObj, and UIControlObject.UIString.
        {
                super(new JTextPane());
                text = (JTextPane)getViewport().getView();
                text.addKeyListener(this);
                uiObj = obj;
                setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
                setAlignment();
                text.setText(obj.UIString.toString());
                setBackground(obj.BackgroundColor.getColor());
                setForeground(obj.ForegroundColor.getColor());
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.UIString);
                sink.listen(obj.HorizontalAlignment);
                sink.listen(obj.BackgroundColor);
                sink.listen(obj.ForegroundColor);
        }
Member Function Documentation
void dispose () [inline]
Implements UIControl.
References HandleEventSinkAdapter.dispose(), and Edit2Control.sink.
        {
                sink.dispose();
        }
JComponent getComponent () [inline]
Implements UIControl.
References Edit2Control.text.
        {
                return text;
        }
void keyPressed (KeyEventevent) [inline]
        {
        }
void keyReleased (KeyEventevent) [inline]
        {
        }
void keyTyped (KeyEventevent) [inline]
References UIControlObject.controlActivated(), and Edit2Control.uiObj.
        {
                if (event.getKeyChar() == '\n' && event.getModifiers() == InputEvent.CTRL_MASK)
                        uiObj.controlActivated(new UIControlEvent(this));
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References UIControlObject.BackgroundColor, UIControlObject.ForegroundColor, ColorProperty.getColor(), UIControlObject.HorizontalAlignment, Edit2Control.setAlignment(), Edit2Control.text, StringProperty.toString(), Edit2Control.uiObj, and UIControlObject.UIString.
Referenced by Edit2Control.Edit2Control().
        {
                if (p == uiObj.UIString)
                        text.setText(uiObj.UIString.toString());
                else if (p == uiObj.HorizontalAlignment)
                        setAlignment();
                else if (p == uiObj.BackgroundColor)
                        setBackground(uiObj.BackgroundColor.getColor());
                else if (p == uiObj.ForegroundColor)
                        setForeground(uiObj.ForegroundColor.getColor());
        }
void setAlignment () [inline]
References UIControlObject.HorizontalAlignment, RadioProperty.is(), Edit2Control.text, and Edit2Control.uiObj.
Referenced by Edit2Control.Edit2Control(), and Edit2Control.propertyChanged().
        {
                MutableAttributeSet s = new SimpleAttributeSet();
                s.addAttribute(
                        StyleConstants.Alignment,
                        new Integer(
                                (uiObj.HorizontalAlignment.is('left') ? StyleConstants.ALIGN_LEFT :
                                 uiObj.HorizontalAlignment.is('center') ? StyleConstants.ALIGN_CENTER :
                                 uiObj.HorizontalAlignment.is('right') ? StyleConstants.ALIGN_RIGHT :
                                 StyleConstants.ALIGN_LEFT)));
                StyledDocument doc = text.getStyledDocument();
                doc.setParagraphAttributes(0, doc.getLength()+1, s, false);
        }
void update () [inline]
Implements UIControl.
References Property.reset(), Edit2Control.text, Edit2Control.uiObj, and UIControlObject.UIString.
        {
                uiObj.UIString.reset(text.getText());
        }
Member Data Documentation
HandleEventSinkAdapter sink [package]
Referenced by Edit2Control.dispose(), and Edit2Control.Edit2Control().
JTextPane text [package]
Referenced by Edit2Control.Edit2Control(), Edit2Control.getComponent(), Edit2Control.propertyChanged(), Edit2Control.setAlignment(), and Edit2Control.update().
UIControlObject uiObj [package]
Referenced by Edit2Control.Edit2Control(), Edit2Control.keyTyped(), Edit2Control.propertyChanged(), Edit2Control.setAlignment(), and Edit2Control.update().
Author
Generated automatically by Doxygen for Octave from the source code.