GLRenderer.GLMarkerDrawer
NAME
GLRenderer.GLMarkerDrawer -
SYNOPSIS
Inherits GLRenderer.MarkerDrawer.
Public Member Functions
GLMarkerDrawer ()
void begin (MarkerProperty m, DoubleProperty ms, float lw)
void end ()
void draw (double x, double y, double z, double[] lc, double[] fc)
Package Attributes
int ID2
Private Attributes
int ID
boolean hasClip
double[] tmp = new double[4]
Constructor & Destructor Documentation
GLMarkerDrawer () [inline]
                {
                }
Member Function Documentation
void begin (MarkerPropertym, DoublePropertyms, floatlw) [inline]
Implements GLRenderer.MarkerDrawer.
References GLRenderer.d, GLRenderer.gl, GLRenderer.GLMarkerDrawer.hasClip, GLRenderer.hasClipping(), GLRenderer.GLMarkerDrawer.ID, GLRenderer.GLMarkerDrawer.ID2, GLRenderer.makeMarkerList(), GLRenderer.setClipping(), GLRenderer.setLineWidth(), GLRenderer.xZ1, and GLRenderer.xZ2.
                {
                        gl.glMatrixMode(GL.GL_PROJECTION);
                        gl.glPushMatrix();
                        gl.glLoadIdentity();
                        gl.glOrtho(0, d.getWidth(), d.getHeight(), 0, xZ1, xZ2);
                        gl.glMatrixMode(GL.GL_MODELVIEW);
                        gl.glPushMatrix();
                        hasClip = hasClipping();
                        setClipping(false);
                        setLineWidth(lw);
                
                        ID = makeMarkerList(m, ms, false);
                        ID2 = makeMarkerList(m, ms, true);
                }
void draw (doublex, doubley, doublez, double[]lc, double[]fc) [inline]
Implements GLRenderer.MarkerDrawer.
References GLRenderer.gl, GLRenderer.GLMarkerDrawer.ID, GLRenderer.GLMarkerDrawer.ID2, GLRenderer.setPolygonOffset(), GLRenderer.GLMarkerDrawer.tmp, Matrix3D.transform(), and GLRenderer.xForm.
                {
                        xForm.transform(x, y, z, tmp, 0);
                        gl.glLoadIdentity();
                        gl.glTranslated(tmp[0], tmp[1], -tmp[2]);
                        if (fc != null)
                        {
                                gl.glColor3d(fc[0], fc[1], fc[2]);
                                setPolygonOffset(true);
                                gl.glCallList(ID2);
                                setPolygonOffset(false);
                        }
                        if (lc != null)
                        {
                                gl.glColor3d(lc[0], lc[1], lc[2]);
                                gl.glCallList(ID);
                        }
                }
void end () [inline]
Implements GLRenderer.MarkerDrawer.
References GLRenderer.gl, GLRenderer.GLMarkerDrawer.hasClip, GLRenderer.GLMarkerDrawer.ID, GLRenderer.GLMarkerDrawer.ID2, GLRenderer.setClipping(), and GLRenderer.setLineWidth().
                {
                        gl.glDeleteLists(ID, 1);
                        gl.glDeleteLists(ID2, 1);
                        gl.glMatrixMode(GL.GL_MODELVIEW);
                        gl.glPopMatrix();
                        gl.glMatrixMode(GL.GL_PROJECTION);
                        gl.glPopMatrix();
                        setClipping(hasClip);
                        setLineWidth(0.5f);
                }
Member Data Documentation
boolean hasClip [private]
Referenced by GLRenderer.GLMarkerDrawer.begin(), and GLRenderer.GLMarkerDrawer.end().
int ID [private]
Referenced by GLRenderer.GLMarkerDrawer.begin(), GLRenderer.GLMarkerDrawer.draw(), and GLRenderer.GLMarkerDrawer.end().
int ID2 [package]
Referenced by GLRenderer.GLMarkerDrawer.begin(), GLRenderer.GLMarkerDrawer.draw(), and GLRenderer.GLMarkerDrawer.end().
double [] tmp = new double[4] [private]
Referenced by GLRenderer.GLMarkerDrawer.draw().
Author
Generated automatically by Doxygen for Octave from the source code.