.TH "PropertyException" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertyException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBException\fP\&.
.SS "Package Functions"

.in +1c
.ti -1c
.RI "\fBPropertyException\fP (String s)"
.br
.ti -1c
.RI "\fBPropertyException\fP (Throwable t)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBPropertyException\fP (Strings)\fC [inline, package]\fP"
.PP
.nf
        {
                super(s);
        }
.fi
.SS "\fBPropertyException\fP (Throwablet)\fC [inline, package]\fP"
.PP
.nf
        {
                super(t);
        }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
