FigureObject
NAME
FigureObject -
SYNOPSIS
Inherits AxesContainer, WindowListener, ComponentListener, and ActionListener.
Classes
class FigurePanel
Public Member Functions
FigureObject (int fignum)
void validate ()
void removeChild (HandleObject child)
void updateToolbars ()
void delete ()
void activate ()
void print (String format, String filename) throws java.io.IOException
void propertyChanged (Property p) throws PropertyException
Component getComponent ()
Object get (Property p)
int getMouseOp ()
void windowClosing (WindowEvent e)
void windowActivated (WindowEvent e)
void windowDeactivated (WindowEvent e)
void windowClosed (WindowEvent e)
void windowIconified (WindowEvent e)
void windowDeiconified (WindowEvent e)
void windowOpened (WindowEvent e)
void componentHidden (ComponentEvent e)
void componentMoved (ComponentEvent e)
void componentResized (ComponentEvent e)
void componentShown (ComponentEvent e)
void actionPerformed (ActionEvent e)
HandleObject getObjectForPoint (Point pt, int margin)
AxesObject getAxesForPoint (Point pt)
void redraw ()
boolean hasMouseOperation ()
void cancelMouseOperation ()
void reshape (RenderCanvas c, int x, int y, int width, int height)
void display (RenderCanvas c)
void mouseClicked (MouseEvent e)
void mouseEntered (MouseEvent e)
void mouseExited (MouseEvent e)
void mousePressed (MouseEvent e)
void mouseReleased (MouseEvent e)
void mouseMoved (MouseEvent e)
void mouseDragged (MouseEvent e)
RenderCanvas getCanvas ()
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
boolean isLegendable ()
void addChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
void set (String name, Object value) throws PropertyException
void set (Property p, Object value) throws PropertyException
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static void redrawRecursive (HandleObject obj)
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Static Public Attributes
static final int OP_NONE = 0
static final int OP_ZOOM = 1
static final int OP_ROTATE = 2
Protected Member Functions
Color getBackgroundColor ()
Container getEmbeddingComponent ()
Point getMouseLocation (MouseEvent e)
void updateCanvas ()
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
RenderCanvas canvas = null
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
VectorProperty Alphamap
CallbackProperty CloseRequestFcn
ColorProperty FigColor
ArrayProperty Colormap
HandleObjectListProperty CurrentAxes
BooleanProperty IntegerHandle
CallbackProperty KeyPressFcn
StringProperty Name
RadioProperty NextPlot
BooleanProperty NumberTitle
RadioProperty PaperOrientation
VectorProperty Position
RadioProperty Renderer
RadioProperty RendererMode
BooleanProperty Resize
CallbackProperty ResizeFcn
RadioProperty SelectionType
RadioProperty Toolbar
RadioProperty Units
BooleanProperty __Dirty__
BooleanProperty __Antialias__
JToolBar figureTB
JToggleButton editBtn
JToggleButton zoomBtn
JToggleButton rotateBtn
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
void createFigure ()
void updateHandle ()
void updatePosition ()
void updateFramePosition ()
void updateTitle ()
Buffer makeColormapTextureData ()
String getBestRenderer ()
int commandToOp (String cmd)
Private Attributes
Frame frame
Panel tbPanel
Panel axPanel
int defaultMouseOp = OP_NONE
String currentUnits
Constructor & Destructor Documentation
FigureObject (intfignum) [inline]
References FigureObject.__Antialias__, FigureObject.__Dirty__, FigureObject.Alphamap, FigureObject.CloseRequestFcn, FigureObject.Colormap, FigureObject.CurrentAxes, FigureObject.currentUnits, RootObject.defaultColorMap(), FigureObject.FigColor, Utils.getBackgroundColor(), RootObject.getInstance(), Utils.getScreenSize(), RadioProperty.getValue(), FigureObject.IntegerHandle, FigureObject.KeyPressFcn, HandleObject.listen(), FigureObject.Name, FigureObject.NextPlot, FigureObject.NumberTitle, FigureObject.PaperOrientation, FigureObject.Position, FigureObject.RendererMode, FigureObject.Resize, FigureObject.ResizeFcn, FigureObject.SelectionType, Property.setVisible(), FigureObject.Toolbar, FigureObject.Units, and HandleObject.Visible.
        {
                super(RootObject.getInstance(), 'figure', fignum);
                CurrentAxes = new HandleObjectListProperty(this, 'CurrentAxes', 1);
                Name = new StringProperty(this, 'Name', '');
                NumberTitle = new BooleanProperty(this, 'NumberTitle', true);
                NextPlot = new RadioProperty(this, 'NextPlot', new String[] {'new', 'add', 'replace', 'replacechildren'}, 'add');
                FigColor = new ColorProperty(this, 'Color', Utils.getBackgroundColor());
                Colormap = new ArrayProperty(this, 'Colormap', new String[] {'double'}, 2,
                        new Matrix(RootObject.getInstance().defaultColorMap()));
                ResizeFcn = new CallbackProperty(this, 'ResizeFcn', (String)null);
                CloseRequestFcn = new CallbackProperty(this, 'CloseRequestFcn', 'closereq');
                double[] amap = new double[64];
                for (int i=0; i<amap.length; i++)
                        amap[i] = ((double)i)/(amap.length-1);
                Alphamap = new VectorProperty(this, 'Alphamap', -1, amap);
                PaperOrientation = new RadioProperty(this, 'PaperOrientation', new String[] {'portrait', 'landscape'}, 'portrait');
                IntegerHandle = new BooleanProperty(this, 'IntegerHandle', true);
                Units = new RadioProperty(this, 'Units', new String[] {'pixels', 'normalized', 'inches', 'centimeters',
                        'points', 'characters'}, 'pixels');
                currentUnits = Units.getValue();
                Dimension d = Utils.getScreenSize();
                Position = new VectorProperty(this, 'Position', 4, new double[] {10, d.height-500, 600, 430});
                Renderer = new RadioProperty(this, 'Renderer', new String[] {'OpenGL', 'Java2D'}, 'OpenGL');
                RendererMode = new RadioProperty(this, 'RendererMode', new String[] {'auto', 'manual'}, 'auto');
                Toolbar = new RadioProperty(this, 'Toolbar', new String[] {'none', 'auto', 'figure'}, 'auto');
                SelectionType = new RadioProperty(this, 'SelectionType', new String[] {'normal', 'extend', 'alt', 'open'}, 'normal');
                KeyPressFcn = new CallbackProperty(this, 'KeyPressFcn', (String)null);
                __Dirty__ = new BooleanProperty(this, '__Dirty__', false);
                __Dirty__.setVisible(false);
                Resize = new BooleanProperty(this, 'Resize', true);
                __Antialias__ = new BooleanProperty(this, '__Antialias__', true);
                __Antialias__.setVisible(false);
                listen(Name);
                listen(NumberTitle);
                listen(IntegerHandle);
                listen(Position);
                listen(Units);
                listen(Toolbar);
                listen(Resize);
                listen(Renderer);
                listen(RendererMode);
                listen(Visible);
        }
Member Function Documentation
void actionPerformed (ActionEvente) [inline]
References FigureObject.commandToOp(), FigureObject.defaultMouseOp, FigureObject.editBtn, AxesContainer.OP_NONE, FigureObject.rotateBtn, and FigureObject.zoomBtn.
        {
                //System.out.println('action');
                if (e.getSource() == editBtn || e.getSource() == zoomBtn || e.getSource() == rotateBtn)
                {
                        if (e.getSource() != editBtn)
                                editBtn.setSelected(false);
                        if (e.getSource() != zoomBtn)
                                zoomBtn.setSelected(false);
                        if (e.getSource() != rotateBtn)
                                rotateBtn.setSelected(false);
                        if (((JToggleButton)e.getSource()).isSelected())
                                defaultMouseOp = commandToOp(e.getActionCommand());
                        else
                                defaultMouseOp = OP_NONE;
                }
        }
void activate () [inline]
References FigureObject.frame.
Referenced by FigureObject.validate().
        {
                frame.toFront();
        }
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void cancelMouseOperation () [inline, inherited]
References AxesObject.cancelOperation(), AxesContainer.hasMouseOperation(), AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
Referenced by FigureObject.windowDeactivated().
        {
                if (hasMouseOperation())
                {
                        mouseAxes.cancelOperation(mouseOp);
                        mouseAxes = null;
                        mouseOp = OP_NONE;
                }
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
int commandToOp (Stringcmd) [inline, private]
References AxesContainer.OP_NONE, AxesContainer.OP_ROTATE, and AxesContainer.OP_ZOOM.
Referenced by FigureObject.actionPerformed().
        {
                if (cmd.equals('edit')) return OP_NONE;
                else if (cmd.equals('zoom')) return OP_ZOOM;
                else if (cmd.equals('rotate')) return OP_ROTATE;
                else return OP_NONE;
        }
void componentHidden (ComponentEvente) [inline]
{}
void componentMoved (ComponentEvente) [inline]
{}
void componentResized (ComponentEvente) [inline]
References CallbackProperty.execute(), HandleObject.getHandle(), and FigureObject.ResizeFcn.
        {
                //System.out.println('resized');
                ResizeFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void componentShown (ComponentEvente) [inline]
{}
void createFigure () [inline, private]
References FigureObject.axPanel, FigureObject.editBtn, FigureObject.FigColor, FigureObject.figureTB, FigureObject.frame, AxesContainer.getCanvas(), ColorProperty.getColor(), FigureObject.getComponent(), BooleanProperty.isSet(), Utils.loadIcon(), FigureObject.Resize, FigureObject.rotateBtn, FigureObject.tbPanel, FigureObject.updateFramePosition(), FigureObject.updateTitle(), FigureObject.updateToolbars(), HandleObject.Visible, and FigureObject.zoomBtn.
Referenced by FigureObject.validate().
        {
                // setup window frame
                frame = new Frame();
                frame.setBackground(FigColor.getColor());
                frame.addWindowListener(this);
                frame.addComponentListener(this);
                frame.setResizable(Resize.isSet());
                // setup toolbar panel
                tbPanel = new Panel(new GridLayout(1, 1));
                frame.add(tbPanel, BorderLayout.NORTH);
                // dummy toolbar
                figureTB = new JToolBar();
                figureTB.setRollover(true);
                figureTB.setFloatable(false);
                editBtn = new JToggleButton(Utils.loadIcon('edit'));
                editBtn.setActionCommand('edit');
                editBtn.setEnabled(false);
                editBtn.setToolTipText('Edit plot');
                editBtn.addActionListener(this);
                zoomBtn = new JToggleButton(Utils.loadIcon('zoom-original'));
                zoomBtn.setActionCommand('zoom');
                zoomBtn.setToolTipText('Zoom');
                zoomBtn.addActionListener(this);
                rotateBtn = new JToggleButton(Utils.loadIcon('view-refresh'));
                rotateBtn.setActionCommand('rotate');
                rotateBtn.setToolTipText('3D rotation');
                rotateBtn.addActionListener(this);
                figureTB.add(editBtn);
                figureTB.add(zoomBtn);
                figureTB.add(rotateBtn);
                updateToolbars();
                // setup axes panel
                axPanel = new Panel(new PositionLayout());
                frame.add(axPanel, BorderLayout.CENTER);
                // setup RenderCanvas
                axPanel.add(getCanvas().getComponent());
                updateTitle();
                if (Visible.isSet())
                        frame.setVisible(true);
                updateFramePosition();
                if (!Visible.isSet())
                {
                        frame.layout();
                        axPanel.layout();
                }
        }
void delete () [inline]
Reimplemented from HandleObject.
References FigureObject.frame.
        {
                if (frame != null && frame.isVisible())
                        frame.setVisible(false);
                super.delete();
                //frame.dispose();
                //frame.setVisible(false);
                if (frame != null)
                        EventQueue.invokeLater(new Runnable() { public void run() { frame.dispose(); } });
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void display (RenderCanvasc) [inline, inherited]
Implements RenderEventListener.
References HandleObject.Children, Renderer.clear(), AxesContainer.getBackgroundColor(), RenderCanvas.getRenderer(), HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
        {
                Renderer r = c.getRenderer();
                // clear background
                r.clear(getBackgroundColor());
                // iterate over axes objects
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (hObj instanceof AxesObject && hObj.isValid())
                                        ((AxesObject)hObj).draw(r);
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
Object get (Propertyp) [inline]
Reimplemented from PropertySet.
References FigureObject.Position, and FigureObject.updatePosition().
        {
                if (p == Position)
                        updatePosition();
                return super.get(p);
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxesForPoint (Pointpt) [inline, inherited]
References AxesContainer.getObjectForPoint().
Referenced by AxesContainer.mouseClicked(), and AxesContainer.mousePressed().
        {
                HandleObject obj = getObjectForPoint(pt, 0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                return null;
        }
Color getBackgroundColor () [inline, protected, virtual]
Implements AxesContainer.
References FigureObject.FigColor, and ColorProperty.getColor().
        {
                return FigColor.getColor();
        }
String getBestRenderer () [inline, private]
Referenced by FigureObject.propertyChanged().
        {
                return 'OpenGL';
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
RenderCanvas getCanvas () [inline, inherited]
Implements RenderCanvas.Container.
References AxesContainer.canvas, and AxesContainer.createCanvas().
Referenced by FigureObject.createFigure().
        {
                if (canvas == null)
                        createCanvas();
                return canvas;
        }
Component getComponent () [inline]
Reimplemented from HandleObject.
References FigureObject.axPanel.
Referenced by FigureObject.createFigure().
        {
                return axPanel;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
Container getEmbeddingComponent () [inline, protected, virtual]
Implements AxesContainer.
References FigureObject.axPanel.
        {
                return axPanel;
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
Point getMouseLocation (MouseEvente) [inline, protected, inherited]
References AxesContainer.canvas, RenderCanvas.getX(), and RenderCanvas.getY().
Referenced by AxesContainer.mouseClicked(), and AxesContainer.mousePressed().
        {
                Point pt = new Point(e.getPoint());
                if (e.getSource() == canvas)
                        pt.translate(canvas.getX(), canvas.getY());
                return pt;
        }
int getMouseOp () [inline]
References FigureObject.defaultMouseOp.
Referenced by AxesContainer.getDefaultMouseOp().
        {
                return defaultMouseOp;
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
HandleObject getObjectForPoint (Pointpt, intmargin) [inline, inherited]
References AxesContainer.canvas, HandleObject.Children, AxesContainer.getEmbeddingComponent(), RenderCanvas.getHeight(), RenderCanvas.getX(), RenderCanvas.getY(), HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
Referenced by AxesContainer.getAxesForPoint(), and AxesContainer.mousePressed().
        {
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        Insets insets = getEmbeddingComponent().getInsets();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (!hObj.isValid())
                                        continue;
                                if (hObj instanceof UIControlObject)
                                {
                                        Rectangle r = ((UIControlObject)hObj).getBounds();
                                        r.setRect(r.x-margin, r.y-margin, r.width+2*margin, r.height+2*margin);
                                        if (r.contains(pt))
                                                return hObj;
                                }
                                else if (hObj instanceof AxesObject)
                                {
                                        Rectangle r = ((AxesObject)hObj).getBoundingBox();
                                        if (r.contains(pt.x-canvas.getX(), canvas.getHeight()-pt.y+canvas.getY()))
                                                return hObj;
                                }
                        }
                }
                return null;
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasMouseOperation () [inline, inherited]
References AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
Referenced by AxesContainer.cancelMouseOperation().
        {
                return (mouseOp != OP_NONE && mouseAxes != null);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented in GraphicObject, and BaseLineObject.
Referenced by AxesObject.autoLegend(), and LegendObject.buildLegend().
        {
                return false;
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
Buffer makeColormapTextureData () [inline, private]
References ArrayProperty.asDoubleMatrix(), and FigureObject.Colormap.
        {
                double[][] cmap = Colormap.asDoubleMatrix();
                float[] buf = new float[cmap.length*4];
                for (int i=0; i<cmap.length; i++)
                {
                        buf[4*i] = (float)cmap[i][0];
                        buf[4*i+1] = (float)cmap[i][1];
                        buf[4*i+2] = (float)cmap[i][2];
                        buf[4*i+3] = 1;
                }
                return FloatBuffer.wrap(buf);
        }
void mouseClicked (MouseEvente) [inline, inherited]
References AxesContainer.getAxesForPoint(), AxesContainer.getDefaultMouseOp(), AxesContainer.getMouseLocation(), AxesContainer.mouseOp, AxesContainer.OP_NONE, AxesContainer.OP_ZOOM, and AxesObject.unZoom().
        {
                if (e.getButton() == MouseEvent.BUTTON3 && mouseOp == OP_NONE && getDefaultMouseOp() == OP_ZOOM)
                {
                        AxesObject ax = getAxesForPoint(getMouseLocation(e));
                        if (ax != null)
                                ax.unZoom();
                }
        }
void mouseDragged (MouseEvente) [inline, inherited]
References AxesContainer.mouseAxes, AxesContainer.mouseOp, AxesContainer.OP_NONE, and AxesObject.operation().
        {
                if (mouseAxes != null && mouseOp != OP_NONE)
                        mouseAxes.operation(mouseOp, e);
        }
void mouseEntered (MouseEvente) [inline, inherited]
{}
void mouseExited (MouseEvente) [inline, inherited]
{}
void mouseMoved (MouseEvente) [inline, inherited]
{}
void mousePressed (MouseEvente) [inline, inherited]
References HandleObject.doButtonDownFcn(), AxesContainer.getAxesForPoint(), AxesContainer.getDefaultMouseOp(), AxesContainer.getMouseLocation(), AxesContainer.getObjectForPoint(), AxesContainer.mouseAxes, AxesContainer.mouseOp, AxesContainer.OP_NONE, and AxesObject.startOperation().
        {
                if (mouseOp == OP_NONE)
                {
                        // Only do something if no operation pending
                        Point pt = getMouseLocation(e);
                        AxesObject ax = getAxesForPoint(pt);
                        HandleObject hObj = getObjectForPoint(pt, 5);
                        if (hObj != null)
                        {
                                boolean doCB = false;
                                if (hObj instanceof AxesObject)
                                {
                                        if (getDefaultMouseOp() == OP_NONE)
                                                doCB = true;
                                        else if (e.getButton() == MouseEvent.BUTTON1)
                                        {
                                                mouseAxes = (AxesObject)hObj;
                                                mouseOp = getDefaultMouseOp();
                                                mouseAxes.startOperation(mouseOp, e);
                                        }
                                }
                                else
                                        doCB = true;
                                if (doCB)
                                        hObj.doButtonDownFcn(e);
                        }
                        else
                                doButtonDownFcn(e);
                }
        }
void mouseReleased (MouseEvente) [inline, inherited]
References AxesObject.endOperation(), AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
        {
                if (mouseOp != OP_NONE)
                {
                        if (e.getButton() == MouseEvent.BUTTON1)
                        {
                                if (mouseAxes != null)
                                        mouseAxes.endOperation(mouseOp, e);
                                mouseAxes = null;
                                mouseOp = OP_NONE;
                        }
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void print (Stringformat, Stringfilename) throws java.io.IOException 	 [inline]
References AxesContainer.canvas, FigureObject.FigColor, ColorProperty.getColor(), RenderCanvas.redraw(), Property.reset(), RenderCanvas.toImage(), and RenderCanvas.toPostScript().
        {
                Color fcolor = FigColor.getColor();
                FigColor.reset(Color.white);
                try
                {
                        if (format .equals('postscript'))
                        {
                                canvas.toPostScript(filename);
                        }
                        else
                        {
                                BufferedImage img = canvas.toImage();
                                javax.imageio.ImageIO.write(img, format, new java.io.File(filename));
                        }
                }
                finally
                {
                        FigColor.reset(fcolor);
                        canvas.redraw();
                }
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from HandleObject.
References HandleObject.autoSet(), FigureObject.currentUnits, FigureObject.frame, FigureObject.getBestRenderer(), RadioProperty.getValue(), FigureObject.IntegerHandle, RadioProperty.is(), HandleObject.isAutoMode(), BooleanProperty.isSet(), FigureObject.Name, FigureObject.NumberTitle, FigureObject.Position, FigureObject.RendererMode, FigureObject.Resize, FigureObject.Toolbar, FigureObject.Units, AxesContainer.updateCanvas(), FigureObject.updateFramePosition(), FigureObject.updateHandle(), FigureObject.updatePosition(), FigureObject.updateTitle(), FigureObject.updateToolbars(), and HandleObject.Visible.
        {
                super.propertyChanged(p);
                if (p == Name || p == NumberTitle)
                        updateTitle();
                else if (p == IntegerHandle)
                {
                        updateHandle();
                        updateTitle();
                }
                else if (p == Visible)
                {
                        frame.setVisible(Visible.isSet());
                        updateFramePosition();
                }
                else if (p == Position && !isAutoMode())
                {
                        updateFramePosition();
                }
                else if (p == Units)
                {
                        updatePosition();
                        currentUnits = Units.getValue();
                }
                else if (p == Toolbar)
                        updateToolbars();
                else if (p == Resize)
                        frame.setResizable(Resize.isSet());
                else if (p == Renderer && !isAutoMode())
                {
                        autoSet(RendererMode, 'manual');
                        updateCanvas();
                }
                else if (p == RendererMode && !isAutoMode())
                {
                        if (RendererMode.is('auto'))
                        {
                                String r = getBestRenderer();
                                if (!Renderer.is(r))
                                {
                                        autoSet(Renderer, getBestRenderer());
                                        updateCanvas();
                                }
                        }
                }
        }
void redraw () [inline, inherited]
References AxesContainer.redrawRecursive().
        {
                redrawRecursive(this);
        }
static void redrawRecursive (HandleObjectobj) [inline, static, inherited]
Referenced by AxesContainer.redraw().
        {
                if (obj instanceof RenderCanvas.Container)
                        ((RenderCanvas.Container)obj).getCanvas().redraw();
                synchronized (obj.Children)
                {
                        Iterator it = obj.Children.iterator();
                        while (it.hasNext())
                                redrawRecursive((HandleObject)it.next());
                }
        }
void removeChild (HandleObjectchild) [inline]
Reimplemented from HandleObject.
References FigureObject.CurrentAxes, HandleObjectListProperty.elementAt(), HandleObjectListProperty.removeAllElements(), and HandleObjectListProperty.size().
        {
                if (CurrentAxes.size() > 0 && child == CurrentAxes.elementAt(0))
                        CurrentAxes.removeAllElements();
                super.removeChild(child);
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void reshape (RenderCanvasc, intx, inty, intwidth, intheight) [inline, inherited]
Implements RenderEventListener.
References HandleObject.Children, HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
        {
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (hObj instanceof AxesObject && hObj.isValid())
                                        ((AxesObject)hObj).updateActivePosition();
                        }
                }
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in UIControlObject, and GraphicObject.
        {
                p.set(value);
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void updateCanvas () [inline, protected, inherited]
References AxesContainer.canvas, AxesContainer.createCanvas(), RenderCanvas.getComponent(), AxesContainer.getEmbeddingComponent(), RenderCanvas.removeMouseListener(), RenderCanvas.removeMouseMotionListener(), and RenderCanvas.removeRenderEventListener().
Referenced by FigureObject.propertyChanged().
        {
                if (canvas != null)
                {
                        canvas.removeMouseListener(this);
                        canvas.removeMouseMotionListener(this);
                        canvas.removeRenderEventListener(this);
                        getEmbeddingComponent().remove(canvas.getComponent());
                        getEmbeddingComponent().validate();
                        canvas = null;
                }
                createCanvas();
        }
void updateFramePosition () [inline, private]
References Utils.convertPosition(), FigureObject.frame, Utils.getScreenSize(), RadioProperty.getValue(), VectorProperty.getVector(), FigureObject.Position, FigureObject.tbPanel, and FigureObject.Units.
Referenced by FigureObject.createFigure(), and FigureObject.propertyChanged().
        {
                double[] pos = Utils.convertPosition(Position.getVector(), Units.getValue(), 'pixels', null);
                Dimension d = Utils.getScreenSize();
                Insets insets = frame.getInsets();
                pos[0]--;
                pos[1] = d.height-pos[1]-pos[3]+1;
                frame.setBounds((int)pos[0]-insets.left, (int)pos[1]-insets.top-tbPanel.getHeight(),
                                (int)pos[2]+insets.left+insets.right, (int)pos[3]+insets.top+insets.bottom+tbPanel.getHeight());
        }
void updateHandle () [inline, private]
References HandleObject.getHandle(), RootObject.getInstance(), RootObject.getUnusedFigureNumber(), HandleObject.handle, FigureObject.IntegerHandle, BooleanProperty.isSet(), HandleObject.newHandle(), and HandleObject.setHandle().
Referenced by FigureObject.propertyChanged(), and FigureObject.validate().
        {
                double handle = getHandle();
                if (IntegerHandle.isSet() && handle < 0)
                        setHandle(RootObject.getInstance().getUnusedFigureNumber());
                else if (!IntegerHandle.isSet() && handle > 0)
                        setHandle(newHandle());
        }
void updatePosition () [inline, private]
References HandleObject.autoSet(), FigureObject.axPanel, Utils.convertPosition(), Utils.getScreenSize(), RadioProperty.getValue(), FigureObject.Position, and FigureObject.Units.
Referenced by FigureObject.get(), and FigureObject.propertyChanged().
        {
                Dimension d = Utils.getScreenSize();
                Point pt = axPanel.getLocationOnScreen();
                double[] pos = new double[] {pt.getX()+1, d.height-pt.getY()-axPanel.getHeight()+1,
                        axPanel.getWidth(), axPanel.getHeight()};
                autoSet(Position, Utils.convertPosition(pos, 'pixels', Units.getValue(), null));
        }
void updateTitle () [inline, private]
References FigureObject.frame, HandleObject.getHandle(), BooleanProperty.isSet(), FigureObject.Name, FigureObject.NumberTitle, and StringProperty.toString().
Referenced by FigureObject.createFigure(), and FigureObject.propertyChanged().
        {
                String title = (NumberTitle.isSet() ? 'Figure ' + getHandle() : ''), name = Name.toString();
                if (name.length() > 0)
                {
                        if (title.length() > 0)
                                title += ': ' + name;
                        else
                                title = name;
                }
                frame.setTitle(title);
        }
void updateToolbars () [inline]
References FigureObject.figureTB, FigureObject.frame, RadioProperty.is(), FigureObject.tbPanel, and FigureObject.Toolbar.
Referenced by FigureObject.createFigure(), and FigureObject.propertyChanged().
        {
                if (Toolbar.is('none'))
                        tbPanel.remove(figureTB);
                else
                        tbPanel.add(figureTB);
                frame.validate();
        }
void validate () [inline]
Reimplemented from HandleObject.
References FigureObject.activate(), FigureObject.createFigure(), and FigureObject.updateHandle().
        {
                updateHandle();
                createFigure();
                super.validate();
                activate();
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
void windowActivated (WindowEvente) [inline]
References HandleObjectListProperty.addElement(), RootObject.CurrentFigure, and RootObject.getInstance().
        {
                RootObject.getInstance().CurrentFigure.addElement(this);
        }
void windowClosed (WindowEvente) [inline]
{}
void windowClosing (WindowEvente) [inline]
References FigureObject.CloseRequestFcn, CallbackProperty.execute(), and HandleObject.getHandle().
        {
                //this.delete();
                CloseRequestFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void windowDeactivated (WindowEvente) [inline]
References AxesContainer.cancelMouseOperation().
        {
                cancelMouseOperation();
        }
void windowDeiconified (WindowEvente) [inline]
{}
void windowIconified (WindowEvente) [inline]
{}
void windowOpened (WindowEvente) [inline]
{}
Member Data Documentation
BooleanProperty __Antialias__ [package]
Referenced by FigureObject.FigureObject(), and J2DRenderer.setXForm().
BooleanProperty __Dirty__ [package]
Referenced by FigureObject.FigureObject(), and GraphicObject.set().
VectorProperty Alphamap [package]
Referenced by FigureObject.FigureObject(), Utils.getAlphaData(), SurfaceObject.getAlphaData(), and PatchObject.getAlphaData().
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
Panel axPanel [private]
Referenced by FigureObject.createFigure(), FigureObject.getComponent(), FigureObject.getEmbeddingComponent(), and FigureObject.updatePosition().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
RenderCanvas canvas = null [protected, inherited]
Referenced by AxesContainer.createCanvas(), AxesContainer.getCanvas(), AxesContainer.getMouseLocation(), AxesContainer.getObjectForPoint(), FigureObject.print(), and AxesContainer.updateCanvas().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CloseRequestFcn [package]
Referenced by FigureObject.FigureObject(), and FigureObject.windowClosing().
ArrayProperty Colormap [package]
Referenced by ColorbarObject.buildColorbar(), AxesObject.convertCData(), AxesObject.convertCDataToIndex(), FigureObject.FigureObject(), FigureObject.makeColormapTextureData(), and ColorbarObject.propertyChanged().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
HandleObjectListProperty CurrentAxes [package]
Referenced by FigureObject.FigureObject(), and FigureObject.removeChild().
String currentUnits [private]
Referenced by FigureObject.FigureObject(), and FigureObject.propertyChanged().
int defaultMouseOp = OP_NONE [private]
Referenced by FigureObject.actionPerformed(), and FigureObject.getMouseOp().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
JToggleButton editBtn [package]
Referenced by FigureObject.actionPerformed(), and FigureObject.createFigure().
ColorProperty FigColor [package]
Referenced by FigureObject.createFigure(), FigureObject.FigureObject(), FigureObject.getBackgroundColor(), and FigureObject.print().
JToolBar figureTB [package]
Referenced by FigureObject.createFigure(), and FigureObject.updateToolbars().
Frame frame [private]
Referenced by FigureObject.activate(), FigureObject.createFigure(), FigureObject.delete(), FigureObject.propertyChanged(), FigureObject.updateFramePosition(), FigureObject.updateTitle(), and FigureObject.updateToolbars().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
BooleanProperty IntegerHandle [package]
Referenced by FigureObject.FigureObject(), FigureObject.propertyChanged(), and FigureObject.updateHandle().
CallbackProperty KeyPressFcn [package]
Referenced by FigureObject.FigureObject().
StringProperty Name [package]
Referenced by FigureObject.FigureObject(), FigureObject.propertyChanged(), and FigureObject.updateTitle().
RadioProperty NextPlot [package]
Referenced by FigureObject.FigureObject().
BooleanProperty NumberTitle [package]
Referenced by FigureObject.FigureObject(), FigureObject.propertyChanged(), and FigureObject.updateTitle().
final int OP_NONE = 0 [static, inherited]
Referenced by FigureObject.actionPerformed(), AxesContainer.cancelMouseOperation(), FigureObject.commandToOp(), AxesContainer.hasMouseOperation(), AxesContainer.mouseClicked(), AxesContainer.mouseDragged(), AxesContainer.mousePressed(), and AxesContainer.mouseReleased().
final int OP_ROTATE = 2 [static, inherited]
Referenced by AxesObject.cancelOperation(), FigureObject.commandToOp(), AxesObject.endOperation(), AxesObject.operation(), and AxesObject.startOperation().
final int OP_ZOOM = 1 [static, inherited]
Referenced by AxesObject.cancelOperation(), FigureObject.commandToOp(), AxesObject.endOperation(), AxesContainer.mouseClicked(), AxesObject.operation(), and AxesObject.startOperation().
RadioProperty PaperOrientation [package]
Referenced by FigureObject.FigureObject().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
VectorProperty Position [package]
Referenced by FigureObject.FigureObject(), FigureObject.get(), FigureObject.propertyChanged(), FigureObject.updateFramePosition(), and FigureObject.updatePosition().
RadioProperty Renderer [package]
RadioProperty RendererMode [package]
Referenced by FigureObject.FigureObject(), and FigureObject.propertyChanged().
BooleanProperty Resize [package]
Referenced by FigureObject.createFigure(), FigureObject.FigureObject(), and FigureObject.propertyChanged().
CallbackProperty ResizeFcn [package]
Referenced by FigureObject.componentResized(), and FigureObject.FigureObject().
JToggleButton rotateBtn [package]
Referenced by FigureObject.actionPerformed(), and FigureObject.createFigure().
RadioProperty SelectionType [package]
Referenced by FigureObject.FigureObject().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
Panel tbPanel [private]
Referenced by FigureObject.createFigure(), FigureObject.updateFramePosition(), and FigureObject.updateToolbars().
RadioProperty Toolbar [package]
Referenced by FigureObject.FigureObject(), FigureObject.propertyChanged(), and FigureObject.updateToolbars().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
RadioProperty Units [package]
Referenced by FigureObject.FigureObject(), FigureObject.propertyChanged(), FigureObject.updateFramePosition(), and FigureObject.updatePosition().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
JToggleButton zoomBtn [package]
Referenced by FigureObject.actionPerformed(), and FigureObject.createFigure().
Author
Generated automatically by Doxygen for Octave from the source code.