.TH "HandleEventSink" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HandleEventSink \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHandleEventSinkAdapter\fP, and \fBHandleObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBeventOccured\fP (\fBHandleEvent\fP evt)  throws PropertyException"
.br
.ti -1c
.RI "void \fBsourceDeleted\fP (Object source)"
.br
.ti -1c
.RI "boolean \fBexecuteOnce\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBeventOccured\fP (\fBHandleEvent\fPevt)  throws \fBPropertyException\fP"
.PP
Implemented in \fBHandleObject\fP, and \fBHandleEventSinkAdapter\fP\&.
.PP
Referenced by HandleEventSourceHelper\&.fireEvent()\&.
.SS "boolean \fBexecuteOnce\fP ()"
.PP
Implemented in \fBHandleObject\fP, and \fBHandleEventSinkAdapter\fP\&.
.PP
Referenced by HandleEventSourceHelper\&.fireEvent()\&.
.SS "void \fBsourceDeleted\fP (Objectsource)"
.PP
Implemented in \fBHandleObject\fP, and \fBHandleEventSinkAdapter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
