.TH "LegendObject.LegendItem" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LegendObject.LegendItem \- 
.SH SYNOPSIS
.br
.PP
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBname\fP"
.br
.ti -1c
.RI "\fBTextObject\fP \fBtext\fP"
.br
.ti -1c
.RI "\fBLineObject\fP \fBline\fP"
.br
.ti -1c
.RI "\fBLineObject\fP \fBmarker\fP"
.br
.ti -1c
.RI "\fBPatchObject\fP \fBpatch\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBLineObject\fP \fBline\fP\fC [package]\fP"
.PP
Referenced by LegendObject\&.doLayout(), and LegendObject\&.makeItemFromLine()\&.
.SS "\fBLineObject\fP \fBmarker\fP\fC [package]\fP"
.PP
Referenced by LegendObject\&.doLayout(), and LegendObject\&.makeItemFromLine()\&.
.SS "\fBString\fP \fBname\fP\fC [package]\fP"
.PP
Referenced by LegendObject\&.makeItemFromLine()\&.
.SS "\fBPatchObject\fP \fBpatch\fP\fC [package]\fP"
.SS "\fBTextObject\fP \fBtext\fP\fC [package]\fP"
.PP
Referenced by LegendObject\&.doLayout(), LegendObject\&.makeItemFromLine(), and LegendObject\&.propertyChanged()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
