Callback
NAME
Callback -
SYNOPSIS
Inherited by OctaveCallback.
Public Member Functions
Callback ()
void addCallbackListener (CallbackListener l)
void removeCallbackListener (CallbackListener l)
void unwind (Property p, Object value)
abstract void execute (HandleObject parent, Object[] args)
void execute (HandleObject parent)
abstract Object get ()
Static Public Member Functions
static Callback makeCallback (Object obj)
Protected Member Functions
void fireCallbackExecuted ()
Protected Attributes
UnwindHandleObject unwinder
Private Attributes
LinkedList listenerList
Constructor & Destructor Documentation
Callback () [inline]
References Callback.listenerList, and Callback.unwinder.
        {
                listenerList = new LinkedList();
                unwinder = null;
        }
Member Function Documentation
void addCallbackListener (CallbackListenerl) [inline]
References Callback.listenerList.
        {
                synchronized(listenerList)
                {
                        listenerList.add(l);
                }
        }
abstract void execute (HandleObjectparent, Object[]args) [pure virtual]
Implemented in OctaveCallback.
Referenced by UIControlObject.controlActivated(), Callback.execute(), and CallbackProperty.execute().
void execute (HandleObjectparent) [inline]
References Callback.execute().
        {
                execute(parent, new Object[0]);
        }
void fireCallbackExecuted () [inline, protected]
References Callback.listenerList.
Referenced by OctaveCallback.execute().
        {
                synchronized(listenerList)
                {
                        Iterator it = listenerList.iterator();
                        while (it.hasNext())
                                ((CallbackListener)it.next()).callbackExecuted(this);
                }
        }
abstract Object get () [pure virtual]
Implemented in OctaveCallback.
Referenced by CallbackProperty.getInternal().
static Callback makeCallback (Objectobj) [inline, static]
Referenced by CallbackProperty.CallbackProperty(), and CallbackProperty.convertValue().
        {
                if (obj instanceof OctaveReference)
                        return new OctaveCallback((OctaveReference)obj);
                else if (obj instanceof String)
                        return new OctaveCallback((String)obj);
                return null;
        }
void removeCallbackListener (CallbackListenerl) [inline]
References Callback.listenerList.
        {
                synchronized(listenerList)
                {
                        listenerList.remove(l);
                }
        }
void unwind (Propertyp, Objectvalue) [inline]
References UnwindHandleObject.unwind(), and Callback.unwinder.
Referenced by OctaveCallback.execute(), and CallbackProperty.unwind().
        {
                if (unwinder == null)
                        unwinder = new UnwindHandleObject();
                unwinder.unwind(p, value);
        }
Member Data Documentation
LinkedList listenerList [private]
Referenced by Callback.addCallbackListener(), Callback.Callback(), Callback.fireCallbackExecuted(), and Callback.removeCallbackListener().
UnwindHandleObject unwinder [protected]
Referenced by Callback.Callback(), OctaveCallback.execute(), and Callback.unwind().
Author
Generated automatically by Doxygen for Octave from the source code.