HandleObject
NAME
HandleObject -
Base class for handle-based graphics.
SYNOPSIS
Inherits PropertySet, HandleEventSource, and HandleEventSink.
Inherited by AxesContainer, AxesObject, GraphicObject, RootObject, and UIControlObject.
Public Member Functions
HandleObject (HandleObject parent, String type)
HandleObject (HandleObject parent, double handle, String type)
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
boolean isLegendable ()
void delete ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void validate ()
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
java.awt.Component getComponent ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
void set (String name, Object value) throws PropertyException
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void propertyChanged (Property p) throws PropertyException
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
Object get (Property p)
void set (Property p, Object value) throws PropertyException
void show ()
String[] getNames ()
Static Public Member Functions
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Protected Member Functions
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
void waitFor (String pname, final Object value, final boolean hasValue)
Private Attributes
double handle
Renderer.CachedData cachedData = null
boolean valid = false
HandleEventSourceHelper eventSource
Set eventSourceSet
Static Private Attributes
static double handleSeed = -1 - Math.random()
static HashMap handleMap = new HashMap()
Detailed Description
Base class for handle-based graphics.
Constructor & Destructor Documentation
HandleObject (HandleObjectparent, Stringtype) [inline]
References HandleObject.newHandle().
Referenced by AxesObject.autoLegend(), LegendObject.buildLegend(), AxesContainer.display(), AxesContainer.getObjectForPoint(), HandleObject.listObjects(), and AxesContainer.reshape().
        {
                this(parent, newHandle(), type);
        }
HandleObject (HandleObjectparent, doublehandle, Stringtype) [inline]
References HandleObject.addHandleObject(), HandleObject.eventSource, HandleObject.eventSourceSet, HandleObject.getHandle(), HandleObject.handle, and HandleObject.initProperties().
        {
                this.handle = handle;
                this.eventSource = new HandleEventSourceHelper(this, new String[] {'ObjectDeleted'});
                this.eventSourceSet = new HashSet();
                addHandleObject(getHandle(), this);
                initProperties(parent, type);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void childValidated (HandleObjectchild) [inline, protected]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
void delete () [inline]
Reimplemented from PropertySet.
Reimplemented in FigureObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
References HandleObject.BeingDeleted, HandleObject.cachedData, HandleEventSourceHelper.delete(), HandleObject.deleteChildren(), HandleObject.DeleteFcn, HandleObjectListProperty.elementAt(), HandleObject.eventSource, HandleObject.eventSourceSet, CallbackProperty.execute(), HandleEventSourceHelper.fireEvent(), HandleObject.getHandle(), HandleObject.Parent, HandleObject.removeChild(), HandleObject.removeHandleEventSink(), HandleObject.removeHandleObject(), and Property.reset().
Referenced by HandleObject.deleteChildren(), AxesObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), and AxesObject.makeLegend().
        {
                BeingDeleted.reset('on');
                try { eventSource.fireEvent('ObjectDeleted'); }
                catch (PropertyException ex) {}
                DeleteFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
                removeHandleObject(getHandle());
                super.delete();
                Iterator it = eventSourceSet.iterator();
                while (it.hasNext())
                        ((HandleEventSource)it.next()).removeHandleEventSink(this);
                eventSource.delete();
                deleteChildren();
                if (cachedData != null)
                        cachedData.dispose();
                Parent.elementAt(0).removeChild(this);
        }
void deleteChildren () [inline]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
HandleObject getAncestor (Stringtype) [inline]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
Renderer.CachedData getCachedData () [inline]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
java.awt.Component getComponent () [inline]
Reimplemented in FigureObject, UIPanelObject, and UIControlObject.
Referenced by UIControlObject.getParentComponent(), and UIPanelObject.getParentComponent().
        {
                System.out.println('Warning: no component associated with ' + getClass());
                return null;
        }
Property getDefaultProperty (Stringname) [inline]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
double getHandle () [inline]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline]
Reimplemented in GraphicObject, and BaseLineObject.
Referenced by AxesObject.autoLegend(), and LegendObject.buildLegend().
        {
                return false;
        }
boolean isValid () [inline]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
static double newHandle () [inline, static, protected]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented in AxesObject, PatchObject, LegendObject, FigureObject, ColorbarObject, SurfaceObject, TextObject, BarseriesObject, UIPanelObject, UIControlObject, RootObject, LineObject, GroupObject, ImageObject, and BaseLineObject.
Referenced by HandleObject.eventOccured().
        {
        }
void removeChild (HandleObjectchild) [inline]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in UIControlObject, and GraphicObject.
        {
                p.set(value);
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void validate () [inline]
Reimplemented from PropertySet.
Reimplemented in AxesObject, FigureObject, UIPanelObject, GroupObject, UIControlObject, PatchObject, TextObject, SurfaceObject, ImageObject, BarseriesObject, LineObject, and LightObject.
References HandleObject.Children, HandleObject.childValidated(), HandleObjectListProperty.contains(), HandleObject.CreateFcn, HandleObjectListProperty.elementAt(), CallbackProperty.execute(), HandleObject.getHandle(), HandleObject.Parent, HandleObjectListProperty.size(), and HandleObject.valid.
Referenced by RootObject.getInstance().
        {
                super.validate();
                valid = true;
                if (Parent.size() > 0)
                {
                        HandleObject parent = Parent.elementAt(0);
                        if (parent.Children.contains(this))
                                parent.childValidated(this);
                }
                CreateFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void waitFor () [inline]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
void waitFor (Stringpname, final Objectvalue, final booleanhasValue) [inline, private]
References Property.addHandleEventSink(), HandleObject.addHandleEventSink(), HandleObject.eventOccured(), HandleObject.executeOnce(), HandleEvent.getName(), PropertySet.getProperty(), Property.isSameValue(), and HandleObject.sourceDeleted().
        {
                final Object waitObj = new Object();
                final Property p = (pname != null ? getProperty(pname) : null);
                if (pname != null && p == null)
                        return;
                if (hasValue && p != null && p.isSameValue(value))
                        return;
                HandleEventSink sink = new HandleEventSink() {
                        private boolean execFlag = false;
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        {
                                execFlag = false;
                                if (evt.getName().equals('ObjectDeleted'))
                                        Octave.endWaitFor(waitObj);
                                else if (evt.getName().equals('PropertyChanged') && !hasValue)
                                        Octave.endWaitFor(waitObj);
                                else if (p.isSameValue(value))
                                        Octave.endWaitFor(waitObj);
                                else
                                        execFlag = true;
                        }
                        public void sourceDeleted(Object source) {}
                        public boolean executeOnce() { return !execFlag; }
                };
                addHandleEventSink('ObjectDeleted', sink);
                if (p != null)
                        p.addHandleEventSink('PropertyChanged', sink);
                Octave.waitFor(waitObj);
        }
Member Data Documentation
int autoMode = 0 [protected]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
BooleanProperty BeingDeleted [package]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
Renderer.CachedData cachedData = null [private]
Referenced by HandleObject.delete(), HandleObject.getCachedData(), and HandleObject.setCachedData().
HandleObjectListProperty Children [package]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
BooleanProperty Clipping [package]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
PropertySet defaultSet = new PropertySet() [protected]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
HandleEventSourceHelper eventSource [private]
Referenced by HandleObject.addHandleEventSink(), HandleObject.delete(), HandleObject.HandleObject(), HandleObject.hasHandleEvent(), and HandleObject.removeHandleEventSink().
Set eventSourceSet [private]
Referenced by HandleObject.delete(), HandleObject.HandleObject(), HandleObject.listen(), and HandleObject.sourceDeleted().
double handle [private]
Referenced by HandleObject.getHandle(), HandleObject.getHandleObject(), HandleObject.HandleObject(), HandleObject.setHandle(), and FigureObject.updateHandle().
HashMap handleMap = new HashMap() [static, private]
Referenced by HandleObject.addHandleObject(), HandleObject.getHandleObject(), HandleObject.isHandle(), HandleObject.listObjects(), HandleObject.removeHandleObject(), and HandleObject.shutdown().
double handleSeed = -1 - Math.random() [static, private]
Referenced by HandleObject.newHandle().
RadioProperty HandleVisibility [package]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
HandleObjectListProperty Parent [package]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
StringProperty Tag [package]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty Type [package]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
ObjectProperty UserData [package]
Referenced by HandleObject.initProperties().
boolean valid = false [private]
Referenced by HandleObject.isValid(), and HandleObject.validate().
BooleanProperty Visible [package]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
Author
Generated automatically by Doxygen for Octave from the source code.