.TH "org.octave.graphics" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.octave.graphics \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBArrayProperty\fP"
.br
.ti -1c
.RI "class \fBAxesContainer\fP"
.br
.ti -1c
.RI "class \fBAxesObject\fP"
.br
.ti -1c
.RI "class \fBBarseriesObject\fP"
.br
.ti -1c
.RI "class \fBBaseLineObject\fP"
.br
.ti -1c
.RI "class \fBBooleanProperty\fP"
.br
.ti -1c
.RI "class \fBCallback\fP"
.br
.ti -1c
.RI "interface \fBCallbackListener\fP"
.br
.ti -1c
.RI "class \fBCallbackProperty\fP"
.br
.ti -1c
.RI "class \fBCheckBoxControl\fP"
.br
.ti -1c
.RI "class \fBColorbarObject\fP"
.br
.ti -1c
.RI "class \fBColorProperty\fP"
.br
.ti -1c
.RI "class \fBDoubleProperty\fP"
.br
.ti -1c
.RI "class \fBDoubleRadioProperty\fP"
.br
.ti -1c
.RI "class \fBEdit2Control\fP"
.br
.ti -1c
.RI "class \fBEditControl\fP"
.br
.ti -1c
.RI "class \fBFactory\fP"
.br
.ti -1c
.RI "class \fBFigureObject\fP"
.br
.ti -1c
.RI "class \fBGL2PS\fP"
.br
.ti -1c
.RI "class \fBGLRenderCanvas\fP"
.br
.ti -1c
.RI "class \fBGLRenderer\fP"
.br
.ti -1c
.RI "class \fBGraphicObject\fP"
.br
.ti -1c
.RI "class \fBGroupObject\fP"
.br
.ti -1c
.RI "class \fBHandleEvent\fP"
.br
.ti -1c
.RI "interface \fBHandleEventSink\fP"
.br
.ti -1c
.RI "class \fBHandleEventSinkAdapter\fP"
.br
.ti -1c
.RI "interface \fBHandleEventSource\fP"
.br
.ti -1c
.RI "class \fBHandleEventSourceHelper\fP"
.br
.ti -1c
.RI "class \fBHandleObject\fP"
.br
.RI "\fIBase class for handle-based graphics\&. \fP"
.ti -1c
.RI "class \fBHandleObjectListProperty\fP"
.br
.ti -1c
.RI "class \fBImageObject\fP"
.br
.ti -1c
.RI "class \fBJ2DRenderCanvas\fP"
.br
.ti -1c
.RI "class \fBJ2DRenderer\fP"
.br
.ti -1c
.RI "class \fBLegendObject\fP"
.br
.ti -1c
.RI "class \fBLightObject\fP"
.br
.ti -1c
.RI "class \fBLineObject\fP"
.br
.ti -1c
.RI "class \fBLineStyleProperty\fP"
.br
.ti -1c
.RI "class \fBListBoxControl\fP"
.br
.ti -1c
.RI "class \fBMarkerProperty\fP"
.br
.ti -1c
.RI "class \fBMatrix3D\fP"
.br
.ti -1c
.RI "class \fBNotImplProperty\fP"
.br
.ti -1c
.RI "class \fBObjectProperty\fP"
.br
.ti -1c
.RI "class \fBOctaveCallback\fP"
.br
.ti -1c
.RI "class \fBOctaveSink\fP"
.br
.ti -1c
.RI "class \fBPatchObject\fP"
.br
.ti -1c
.RI "class \fBPoint3D\fP"
.br
.ti -1c
.RI "class \fBPopupMenuControl\fP"
.br
.ti -1c
.RI "interface \fBPositionable\fP"
.br
.ti -1c
.RI "class \fBPositionLayout\fP"
.br
.ti -1c
.RI "class \fBProperty\fP"
.br
.RI "\fIAbstract root class for any kind of property\&. \fP"
.ti -1c
.RI "class \fBPropertyException\fP"
.br
.ti -1c
.RI "class \fBPropertySet\fP"
.br
.ti -1c
.RI "class \fBPushButtonControl\fP"
.br
.ti -1c
.RI "class \fBRadioProperty\fP"
.br
.ti -1c
.RI "interface \fBRenderCanvas\fP"
.br
.ti -1c
.RI "interface \fBRenderer\fP"
.br
.ti -1c
.RI "interface \fBRenderEventListener\fP"
.br
.ti -1c
.RI "class \fBRootObject\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\fP"
.br
.ti -1c
.RI "class \fBStringArrayProperty\fP"
.br
.ti -1c
.RI "class \fBStringProperty\fP"
.br
.ti -1c
.RI "class \fBSurfaceObject\fP"
.br
.ti -1c
.RI "class \fBTextControl\fP"
.br
.ti -1c
.RI "class \fBTextObject\fP"
.br
.ti -1c
.RI "class \fBTextProperty\fP"
.br
.ti -1c
.RI "interface \fBUIControl\fP"
.br
.ti -1c
.RI "class \fBUIControlAdapter\fP"
.br
.ti -1c
.RI "class \fBUIControlEvent\fP"
.br
.ti -1c
.RI "class \fBUIControlObject\fP"
.br
.ti -1c
.RI "class \fBUIPanelObject\fP"
.br
.ti -1c
.RI "class \fBUnwindHandleObject\fP"
.br
.ti -1c
.RI "class \fBUtils\fP"
.br
.ti -1c
.RI "class \fBVector3D\fP"
.br
.ti -1c
.RI "class \fBVectorProperty\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
