UIControlObject
NAME
UIControlObject -
SYNOPSIS
Inherits HandleObject.
Public Member Functions
UIControlObject (HandleObject parent)
void delete ()
void validate ()
UIControlAdapter makeControl ()
double[] getPosition ()
Rectangle getBounds ()
Component getComponent ()
Component getParentComponent ()
void propertyChanged (Property p) throws PropertyException
Object get (Property p)
void set (Property p, Object value) throws PropertyException
void controlActivated (UIControlEvent event)
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
boolean isLegendable ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
void set (String name, Object value) throws PropertyException
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Protected Member Functions
void deleteComponent ()
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
ColorProperty BackgroundColor
CallbackProperty Callback
RadioProperty Enable
VectorProperty Extent
RadioProperty FontAngle
StringProperty FontName
DoubleProperty FontSize
RadioProperty FontUnits
RadioProperty FontWeight
ColorProperty ForegroundColor
RadioProperty HorizontalAlignment
DoubleProperty ListboxTop
DoubleProperty Min
DoubleProperty Max
VectorProperty Position
VectorProperty SliderStep
StringProperty UIString
RadioProperty Style
StringProperty TooltipString
RadioProperty Units
VectorProperty Value
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Attributes
UIControlAdapter ctrl
String currentUnits
boolean flag = false
Constructor & Destructor Documentation
UIControlObject (HandleObjectparent) [inline]
References UIControlObject.BackgroundColor, UIControlObject.Enable, UIControlObject.Extent, UIControlObject.FontAngle, UIControlObject.FontName, UIControlObject.FontSize, UIControlObject.FontUnits, UIControlObject.FontWeight, UIControlObject.ForegroundColor, UIControlObject.HorizontalAlignment, UIControlObject.ListboxTop, HandleObject.listen(), UIControlObject.Max, UIControlObject.Min, UIControlObject.Position, UIControlObject.SliderStep, UIControlObject.Style, UIControlObject.TooltipString, UIControlObject.UIString, UIControlObject.Units, and UIControlObject.Value.
        {
                super(parent, 'uicontrol');
                BackgroundColor = new ColorProperty(this, 'BackgroundColor');
                Callback = new CallbackProperty(this, 'Callback', (String)null);
                Enable = new RadioProperty(this, 'Enable', new String[] {'on', 'inactive', 'off'});
                Extent = new VectorProperty(this, 'Extent', 4, new double[] {0, 0, 0, 0});
                FontAngle = new RadioProperty(this, 'FontAngle', new String[] {'normal', 'italic', 'oblique'});
                FontName = new StringProperty(this, 'FontName');
                FontSize = new DoubleProperty(this, 'FontSize');
                FontUnits = new RadioProperty(this, 'FontUnits',
                        new String[] {'points', 'normalized', 'inches', 'centimeters', 'pixels'});
                FontWeight = new RadioProperty(this, 'FontWeight', new String[] {'light', 'normal', 'demi', 'bold'});
                ForegroundColor = new ColorProperty(this, 'ForegroundColor');
                HorizontalAlignment = new RadioProperty(this, 'HorizontalAlignment', new String[] {'left', 'center', 'right'});
                ListboxTop = new DoubleProperty(this, 'ListboxTop', 1);
                Min = new DoubleProperty(this, 'Min');
                Max = new DoubleProperty(this, 'Max');
                Position = new VectorProperty(this, 'Position', 4);
                UIString = new StringProperty(this, 'String');
                SliderStep = new VectorProperty(this, 'SliderStep', 2);
                Style = new RadioProperty(this, 'Style', new String[] {
                          'pushbutton',
                          'togglebutton',
                          'radiobutton',
                          'checkbox',
                          'edit',
                          'text',
                          'slider',
                          'frame',
                          'listbox',
                          'popupmenu'});
                TooltipString = new StringProperty(this, 'TooltipString');
                Units = new RadioProperty(this, 'Units', new String[] {'pixels', 'normalized', 'characters', 'inches',
                        'centimeters', 'points'});
                Value = new VectorProperty(this, 'Value', -1, new double[] {0});
                listen(FontUnits);
                listen(Style);
                listen(Units);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
void controlActivated (UIControlEventevent) [inline]
References UIControlObject.Enable, Callback.execute(), HandleObject.getHandle(), RadioProperty.is(), and HandleObject.isValid().
Referenced by PushButtonControl.actionPerformed(), CheckBoxControl.actionPerformed(), EditControl.actionPerformed(), PopupMenuControl.actionPerformed(), EditControl.focusLost(), Edit2Control.keyTyped(), and ListBoxControl.valueChanged().
        {
                if (isValid() && Enable.is('on'))
                {
                        //System.out.println('Control activated');
                        Callback.execute(new Object[] {
                                new Double(getHandle()),
                                event});
                }
        }
void delete () [inline]
Reimplemented from HandleObject.
References UIControlObject.deleteComponent().
        {
                super.delete();
                deleteComponent();
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void deleteComponent () [inline, protected]
References UIControlObject.ctrl, and UIControlAdapter.dispose().
Referenced by UIControlObject.delete(), UIControlObject.makeControl(), and UIControlObject.validate().
        {
                if (ctrl != null)
                {
                        ctrl.dispose();
                        ctrl = null;
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline]
Reimplemented from PropertySet.
References UIControlObject.ctrl, RadioProperty.is(), UIControlObject.Style, StringProperty.toString(), UIControlObject.UIString, and UIControlAdapter.update().
        {
                if (ctrl != null)
                        ctrl.update();
                if (p == UIString && (Style.is('listbox') || Style.is('popupmenu')))
                        return UIString.toString().split('\|');
                else
                        return super.get(p);
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
Rectangle getBounds () [inline]
References UIControlObject.ctrl.
        {
                return (ctrl != null ? ctrl.getBounds() : new Rectangle());
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
Component getComponent () [inline]
Reimplemented from HandleObject.
References UIControlObject.ctrl, and UIControlAdapter.getComponent().
        {
                if (ctrl != null)
                        return ctrl.getComponent();
                else
                        return null;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Component getParentComponent () [inline]
References HandleObjectListProperty.elementAt(), HandleObject.getComponent(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by UIControlObject.getPosition(), UIControlObject.makeControl(), and UIControlObject.propertyChanged().
        {
                if (Parent.size() > 0)
                {
                        HandleObject obj = Parent.elementAt(0);
                        return obj.getComponent();
                }
                else
                        return null;
        }
double [] getPosition () [inline]
References Utils.convertPosition(), VectorProperty.getArray(), UIControlObject.getParentComponent(), RadioProperty.getValue(), UIControlObject.Position, and UIControlObject.Units.
Referenced by UIControlAdapter.getPosition(), and UIControlAdapter.init().
        {
                Component pComp = getParentComponent();
                if (pComp != null)
                        return Utils.convertPosition(Position.getArray(), Units.getValue(), 'pixels', pComp);
                else
                {
                        System.out.println('Warning: cannot compute position of parentless controls');
                        return new double[] {0, 0, 0, 0};
                }
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented in GraphicObject, and BaseLineObject.
Referenced by AxesObject.autoLegend(), and LegendObject.buildLegend().
        {
                return false;
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
UIControlAdapter makeControl () [inline]
References UIControlObject.ctrl, UIControlObject.deleteComponent(), and UIControlObject.getParentComponent().
Referenced by UIControlObject.validate().
        {
                deleteComponent();
                try { ctrl = new UIControlAdapter(this); }
                catch (Exception e)
                {
                        System.out.println('Warning: unable to create UI control');
                        e.printStackTrace();
                        return null;
                }
                Container pContainer = (Container)getParentComponent();
                pContainer.add(ctrl, 0);
                pContainer.validate();
                return ctrl;
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from HandleObject.
References Utils.convertPosition(), UIControlObject.ctrl, UIControlObject.currentUnits, UIControlObject.FontUnits, VectorProperty.getArray(), UIControlObject.getParentComponent(), RadioProperty.getValue(), UIControlObject.Position, Property.set(), UIControlObject.Style, and UIControlObject.Units.
        {
                super.propertyChanged(p);
                if (p == Style)
                {
                }
                else if (ctrl != null)
                {
                        if (p == Units)
                        {
                                double[] pos = Utils.convertPosition(Position.getArray(), currentUnits, Units.getValue(), getParentComponent());
                                Position.set(pos, true);
                                currentUnits = Units.getValue();
                        }
                        else if (p == FontUnits)
                        {
                        }
                        
                }
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline]
Reimplemented from PropertySet.
References UIControlObject.ctrl, DoubleProperty.doubleValue(), RadioProperty.is(), Utils.join(), UIControlObject.Max, UIControlObject.Min, UIControlObject.Style, UIControlObject.UIString, and UIControlAdapter.update().
        {
                if (ctrl != null)
                        ctrl.update();
                if (p == UIString && value != null)
                {
                        try
                        {
                                String[] items = (String[])value;
                                if (Style.is('listbox') || Style.is('popupmenu'))
                                        value = Utils.join(items, '|');
                                else if (Style.is('text') || (Style.is('edit') && (Max.doubleValue()-Min.doubleValue()) > 1))
                                        value = Utils.join(items, '\n');
                                else
                                        value = (items.length > 0 ? items[0] : '');
                        }
                        catch (ClassCastException e) {}
                }
                super.set(p, value);
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void validate () [inline]
Reimplemented from HandleObject.
References UIControlObject.ctrl, UIControlObject.currentUnits, UIControlObject.deleteComponent(), RadioProperty.getValue(), UIControlObject.makeControl(), and UIControlObject.Units.
        {
                deleteComponent();
                currentUnits = Units.getValue();
                ctrl = makeControl();
                super.validate();
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
ColorProperty BackgroundColor [package]
Referenced by Edit2Control.Edit2Control(), UIControlAdapter.init(), ListBoxControl.ListBoxControl(), Edit2Control.propertyChanged(), UIControlAdapter.propertyChanged(), ListBoxControl.propertyChanged(), UIControlObject.UIControlObject(), and ListBoxControl.updateColors().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
CallbackProperty Callback [package]
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
UIControlAdapter ctrl [private]
Referenced by UIControlObject.deleteComponent(), UIControlObject.get(), UIControlObject.getBounds(), UIControlObject.getComponent(), UIControlObject.makeControl(), UIControlObject.propertyChanged(), UIControlObject.set(), and UIControlObject.validate().
String currentUnits [private]
Referenced by UIControlObject.propertyChanged(), and UIControlObject.validate().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
RadioProperty Enable [package]
Referenced by UIControlObject.controlActivated(), UIControlAdapter.init(), UIControlAdapter.mousePressed(), UIControlAdapter.propertyChanged(), and UIControlObject.UIControlObject().
VectorProperty Extent [package]
Referenced by UIControlObject.UIControlObject().
boolean flag = false [private]
RadioProperty FontAngle [package]
Referenced by UIControlAdapter.init(), UIControlAdapter.propertyChanged(), and UIControlObject.UIControlObject().
StringProperty FontName [package]
Referenced by UIControlAdapter.init(), UIControlAdapter.propertyChanged(), and UIControlObject.UIControlObject().
DoubleProperty FontSize [package]
Referenced by UIControlAdapter.init(), UIControlAdapter.propertyChanged(), and UIControlObject.UIControlObject().
RadioProperty FontUnits [package]
Referenced by UIControlAdapter.init(), UIControlAdapter.propertyChanged(), UIControlObject.propertyChanged(), and UIControlObject.UIControlObject().
RadioProperty FontWeight [package]
Referenced by UIControlAdapter.init(), UIControlAdapter.propertyChanged(), and UIControlObject.UIControlObject().
ColorProperty ForegroundColor [package]
Referenced by Edit2Control.Edit2Control(), UIControlAdapter.init(), ListBoxControl.ListBoxControl(), Edit2Control.propertyChanged(), UIControlAdapter.propertyChanged(), ListBoxControl.propertyChanged(), UIControlObject.UIControlObject(), and ListBoxControl.updateColors().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
RadioProperty HorizontalAlignment [package]
Referenced by Edit2Control.Edit2Control(), EditControl.EditControl(), TextControl.getAlignment(), EditControl.propertyChanged(), Edit2Control.propertyChanged(), TextControl.propertyChanged(), Edit2Control.setAlignment(), EditControl.setAlignment(), TextControl.stringToHTML(), TextControl.TextControl(), and UIControlObject.UIControlObject().
DoubleProperty ListboxTop [package]
Referenced by ListBoxControl.ListBoxControl(), ListBoxControl.propertyChanged(), UIControlObject.UIControlObject(), ListBoxControl.update(), and ListBoxControl.updateTop().
DoubleProperty Max [package]
Referenced by ListBoxControl.ListBoxControl(), CheckBoxControl.propertyChanged(), ListBoxControl.propertyChanged(), UIControlObject.set(), UIControlObject.UIControlObject(), CheckBoxControl.update(), and ListBoxControl.updateSelectionMode().
DoubleProperty Min [package]
Referenced by ListBoxControl.ListBoxControl(), ListBoxControl.propertyChanged(), UIControlObject.set(), UIControlObject.UIControlObject(), CheckBoxControl.update(), and ListBoxControl.updateSelectionMode().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
VectorProperty Position [package]
Referenced by UIControlObject.getPosition(), UIControlAdapter.propertyChanged(), UIControlObject.propertyChanged(), and UIControlObject.UIControlObject().
VectorProperty SliderStep [package]
Referenced by UIControlObject.UIControlObject().
RadioProperty Style [package]
Referenced by UIControlObject.get(), UIControlObject.propertyChanged(), UIControlObject.set(), and UIControlObject.UIControlObject().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty TooltipString [package]
Referenced by UIControlAdapter.init(), UIControlAdapter.propertyChanged(), and UIControlObject.UIControlObject().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
StringProperty UIString [package]
Referenced by CheckBoxControl.CheckBoxControl(), Edit2Control.Edit2Control(), EditControl.EditControl(), UIControlObject.get(), ListBoxControl.ListBoxControl(), PopupMenuControl.PopupMenuControl(), CheckBoxControl.propertyChanged(), PushButtonControl.propertyChanged(), EditControl.propertyChanged(), PopupMenuControl.propertyChanged(), Edit2Control.propertyChanged(), TextControl.propertyChanged(), ListBoxControl.propertyChanged(), PushButtonControl.PushButtonControl(), UIControlObject.set(), TextControl.TextControl(), UIControlObject.UIControlObject(), EditControl.update(), Edit2Control.update(), PopupMenuControl.updateItems(), and ListBoxControl.updateItems().
RadioProperty Units [package]
Referenced by UIControlObject.getPosition(), UIControlObject.propertyChanged(), UIControlObject.UIControlObject(), and UIControlObject.validate().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
VectorProperty Value [package]
Referenced by CheckBoxControl.CheckBoxControl(), ListBoxControl.ListBoxControl(), PopupMenuControl.PopupMenuControl(), CheckBoxControl.propertyChanged(), PopupMenuControl.propertyChanged(), ListBoxControl.propertyChanged(), UIControlObject.UIControlObject(), CheckBoxControl.update(), PopupMenuControl.update(), ListBoxControl.update(), PopupMenuControl.updateValue(), and ListBoxControl.updateValue().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
Author
Generated automatically by Doxygen for Octave from the source code.