UIPanelObject
NAME
UIPanelObject -
SYNOPSIS
Inherits AxesContainer, and ComponentListener.
Classes
class PanelWrapper
Public Member Functions
UIPanelObject (HandleObject parent)
void delete ()
void validate ()
void makePanel ()
double[] getPosition ()
Component getComponent ()
Component getParentComponent ()
void propertyChanged (Property p) throws PropertyException
void componentHidden (ComponentEvent e)
void componentMoved (ComponentEvent e)
void componentResized (ComponentEvent e)
void componentShown (ComponentEvent e)
HandleObject getObjectForPoint (Point pt, int margin)
AxesObject getAxesForPoint (Point pt)
void redraw ()
boolean hasMouseOperation ()
void cancelMouseOperation ()
void reshape (RenderCanvas c, int x, int y, int width, int height)
void display (RenderCanvas c)
void mouseClicked (MouseEvent e)
void mouseEntered (MouseEvent e)
void mouseExited (MouseEvent e)
void mousePressed (MouseEvent e)
void mouseReleased (MouseEvent e)
void mouseMoved (MouseEvent e)
void mouseDragged (MouseEvent e)
RenderCanvas getCanvas ()
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
boolean isLegendable ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
Object get (Property p)
void set (String name, Object value) throws PropertyException
void set (Property p, Object value) throws PropertyException
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static void redrawRecursive (HandleObject obj)
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Static Public Attributes
static final int OP_NONE = 0
static final int OP_ZOOM = 1
static final int OP_ROTATE = 2
Protected Member Functions
void deleteComponent ()
Color getBackgroundColor ()
Container getEmbeddingComponent ()
Point getMouseLocation (MouseEvent e)
void updateCanvas ()
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
JPanel panel
Panel panelWrapper
RenderCanvas canvas = null
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
ColorProperty BackgroundColor
RadioProperty BorderType
RadioProperty FontAngle
StringProperty FontName
DoubleProperty FontSize
RadioProperty FontUnits
RadioProperty FontWeight
ColorProperty ForegroundColor
ColorProperty HighlightColor
VectorProperty Position
CallbackProperty ResizeFcn
ColorProperty ShadowColor
StringProperty Title
RadioProperty TitlePosition
RadioProperty Units
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
Border makeBorder ()
Private Attributes
String currentUnits
Constructor & Destructor Documentation
UIPanelObject (HandleObjectparent) [inline]
References UIPanelObject.BackgroundColor, UIPanelObject.BorderType, UIPanelObject.FontAngle, UIPanelObject.FontName, UIPanelObject.FontSize, UIPanelObject.FontUnits, UIPanelObject.FontWeight, UIPanelObject.ForegroundColor, Utils.getBackgroundColor(), Utils.getHighlightColor(), Utils.getShadowColor(), UIPanelObject.HighlightColor, HandleObject.listen(), HandleObject.newHandle(), UIPanelObject.Position, UIPanelObject.ResizeFcn, UIPanelObject.ShadowColor, UIPanelObject.Title, UIPanelObject.TitlePosition, and UIPanelObject.Units.
        {
                super(parent, 'uipanel', newHandle());
                BackgroundColor = new ColorProperty(this, 'BackgroundColor', Utils.getBackgroundColor());
                BorderType = new RadioProperty(this, 'BorderType', new String[] {'none', 'etchedin', 'etchedout',
                        'beveledin', 'beveledout', 'line'}, 'etchedin');
                FontAngle = new RadioProperty(this, 'FontAngle', new String[] {'normal', 'italic', 'oblique'}, 'normal');
                FontName = new StringProperty(this, 'FontName', 'Helvetica');
                FontSize = new DoubleProperty(this, 'FontSize', 8);
                FontUnits = new RadioProperty(this, 'FontUnits',
                        new String[] {'points', 'normalized', 'inches', 'centimeters', 'pixels'}, 'points');
                FontWeight = new RadioProperty(this, 'FontWeight', new String[] {'light', 'normal', 'demi', 'bold'}, 'normal');
                ForegroundColor = new ColorProperty(this, 'ForegroundColor', Color.black);
                HighlightColor = new ColorProperty(this, 'HighlightColor', Utils.getHighlightColor());
                Position = new VectorProperty(this, 'Position', 4, new double[] {0, 0, 1, 1});
                ResizeFcn = new CallbackProperty(this, 'ResizeFcn', (String)null);
                ShadowColor = new ColorProperty(this, 'ShadowColor', Utils.getShadowColor());
                Title = new StringProperty(this, 'Title', '');
                TitlePosition = new RadioProperty(this, 'TitlePosition', new String[] {
                        'lefttop', 'centertop', 'righttop',
                        'leftbottom', 'centerbottom', 'rightbottom'}, 'lefttop');
                Units = new RadioProperty(this, 'Units', new String[] {'pixels', 'normalized', 'characters',
                        'inches', 'centimeters', 'points'}, 'normalized');
                listen(BackgroundColor);
                listen(FontAngle);
                listen(FontName);
                listen(FontSize);
                listen(FontUnits);
                listen(FontWeight);
                listen(ForegroundColor);
                listen(HighlightColor);
                listen(Position);
                listen(ShadowColor);
                listen(Title);
                listen(TitlePosition);
                listen(Units);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void cancelMouseOperation () [inline, inherited]
References AxesObject.cancelOperation(), AxesContainer.hasMouseOperation(), AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
Referenced by FigureObject.windowDeactivated().
        {
                if (hasMouseOperation())
                {
                        mouseAxes.cancelOperation(mouseOp);
                        mouseAxes = null;
                        mouseOp = OP_NONE;
                }
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
void componentHidden (ComponentEvente) [inline]
{}
void componentMoved (ComponentEvente) [inline]
{}
void componentResized (ComponentEvente) [inline]
References CallbackProperty.execute(), HandleObject.getHandle(), and UIPanelObject.ResizeFcn.
        {
                ResizeFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void componentShown (ComponentEvente) [inline]
{}
void delete () [inline]
Reimplemented from HandleObject.
References UIPanelObject.deleteComponent().
        {
                super.delete();
                deleteComponent();
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void deleteComponent () [inline, protected]
References UIPanelObject.panel, and UIPanelObject.panelWrapper.
Referenced by UIPanelObject.delete(), and UIPanelObject.validate().
        {
                if (panel != null)
                {
                        panelWrapper.getParent().remove(panelWrapper);
                        panel = null;
                        panelWrapper = null;
                }
        }
void display (RenderCanvasc) [inline, inherited]
Implements RenderEventListener.
References HandleObject.Children, Renderer.clear(), AxesContainer.getBackgroundColor(), RenderCanvas.getRenderer(), HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
        {
                Renderer r = c.getRenderer();
                // clear background
                r.clear(getBackgroundColor());
                // iterate over axes objects
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (hObj instanceof AxesObject && hObj.isValid())
                                        ((AxesObject)hObj).draw(r);
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxesForPoint (Pointpt) [inline, inherited]
References AxesContainer.getObjectForPoint().
Referenced by AxesContainer.mouseClicked(), and AxesContainer.mousePressed().
        {
                HandleObject obj = getObjectForPoint(pt, 0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                return null;
        }
Color getBackgroundColor () [inline, protected, virtual]
Implements AxesContainer.
References UIPanelObject.BackgroundColor, and ColorProperty.getColor().
        {
                return BackgroundColor.getColor();
        }
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
RenderCanvas getCanvas () [inline, inherited]
Implements RenderCanvas.Container.
References AxesContainer.canvas, and AxesContainer.createCanvas().
Referenced by FigureObject.createFigure().
        {
                if (canvas == null)
                        createCanvas();
                return canvas;
        }
Component getComponent () [inline]
Reimplemented from HandleObject.
References UIPanelObject.panel.
        {
                return panel;
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
Container getEmbeddingComponent () [inline, protected, virtual]
Implements AxesContainer.
References UIPanelObject.panel.
        {
                return panel;
        }
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
Point getMouseLocation (MouseEvente) [inline, protected, inherited]
References AxesContainer.canvas, RenderCanvas.getX(), and RenderCanvas.getY().
Referenced by AxesContainer.mouseClicked(), and AxesContainer.mousePressed().
        {
                Point pt = new Point(e.getPoint());
                if (e.getSource() == canvas)
                        pt.translate(canvas.getX(), canvas.getY());
                return pt;
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
HandleObject getObjectForPoint (Pointpt, intmargin) [inline, inherited]
References AxesContainer.canvas, HandleObject.Children, AxesContainer.getEmbeddingComponent(), RenderCanvas.getHeight(), RenderCanvas.getX(), RenderCanvas.getY(), HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
Referenced by AxesContainer.getAxesForPoint(), and AxesContainer.mousePressed().
        {
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        Insets insets = getEmbeddingComponent().getInsets();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (!hObj.isValid())
                                        continue;
                                if (hObj instanceof UIControlObject)
                                {
                                        Rectangle r = ((UIControlObject)hObj).getBounds();
                                        r.setRect(r.x-margin, r.y-margin, r.width+2*margin, r.height+2*margin);
                                        if (r.contains(pt))
                                                return hObj;
                                }
                                else if (hObj instanceof AxesObject)
                                {
                                        Rectangle r = ((AxesObject)hObj).getBoundingBox();
                                        if (r.contains(pt.x-canvas.getX(), canvas.getHeight()-pt.y+canvas.getY()))
                                                return hObj;
                                }
                        }
                }
                return null;
        }
Component getParentComponent () [inline]
References HandleObjectListProperty.elementAt(), HandleObject.getComponent(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by UIPanelObject.getPosition(), UIPanelObject.makePanel(), and UIPanelObject.propertyChanged().
        {
                if (Parent.size() > 0)
                {
                        HandleObject obj = Parent.elementAt(0);
                        return obj.getComponent();
                }
                else
                        return null;
        }
double [] getPosition () [inline]
References Utils.convertPosition(), VectorProperty.getArray(), UIPanelObject.getParentComponent(), RadioProperty.getValue(), UIPanelObject.Position, and UIPanelObject.Units.
Referenced by UIPanelObject.PanelWrapper.getPosition().
        {
                Component pComp = getParentComponent();
                if (pComp != null)
                        return Utils.convertPosition(Position.getArray(), Units.getValue(), 'pixels', pComp);
                else
                {
                        System.out.println('Warning: cannot compute position of parentless controls');
                        return new double[] {0, 0, 0, 0};
                }
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasMouseOperation () [inline, inherited]
References AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
Referenced by AxesContainer.cancelMouseOperation().
        {
                return (mouseOp != OP_NONE && mouseAxes != null);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented in GraphicObject, and BaseLineObject.
Referenced by AxesObject.autoLegend(), and LegendObject.buildLegend().
        {
                return false;
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
Border makeBorder () [inline, private]
References UIPanelObject.BorderType, ColorProperty.getColor(), UIPanelObject.HighlightColor, RadioProperty.is(), and UIPanelObject.ShadowColor.
Referenced by UIPanelObject.makePanel().
        {
                if (BorderType.is('etchedin'))
                        return BorderFactory.createEtchedBorder(HighlightColor.getColor(), ShadowColor.getColor());
                else if (BorderType.is('etchedout'))
                        return BorderFactory.createEtchedBorder(EtchedBorder.RAISED, HighlightColor.getColor(), ShadowColor.getColor());
                else if (BorderType.is('beveledin'))
                        return BorderFactory.createBevelBorder(BevelBorder.LOWERED, HighlightColor.getColor(), ShadowColor.getColor());
                else if (BorderType.is('beveledout'))
                        return BorderFactory.createBevelBorder(BevelBorder.RAISED, HighlightColor.getColor(), ShadowColor.getColor());
                else if (BorderType.is('line'))
                        return BorderFactory.createLineBorder(ShadowColor.getColor());
                else
                        return BorderFactory.createEmptyBorder();
        }
void makePanel () [inline]
References UIPanelObject.BackgroundColor, UIPanelObject.FontAngle, UIPanelObject.FontName, UIPanelObject.FontSize, UIPanelObject.FontUnits, UIPanelObject.FontWeight, UIPanelObject.ForegroundColor, ColorProperty.getColor(), Utils.getFont(), UIPanelObject.getParentComponent(), RadioProperty.getValue(), UIPanelObject.makeBorder(), UIPanelObject.panel, UIPanelObject.panelWrapper, UIPanelObject.Title, UIPanelObject.TitlePosition, and StringProperty.toString().
Referenced by UIPanelObject.validate().
        {
                TitledBorder border = BorderFactory.createTitledBorder(
                                makeBorder(),
                                Title.toString());
                String tPos = TitlePosition.getValue().toLowerCase();
                
                panel = new JPanel(new PositionLayout());
                panel.setBackground(BackgroundColor.getColor());
                panelWrapper = new PanelWrapper(this);
                panelWrapper.add(panel, BorderLayout.CENTER);
                border.setTitleFont(Utils.getFont(FontName, FontSize, FontUnits, FontAngle, FontWeight, panelWrapper.getHeight()));
                border.setTitleColor(ForegroundColor.getColor());
                border.setTitlePosition(tPos.contains('bottom') ? TitledBorder.BOTTOM : TitledBorder.TOP);
                border.setTitleJustification(
                                tPos.contains('left') ? TitledBorder.LEFT :
                                tPos.contains('center') ? TitledBorder.CENTER :
                                tPos.contains('right') ? TitledBorder.RIGHT :
                                TitledBorder.LEFT);
                panel.setBorder(border);
                panel.addComponentListener(this);
                Container pContainer = (Container)getParentComponent();
                pContainer.add(panelWrapper, 0);
                pContainer.validate();
        }
void mouseClicked (MouseEvente) [inline, inherited]
References AxesContainer.getAxesForPoint(), AxesContainer.getDefaultMouseOp(), AxesContainer.getMouseLocation(), AxesContainer.mouseOp, AxesContainer.OP_NONE, AxesContainer.OP_ZOOM, and AxesObject.unZoom().
        {
                if (e.getButton() == MouseEvent.BUTTON3 && mouseOp == OP_NONE && getDefaultMouseOp() == OP_ZOOM)
                {
                        AxesObject ax = getAxesForPoint(getMouseLocation(e));
                        if (ax != null)
                                ax.unZoom();
                }
        }
void mouseDragged (MouseEvente) [inline, inherited]
References AxesContainer.mouseAxes, AxesContainer.mouseOp, AxesContainer.OP_NONE, and AxesObject.operation().
        {
                if (mouseAxes != null && mouseOp != OP_NONE)
                        mouseAxes.operation(mouseOp, e);
        }
void mouseEntered (MouseEvente) [inline, inherited]
{}
void mouseExited (MouseEvente) [inline, inherited]
{}
void mouseMoved (MouseEvente) [inline, inherited]
{}
void mousePressed (MouseEvente) [inline, inherited]
References HandleObject.doButtonDownFcn(), AxesContainer.getAxesForPoint(), AxesContainer.getDefaultMouseOp(), AxesContainer.getMouseLocation(), AxesContainer.getObjectForPoint(), AxesContainer.mouseAxes, AxesContainer.mouseOp, AxesContainer.OP_NONE, and AxesObject.startOperation().
        {
                if (mouseOp == OP_NONE)
                {
                        // Only do something if no operation pending
                        Point pt = getMouseLocation(e);
                        AxesObject ax = getAxesForPoint(pt);
                        HandleObject hObj = getObjectForPoint(pt, 5);
                        if (hObj != null)
                        {
                                boolean doCB = false;
                                if (hObj instanceof AxesObject)
                                {
                                        if (getDefaultMouseOp() == OP_NONE)
                                                doCB = true;
                                        else if (e.getButton() == MouseEvent.BUTTON1)
                                        {
                                                mouseAxes = (AxesObject)hObj;
                                                mouseOp = getDefaultMouseOp();
                                                mouseAxes.startOperation(mouseOp, e);
                                        }
                                }
                                else
                                        doCB = true;
                                if (doCB)
                                        hObj.doButtonDownFcn(e);
                        }
                        else
                                doButtonDownFcn(e);
                }
        }
void mouseReleased (MouseEvente) [inline, inherited]
References AxesObject.endOperation(), AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
        {
                if (mouseOp != OP_NONE)
                {
                        if (e.getButton() == MouseEvent.BUTTON1)
                        {
                                if (mouseAxes != null)
                                        mouseAxes.endOperation(mouseOp, e);
                                mouseAxes = null;
                                mouseOp = OP_NONE;
                        }
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
Reimplemented from HandleObject.
References UIPanelObject.BackgroundColor, Utils.convertPosition(), UIPanelObject.currentUnits, UIPanelObject.FontAngle, UIPanelObject.FontName, UIPanelObject.FontSize, UIPanelObject.FontUnits, UIPanelObject.FontWeight, UIPanelObject.ForegroundColor, VectorProperty.getArray(), ColorProperty.getColor(), Utils.getFont(), UIPanelObject.getParentComponent(), RadioProperty.getValue(), UIPanelObject.HighlightColor, UIPanelObject.panel, UIPanelObject.panelWrapper, UIPanelObject.Position, Property.set(), UIPanelObject.ShadowColor, UIPanelObject.Title, UIPanelObject.TitlePosition, StringProperty.toString(), and UIPanelObject.Units.
        {
                super.propertyChanged(p);
                if (panel != null)
                {
                        TitledBorder border = (TitledBorder)panel.getBorder();
                        if (p == BackgroundColor)
                                panel.setBackground(BackgroundColor.getColor());
                        else if (p == FontAngle || p == FontName || p == FontSize ||
                                        p == FontWeight || p == FontUnits)
                        {
                                border.setTitleFont(Utils.getFont(FontName, FontSize, FontUnits, FontAngle, FontWeight, panelWrapper.getHeight()));
                                panel.doLayout();
                                panel.validate();
                        }
                        else if (p == ForegroundColor)
                                border.setTitleColor(ForegroundColor.getColor());
                        else if (p == HighlightColor || p == ShadowColor)
                                border.setBorder(BorderFactory.createEtchedBorder(HighlightColor.getColor(), ShadowColor.getColor()));
                        else if (p == Position)
                        {
                                panelWrapper.getParent().doLayout();
                                panelWrapper.getParent().validate();
                        }
                        else if (p == Title)
                        {
                                border.setTitle(Title.toString());
                                panel.doLayout();
                                panel.validate();
                        }
                        else if (p == TitlePosition)
                        {
                                String loc = TitlePosition.getValue().toLowerCase();
                                border.setTitlePosition(loc.contains('bottom') ? TitledBorder.BOTTOM : TitledBorder.TOP);
                                border.setTitleJustification(
                                                loc.contains('left') ? TitledBorder.LEFT :
                                                loc.contains('center') ? TitledBorder.CENTER :
                                                loc.contains('right') ? TitledBorder.RIGHT :
                                                TitledBorder.LEFT);
                                panel.doLayout();
                                panel.validate();
                        }
                        else if (p == Units)
                        {
                                double[] pos = Utils.convertPosition(Position.getArray(), currentUnits, Units.getValue(), getParentComponent());
                                Position.set(pos, true);
                                currentUnits = Units.getValue();
                        }
                        panel.repaint();
                }
        }
void redraw () [inline, inherited]
References AxesContainer.redrawRecursive().
        {
                redrawRecursive(this);
        }
static void redrawRecursive (HandleObjectobj) [inline, static, inherited]
Referenced by AxesContainer.redraw().
        {
                if (obj instanceof RenderCanvas.Container)
                        ((RenderCanvas.Container)obj).getCanvas().redraw();
                synchronized (obj.Children)
                {
                        Iterator it = obj.Children.iterator();
                        while (it.hasNext())
                                redrawRecursive((HandleObject)it.next());
                }
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void reshape (RenderCanvasc, intx, inty, intwidth, intheight) [inline, inherited]
Implements RenderEventListener.
References HandleObject.Children, HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
        {
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (hObj instanceof AxesObject && hObj.isValid())
                                        ((AxesObject)hObj).updateActivePosition();
                        }
                }
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in UIControlObject, and GraphicObject.
        {
                p.set(value);
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void updateCanvas () [inline, protected, inherited]
References AxesContainer.canvas, AxesContainer.createCanvas(), RenderCanvas.getComponent(), AxesContainer.getEmbeddingComponent(), RenderCanvas.removeMouseListener(), RenderCanvas.removeMouseMotionListener(), and RenderCanvas.removeRenderEventListener().
Referenced by FigureObject.propertyChanged().
        {
                if (canvas != null)
                {
                        canvas.removeMouseListener(this);
                        canvas.removeMouseMotionListener(this);
                        canvas.removeRenderEventListener(this);
                        getEmbeddingComponent().remove(canvas.getComponent());
                        getEmbeddingComponent().validate();
                        canvas = null;
                }
                createCanvas();
        }
void validate () [inline]
Reimplemented from HandleObject.
References UIPanelObject.currentUnits, UIPanelObject.deleteComponent(), RadioProperty.getValue(), UIPanelObject.makePanel(), and UIPanelObject.Units.
        {
                deleteComponent();
                currentUnits = Units.getValue();
                makePanel();
                super.validate();
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
ColorProperty BackgroundColor [package]
Referenced by UIPanelObject.getBackgroundColor(), UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
RadioProperty BorderType [package]
Referenced by UIPanelObject.makeBorder(), and UIPanelObject.UIPanelObject().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
RenderCanvas canvas = null [protected, inherited]
Referenced by AxesContainer.createCanvas(), AxesContainer.getCanvas(), AxesContainer.getMouseLocation(), AxesContainer.getObjectForPoint(), FigureObject.print(), and AxesContainer.updateCanvas().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
String currentUnits [private]
Referenced by UIPanelObject.propertyChanged(), and UIPanelObject.validate().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
RadioProperty FontAngle [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
StringProperty FontName [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
DoubleProperty FontSize [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
RadioProperty FontUnits [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
RadioProperty FontWeight [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
ColorProperty ForegroundColor [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
ColorProperty HighlightColor [package]
Referenced by UIPanelObject.makeBorder(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
final int OP_NONE = 0 [static, inherited]
Referenced by FigureObject.actionPerformed(), AxesContainer.cancelMouseOperation(), FigureObject.commandToOp(), AxesContainer.hasMouseOperation(), AxesContainer.mouseClicked(), AxesContainer.mouseDragged(), AxesContainer.mousePressed(), and AxesContainer.mouseReleased().
final int OP_ROTATE = 2 [static, inherited]
Referenced by AxesObject.cancelOperation(), FigureObject.commandToOp(), AxesObject.endOperation(), AxesObject.operation(), and AxesObject.startOperation().
final int OP_ZOOM = 1 [static, inherited]
Referenced by AxesObject.cancelOperation(), FigureObject.commandToOp(), AxesObject.endOperation(), AxesContainer.mouseClicked(), AxesObject.operation(), and AxesObject.startOperation().
JPanel panel [protected]
Referenced by UIPanelObject.deleteComponent(), UIPanelObject.getComponent(), UIPanelObject.getEmbeddingComponent(), UIPanelObject.makePanel(), and UIPanelObject.propertyChanged().
Panel panelWrapper [protected]
Referenced by UIPanelObject.deleteComponent(), UIPanelObject.makePanel(), and UIPanelObject.propertyChanged().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
VectorProperty Position [package]
Referenced by UIPanelObject.getPosition(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
CallbackProperty ResizeFcn [package]
Referenced by UIPanelObject.componentResized(), and UIPanelObject.UIPanelObject().
ColorProperty ShadowColor [package]
Referenced by UIPanelObject.makeBorder(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty Title [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
RadioProperty TitlePosition [package]
Referenced by UIPanelObject.makePanel(), UIPanelObject.propertyChanged(), and UIPanelObject.UIPanelObject().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
RadioProperty Units [package]
Referenced by UIPanelObject.getPosition(), UIPanelObject.propertyChanged(), UIPanelObject.UIPanelObject(), and UIPanelObject.validate().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
Author
Generated automatically by Doxygen for Octave from the source code.