Factory
NAME
Factory -
SYNOPSIS
Inherits PropertySet.
Public Member Functions
void addProperty (Property p)
Property getProperty (String name)
boolean hasProperty (String name)
Object get (String name) throws PropertyException
Object get (Property p)
void set (String name, Object value) throws PropertyException
void set (Property p, Object value) throws PropertyException
void show ()
void validate ()
String[] getNames ()
void delete ()
Static Public Member Functions
static Property getDefaultProperty (String name)
Static Package Functions
[static initializer]
Private Member Functions
Factory ()
void initLineProperties ()
void initUIControlProperties ()
Static Private Attributes
static Factory self = new Factory()
Constructor & Destructor Documentation
Factory () [inline, private]
References Factory.initLineProperties(), and Factory.initUIControlProperties().
        {
                initLineProperties();
                initUIControlProperties();
        }
Member Function Documentation
[static initializer] () [inline, static, package]
void addProperty (Propertyp) [inline, inherited]
Reimplemented in HandleObject.
References Property.getName().
Referenced by Property.Property(), and HandleObject.set().
        {
                put(p.getName().toLowerCase(), p);
        }
void delete () [inline, inherited]
Reimplemented in FigureObject, HandleObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                        ((Property)it.next()).delete();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented in HandleObject.
References PropertySet.getProperty().
        {
                Property p = getProperty(name);
                if (p != null)
                        return get(p);
                throw new PropertyException('property not found - ' + name);
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
static Property getDefaultProperty (Stringname) [inline, static]
Referenced by HandleObject.getDefaultProperty().
        {
                return self.getProperty(name);
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initLineProperties () [inline, private]
Referenced by Factory.Factory().
        {
                // BeingDeleted
                new RadioProperty(this, 'DefaultLineBusyAction', new String[] {'cancel', 'queue'}, 'queue');
                new CallbackProperty(this, 'DefaultLineButtonDownFcn', (String)null);
                // Children
                new BooleanProperty(this, 'DefaultLineClipping', true);
                new ColorProperty(this, 'DefaultLineColor', Color.black);
                new CallbackProperty(this, 'DefaultLineCreateFcn', (String)null);
                new CallbackProperty(this, 'DefaultLineDeleteFcn', (String)null);
                new RadioProperty(this, 'DefaultLineEraseMode', new String[] {'normal', 'none', 'xor', 'background'}, 'normal');
                new RadioProperty(this, 'DefaultLineHandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                new BooleanProperty(this, 'DefaultLineHitTest', true);
                new BooleanProperty(this, 'DefaultLineInterruptible', true);
                new LineStyleProperty(this, 'DefaultLineLineStyle', '-');
                new DoubleProperty(this, 'DefaultLineLineWidth', 0.5);
                new MarkerProperty(this, 'DefaultLineMarker', 'none');
                new ColorProperty(this, 'DefaultLineMarkerEdgeColor', new String[] {'none', 'auto'}, 'auto');
                new ColorProperty(this, 'DefaultLineMarkerFaceColor', new String[] {'none', 'auto'}, 'none');
                new DoubleProperty(this, 'DefaultLineMarkerSize', 6);
                // Parent
                // Selected
                new BooleanProperty(this, 'DefaultLineSelectionHighlight', true);
                new StringProperty(this, 'DefaultLineTag', '');
                // Type
                // UIContextMenu
                new ObjectProperty(this, 'DefaultLineUserData', null);
                new BooleanProperty(this, 'DefaultLineVisible', true);
                new VectorProperty(this, 'DefaultLineXData', -1, new double[] {0, 1});
                new VectorProperty(this, 'DefaultLineYData', -1, new double[] {0, 1});
                new VectorProperty(this, 'DefaultLineZData', -1, new Matrix());
        }
void initUIControlProperties () [inline, private]
References Utils.getBackgroundColor().
Referenced by Factory.Factory().
        {
                // BeingDeleted
                new ColorProperty(this, 'DefaultUIControlBackgroundColor', (Color)Utils.getBackgroundColor());
                new RadioProperty(this, 'DefaultUIControlBusyAction', new String[] {'cancel', 'queue'}, 'queue');
                new CallbackProperty(this, 'DefaultUIControlButtonDownFcn', (String)null);
                // Callback
                new ArrayProperty(this, 'DefaultUIControlCData', new String[] {'double'}, 3, new Matrix());
                // Children
                new BooleanProperty(this, 'DefaultUIControlClipping', true);
                new CallbackProperty(this, 'DefaultUIControlCreateFcn', (String)null);
                new CallbackProperty(this, 'DefaultUIControlDeleteFcn', (String)null);
                new RadioProperty(this, 'DefaultUIControlEnable', new String[] {'on', 'inactive', 'off'}, 'on');
                // Extent
                new RadioProperty(this, 'DefaultUIControlFontAngle', new String[] {'normal', 'italic', 'oblique'}, 'normal');
                new StringProperty(this, 'DefaultUIControlFontName', 'Helvetica');
                new DoubleProperty(this, 'DefaultUIControlFontSize', 8);
                new RadioProperty(this, 'DefaultUIControlFontUnits',
                        new String[] {'points', 'normalized', 'inches', 'centimeters', 'pixels'}, 'points');
                new RadioProperty(this, 'DefaultUIControlFontWeight', new String[] {'light', 'normal', 'demi', 'bold'}, 'normal');
                new ColorProperty(this, 'DefaultUIControlForegroundColor', Color.black);
                new RadioProperty(this, 'DefaultUIControlHandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                new BooleanProperty(this, 'DefaultUIControlHitTest', true);
                new RadioProperty(this, 'DefaultUIControlHorizontalAlignment', new String[] {'left', 'center', 'right'}, 'center');
                new BooleanProperty(this, 'DefaultUIControlInterruptible', true);
                new CallbackProperty(this, 'DefaultUIControlKeyPressFcn', (String)null);
                // ListboxTop
                new DoubleProperty(this, 'DefaultUIControlMax', 1.0);
                new DoubleProperty(this, 'DefaultUIControlMin', 0.0);
                // Parent
                new VectorProperty(this, 'DefaultUIControlPosition', 4, new double[] {10, 10, 80, 24});
                // Selected
                new BooleanProperty(this, 'DefaultUIControlSelectionHighlight', true);
                new VectorProperty(this, 'DefaultUIControlSliderStep', 2, new double[] {0.01, 0.10});
                new StringProperty(this, 'DefaultUIControlString', '');
                new RadioProperty(this, 'DefaultUIControlStyle', new String[] {'pushbutton', 'togglebutton', 'radiobutton',
                        'checkbox', 'text', 'edit', 'slider', 'frame', 'listbox', 'popupmenu'}, 'pushbutton');
                new StringProperty(this, 'DefaultUIControlTag', '');
                new StringProperty(this, 'DefaultUIControlTooltipString', '');
                new RadioProperty(this, 'DefaultUIControlUnits',
                        new String[] {'pixels', 'normalized', 'inches', 'centimeters', 'points', 'characters'}, 'pixels');
                new ObjectProperty(this, 'DefaultUIControlUserData', null);
                new BooleanProperty(this, 'DefaultUIControlVisible', true);
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in HandleObject.
References PropertySet.getProperty().
        {
                Property p = getProperty(name);
                if (p != null)
                        set(p, value);
                else
                        throw new PropertyException('property not found - ' + name);
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in UIControlObject, and GraphicObject.
        {
                p.set(value);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
void validate () [inline, inherited]
Reimplemented in AxesObject, HandleObject, FigureObject, UIPanelObject, GroupObject, UIControlObject, PatchObject, TextObject, SurfaceObject, ImageObject, BarseriesObject, LineObject, and LightObject.
References Property.unLock().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        p.unLock();
                }
        }
Member Data Documentation
Factory self = new Factory() [static, private]
Author
Generated automatically by Doxygen for Octave from the source code.