TextControl
NAME
TextControl -
SYNOPSIS
Inherits JLabel, and UIControl.
Public Member Functions
TextControl (UIControlObject obj)
void propertyChanged (Property p) throws PropertyException
void update ()
JComponent getComponent ()
void dispose ()
Private Member Functions
String stringToHTML (String s)
int getAlignment ()
Private Attributes
UIControlObject uiObj
HandleEventSinkAdapter sink
Constructor & Destructor Documentation
TextControl (UIControlObjectobj) [inline]
References TextControl.getAlignment(), HandleEvent.getProperty(), UIControlObject.HorizontalAlignment, HandleEventSinkAdapter.listen(), TextControl.propertyChanged(), TextControl.sink, TextControl.stringToHTML(), StringProperty.toString(), TextControl.uiObj, and UIControlObject.UIString.
        {
                super();
                uiObj = obj;
                setText(stringToHTML(obj.UIString.toString()));
                setVerticalAlignment(SwingConstants.TOP);
                setHorizontalAlignment(getAlignment());
                setOpaque(true);
                sink = new HandleEventSinkAdapter() {
                        public void eventOccured(HandleEvent evt) throws PropertyException
                        { propertyChanged(evt.getProperty()); }
                };
                sink.listen(obj.UIString);
                sink.listen(obj.HorizontalAlignment);
        }
Member Function Documentation
void dispose () [inline]
Implements UIControl.
References HandleEventSinkAdapter.dispose(), and TextControl.sink.
        {
                sink.dispose();
        }
int getAlignment () [inline, private]
References UIControlObject.HorizontalAlignment, RadioProperty.is(), and TextControl.uiObj.
Referenced by TextControl.propertyChanged(), and TextControl.TextControl().
        {
                if (uiObj.HorizontalAlignment.is('left'))
                        return SwingConstants.LEFT;
                else if (uiObj.HorizontalAlignment.is('center'))
                        return SwingConstants.CENTER;
                else if (uiObj.HorizontalAlignment.is('right'))
                        return SwingConstants.RIGHT;
                return SwingConstants.LEFT;
        }
JComponent getComponent () [inline]
Implements UIControl.
        {
                return this;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline]
References TextControl.getAlignment(), UIControlObject.HorizontalAlignment, TextControl.stringToHTML(), StringProperty.toString(), TextControl.uiObj, and UIControlObject.UIString.
Referenced by TextControl.TextControl().
        {
                if (p == uiObj.HorizontalAlignment)
                {
                        setHorizontalAlignment(getAlignment());
                        setText(stringToHTML(uiObj.UIString.toString()));
                }
                else if (p == uiObj.UIString)
                        setText(stringToHTML(uiObj.UIString.toString()));
        }
String stringToHTML (Strings) [inline, private]
References RadioProperty.getValue(), UIControlObject.HorizontalAlignment, and TextControl.uiObj.
Referenced by TextControl.propertyChanged(), and TextControl.TextControl().
        {
                if (s.indexOf('\n') < 0)
                        return s;
                else
                {
                        String[] lines = s.split('\n');
                        String result = '';
                        for (int i=0; i<lines.length; i++)
                                result += ('<p align='' + uiObj.HorizontalAlignment.getValue() + ''>' + lines[i] + '</p>');
                        return ('<html>' + result + '</html>');
                }
        }
void update () [inline]
Implements UIControl.
        {
        }
Member Data Documentation
HandleEventSinkAdapter sink [private]
Referenced by TextControl.dispose(), and TextControl.TextControl().
UIControlObject uiObj [private]
Referenced by TextControl.getAlignment(), TextControl.propertyChanged(), TextControl.stringToHTML(), and TextControl.TextControl().
Author
Generated automatically by Doxygen for Octave from the source code.