AxesContainer
NAME
AxesContainer -
SYNOPSIS
Inherits HandleObject, RenderEventListener, MouseListener, MouseMotionListener, and RenderCanvas.Container.
Inherited by FigureObject, and UIPanelObject.
Public Member Functions
AxesContainer (HandleObject parent, String type, double handle)
HandleObject getObjectForPoint (Point pt, int margin)
AxesObject getAxesForPoint (Point pt)
void redraw ()
boolean hasMouseOperation ()
void cancelMouseOperation ()
void reshape (RenderCanvas c, int x, int y, int width, int height)
void display (RenderCanvas c)
void mouseClicked (MouseEvent e)
void mouseEntered (MouseEvent e)
void mouseExited (MouseEvent e)
void mousePressed (MouseEvent e)
void mouseReleased (MouseEvent e)
void mouseMoved (MouseEvent e)
void mouseDragged (MouseEvent e)
RenderCanvas getCanvas ()
double getHandle ()
String getType ()
Property getDefaultProperty (String name)
void deleteChildren ()
boolean isLegendable ()
void delete ()
void addChild (HandleObject child)
void removeChild (HandleObject child)
void validate ()
void addProperty (Property p)
boolean isValid ()
void setCachedData (Renderer.CachedData d)
Renderer.CachedData getCachedData ()
java.awt.Component getComponent ()
HandleObject getAncestor (String type)
Object get (String name) throws PropertyException
Object get (Property p)
void set (String name, Object value) throws PropertyException
void set (Property p, Object value) throws PropertyException
void waitFor ()
void waitFor (String pname)
void waitFor (String pname, Object value)
void propertyChanged (Property p) throws PropertyException
void doButtonDownFcn (MouseEvent e)
void addHandleEventSink (String name, HandleEventSink sink)
void removeHandleEventSink (HandleEventSink sink)
boolean hasHandleEvent (String name)
void eventOccured (HandleEvent evt) throws PropertyException
void sourceDeleted (Object source)
boolean executeOnce ()
Property getProperty (String name)
boolean hasProperty (String name)
void show ()
String[] getNames ()
Static Public Member Functions
static void redrawRecursive (HandleObject obj)
static boolean isHandle (double handle)
static HandleObject getHandleObject (double handle) throws Exception
static void removeHandleObject (double handle)
static void addHandleObject (double handle, HandleObject obj)
static void shutdown ()
static void listObjects ()
Static Public Attributes
static final int OP_NONE = 0
static final int OP_ZOOM = 1
static final int OP_ROTATE = 2
Protected Member Functions
abstract Color getBackgroundColor ()
abstract Container getEmbeddingComponent ()
Point getMouseLocation (MouseEvent e)
void updateCanvas ()
void initProperties (HandleObject parent, String type)
void setHandle (double handle)
void listen (Property p)
void childValidated (HandleObject child)
void autoSet (Property p, Object value)
boolean isAutoMode ()
Static Protected Member Functions
static double newHandle ()
Protected Attributes
RenderCanvas canvas = null
int autoMode = 0
PropertySet defaultSet = new PropertySet()
Package Attributes
BooleanProperty BeingDeleted
CallbackProperty ButtonDownFcn
HandleObjectListProperty Children
BooleanProperty Clipping
CallbackProperty CreateFcn
CallbackProperty DeleteFcn
RadioProperty HandleVisibility
HandleObjectListProperty Parent
StringProperty Tag
StringProperty Type
ObjectProperty UserData
BooleanProperty Visible
Private Member Functions
int getDefaultMouseOp ()
void createCanvas ()
Private Attributes
AxesObject mouseAxes = null
int mouseOp = OP_NONE
Constructor & Destructor Documentation
AxesContainer (HandleObjectparent, Stringtype, doublehandle) [inline]
        {
                super(parent, handle, type);
        }
Member Function Documentation
void addChild (HandleObjectchild) [inline, inherited]
References HandleObjectListProperty.addElement(), and HandleObject.Children.
Referenced by HandleObject.initProperties().
        {
                synchronized (Children)
                {
                        Children.addElement(child);
                }
        }
void addHandleEventSink (Stringname, HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleEventSourceHelper.addHandleEventSink(), and HandleObject.eventSource.
Referenced by HandleObject.waitFor().
        {
                eventSource.addHandleEventSink(name, sink);
        }
static void addHandleObject (doublehandle, HandleObjectobj) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.HandleObject(), and HandleObject.setHandle().
        {
                handleMap.put(new Double(handle), new WeakReference(obj));
        }
void addProperty (Propertyp) [inline, inherited]
Reimplemented from PropertySet.
References HandleObject.isValid(), and Property.unLock().
        {
                super.addProperty(p);
                if (isValid())
                        p.unLock();
        }
void autoSet (Propertyp, Objectvalue) [inline, protected, inherited]
References HandleObject.autoMode, and Property.set().
Referenced by AxesObject.autoAspectRatio(), AxesObject.autoAxis(), AxesObject.autoScaleC(), AxesObject.computeAutoTickLabels(), FigureObject.propertyChanged(), AxesObject.propertyChanged(), AxesObject.setInternalPosition(), PatchObject.updateCData(), PatchObject.updateFVCData(), PatchObject.updateFVData(), AxesObject.updateOuterPosition(), FigureObject.updatePosition(), AxesObject.updatePosition(), AxesObject.updateXFormMatrices(), and PatchObject.updateXYZData().
        {
                autoMode++;
                p.set(value, true);
                autoMode--;
        }
void cancelMouseOperation () [inline]
References AxesObject.cancelOperation(), AxesContainer.hasMouseOperation(), AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
Referenced by FigureObject.windowDeactivated().
        {
                if (hasMouseOperation())
                {
                        mouseAxes.cancelOperation(mouseOp);
                        mouseAxes = null;
                        mouseOp = OP_NONE;
                }
        }
void childValidated (HandleObjectchild) [inline, protected, inherited]
Reimplemented in AxesObject, and GroupObject.
Referenced by HandleObject.validate().
        {
        }
void createCanvas () [inline, private]
References RenderCanvas.addMouseListener(), RenderCanvas.addMouseMotionListener(), RenderCanvas.addRenderEventListener(), AxesContainer.canvas, HandleObject.getAncestor(), RenderCanvas.getComponent(), AxesContainer.getEmbeddingComponent(), and RadioProperty.is().
Referenced by AxesContainer.getCanvas(), and AxesContainer.updateCanvas().
        {
                if (canvas != null)
                        return;
                RadioProperty rp = ((FigureObject)getAncestor('figure')).Renderer;
                if (rp.is('OpenGL'))
                        canvas = new GLRenderCanvas();
                else if (rp.is('Java2D'))
                        canvas = new J2DRenderCanvas();
                canvas.getComponent().setVisible(false);
                canvas.addMouseListener(this);
                canvas.addMouseMotionListener(this);
                canvas.addRenderEventListener(this);
                getEmbeddingComponent().add(canvas.getComponent());
                getEmbeddingComponent().validate();
                canvas.getComponent().setVisible(true);
        }
void delete () [inline, inherited]
Reimplemented from PropertySet.
Reimplemented in FigureObject, UIPanelObject, UIControlObject, BarseriesObject, and ColorbarObject.
References HandleObject.BeingDeleted, HandleObject.cachedData, HandleEventSourceHelper.delete(), HandleObject.deleteChildren(), HandleObject.DeleteFcn, HandleObjectListProperty.elementAt(), HandleObject.eventSource, HandleObject.eventSourceSet, CallbackProperty.execute(), HandleEventSourceHelper.fireEvent(), HandleObject.getHandle(), HandleObject.Parent, HandleObject.removeChild(), HandleObject.removeHandleEventSink(), HandleObject.removeHandleObject(), and Property.reset().
Referenced by HandleObject.deleteChildren(), AxesObject.deleteChildren(), ColorbarObject.doClear(), LegendObject.doClear(), and AxesObject.makeLegend().
        {
                BeingDeleted.reset('on');
                try { eventSource.fireEvent('ObjectDeleted'); }
                catch (PropertyException ex) {}
                DeleteFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
                removeHandleObject(getHandle());
                super.delete();
                Iterator it = eventSourceSet.iterator();
                while (it.hasNext())
                        ((HandleEventSource)it.next()).removeHandleEventSink(this);
                eventSource.delete();
                deleteChildren();
                if (cachedData != null)
                        cachedData.dispose();
                Parent.elementAt(0).removeChild(this);
        }
void deleteChildren () [inline, inherited]
Reimplemented in AxesObject.
References HandleObject.Children, HandleObject.delete(), HandleObjectListProperty.elementAt(), HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        while (Children.size() > 0)
                        {
                                int len = Children.size();
                                HandleObject obj = Children.elementAt(0);
                                obj.delete();
                                if (Children.size() == len)
                                {
                                        System.out.println('ERROR: wrong parentship in graphic object of class `' + Type.toString() + '' with child of class `' +
                                                        obj.Type.toString() + ''');
                                        break;
                                }
                        }
                }
        }
void display (RenderCanvasc) [inline]
Implements RenderEventListener.
References HandleObject.Children, Renderer.clear(), AxesContainer.getBackgroundColor(), RenderCanvas.getRenderer(), HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
        {
                Renderer r = c.getRenderer();
                // clear background
                r.clear(getBackgroundColor());
                // iterate over axes objects
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (hObj instanceof AxesObject && hObj.isValid())
                                        ((AxesObject)hObj).draw(r);
                        }
                }
        }
void doButtonDownFcn (MouseEvente) [inline, inherited]
References HandleObject.ButtonDownFcn, CallbackProperty.execute(), HandleObject.getAncestor(), HandleObject.getHandle(), and CallbackProperty.unwind().
Referenced by UIControlAdapter.mousePressed(), and AxesContainer.mousePressed().
        {
                String selType = 'normal';
                switch (e.getButton())
                {
                        case MouseEvent.BUTTON2:
                                selType = 'extend';
                                break;
                        case MouseEvent.BUTTON3:
                                selType = 'alt';
                                break;
                }
                switch (e.getModifiers() & (MouseEvent.SHIFT_MASK|MouseEvent.CTRL_MASK))
                {
                        case MouseEvent.CTRL_MASK:
                                selType = 'alt';
                                break;
                        case MouseEvent.SHIFT_MASK:
                                selType = 'extend';
                                break;
                        case 0:
                                if (e.getClickCount() == 2)
                                        selType = 'open';
                                break;
                }
                ButtonDownFcn.unwind(((FigureObject)getAncestor('figure')).SelectionType, selType);
                ButtonDownFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void eventOccured (HandleEventevt) throws PropertyException 	 [inline, inherited]
Implements HandleEventSink.
References HandleObject.propertyChanged().
Referenced by HandleObject.waitFor().
        {
                if (evt.getName().equals('PropertyChanged'))
                        propertyChanged(evt.getProperty());
        }
boolean executeOnce () [inline, inherited]
Implements HandleEventSink.
Referenced by HandleObject.waitFor().
        {
                return false;
        }
Object get (Propertyp) [inline, inherited]
Reimplemented in FigureObject, and UIControlObject.
        {
                return p.get();
        }
Object get (Stringname) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References Property.get(), and HandleObject.getDefaultProperty().
Referenced by AxesObject.autoScaleC(), and LegendObject.makeItemFromLine().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                                return p.get();
                        throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        return super.get(name);
        }
HandleObject getAncestor (Stringtype) [inline, inherited]
References HandleObjectListProperty.elementAt(), HandleObject.Parent, HandleObjectListProperty.size(), StringProperty.toString(), and HandleObject.Type.
Referenced by AxesContainer.createCanvas(), HandleObject.doButtonDownFcn(), AxesContainer.getDefaultMouseOp(), AxesObject.getFigure(), and GraphicObject.set().
        {
                HandleObject curr = this;
                while (true)
                {
                        if (curr.Type.toString().equalsIgnoreCase(type))
                                return curr;
                        else if (curr.Parent.size() <= 0)
                                return null;
                        else
                                curr = curr.Parent.elementAt(0);
                }
        }
AxesObject getAxesForPoint (Pointpt) [inline]
References AxesContainer.getObjectForPoint().
Referenced by AxesContainer.mouseClicked(), and AxesContainer.mousePressed().
        {
                HandleObject obj = getObjectForPoint(pt, 0);
                if (obj instanceof AxesObject)
                        return (AxesObject)obj;
                return null;
        }
abstract Color getBackgroundColor () [protected, pure virtual]
Implemented in FigureObject, and UIPanelObject.
Referenced by AxesContainer.display().
Renderer.CachedData getCachedData () [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw().
        {
                return cachedData;
        }
RenderCanvas getCanvas () [inline]
Implements RenderCanvas.Container.
References AxesContainer.canvas, and AxesContainer.createCanvas().
Referenced by FigureObject.createFigure().
        {
                if (canvas == null)
                        createCanvas();
                return canvas;
        }
java.awt.Component getComponent () [inline, inherited]
Reimplemented in FigureObject, UIPanelObject, and UIControlObject.
Referenced by UIControlObject.getParentComponent(), and UIPanelObject.getParentComponent().
        {
                System.out.println('Warning: no component associated with ' + getClass());
                return null;
        }
int getDefaultMouseOp () [inline, private]
References HandleObject.getAncestor(), and FigureObject.getMouseOp().
Referenced by AxesContainer.mouseClicked(), and AxesContainer.mousePressed().
        {
                FigureObject fig = (FigureObject)getAncestor('figure');
                return fig.getMouseOp();
        }
Property getDefaultProperty (Stringname) [inline, inherited]
References HandleObject.defaultSet, HandleObjectListProperty.elementAt(), Factory.getDefaultProperty(), HandleObject.getDefaultProperty(), PropertySet.getProperty(), HandleObject.Parent, and HandleObjectListProperty.size().
Referenced by HandleObject.get(), HandleObject.getDefaultProperty(), Property.initDefault(), and HandleObject.set().
        {
                Property p = defaultSet.getProperty(name);
                if (p != null)
                        return p;
                else if (Parent.size() > 0)
                        return Parent.elementAt(0).getDefaultProperty(name);
                else
                        return Factory.getDefaultProperty(name);
        }
abstract Container getEmbeddingComponent () [protected, pure virtual]
Implemented in FigureObject, and UIPanelObject.
Referenced by AxesContainer.createCanvas(), AxesContainer.getObjectForPoint(), and AxesContainer.updateCanvas().
double getHandle () [inline, inherited]
References HandleObject.handle.
Referenced by UIPanelObject.componentResized(), FigureObject.componentResized(), UIControlObject.controlActivated(), HandleObject.delete(), HandleObject.doButtonDownFcn(), OctaveSink.doInvoke(), RootObject.findFigure(), HandleObjectListProperty.getHandleArray(), HandleObject.HandleObject(), AxesObject.reset(), HandleObject.setHandle(), HandleObjectListProperty.toString(), FigureObject.updateHandle(), FigureObject.updateTitle(), HandleObject.validate(), and FigureObject.windowClosing().
        {
                return handle;
        }
static HandleObject getHandleObject (doublehandle) throws Exception 	 [inline, static, inherited]
References RootObject.getInstance(), HandleObject.handle, and HandleObject.handleMap.
Referenced by TextProperty.convertValue(), HandleObjectListProperty.convertValue(), and RootObject.createNewFigure().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                {
                        return (HandleObject)ref.get();
                }
                if (handle == 0)
                        return RootObject.getInstance();
                throw new Exception('invalid handle - ' + handle);
        }
Point getMouseLocation (MouseEvente) [inline, protected]
References AxesContainer.canvas, RenderCanvas.getX(), and RenderCanvas.getY().
Referenced by AxesContainer.mouseClicked(), and AxesContainer.mousePressed().
        {
                Point pt = new Point(e.getPoint());
                if (e.getSource() == canvas)
                        pt.translate(canvas.getX(), canvas.getY());
                return pt;
        }
String [] getNames () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                List names = new ArrayList();
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                                names.add(p.getName());
                }
                return (String[])names.toArray(new String[names.size()]);
        }
HandleObject getObjectForPoint (Pointpt, intmargin) [inline]
References AxesContainer.canvas, HandleObject.Children, AxesContainer.getEmbeddingComponent(), RenderCanvas.getHeight(), RenderCanvas.getX(), RenderCanvas.getY(), HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
Referenced by AxesContainer.getAxesForPoint(), and AxesContainer.mousePressed().
        {
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        Insets insets = getEmbeddingComponent().getInsets();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (!hObj.isValid())
                                        continue;
                                if (hObj instanceof UIControlObject)
                                {
                                        Rectangle r = ((UIControlObject)hObj).getBounds();
                                        r.setRect(r.x-margin, r.y-margin, r.width+2*margin, r.height+2*margin);
                                        if (r.contains(pt))
                                                return hObj;
                                }
                                else if (hObj instanceof AxesObject)
                                {
                                        Rectangle r = ((AxesObject)hObj).getBoundingBox();
                                        if (r.contains(pt.x-canvas.getX(), canvas.getHeight()-pt.y+canvas.getY()))
                                                return hObj;
                                }
                        }
                }
                return null;
        }
Property getProperty (Stringname) [inline, inherited]
Referenced by AxesObject.childValidated(), AxesObject.draw(), PropertySet.get(), AxesObject.getChildrenLimits(), HandleObject.getDefaultProperty(), OctaveSink.OctaveSink(), PropertySet.set(), and HandleObject.waitFor().
        {
                return (Property)get((Object)name.toLowerCase());
        }
String getType () [inline, inherited]
References StringProperty.toString(), and HandleObject.Type.
Referenced by Property.initDefault().
        {
                return (Type != null ? Type.toString() : '');
        }
boolean hasHandleEvent (Stringname) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.hasHandleEvent().
Referenced by OctaveSink.OctaveSink().
        {
                return eventSource.hasHandleEvent(name);
        }
boolean hasMouseOperation () [inline]
References AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
Referenced by AxesContainer.cancelMouseOperation().
        {
                return (mouseOp != OP_NONE && mouseAxes != null);
        }
boolean hasProperty (Stringname) [inline, inherited]
Referenced by AxesObject.draw().
        {
                return containsKey(name.toLowerCase());
        }
void initProperties (HandleObjectparent, Stringtype) [inline, protected, inherited]
References HandleObject.addChild(), HandleObjectListProperty.addElement(), HandleObject.BeingDeleted, HandleObject.ButtonDownFcn, HandleObject.Children, HandleObject.Clipping, HandleObject.CreateFcn, HandleObject.DeleteFcn, HandleObject.HandleVisibility, HandleObject.Parent, HandleObject.Tag, HandleObject.Type, HandleObject.UserData, and HandleObject.Visible.
Referenced by HandleObject.HandleObject().
        {
                // These properties must be created first, in order to
                // get correct behavior when looking for default values
                // of properties
                Type = new StringProperty(this, 'Type', type);
                Parent = new HandleObjectListProperty(this, 'Parent', -1);
                if (parent != null)
                        Parent.addElement(parent);
                // Create other properties
                BeingDeleted = new BooleanProperty(this, 'BeingDeleted', false);
                ButtonDownFcn = new CallbackProperty(this, 'ButtonDownFcn', (String)null);
                Children = new HandleObjectListProperty(this, 'Children', -1);
                Clipping = new BooleanProperty(this, 'Clipping', true);
                CreateFcn = new CallbackProperty(this, 'CreateFcn', (String)null);
                DeleteFcn = new CallbackProperty(this, 'DeleteFcn', (String)null);
                HandleVisibility = new RadioProperty(this, 'HandleVisibility', new String[] {'on', 'callback', 'off'}, 'on');
                Tag = new StringProperty(this, 'Tag', '');
                UserData = new ObjectProperty(this, 'UserData', null);
                Visible = new BooleanProperty(this, 'Visible', true);
                // TODO: move this to validate() ??
                if (parent != null)
                        parent.addChild(this);
        }
boolean isAutoMode () [inline, protected, inherited]
References HandleObject.autoMode.
Referenced by ColorbarObject.propertyChanged(), FigureObject.propertyChanged(), LegendObject.propertyChanged(), and PatchObject.propertyChanged().
        {
                return (autoMode > 0);
        }
static boolean isHandle (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by TextProperty.convertValue(), RootObject.createNewFigure(), and RootObject.getUnusedFigureNumber().
        {
                WeakReference ref = (WeakReference)handleMap.get(new Double(handle));
                if (ref != null && ref.get() != null)
                        return true;
                return false;
        }
boolean isLegendable () [inline, inherited]
Reimplemented in GraphicObject, and BaseLineObject.
Referenced by AxesObject.autoLegend(), and LegendObject.buildLegend().
        {
                return false;
        }
boolean isValid () [inline, inherited]
References HandleObject.valid.
Referenced by HandleObject.addProperty(), AxesObject.childValidated(), UIControlObject.controlActivated(), AxesContainer.display(), AxesContainer.getObjectForPoint(), and AxesContainer.reshape().
        {
                return valid;
        }
void listen (Propertyp) [inline, protected, inherited]
References Property.addHandleEventSink(), HandleObject.eventSourceSet, and Property.getParent().
Referenced by AxesObject.AxesObject(), BarseriesObject.BarseriesObject(), BaseLineObject.BaseLineObject(), GroupObject.childValidated(), AxesObject.childValidated(), ColorbarObject.ColorbarObject(), FigureObject.FigureObject(), ImageObject.ImageObject(), LegendObject.LegendObject(), LineObject.LineObject(), PatchObject.PatchObject(), RootObject.RootObject(), SurfaceObject.SurfaceObject(), TextObject.TextObject(), UIControlObject.UIControlObject(), and UIPanelObject.UIPanelObject().
        {
                p.addHandleEventSink('PropertyChanged', this);
                if (p.getParent() != this)
                        eventSourceSet.add(p);
        }
static void listObjects () [inline, static, inherited]
References HandleObject.handleMap, and HandleObject.HandleObject().
        {
                Iterator it = handleMap.entrySet().iterator();
                while (it.hasNext())
                {
                        Map.Entry entry = (Map.Entry)it.next();
                        HandleObject hObj = (HandleObject)((WeakReference)entry.getValue()).get();
                        System.out.println(entry.getKey() + ' = ' + hObj.getClass());
                }
        }
void mouseClicked (MouseEvente) [inline]
References AxesContainer.getAxesForPoint(), AxesContainer.getDefaultMouseOp(), AxesContainer.getMouseLocation(), AxesContainer.mouseOp, AxesContainer.OP_NONE, AxesContainer.OP_ZOOM, and AxesObject.unZoom().
        {
                if (e.getButton() == MouseEvent.BUTTON3 && mouseOp == OP_NONE && getDefaultMouseOp() == OP_ZOOM)
                {
                        AxesObject ax = getAxesForPoint(getMouseLocation(e));
                        if (ax != null)
                                ax.unZoom();
                }
        }
void mouseDragged (MouseEvente) [inline]
References AxesContainer.mouseAxes, AxesContainer.mouseOp, AxesContainer.OP_NONE, and AxesObject.operation().
        {
                if (mouseAxes != null && mouseOp != OP_NONE)
                        mouseAxes.operation(mouseOp, e);
        }
void mouseEntered (MouseEvente) [inline]
{}
void mouseExited (MouseEvente) [inline]
{}
void mouseMoved (MouseEvente) [inline]
{}
void mousePressed (MouseEvente) [inline]
References HandleObject.doButtonDownFcn(), AxesContainer.getAxesForPoint(), AxesContainer.getDefaultMouseOp(), AxesContainer.getMouseLocation(), AxesContainer.getObjectForPoint(), AxesContainer.mouseAxes, AxesContainer.mouseOp, AxesContainer.OP_NONE, and AxesObject.startOperation().
        {
                if (mouseOp == OP_NONE)
                {
                        // Only do something if no operation pending
                        Point pt = getMouseLocation(e);
                        AxesObject ax = getAxesForPoint(pt);
                        HandleObject hObj = getObjectForPoint(pt, 5);
                        if (hObj != null)
                        {
                                boolean doCB = false;
                                if (hObj instanceof AxesObject)
                                {
                                        if (getDefaultMouseOp() == OP_NONE)
                                                doCB = true;
                                        else if (e.getButton() == MouseEvent.BUTTON1)
                                        {
                                                mouseAxes = (AxesObject)hObj;
                                                mouseOp = getDefaultMouseOp();
                                                mouseAxes.startOperation(mouseOp, e);
                                        }
                                }
                                else
                                        doCB = true;
                                if (doCB)
                                        hObj.doButtonDownFcn(e);
                        }
                        else
                                doButtonDownFcn(e);
                }
        }
void mouseReleased (MouseEvente) [inline]
References AxesObject.endOperation(), AxesContainer.mouseAxes, AxesContainer.mouseOp, and AxesContainer.OP_NONE.
        {
                if (mouseOp != OP_NONE)
                {
                        if (e.getButton() == MouseEvent.BUTTON1)
                        {
                                if (mouseAxes != null)
                                        mouseAxes.endOperation(mouseOp, e);
                                mouseAxes = null;
                                mouseOp = OP_NONE;
                        }
                }
        }
static double newHandle () [inline, static, protected, inherited]
References HandleObject.handleSeed.
Referenced by HandleObject.HandleObject(), UIPanelObject.UIPanelObject(), and FigureObject.updateHandle().
        {
                double h = handleSeed;
                handleSeed = Math.ceil(handleSeed) - 1 - Math.random();
                return h;
        }
void propertyChanged (Propertyp) throws PropertyException 	 [inline, inherited]
Reimplemented in AxesObject, PatchObject, LegendObject, FigureObject, ColorbarObject, SurfaceObject, TextObject, BarseriesObject, UIPanelObject, UIControlObject, RootObject, LineObject, GroupObject, ImageObject, and BaseLineObject.
Referenced by HandleObject.eventOccured().
        {
        }
void redraw () [inline]
References AxesContainer.redrawRecursive().
        {
                redrawRecursive(this);
        }
static void redrawRecursive (HandleObjectobj) [inline, static]
Referenced by AxesContainer.redraw().
        {
                if (obj instanceof RenderCanvas.Container)
                        ((RenderCanvas.Container)obj).getCanvas().redraw();
                synchronized (obj.Children)
                {
                        Iterator it = obj.Children.iterator();
                        while (it.hasNext())
                                redrawRecursive((HandleObject)it.next());
                }
        }
void removeChild (HandleObjectchild) [inline, inherited]
Reimplemented in AxesObject, FigureObject, GroupObject, and RootObject.
References HandleObject.Children, and HandleObjectListProperty.removeElement().
Referenced by HandleObject.delete().
        {
                synchronized (Children)
                {
                        Children.removeElement(child);
                }
        }
void removeHandleEventSink (HandleEventSinksink) [inline, inherited]
Implements HandleEventSource.
References HandleObject.eventSource, and HandleEventSourceHelper.removeHandleEventSink().
Referenced by HandleObject.delete().
        {
                eventSource.removeHandleEventSink(sink);
        }
static void removeHandleObject (doublehandle) [inline, static, inherited]
References HandleObject.handleMap.
Referenced by HandleObject.delete(), and HandleObject.setHandle().
        {
                handleMap.remove(new Double(handle));
        }
void reshape (RenderCanvasc, intx, inty, intwidth, intheight) [inline]
Implements RenderEventListener.
References HandleObject.Children, HandleObject.HandleObject(), HandleObject.isValid(), and HandleObjectListProperty.iterator().
        {
                synchronized (Children)
                {
                        Iterator it = Children.iterator();
                        while (it.hasNext())
                        {
                                HandleObject hObj = (HandleObject)it.next();
                                if (hObj instanceof AxesObject && hObj.isValid())
                                        ((AxesObject)hObj).updateActivePosition();
                        }
                }
        }
void set (Propertyp, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented in UIControlObject, and GraphicObject.
        {
                p.set(value);
        }
void set (Stringname, Objectvalue) throws PropertyException 	 [inline, inherited]
Reimplemented from PropertySet.
References PropertySet.addProperty(), Property.cloneProperty(), HandleObject.defaultSet, HandleObject.getDefaultProperty(), and Property.set().
        {
                if (name.toLowerCase().startsWith('default'))
                {
                        Property p = getDefaultProperty(name);
                        if (p != null)
                        {
                                Property new_p = p.cloneProperty();
                                new_p.set(value);
                                defaultSet.addProperty(new_p);
                        }
                        else
                                throw new PropertyException('invalid default property - ' + name.toLowerCase());
                }
                else
                        super.set(name, value);
        }
void setCachedData (Renderer.CachedDatad) [inline, inherited]
References HandleObject.cachedData.
Referenced by GLRenderer.draw(), and SurfaceObject.propertyChanged().
        {
                if (cachedData != null)
                        cachedData.dispose();
                cachedData = d;
        }
void setHandle (doublehandle) [inline, protected, inherited]
References HandleObject.addHandleObject(), HandleObject.getHandle(), HandleObject.handle, and HandleObject.removeHandleObject().
Referenced by FigureObject.updateHandle().
        {
                removeHandleObject(getHandle());
                this.handle = handle;
                addHandleObject(getHandle(), this);
        }
void show () [inline, inherited]
References Property.getName(), and Property.isVisible().
        {
                Iterator it = values().iterator();
                while (it.hasNext())
                {
                        Property p = (Property)it.next();
                        if (p.isVisible())
                        {
                                get(p); /* force any getter to execute */
                                System.out.println(' ' + p.getName() + ' = ' + p);
                        }
                }
        }
static void shutdown () [inline, static, inherited]
References HandleObject.handleMap.
        {
                LinkedList figList = new LinkedList();
                Iterator it = handleMap.values().iterator();
                while (it.hasNext())
                {
                        WeakReference ref = (WeakReference)it.next();
                        if (ref != null && ref.get() != null && ref.get() instanceof FigureObject)
                                figList.add(ref.get());
                }
                it = figList.iterator();
                while (it.hasNext())
                        ((HandleObject)it.next()).delete();
        }
void sourceDeleted (Objectsource) [inline, inherited]
Implements HandleEventSink.
References HandleObject.eventSourceSet.
Referenced by HandleObject.waitFor().
        {
                eventSourceSet.remove(source);
        }
void updateCanvas () [inline, protected]
References AxesContainer.canvas, AxesContainer.createCanvas(), RenderCanvas.getComponent(), AxesContainer.getEmbeddingComponent(), RenderCanvas.removeMouseListener(), RenderCanvas.removeMouseMotionListener(), and RenderCanvas.removeRenderEventListener().
Referenced by FigureObject.propertyChanged().
        {
                if (canvas != null)
                {
                        canvas.removeMouseListener(this);
                        canvas.removeMouseMotionListener(this);
                        canvas.removeRenderEventListener(this);
                        getEmbeddingComponent().remove(canvas.getComponent());
                        getEmbeddingComponent().validate();
                        canvas = null;
                }
                createCanvas();
        }
void validate () [inline, inherited]
Reimplemented from PropertySet.
Reimplemented in AxesObject, FigureObject, UIPanelObject, GroupObject, UIControlObject, PatchObject, TextObject, SurfaceObject, ImageObject, BarseriesObject, LineObject, and LightObject.
References HandleObject.Children, HandleObject.childValidated(), HandleObjectListProperty.contains(), HandleObject.CreateFcn, HandleObjectListProperty.elementAt(), CallbackProperty.execute(), HandleObject.getHandle(), HandleObject.Parent, HandleObjectListProperty.size(), and HandleObject.valid.
Referenced by RootObject.getInstance().
        {
                super.validate();
                valid = true;
                if (Parent.size() > 0)
                {
                        HandleObject parent = Parent.elementAt(0);
                        if (parent.Children.contains(this))
                                parent.childValidated(this);
                }
                CreateFcn.execute(new Object[] {
                        new Double(getHandle()),
                        null});
        }
void waitFor () [inline, inherited]
Referenced by HandleObject.waitFor().
        {
                waitFor(null, null, false);
        }
void waitFor (Stringpname) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, null, false);
        }
void waitFor (Stringpname, Objectvalue) [inline, inherited]
References HandleObject.waitFor().
        {
                waitFor(pname, value, true);
        }
Member Data Documentation
int autoMode = 0 [protected, inherited]
Referenced by HandleObject.autoSet(), ColorbarObject.doLocate(), LegendObject.doLocate(), AxesObject.doZoom(), AxesObject.draw(), HandleObject.isAutoMode(), ColorbarObject.propertyChanged(), LegendObject.propertyChanged(), AxesObject.propertyChanged(), and AxesObject.unZoom().
BooleanProperty BeingDeleted [package, inherited]
Referenced by HandleObject.delete(), HandleObject.initProperties(), and AxesObject.removeChild().
CallbackProperty ButtonDownFcn [package, inherited]
Referenced by HandleObject.doButtonDownFcn(), and HandleObject.initProperties().
RenderCanvas canvas = null [protected]
Referenced by AxesContainer.createCanvas(), AxesContainer.getCanvas(), AxesContainer.getMouseLocation(), AxesContainer.getObjectForPoint(), FigureObject.print(), and AxesContainer.updateCanvas().
HandleObjectListProperty Children [package, inherited]
Referenced by HandleObject.addChild(), AxesObject.autoLegend(), AxesObject.autoScaleC(), LegendObject.buildLegend(), HandleObject.deleteChildren(), AxesContainer.display(), ColorbarObject.doClear(), LegendObject.doClear(), GroupObject.draw(), AxesObject.draw(), RootObject.findFigure(), AxesObject.getChildrenLimits(), AxesContainer.getObjectForPoint(), BarseriesObject.getPatch(), HandleObject.initProperties(), RootObject.removeChild(), HandleObject.removeChild(), AxesContainer.reshape(), ColorbarObject.updateImageFromColormap(), GroupObject.updateLimits(), GroupObject.validate(), and HandleObject.validate().
BooleanProperty Clipping [package, inherited]
Referenced by GLRenderer.draw(), AxesObject.draw(), HandleObject.initProperties(), and TextObject.TextObject().
CallbackProperty CreateFcn [package, inherited]
Referenced by HandleObject.initProperties(), and HandleObject.validate().
PropertySet defaultSet = new PropertySet() [protected, inherited]
Referenced by HandleObject.getDefaultProperty(), and HandleObject.set().
CallbackProperty DeleteFcn [package, inherited]
Referenced by HandleObject.delete(), and HandleObject.initProperties().
RadioProperty HandleVisibility [package, inherited]
Referenced by HandleObjectListProperty.getVisibleObjects(), HandleObject.initProperties(), and AxesObject.makeTextObject().
AxesObject mouseAxes = null [private]
Referenced by AxesContainer.cancelMouseOperation(), AxesContainer.hasMouseOperation(), AxesContainer.mouseDragged(), AxesContainer.mousePressed(), and AxesContainer.mouseReleased().
int mouseOp = OP_NONE [private]
Referenced by AxesContainer.cancelMouseOperation(), AxesContainer.hasMouseOperation(), AxesContainer.mouseClicked(), AxesContainer.mouseDragged(), AxesContainer.mousePressed(), and AxesContainer.mouseReleased().
final int OP_NONE = 0 [static]
Referenced by FigureObject.actionPerformed(), AxesContainer.cancelMouseOperation(), FigureObject.commandToOp(), AxesContainer.hasMouseOperation(), AxesContainer.mouseClicked(), AxesContainer.mouseDragged(), AxesContainer.mousePressed(), and AxesContainer.mouseReleased().
final int OP_ROTATE = 2 [static]
Referenced by AxesObject.cancelOperation(), FigureObject.commandToOp(), AxesObject.endOperation(), AxesObject.operation(), and AxesObject.startOperation().
final int OP_ZOOM = 1 [static]
Referenced by AxesObject.cancelOperation(), FigureObject.commandToOp(), AxesObject.endOperation(), AxesContainer.mouseClicked(), AxesObject.operation(), and AxesObject.startOperation().
HandleObjectListProperty Parent [package, inherited]
Referenced by HandleObject.delete(), HandleObject.getAncestor(), GraphicObject.getAxes(), AxesObject.getAxesContainer(), AxesObject.getCanvas(), HandleObject.getDefaultProperty(), UIControlObject.getParentComponent(), UIPanelObject.getParentComponent(), HandleObject.initProperties(), LegendObject.LegendObject(), and HandleObject.validate().
StringProperty Tag [package, inherited]
Referenced by ColorbarObject.ColorbarObject(), HandleObject.initProperties(), and LegendObject.LegendObject().
StringProperty Type [package, inherited]
Referenced by HandleObject.deleteChildren(), HandleObject.getAncestor(), HandleObject.getType(), HandleObject.initProperties(), and OctaveSink.OctaveSink().
ObjectProperty UserData [package, inherited]
Referenced by HandleObject.initProperties().
BooleanProperty Visible [package, inherited]
Referenced by AxesObject.childValidated(), FigureObject.createFigure(), AxesObject.draw(), FigureObject.FigureObject(), AxesObject.getChildrenLimits(), HandleObject.initProperties(), FigureObject.propertyChanged(), and AxesObject.reset().
Author
Generated automatically by Doxygen for Octave from the source code.