.TH "plt.py" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plt.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBplt\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBdata\fP = genfromtxt('/tmp/plot\&.txt')"
.br
.ti -1c
.RI "list \fBx\fP = data[:,0]"
.br
.ti -1c
.RI "list \fBy\fP = data[:,1]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
