.TH "plt" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
plt \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBdata\fP = genfromtxt('/tmp/plot\&.txt')"
.br
.ti -1c
.RI "list \fBx\fP = \fBdata\fP[:,0]"
.br
.ti -1c
.RI "list \fBy\fP = \fBdata\fP[:,1]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBdata\fP = genfromtxt('/tmp/plot\&.txt')"
.PP
Referenced by GLRenderer\&.draw(), GLRenderer\&.drawBitmap(), and MarkerProperty\&.makeMarker()\&.
.SS "list \fBx\fP = \fBdata\fP[:,0]"
.PP
Referenced by BarseriesObject\&.BarseriesObject(), SurfaceObject\&.computeNormals(), BarseriesObject\&.doLayout(), J2DRenderer\&.draw(), GLRenderer\&.draw(), TextObject\&.drawAsImage(), MarkerProperty\&.drawMarker(), GLRenderer\&.drawMarkers(), J2DRenderer\&.drawQuads(), J2DRenderer\&.drawRubberBox(), AxesObject\&.drawZoomBox(), gl2psPrintPDFBeginViewport(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPGFBeginViewport(), gl2psPrintPostScriptBeginViewport(), gl2psPrintSVGBeginViewport(), gl2psPrintSVGHeader(), AxesObject\&.LinearScaler\&.scale(), Vector3D\&.scale(), J2DRenderer\&.setClipBox(), TextObject\&.toPostScript(), AxesObject\&.LinearScaler\&.unscale(), PatchObject\&.updateFVData(), ImageObject\&.updateMinMax(), SurfaceObject\&.updateMinMax(), and PatchObject\&.updateXYZData()\&.
.SS "list \fBy\fP = \fBdata\fP[:,1]"
.PP
Referenced by BarseriesObject\&.BarseriesObject(), SurfaceObject\&.computeNormals(), BarseriesObject\&.doLayout(), LegendObject\&.doLayout(), J2DRenderer\&.draw(), GLRenderer\&.draw(), TextObject\&.drawAsImage(), MarkerProperty\&.drawMarker(), GLRenderer\&.drawMarkers(), J2DRenderer\&.drawQuads(), J2DRenderer\&.drawRubberBox(), gl2psGetRGB(), gl2psPrintPDFBeginViewport(), gl2psPrintPDFPixmapStreamData(), gl2psPrintPGFBeginViewport(), gl2psPrintPostScriptBeginViewport(), gl2psPrintSVGBeginViewport(), gl2psPrintSVGHeader(), Vector3D\&.scale(), AxesObject\&.LogScaler\&.scale(), J2DRenderer\&.setClipBox(), TextObject\&.toPostScript(), PatchObject\&.updateFVData(), ImageObject\&.updateMinMax(), SurfaceObject\&.updateMinMax(), and PatchObject\&.updateXYZData()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
