.TH "packages/jhandles-0.3.5/src/org/octave/graphics/SimpleTextEngine.java" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/jhandles-0.3.5/src/org/octave/graphics/SimpleTextEngine.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleTextEngine\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.SimpleFactory\fP"
.br
.ti -1c
.RI "interface \fBSimpleTextEngine\&.TextRenderer\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.PSTextRenderer\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.PSTextRenderer\&.PSState\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.Layouter\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.Element\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.LineElement\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.SubscriptElement\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.SuperscriptElement\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.ScriptElement\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.TeXFontCommand\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.TeXFontSwitchCommand\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.TeXFontSizeCommand\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.TeXFontColorCommand\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.TeXFontNameCommand\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.TeXElement\fP"
.br
.ti -1c
.RI "class \fBSimpleTextEngine\&.Content\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBorg\&.octave\&.graphics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
