.TH "stp.m" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stp.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBstp\fP (in fnamem)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function \fBstp\fP (infnamem)"
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
