.TH "packages/jhandles-0.3.5/src/org/octave/graphics/StringProperty.java" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
packages/jhandles-0.3.5/src/org/octave/graphics/StringProperty.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStringProperty\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBorg\&.octave\&.graphics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
