.TH "teste.py" 3 "Tue Nov 27 2012" "Version 3.2" "Octave" \" -*- nroff -*-
.ad l
.nh
.SH NAME
teste.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBteste\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBt\fP = linspace(0,10,1000)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Octave from the source code\&.
