teste
NAME
teste -
SYNOPSIS
Variables
tuple t = linspace(0,10,1000)
Variable Documentation
tuple t = linspace(0,10,1000)
Referenced by gl2psPDFgroupListWriteMainStream(), gl2psSortOutTrianglePDFgroup(), and GLRenderer.makeTextureFromCData().
Author
Generated automatically by Doxygen for Octave from the source code.